### ISSUE TITLE
OneShot deal page links to the wrong game

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1000]
The OneShot deal page (https://isthereanydeal.com/#/page:game/info?plain=oneshot) links to a game called One Shot on itch.io (at the time of writing, it is free); however, these are two different games. The page also does not link to the real game on Steam (https://store.steampowered.com/app/420530/OneShot/).

[Issue created by kitsuta: 2018-04-26]

[Comment created by tfedor: 2018-04-26]
Split it into two entries:
https://isthereanydeal.com/#/page:game/info?plain=oneshot
https://isthereanydeal.com/#/page:game/info?plain=one_shot

[Comment created by treetrunks: 2018-04-26]
Same issue - deal redirects not to OneShot, but One Shot - completely different game https://onbox.itch.io/one-shot
Moreso, itch.io requires to create an account to claim the game and doesn't show the screenshots of it until the account is created (I feel like a jackass for blindly following the instructions without the double-check)

**Comment by MarkitkaM** [comment]
Entries to split #2323
