### ISSUE TITLE
Not Getting Any Waitlist Notifications Lately

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1003]
... although set price was met for several games. Nothing in spam either.
Dacxster

[Issue created by [deleted]: 2018-04-28]
[Last updated on bitbucket: 2018-05-21]

[Comment created by Dacxster: 2018-05-21]
It worked.

[Comment created by Dacxster: 2018-04-28]
I've just changed the account email to gmail; let's see how that works.

[Comment created by Dacxster: 2018-04-28]
Ok, thanks, I'll contact yahoo

[Comment created by Dacxster: 2018-04-28]
I do report spam a lot, but not from ITAD...

[Comment created by Dacxster: 2018-04-28]
Exactly: both meet waitlist price yet I haven't received any email. I'm not sure when this started.

[Comment created by tfedor: 2018-04-28]
I have checked sparkpost and it seems like emails to you are being delayed:

Messages from [..] temporarily deferred due to user complaints - 4.16.55.1; see https://help.yahoo.com/kb/postmaster/SLN3434.html

Historically the yahoo is the most problematic domain and users often complain about not receiving emails there. If you can, try to use another email address or contact yahoo about this.

[Comment created by tfedor: 2018-04-28]
Hm, based on what I can see we are sending you emails without issue, you should have received email about Arma 3 today and about Wargame yesterday

[Comment created by Dacxster: 2018-04-28]
Checked - green

[Comment created by tfedor: 2018-04-28]
Please check your email status first https://isthereanydeal.com/settings/account/?a=email

**Comment by MarkitkaM** [comment]
Solved within conversation above.
