### ISSUE TITLE
Steam profile not sycning. 18 days

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1007]
I've read the collections update with making your profile public, it's not that. The steam profile on ITAD hasnt updated. I've even tried to remove the steam profile and add it back in, but upon attempt of removal i get a 500 error

[Issue created by [deleted]: 2018-04-30]

[Comment created by tfedor: 2018-04-30]
There has been an issue with URLs which was fixed over the weekend. It may take one or two days for sync to catch up. Have you tried importing it manually? You may also send me your profile link and I'll check it.

**Comment by MarkitkaM** [comment]
Should be fixed within the conversation above. There is no additional info as the link for the profile of the user.
