### ISSUE TITLE
Error 500 on collection sync and log out

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1011]
If I try to manually sync my collection profile.import.php returns error 500. If I log out from ITAD I get error 500 too. My steam profile is all public. I can sync waitlist without errors.

This is my profile:  _deleted_
[Issue created by [deleted]: 2018-05-02]

[Comment created by tonilia: 2018-05-02]
Hi, I created an account to reply. The logout error disappeared as soon as you fixed the sync. Thank you! Can you please remove the profile link from the first message?

[Comment created by tfedor: 2018-05-02]
Import should work now but I'm not sure what's that about log out? It seems to me working fine for me. It's when you just click sign out from the menu?

**Comment by MarkitkaM** [comment]
Solved withing conversation. I am gonna delete the link of the user's account as he wish.
