### ISSUE TITLE
steam collection import

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1012]
having trouble syncing to my steam collection, tried manually syncing but it says "Oops, we failed to sync this profile" and nothing happens. 

My steam account profile is set to public so it shouldnt be any problem but it does but if change my steam profile settings to "friends only" it looks its working but its not.

[Issue created by [deleted]: 2018-05-02]

[Comment created by tfedor: 2018-05-02]
It should work now

**Comment by MarkitkaM** [comment]
Solved within the conversation above.
