### ISSUE TITLE
IPv6 path MTU discovery appears to be broken

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1018]
Hi there,

I'm unable to connect to your site on IPv6.

The TCP connection establishes successfully, but the TLS handshake never completes due to your server sending 1514 byte frames and seemingly not honoring ICMPv6 Packet Too Big messages being sent by my tunnel endpoint, which are required for PMTUD to function (see attached pcap).

Typically this is caused by an over-zealous firewall blocking ICMPv6 Packet Too Big (Type 2) messages - https://test-ipv6.com/faq_pmtud.html.

This would usually not affect anyone with native IPv6 connectivity, but will mean users connecting via any type of tunnel may be unable to access your site depending on browser behavior.

[Issue created by [deleted]: 2018-05-12]
[Last updated on bitbucket: 2020-04-28]

[Comment created by AZeroEight: 2020-04-28]
Apparently I have the same issue…

```shell
# curl --connect-timeout 30 --head -v6 https://isthereanydeal.com
* Rebuilt URL to: https://isthereanydeal.com/
*   Trying 2a05:d018:f48:8a00:b474:141c:35e2:7ff7...
* Connected to isthereanydeal.com (2a05:d018:f48:8a00:b474:141c:35e2:7ff7) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* Operation timed out after 0 milliseconds with 0 out of 0 bytes received
* Closing connection 0
curl: (28) Operation timed out after 0 milliseconds with 0 out of 0 bytes received
```

‌

[Comment created by navarius: 2020-04-04]
It looks like this on my side:

```shell
curl --connect-timeout 30 --head -v6 https://isthereanydeal.com/
*   Trying 2a05:d018:f48:8a00:b474:141c:35e2:7ff7:443...
* TCP_NODELAY set
* Immediate connect fail for 2a05:d018:f48:8a00:b474:141c:35e2:7ff7: Network is unreachable
* Closing connection 0
curl: (7) Couldn't connect to server
```

But that doesn’t matter. I’m aware of the issue and **would love to fix it**, but don’t know how.

I do NOT block ICMP6 PTB packets in any part of configuration I am able to configure and I was able to ping6 using one of the web tools \(as well as confirmed by @Andrew above\), so general packets get through. But web is scarce of information how to set this up and even SO failed. Unless somebody is able to tell me / point me to something like “you need to set sysctl”, “you need to ask AWS to do this”,… - an actual solution - this will remain unfixed.

[Comment created by NHellFire: 2020-04-03]
This is still an issue. I have native IPv6 and can't load the site, others are fine. My firewall is allowing PMTUD.

[https://ipv6alizer.se?address=https://isthereanydeal.com](https://ipv6alizer.se?address=https://isthereanydeal.com) reports that you're blocking the PMTUD packets.

```
$ curl --connect-timeout 30 --head -v6 https://isthereanydeal.com/
*   Trying 2a05:d018:f48:8a00:b474:141c:35e2:7ff7...
* TCP_NODELAY set
* Connected to isthereanydeal.com (2a05:d018:f48:8a00:b474:141c:35e2:7ff7) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* Operation timed out after 30000 milliseconds with 0 out of 0 bytes received
* stopped the pause stream!
* Closing connection 0
curl: (28) Operation timed out after 30000 milliseconds with 0 out of 0 bytes received
```

‌

[Comment created by andrewvs: 2018-06-02]
Hi Thomas, apologies for the delayed response.

Regular ping6 does indeed work, however that is an ICMPv6 Echo Request (type 128), rather than Packet Too Big (type 2) .

There are a couple of web based tools I've come across to test PMTUD functionality of web servers, see https://ipv6alizer.se/ and https://wand.net.nz/pmtud/.

[Comment created by thomasnavara: 2018-05-20]
Hi, we don't block mentioned ICMPv6 messages on our side (not am I aware, that Amazon would do that).

Regular ping6 to our server works?

**Comment by MarkitkaM** [comment]
It is an old bug. We don't know, if it is still happening or not.
