### ISSUE TITLE
LEGO Batman 1 Steam version missing

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#102]
For some weird reason Steam is only store completely missing from this game.  
http://isthereanydeal.com/dots#/page:game/info?plain=legobatmanvideogame  
http://isthereanydeal.com/dots#/page:game/info?plain=legobatmandasvideospiel  
http://isthereanydeal.com/dots#/page:game/info?plain=legobatmanpack  
http://isthereanydeal.com/dots#/page:game/info?plain=legobatman  

Also the last link is supposed to ber merged but it isn't.  

[Issue created by Nokiaman: 2015-02-06]
[Last updated on bitbucket: 2019-02-01]

**Comment by MarkitkaM** [comment]
https://store.steampowered.com/search/?term=+LEGO+Batman
-> 

Steam is tracked -> https://isthereanydeal.com/game/legobatmanvideogame/info/
Not found at Steam->https://isthereanydeal.com/game/legobatmandasvideospiel/info/

**MERGE ENTRIES:**
https://isthereanydeal.com/game/legobatmanpack/info/
https://isthereanydeal.com/game/legobatman/info/
-> Steam is not tracked

**Comment by MarkitkaM** [comment]
Entries to merge #2324
