### ISSUE TITLE
Not All Stores Merging Properly

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1022]
Not all stores seem to be merging properly for some titles. For example, [Space Pirates and Zombies](https://isthereanydeal.com/search/?q=Space+Pirates+and+Zombies#/page:game/info?plain=spacepiratesandzombies) has a merge at [this longer title](https://isthereanydeal.com/search/?q=Space+Pirates+and+Zombies#/page:game/info?plain=spacepiratesandzombiesspaz), where at the "longer title" it still tracks the Humble Store. 

Since the merge from (longer title) version is still tracking Humble Store and gives the "This is an old entry" on the waitlist tab/page and prevents you from waitlisting it, the main title doesn't track Humble Store leaving a situation where you can't make a waitlist the Humble Store for this title.

[Issue created by MetalPlateMage: 2018-05-14]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
