### ISSUE TITLE
exported urls in csv are not working

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1025]
I just exported my collection to csv and noticed the urls linking to game pages don't seem to work. For example all links in my csv are urls like this :

https://isthereanydeal.com//#/page:game/info?=ysorigin

but this url does not work however if i change the url to the url below it works

https://isthereanydeal.com//#/page:game/info?plain=ysorigin

it somehow seems like the plain parameter is missing, unless the plain parameter can be something else as well then it might be intended to be exported like this. But i'm sure what other parameters besides plain it can be then. so it could be a bug or could be intended

i also noticed i have a double // after the domain however (in chrome) this does not produce a problem (for me)

[Issue created by [deleted]: 2018-05-14]
[Last updated on bitbucket: 2018-05-15]

[Comment created by tfedor: 2018-05-15]
Should be fixed now

**Comment by MarkitkaM** [comment]
![EXCEL_gMjEFXzst5](https://user-images.githubusercontent.com/88401908/137001050-3a6c3817-f954-4dd2-af17-787d77e2ba5f.png)
Fixed https://isthereanydeal.com/#/page:game/info?plain=ysorigin
