### ISSUE TITLE
Two different entries got mixed together due to same name

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1028]
Two different games on Steam - https://isthereanydeal.com/#/page:game/info?plain=greatescape
A game and a movie on Steam - https://isthereanydeal.com/#/page:game/info?plain=hardreset **Could not reproduce**

[Issue created by HYBRID_BEING: 2018-05-21]
[Last updated on bitbucket: 2020-12-26]

[Comment created by Bujno: 2020-12-26]
[https://isthereanydeal.com/game/halomasterchiefcollection/info/](https://isthereanydeal.com/game/halomasterchiefcollection/info/) \([https://store.steampowered.com/sub/376282/](https://store.steampowered.com/sub/376282/) and [https://store.steampowered.com/app/976730](https://store.steampowered.com/app/976730)\) **Could not reproduce**

![](https://bitbucket.org/repo/b6qGGA/images/1099998543-2020-12-26_23-02-35.png)
‌

[Comment created by HYBRID_BEING: 2019-02-12]
Escape Goat seems to be fixed, but here are another mixed entries:

https://isthereanydeal.com/game/minotaur/info/ **Duplication of the #1794**

https://isthereanydeal.com/game/dontdie/info/

And packages/bundles containing themselves:

https://isthereanydeal.com/game/iii0viiixiii0viiiixiv0viiiixtriplepack/info/

https://isthereanydeal.com/game/halospartanbundle/info/

https://isthereanydeal.com/game/trapthemdeluxebundle/info/ (also, "TrapThem" should be renamed to "Trap Them")

[Comment created by HYBRID_BEING: 2018-06-23]
And another strange one https://isthereanydeal.com/#/page:game/info?plain=escapegoat Now it's game and a bundle with said game (why the heck do they even have a bundle for a single game?).

[Comment created by tfedor: 2018-06-22]
Both should be fixed

[Comment created by HYBRID_BEING: 2018-06-22]
And yet another one https://isthereanydeal.com/#/page:game/info?plain=basement
**-> Duplication of the #1841**

[Comment created by HYBRID_BEING: 2018-06-21]
And another one https://isthereanydeal.com/search/?q=no+thing#/page:game/info?plain=nothing Now these have different names actually ("NO THING" and "The Nothing"), but ITAD chose a single slug ("nothing") for both, which is neither. **Duplication of the #1488**

[Comment created by HYBRID_BEING: 2018-06-17]
Ah, they just don't come up in search on ITAD.

[Comment created by tfedor: 2018-06-16]
What do you mean there are no entries?

* https://isthereanydeal.com/#/page:game/info?plain=greatescape
* https://isthereanydeal.com/#/page:game/info?plain=greatescape1

* https://isthereanydeal.com/#/page:game/info?plain=hardreset
* https://isthereanydeal.com/#/page:game/info?plain=hardreset1

Also fixed debris:

* https://isthereanydeal.com/#/page:game/info?plain=debris
* https://isthereanydeal.com/#/page:game/info?plain=debris1

[Comment created by speraas: 2018-06-15]
This same issues happened with two games by the name of "Debris", as I got notified about the anime one (https://store.steampowered.com/app/866180/Debris/) even though I only have the underwater one (https://store.steampowered.com/app/669660/Debris/) on my Waitlist.  
They are both listed as Steam entries on ITAD: https://isthereanydeal.com/#/page:game/info?plain=debris

[Comment created by HYBRID_BEING: 2018-06-14]
So, there are no entries for https://store.steampowered.com/app/434800/The_Great_Escape/ and https://store.steampowered.com/app/669970/Hard_Reset/ (wanted to have latter on waitlist) now? Both are searchable, at least in RU region.

**Comment by MarkitkaM** [comment]
Entries to split #2323
