### ISSUE TITLE
Crawl Game mispriced

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1036]
The game on Steam, "Crawl" is shown at the wrong price, because a video on Steam of the same name, "Crawl", is at that price. The ITAD price tracking algorithm likely mistook the title for Crawl the game. Please remove Crawl the film from ITAD's system.

[Issue created by [deleted]: 2018-05-30]

**Comment by MarkitkaM** [comment]
**SPLIT ENTRIES:**
https://isthereanydeal.com/game/crawl/info/
https://goldworldgames.itch.io/crawl
![chrome_LHuOBRw6hX](https://user-images.githubusercontent.com/88401908/136902245-58773762-aeb2-457c-b8d6-26ae9efcb4b2.png)

**Comment by MarkitkaM** [comment]
Entries to split - #2323
