### ISSUE TITLE
Wrong Prices in Email Alert

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1040]
.
I've got 3 email alerts today and they all have the wrong price. I set the price region as Brazil but as you can see in the attached screenshot, the prices don't match. Additionally it shows like it has a 0% discount (does this means the normal price went down?)

(Rimworld alert= 8 dollars, In steam (R$) = 15,57 dollars)

[Issue created by darius_bd: 2018-05-31]
[Last updated on bitbucket: 2018-06-14]

[Comment created by kraio: 2018-06-14]
As for me, it was solved! Now I'm receiving correct prices.
Thank you!

[Comment created by tfedor: 2018-06-14]
May I mark as solved? Regarding prices, I'm afraid there's nothing I can do, unfortunately. The best I can suggest is to reapply default settings.

[Comment created by darius_bd: 2018-06-02]
So far so good but the bug changed the prices at which ITAD would send the email alert ;/

[Comment created by tfedor: 2018-05-31]
I found the bug, please let me know in about a day whether you still see incorrect prices

[Comment created by tfedor: 2018-05-31]
No, I just need to check whether this is a currency conversion issue, a region specific issue, a parsing issue or something completely different :)

[Comment created by darius_bd: 2018-05-31]
I selected Brazil, yes, but I live in Chile (is the closest thing with prices). But that shouldn't affect it right?

[Comment created by tfedor: 2018-05-31]
Darius what's your region, Brazil?

[Comment created by kraio: 2018-05-31]
Same here. I'm receiving a lot of emails for a couple of days with wrong prices that has a 0% discount, up to utterly ridiculous like $0.2 for games with $10 real price. My region is Russia and my prices set in Roubles.

**Comment by MarkitkaM** [comment]
Solved within the conversation above.
