### ISSUE TITLE
Voidu deals return 404 error

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1049]
I have waitlisted:
Oh...Sir!! The Insult Simulator
Oh...Sir! The Hollywood Roast

and they are supposed to be on sale on Voidu according to ITAD, but the link takes me to a page not found screen. I searched for them Voidu on google (voidu.com doesn't even "have" these games) and I found them on tr.voidu.com: are these deals regional exclusives or something?

[Issue created by [deleted]: 2018-06-06]
[Last updated on bitbucket: 2018-06-14]

[Comment created by tfedor: 2018-06-14]
Yeah, this might be a regional issue

**Comment by MarkitkaM** [comment]
https://isthereanydeal.com/game/ohsirinsultsimulator/info/
https://isthereanydeal.com/game/ohsirhollywoodroast/info/

I did not find the Voidu store in any of the regions.
