### ISSUE TITLE
Wrong number of games found

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1069]
[Issue created by Bujno: 2018-06-19]

**Comment by MarkitkaM** [comment]
Not enough information.

**Comment by Korb** [comment]
Probably, the screenshot was lost when the bugtracker platform was changed.

**Comment by MarkitkaM** [comment]
@Korb  Thank you for the remark. Could you please reproduce the bug and send us the link?

The screenshot is here:
![image](https://user-images.githubusercontent.com/88401908/136895430-e6b11c0a-d2d7-41f0-891d-c467b0a6ff6b.png)

**Comment by Korb** [comment]
https://isthereanydeal.com/search/?q=%2B%22elder+scrolls%22+%2Bonline

Now at the top of the page is not
> 65 games were found for +"elder scrolls" +online

but
> Search Results for "+"elder scrolls" +online"

That is, the number of games found is not displayed, and the issue can be closed as it has lost its relevance in 3.5 years.
