### ISSUE TITLE
Unable to sync collection of over 9k games

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1072]
Ever since I gotten over 9,000 games in my library I've been unable to sync my collection: https://steamcommunity.com/profiles/76561197992076130/games/?tab=all

My collection is public as I was able to view it in private mode w/o logging in.

[Issue created by revlisoft: 2018-06-19]
[Last updated on bitbucket: 2018-06-20]

[Comment created by revlisoft: 2018-06-20]
It works now. Thanks

Vin

> 

[Comment created by tfedor: 2018-06-20]
Should be fixed, please verify

[Comment created by tfedor: 2018-06-20]
Issue #1073 was marked as a duplicate of this issue.

**Comment by MarkitkaM** [comment]
Solved within the conversation above.
