### ISSUE TITLE
The released date is bug ;)

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1087]
https://isthereanydeal.com/#/page:game/info?plain=deadcells

It says "Released 01 Jan 1970"

[Issue created by joker999: 2018-06-28]

**Comment by MarkitkaM** [comment]
Already correct.
![image](https://user-images.githubusercontent.com/88401908/137365510-c93fc4e9-11fd-420a-8cc9-b0cfb8280577.png)
