### ISSUE TITLE
Battlefield 4 Premium not showing prices

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1098]
I'd like to add BF4 Premium Edition to my waitlist, but it seems pointless because there are never any prices shown for it.

[This](https://isthereanydeal.com/#/page:game/info?plain=battlefieldivpremiumedition) link shows prices, but when I try to add it to my waitlist it tells me to instead use [this](https://isthereanydeal.com/#/page:game/info?plain=battlefieldivpremium) link. If you could either unmerge them or fix the prices for the new entry that would be great.

[Issue created by [deleted]: 2018-07-06]

**Comment by MarkitkaM** [comment]
Entries to merge - #2324
