### ISSUE TITLE
Trouble in signing in using Steam Account

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1100]
In the last week or so, i've been having an issue with the sign-in using my steam account. I've recently changed my account's password but i can log into steam without any problem.

However, logging into ISTAD using the steam account has stopped working. Although it prompts me to enter my 2-step-verification-token and everything but after that it shows me an invalid username/password error message.

[Issue created by [deleted]: 2018-07-06]

**Comment by MarkitkaM** [comment]
Not enough info from the "former user" of the bitbucket.
