### ISSUE TITLE
Cannot sync with Public Steam wishlist

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1104]
When I try to sync my steam Wishlist with your Waitlist, IT doesn'T work and I get a message saying that a private account cannot be synced. However, my Steam account is Public. Am I doing something wrong?
Thanks!
Alex

[Issue created by [deleted]: 2018-07-13]

[Comment created by tfedor: 2018-07-13]
To really confirm that your wishlist is public, please try to open it in private window. If it works in private window, I would need more info for debugging - ideally link to your profile.

**Comment by MarkitkaM** [comment]
No additional info from the user.
