### ISSUE TITLE
Wrong image for "The Bridge"

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1110]
For some reason the entry on ITAD for The Bridge is using the image from a game called Planet Jump.

[Issue created by [deleted]: 2018-07-15]

**Comment by MarkitkaM** [comment]
The picture is already correct:
https://isthereanydeal.com/game/thebridge/info/
![image](https://user-images.githubusercontent.com/88401908/136706157-5db6c735-95f4-42e0-bc01-526c0a385256.png)
