### ISSUE TITLE
Unable to edit/add Mount & Blade in my collection

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1113]
There are two entries for Mount & Blade: one @ "plain=mountandblade" and another @ "plain=mountblade". "mountandblade" is already in my collection from an old import. It has data as expected on the Info page and whatnot, but the Collection page simply displays the attached error message, which links me back to "mountblade". This "mountblade" doesn't seem to have any data at all and its Collection page has another error message linking right back to the first game.

[Issue created by [deleted]: 2018-07-16]

**Comment by MarkitkaM** [comment]
https://isthereanydeal.com/game/mountandblade/info/
https://isthereanydeal.com/game/mountblade/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
