### ISSUE TITLE
Sniper: Ghost Warrior 3 Season Pass Edition is tracking Season Pass, not the game

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1114]
Listing page: https://isthereanydeal.com/#/page:game/info?plain=sniperghostwarrioriiiseasonpassedition

I have a watchlist item for Sniper: Ghost Warrior 3 Season Pass Edition, but despite the title "Season Pass Edition" and matching image, the waitlist notification links to the Season Pass (DLC), not the Season Pass Edition (Game + DLC). All the links on the listing page above seem to be wrong too.

eg https://www.greenmangaming.com/games/sniper-ghost-warrior-3-season-pass/?utm_source=Tomas%20Fedor&utm_medium=affiliate&utm_campaign=cj

[Issue created by seanf: 2018-07-17]

**Comment by MarkitkaM** [comment]
Now it is marked as a DLC

**Comment by MarkitkaM** [comment]
Entries to split #2323

Almost all stores are listed twice once for **Sniper: Ghost Warrior 3 Season Pass Edition** and once for **Sniper: Ghost Warrior 3 Season Pass**. Must be split.
