### ISSUE TITLE
Cannot access Isthereanydeals.com

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1118]
hello, sometimes i cannot access the site for some reason it tells me I connot acess the web site!

[Issue created by [deleted]: 2018-07-19]
[Last updated on bitbucket: 2019-10-01]

[Comment created by NHellFire: 2019-10-01]
Also unable to load the site on IPv6, IPv4 works. Haven't found any other site that doesn't work on IPv6 and ICMPv6 tests \(including PMTUD\) pass from all my devices.

[Comment created by Dacxster: 2018-07-21]
Same problem here: for quite some time (several weeks) I haven't been able to access the site from pc, only from android device.

[Comment created by tfedor: 2018-07-19]
Another problem might be IPv6, there are some issues with that, but we don't have enough info to debug it yet

[Comment created by bb34887: 2018-07-19]
The problem could be anywhere between you and the server. Try doing a traceroute to isthereanydeal.com from the commandline and posting its output in a comment. (on Windows it's `tracert.exe`)

**Comment by MarkitkaM** [comment]
It is an old bug. We don't know, if it is still happening or not.
