### ISSUE TITLE
[Feature Request] Icons for game info page menu to improve usability

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#112]
Right now every time I need to use the menu (Info, DRM, DLCs, etc) I have to read through it and feel that it lacks a visual distinctiveness.

I think thematic icons on the left side could improve this situation.

[Issue created by enchained: 2015-02-13]
[Last updated on bitbucket: 2015-02-28]

[Comment created by tfedor: 2015-02-28]
Improved differentiation for when the game is in Waitlist and Collection. Icons are little problematic right  now, since we don't have capacity to create icons and keep them updated when new stuff is added. The fact that ITAD is iconless allows me to be more flexible.

[Comment created by enchained: 2015-02-16]
Also icons next to Add to Waitlist and Collection should be slightly different when the game is already in Waitlist/Collection. That kind of visual info often needed when I wonder if the game is already on Waitlist and have to check every time and even then the only difference is Add or Edit word on the button, so it's not very distinctive.

**Comment by MarkitkaM** [comment]
Solved.
