### ISSUE TITLE
Game page combines 2 games

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1124]
https://isthereanydeal.com/game/insane/info/ -- this page combines the games 1nsane and Insane.

1nsane - GOG, Metacritic, synopsis.
Insane - Steam, Fanatical, Gamersgate, header image.

[Issue created by [deleted]: 2018-07-22]

**Comment by MarkitkaM** [comment]
![chrome_IM1OIfVkMv](https://user-images.githubusercontent.com/88401908/136702955-8c58472e-3c65-43d4-80d4-7db38a84c670.png)

**Comment by MarkitkaM** [comment]
Entries to split #2323

**Comment by rob-stone** [comment]
@tfedor, @MarkitkaM: Issue should be re-opened, 2 completely different games are still combined under the same ITAD entry.
