### ISSUE TITLE
Game page combines 2 games (Pulstar)

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1125]
https://isthereanydeal.com/game/pulstar/info/ -- combines 2 different games with the same name.

[Issue created by [deleted]: 2018-07-22]

**Comment by MarkitkaM** [comment]
![chrome_ABjfRaTzCt](https://user-images.githubusercontent.com/88401908/136702808-8a1e18a0-8a34-4d82-9b04-45c56bd78a40.png)

**Comment by MarkitkaM** [comment]
Entries to split #2323
