### ISSUE TITLE
Prey (2017) and Prey - all stores actually point to Prey (2017)

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1130]
As the title says:

[https://isthereanydeal.com/game/preyii0ivii/info/
](Link URL)
[https://isthereanydeal.com/game/prey/info/
](Link URL)

All deals are for the same game: Prey (2017), even the Metacritic link of the latter points to the 2017 game.
The only references left to the 2006 game are the image and a broken link to Steam (since the game is no longer available there).

IMO it would make sense to merge those two into Prey (2017).

[Issue created by [deleted]: 2018-07-26]
[Last updated on bitbucket: 2018-07-29]

[Comment created by tfedor: 2018-07-29]
Should be merged.

**Comment by MarkitkaM** [comment]
Seem like they are not merged yet.. 
or here is still an older picture with a different logo https://isthereanydeal.com/game/prey/info/
![image](https://user-images.githubusercontent.com/88401908/136701348-18f1949f-7503-4318-a158-c7e47519e650.png)

But the link for Steam is not broken anymore.

**Comment by MarkitkaM** [comment]
Entries to merge #2324
