### ISSUE TITLE
Sid Meier's Pirates - Incorrect version

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1133]
Hi,

https://isthereanydeal.com/game/sidmeierspirates/info/

This is the page for Sid Meier's Pirates, the 2004 edition. You can see here that "Humble Widgets" sells the game for a lower price than the other stores. However, the version sold on Humble Widgets is the 1987 version. This caused confusion when I bought the game only to find out it wasn't what I wanted. I am currently trying to get a refund, but I just wanted to let you know so that this mix-up can be avoided in the future.

[Issue created by [deleted]: 2018-08-01]

**Comment by MarkitkaM** [comment]
Entries to split #2323
