### ISSUE TITLE
Two different games on same page

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1136]
Games:
https://store.steampowered.com/app/561970/REALITY/
https://store.steampowered.com/app/562280/reality/

should be separate, but is combined here:
https://isthereanydeal.com/game/reality/info/

[Issue created by [deleted]: 2018-08-03]

**Comment by MarkitkaM** [comment]
![image](https://user-images.githubusercontent.com/88401908/136698298-fb31e880-b419-4742-a7b9-8d1b8761fee4.png)

**Comment by MarkitkaM** [comment]
Entries to split #2323
