### ISSUE TITLE
Citadel: Forged with Fire error

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1142]
(https://isthereanydeal.com/game/citadel/info/)

Citadel: Forged with Fire (https://store.steampowered.com/app/487120/Citadel_Forged_with_Fire/), this game appears to be tracked on the same page as data for 
Citadel (https://store.steampowered.com/app/485590/Citadel/)

[Issue created by [deleted]: 2018-08-08]

**Comment by MarkitkaM** [comment]
![image](https://user-images.githubusercontent.com/88401908/136698045-05aaa07f-3402-47bf-b913-e8adfd335795.png)

**Comment by MarkitkaM** [comment]
Entries to split #2323

Duplication #1874
