### ISSUE TITLE
4 games that have x2 listings

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1163]
After checking my waitlist i noticed these 4 games having 2 listings under slightly different names and oddly enough not tracked by the same store even if they are the same product.
(**example:** 1 of them have a link to steam and the other listing **has the other stores that sell the game**)

**Nioh: Complete Edition / 仁王 Complete Edition**
https://isthereanydeal.com/game/niohcompleteeditionrenwangcompleteedition/info/

&
**Nioh: Complete Edition** 
https://isthereanydeal.com/game/niohcompleteedition/info/
---
**AER**
https://isthereanydeal.com/game/aer/info/

&
**AER Memories of Old**
https://isthereanydeal.com/game/aermemoriesofold/info/
---
**Conception II: Children of the Seven Stars**
https://isthereanydeal.com/game/conceptioniichildrenofsevenstars/info/

&
**Conception II**
https://isthereanydeal.com/game/conceptionii/info/
---
**Styx**
https://isthereanydeal.com/game/styx/info/

&
**Styx: Master of Shadows**
https://isthereanydeal.com/game/styxmasterofshadows/info/

[Issue created by [deleted]: 2018-08-28]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
