### ISSUE TITLE
Currency setting override

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1164]
Would be awesome to have currency configurable next to https://isthereanydeal.com/settings/account/?a=region and not tied to a region.

Use case: my country is in RU region, but I have no idea how much ruble costs and would like to see prices in USD instead.

[Issue created by Ugzuzg: 2018-08-28]
[Last updated on bitbucket: 2018-08-29]

[Comment created by Ugzuzg: 2018-08-29]
Thanks, that works.

[Comment created by tfedor: 2018-08-29]
Although there's not a setting, you can change your currency to anything the currency converter API we use support (so even bitcoins last time I checked), by adding ?currency=USD to the page. It should be stored in cookie after that.

**Comment by MarkitkaM** [comment]
Solved within the conversation above.
