### ISSUE TITLE
Wrong link to Steam on Game Page

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1173]
Your Game Page for this Game: https://isthereanydeal.com/game/scarf/info/

Your link: https://store.steampowered.com/app/**844740**/

Correct one: https://store.steampowered.com/app/**645320**/

[Issue created by [deleted]: 2018-09-17]

**Comment by MarkitkaM** [comment]
Entries to split #2323
