### ISSUE TITLE
Skyrim Special Edition 2game

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1177]
2game 19.99 is not for special edition, it is for standard skyrim. The offer expired in 2016. I did not read carefully enough and am out 18 dollars, but it should be removed from the listings.

[Issue created by [deleted]: 2018-09-22]

**Comment by MarkitkaM** [comment]
Seems like removed already https://isthereanydeal.com/specials/#/filter:&search/Skyrim%20Special%20Edition%202game
