### ISSUE TITLE
Mapping error for "The Hex"

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1182]
I have "The Hex" (steam id: 510420 [1]) on my steam wishlist, but the autosync seemed to have synced "Hex" (steam id: 727070 [2]) into my waitlist.

The game page [3] shows the logo of "The Hex", but links "Hex".

[1] https://store.steampowered.com/app/510420/The_Hex/
[2] https://store.steampowered.com/app/727070/Hex/
[3] https://isthereanydeal.com/game/hex/info/

[Issue created by [deleted]: 2018-09-25]

**Comment by MarkitkaM** [comment]
Duplication of the #1207
