### ISSUE TITLE
Oculus-only game "The Climb" is incorrectly grouped with a free Steam game just called "Climb"

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1199]
**SPLIT ENTRIES:**

This entry:

https://isthereanydeal.com/game/climb/info/#/

Is for a free-to-play Steam game, but it also is connected to the Oculus game "The Climb" for the Oculus Store entry, resulting in erroneous pricing info (The Climb is not available on Steam, much less free!)

The Climb's Oculus store price should be filed under this entry:
https://isthereanydeal.com/game/climboculusrift/info/

This entry has very little metadata, but does have some old prices from Amazon, which used to but no longer sells The Climb.

[Issue created by [deleted]: 2018-10-11]

**Comment by MarkitkaM** [comment]
Entries to split #2323
