### ISSUE TITLE
Singularity is linking to wrong game

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1201]
https://isthereanydeal.com/waitlist/?by=pricediff:desc#/page:game/info?plain=singularity

The Oculus Store is selling a different game for free

[Issue created by [deleted]: 2018-10-14]

**Comment by MarkitkaM** [comment]
The Oculus Store is not tracked anymore.

But Steam is linked twice and one of the trackings is wrong -> 
https://store.steampowered.com/app/1429890/Singularity/

![chrome_k9Qa5qxdUr](https://user-images.githubusercontent.com/88401908/136252879-7a934606-8023-4188-b9d1-53146df4a19e.png)

**Comment by MarkitkaM** [comment]
Entries to split #2323
