### ISSUE TITLE
Some Games Not Appearing in Search

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1206]
I am unable to find:
Assassin's Creed Odyssey >> https://store.steampowered.com/app/812140/Assassins_Creed_Odyssey/
World War 3 >> https://store.steampowered.com/app/674020/World_War_3/

[Issue created by [deleted]: 2018-10-19]

**Comment by MarkitkaM** [comment]
**Found:**
https://isthereanydeal.com/search/?q=Assassin%27s+Creed%C2%AE+Odyssey
https://isthereanydeal.com/search/?q=World+War+3
