### ISSUE TITLE
The Hex and Hex are being confused by the site

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1207]
https://store.steampowered.com/app/727070/Hex/ being linked when I have https://store.steampowered.com/app/510420/The_Hex/ on my waitlist.

[Issue created by [deleted]: 2018-10-20]

**Comment by MarkitkaM** [comment]
**SPLIT ENTRIES:**
https://isthereanydeal.com/game/hex/info/ -> 2x Steam
https://store.steampowered.com/app/727070/Hex/ https://store.steampowered.com/app/510420/The_Hex/ 

https://isthereanydeal.com/game/thehex/info/ - Any stores tracked.

**Comment by MarkitkaM** [comment]
Entries to split #2323
