### ISSUE TITLE
The Warlock of Firetop Mountain game listing bug

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1210]
https://isthereanydeal.com/game/warlockoffiretopmountain/info/

The listing has two Steam page links. The two links are for separate games, each with almost the same name. One has "(Fighting Fantasy Classics)" appended to the game name and is very cheap. The other is 19.99 and has added graphics.

Please split the page into two separate listings.

Regards,

PL

[Issue created by [deleted]: 2018-10-24]
[Last updated on bitbucket: 2018-10-28]

**Comment by ghost** [comment]
There are now two separate entries, but they both point to the less expensive version of the game. Can you fix the non-"(Fighting Fantasy Classics)" version to point to https://store.steampowered.com/app/324740/The_Warlock_of_Firetop_Mountain/

Thanks
