### ISSUE TITLE
Fly'n cannot be found in search, can be found in filter search

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1219]
Fly'n cannot be found in search
https://isthereanydeal.com/search/?q=Fly%27n

but can be found in filter search
https://isthereanydeal.com/#/filter:&search/Fly'n

[Issue created by zelgaris: 2018-10-30]

**Comment by MarkitkaM** [comment]
Already fixed https://isthereanydeal.com/search/?q=Fly%27n
