### ISSUE TITLE
Elite Dangerous: Horizons listed as 2 different titles for Steam & Humble Bundle stores

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1220]
... which defeats the purpose of price comparison.

This is exactly the same DLC:

https://isthereanydeal.com/game/elitedangeroushorizons/info/

https://isthereanydeal.com/game/elitedangeroushorizonsseasonpass/info/

[Issue created by [deleted]: 2018-10-31]

**Comment by MarkitkaM** [comment]
Any store is tracked actually for both.

**Comment by MarkitkaM** [comment]
Entries to merge #2324
