### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1223]
https://isthereanydeal.com/search/?q=Assassin's+Creed
![Clipboard02.png](https://bitbucket.org/repo/b6qGGA/images/265994315-Clipboard02.png)

[Issue created by SwampThing387: 2018-11-10]
[Last updated on bitbucket: 2018-11-28]

[Comment created by SwampThing387: 2018-11-28]
It's still broken!
Compare these results:

https://isthereanydeal.com/search/?q=Assassin's+Creed+Brotherhood

and

https://isthereanydeal.com/search/?q=Assassin's+Creed

**Comment by MarkitkaM** [comment]
Not broken anymore
