### ISSUE TITLE
Add third-state "Exclude" instead of only Include for filter.

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1227]
I cannot exclude DLC from the filter, only include it, applies across the board.

Some categories get around this by having all possible options, but others don't.

[Issue created by [deleted]: 2018-11-10]
[Last updated on bitbucket: 2018-11-14]

[Comment created by bb34887: 2018-11-14]
Select DLC, hover the mouse over the "DLC" in your Filters, and click "-":

![Screen Shot 2018-11-14 at 1.48.34 PM.png](https://bitbucket.org/repo/b6qGGA/images/2554941349-Screen%20Shot%202018-11-14%20at%201.48.34%20PM.png)

After only excluding DLCs, the URL I got was https://isthereanydeal.com/#/filter:-dlc

**Comment by MarkitkaM** [comment]
Solved within the conversation.
