### ISSUE TITLE
Metacritc typo

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1232]
On pages where a Metacritic score is shown (e.g. https://isthereanydeal.com/#/page:game/info?plain=saintsrowiv or https://isthereanydeal.com/game/saintsrowiv/info/), it's shown as "Metacritc User Score" (missing the second I). Just letting you know, since I couldn't see a mention of it elsewhere here.

[Issue created by [deleted]: 2018-11-20]

**Comment by MarkitkaM** [comment]
Already correct.
