### ISSUE TITLE
Mass Effect 3 wrong price

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1235]
It says on your site that Mass Effect 3 is available for 2,49 € in EU1. But on origin it costs 4,99 €. So if I'm not mistaken it is the wrong price.

Cheers

[Issue created by [deleted]: 2018-11-21]

[Comment created by tfedor: 2018-11-21]
What's your country?

**Comment by MarkitkaM** [comment]
Duplication of the #1688
