### ISSUE TITLE
Homepage doesn't track prices anymore ?

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1251]
Hi guys,

Is it me or the tracking prices isn't working anymore on the homepage ? Within a few exceptions, I think the list hasn't been refreshing since 1 or 2 days (Lara croft Go is in the first position since this weekend for instance).

Thx for all your work !

[Issue created by [deleted]: 2018-11-27]
[Last updated on bitbucket: 2018-12-02]

[Comment created by tfedor: 2018-12-02]
We have changed default sorting from Time to Trending. List is working fine.

**Comment by MarkitkaM** [comment]
Solved within coversation.
