### ISSUE TITLE
Wrong information on Yogcast jingle jam 2018 guild wars

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1259]
The email sent out and the link it sends you to for "Guild Wars 2: Path Of Fire Heroic Edition" is incorrect. The bundle is for the original Heroic edition(also now includes 2 past dlcs) and does not include path of fire. the coupon can be used to purchase any edition of the newest expansion path of fire though.

[Issue created by [deleted]: 2018-12-04]

**Comment by MarkitkaM** [comment]
https://isthereanydeal.com/game/guildwarsiiheroicedition/info/?
https://isthereanydeal.com/search/?q=+Guild+Wars+2%3A+Heroic+Edition

-> Entries to merge #2324

**Comment by MarkitkaM** [comment]
Former user of bitbucket.
