### ISSUE TITLE
Item shown on sale isn't

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1267]
Currently the website shows Stellaris DLC Apocalypse (And several other DLC for this game) as being discounted on Savemi.com.au but looking at the website none of these low prices exist and the games are being sold for full price. 

Example: https://www.savemi.com.au/product/stellaris-apocalypse-dlc-2/?ref=4773

[Issue created by [deleted]: 2018-12-11]

**Comment by MarkitkaM** [comment]
The shop does not exist anymore.
