### ISSUE TITLE
Please add https://www.instant-gaming.com/ to the database

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1268]
Google randomly suggested this site while I was looking for Crusader Kings II (after apparently mistakenly being reported going for $1 at GMG). It currently has the best deal by far for that game and many other games such as Staxel which is currently going for $10 less than *the best  historical* available in ITAD, or Dishonored 2 which currently is slightly beating the best historical deal as well. I think it would be a worthy addition. Thanks.

[Issue created by [deleted]: 2018-12-11]
[Last updated on bitbucket: 2019-02-12]

[Comment created by Knightw0lf: 2019-02-12]
Issue #978

this can be closed

**Comment by MarkitkaM** [comment]
Duplication of the #2025
