### ISSUE TITLE
Letter/title-based filtering bugged

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1282]
On the main page's filterable list of deals, I was attempting to filter a list of sales for a store, sorted by title for ease - only to discover that the sort by "title" is now no longer present? (Is that a bug too?)

Attempting to work around this issue by restricting the list to single letter sections (# A B etc.) has brought a bug to light: combining the alphabet filter with any store filter interacts wrongly with the store filter.

The fastest way to reproduce this is to use the Epic store, as the only game listed on-sale at this time is Super Meat Boy. (Blizzard also works due to small game count.) The below were all tried from the main page with its default unfiltered/unsorted layout:

**Works:**
* Filter for Epic store.
* Result: SMB shows up as the only entry as expected.

**Works:**
* Filter for a letter + a non-store filter.
* Result: Games for the selected letter are filtered as expected.

**Doesn't work:**
* Filter for any letter + Filter for Epic store. (Order does not matter.)
* Result: All entries for the selected letter *plus* the entry for SMB show up in the list.
* *Expected result*: The "S" + "Epic" filter combo should show SMB as the only entry. All other letters combined with the filter should show the usual "no games match" error.

[Issue created by [deleted]: 2018-12-29]
[Last updated on bitbucket: 2018-12-31]

[Comment created by Arth1284: 2018-12-31]
Hello, original anon here - thank you for the reminder about the filter info pages. Removing that "+" **does** make it behave as I desired, so that's entirely my error and I would like to humbly apologize.

However, it does make me wonder if this default "OR" setting on the letter restriction may be less intuitive for the average user? It looks like every other non-store filter defaults to a restricted no-"+" setting, so the letter filters behaving "inconsistently" was what tripped me up in this case as I'd never used this filter before. (Of course, I don't know how many users regularly restrict to multiple letters at a time vs. one letter only.)

Regarding the sort-by-title removal: when you have the time, would you mind sharing the reason it is considered obsolete? I am genuinely puzzled because I can't really think of any site/software which presents a list of items that does *not* have an alphabetical sort, so I've always considered it "standard". I know when I'm faced with a sluggish/unfriendly storefront or one with terrible filters, I'd rather spend a mere fraction of that time coming to ITAD and filtering that store appropriately to view the deals - so title-sort gave lists that were very quick to read, and also grouped (most) games & their dlcs together.

*(PS: Please do forgive my questioning - I love ITAD dearly, and appreciate the amazing work you have been doing all these years!)*

[Comment created by tfedor: 2018-12-30]
We have removed sort by title because we think it's obsolete. For filters, those should still work, but you have to remove "+" by clicking on a tag. Check "How filters interact" here: https://isthereanydeal.com/about/filters/basics/

**Comment by MarkitkaM** [comment]
Solved within the conversation. Not a bug.
