### ISSUE TITLE
Prices Missing for Sid Meiers Civilization VI Gold

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1286]
The listing for [Sid Meiers Civilization VI Gold](https://isthereanydeal.com/game/sidmeierscivilizationvigold/info/) doesn't show any prices.
However, it's on sale at a number of places that you normally track including [Steam](https://store.steampowered.com/bundle/9193/Sid_Meiers_Civilization_VI_Gold_Edition/) and [WinGameStore](https://www.wingamestore.com/product/9876/Sid-Meiers-Civilization-VI-Gold-Edition/).  Perhaps the problem is that the name in your system is slightly different from the name used on these other sites?

[Issue created by Green_Fox: 2019-01-01]

[Comment created by tfedor: 2019-01-01]
https://isthereanydeal.com/#/page:game/info?plain=sidmeierscivilizationvigoldedition

**Comment by MarkitkaM** [comment]
Entries to split #2323
Entries to merge #2324
