### ISSUE TITLE
In need of a merge for Tempest. Thanks!

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1298]
As seen here:

https://isthereanydeal.com/game/tempest/info/
and
https://isthereanydeal.com/game/tempestpirateactionrpg/info/

[Issue created by buckthebit: 2019-01-16]
[Last updated on bitbucket: 2021-07-13]

[Comment created by HYBRID_BEING: 2021-07-13]
Explains why i’m not getting any notification <\_<

**Comment by MarkitkaM** [comment]
Entries to merge #2324
