### ISSUE TITLE
Duplicate DLCs

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1303]
A lot of the DLCs for 100% Orange Juice is duplicated. There are separate positions for Steam and other stores.
https://isthereanydeal.com/game/i00orangejuice/info/

Only DLCs with "&" in name seem to be affected.
Additionally the below DLC appears 3 times.
100% Orange Juice - Kiriko & NoName Character Pack
100% Orange Juice - Kiriko & NoName Pack
100% Orange Juice - Kiriko & NoName Character Pack

[Issue created by [deleted]: 2019-01-19]

**Comment by MarkitkaM** [comment]
https://isthereanydeal.com/search/?q=100%25+Orange+Juice

**Comment by MarkitkaM** [comment]
Entries to merge #2324
