### ISSUE TITLE
Sid Meier's Alpha Centauri on GOG not being tracked/reported

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1313]
Only Origin is displayed for pricing info and history, regardless of region.

[Issue created by [deleted]: 2019-01-31]

[Comment created by tfedor: 2019-01-31]
GOG lists Planetary Pack, which includes expansion. I'm not sure Origin does as well.

Here it is on GOG https://isthereanydeal.com/game/sidmeiersalphacentauriplanetarypack/info/

**Comment by MarkitkaM** [comment]
https://isthereanydeal.com/search/?q=Sid+Meier%27s+Alpha+Centauri

**Comment by MarkitkaM** [comment]
There is no planetary pack at Origin https://www.origin.com/idn/en-us/search?searchString=Sid%2520Meier%27s%2520Alpha%2520Centauri%25E2%2584%25A2
