### ISSUE TITLE
Steam profile sync links some wrong game in the ITAD collection

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1314]
When the Steam library is imported in the ITAD collection some of the linked games are not correct.

For example: 
- In the Steam library I have "Poker Night 2" but on ITAD it is linked as "Poker Night at the Inventory"
- The steam game "Edna and harvey: Harvey's new Eyes" is linked as "Deadelic Adventure Bundle"
(there are few other games with the same issue)

[Issue created by [deleted]: 2019-02-02]

**Comment by MarkitkaM** [comment]
1. **MERGE ENTRIES:**
"Poker Night 2"
-> Any store listed 
https://isthereanydeal.com/game/pokernightii/info/
https://isthereanydeal.com/game/pokernightiimac/info/

2.  "Poker Night at the Inventory"
https://isthereanydeal.com/game/pokernightatinventory/info/ - Any store listed

3. **MERGE ENTRIES:**
"Edna and harvey: Harvey's new Eyes"
Steam is linked correctly
https://isthereanydeal.com/game/ednaharveyharveysneweyes/info/
https://isthereanydeal.com/game/ednaandharveyharveysneweyes/info/

4. Deadelic Adventure Bundle - Not found on ITAD.

**Comment by MarkitkaM** [comment]
ad4) Not found on ITAD

Entries to merge #2324
