### ISSUE TITLE
Set Custom Discount / Coupon / Cut

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1317]
I want to be able to set my own custom discounts.

Example: I'm a premium user for the german games site Gamestar and get a 5% discount on Gamesplanet(de). I want to be able set this 5% discount in my profile, so it it taken into consideration when I compare the best prices.

[Issue created by [deleted]: 2019-02-04]

[Comment created by Bugsh0t: 2019-02-04]
Solution:

Go to: https://isthereanydeal.com/settings/stores/ , search for your store and enter multiplyer: 0.95

**Comment by MarkitkaM** [comment]
Solved via issue.
