### ISSUE TITLE
Total number of my collections ?

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1319]
I'd like to see total number of my collections in the Collections page. Thanks!

[Issue created by [deleted]: 2019-02-05]

**Comment by MarkitkaM** [comment]
Done at alfa https://new.isthereanydeal.com/

![chrome_JUfUbzB9kG](https://user-images.githubusercontent.com/88401908/135883156-27e799e9-04dd-415f-9959-2f712fc4034f.png)
