### ISSUE TITLE
[Merge] Age of Wonders III Collection

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1325]
Three entries - second is empty, third only contains Steam store, from which it was already pulled.

https://isthereanydeal.com/game/ageofwondersiiicollection/info/

https://isthereanydeal.com/game/ageofwondersiiicollectiondigital/info/

https://isthereanydeal.com/game/ageofwondersiiicollectionrucis/info/

[Issue created by HYBRID_BEING: 2019-02-12]

**Comment by MarkitkaM** [comment]
Related #1792

**Comment by MarkitkaM** [comment]
Entries to merge #2324
