### ISSUE TITLE
[Merge] Blades of Times

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1326]
Two entries for Limited Edition:

https://isthereanydeal.com/game/bladesoftimelimitededition/info/

https://isthereanydeal.com/game/bladesoftimeslimitededition/info/

Secondly, there are 3 entries for Dismal Swamp DLC - the latter two are empty and not searchable, but are shown in DLC list and Limited Edition contents.

https://isthereanydeal.com/game/bladesoftimedismalswamp/info/

https://isthereanydeal.com/game/dismalswamp/info/

https://isthereanydeal.com/game/dismalswampdlc/info/

Also, dunno if MAC version should be separate entries, but there are also two entries for Limited Edition:

https://isthereanydeal.com/game/bladesoftimelimitededitionmac/info/

https://isthereanydeal.com/game/bladesoftimelimitededitionpcmac/info/ (seems to be empty)

[Issue created by HYBRID_BEING: 2019-02-12]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
