### ISSUE TITLE
The Stalker, wrong name, wrong image

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1331]
**SPLIT ENTRIES:**

[Stalker](https://isthereanydeal.com/game/stalker/info/) : 
This is presented with false name S.T.A.L.K.E.R. and incorrect image from the game S.T.A.L.K.E.R.: Shadow of Chernobyl . 
Actual only game link in Microsoft Store is for some game called "The Stalker" (store link is also hardlinked to a French language subpage instead expected general english?)

[Issue created by [deleted]: 2019-02-20]

**Comment by MarkitkaM** [comment]
Steam and itch.io are all completely different games.

**Comment by MarkitkaM** [comment]
Duplication of the #2009.
