### ISSUE TITLE
Distant Worlds: Universe has 2 ITAD entries which should be merged

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1337]
**MERGE ENTRIES:**
Distant Worlds: Universe has 2 ITAD entries: https://isthereanydeal.com/game/distantworlds/info/ (which only has Steam prices but Steam page directs to Distant Worlds: Universe) and  https://isthereanydeal.com/game/distantworldsuniverse/info/ (which lacks Steam prices)

[Issue created by TheLuax: 2019-02-22]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
