### ISSUE TITLE
Warhammer: Vermintide 2 - Shadows Over Bögenhafen has two entries

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1339]
Warhammer: Vermintide 2 - Shadows Over Bögenhafen has two entries:

One has the DLC name correctly spelled:
https://isthereanydeal.com/game/warhammervermintideiishadowsoverbogenhafen/info/
and here is the other with the incorrect spelling: 
https://isthereanydeal.com/game/warhammervermintideiishadowsoverbgenhafen/info/

[Issue created by sandpaperbackrub: 2019-02-27]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
