### ISSUE TITLE
Resident Evil 2 - Multiple Listings

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1341]
Searching for Resident Evil 2 will list multiple options.

https://isthereanydeal.com/game/residenteviliibiohazardreii/info/
https://isthereanydeal.com/game/residentevilii/info/
https://isthereanydeal.com/game/residenteviliibiohazardreiistandardedition/info/

Oddly the last one cannot even be found when searching "Resident Evil 2"

[Issue created by [deleted]: 2019-03-02]

**Comment by MarkitkaM** [comment]
> Oddly the last one cannot even be found when searching "Resident Evil 2"
> https://isthereanydeal.com/search/?q=resident+evil+2%C2%A8

#1341

> Searching for Resident Evil 2 will list multiple options.

Entries to merge #2324
