### ISSUE TITLE
Fix Dragon Ball FighterZ title

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1344]
https://isthereanydeal.com/game/dragonballfighterz/info

The game shows up as Dragon Ball Fighter Z, which consequently doesn't show up in search when you type "dragon ball fighterz". All the DLC and other editions show up correctly. 
To clarify, the correct title is FighterZ, with no space.

[Issue created by [deleted]: 2019-03-09]

**Comment by MarkitkaM** [comment]
On Alpha is this game showing up 
https://new.isthereanydeal.com/search/?q=dragon%20ball%20fighterz
https://new.isthereanydeal.com/game/dragonballfighterz/info/
