### ISSUE TITLE
[Duplicates] Truberbrook / Trüberbrook

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1348]
**MERGE ENTRIES:**

All the same game:

https://isthereanydeal.com/game/truberbrooktruberbrook/info/
https://isthereanydeal.com/game/truberbrook/info/
https://isthereanydeal.com/game/truberbrookanerdsavesworld/info/#/

[Issue created by [deleted]: 2019-03-12]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
