### ISSUE TITLE
Unable to sync via steam, also unable to delete collection

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1353]
Hello, 

I've been unable to sync my game collection to http://steamcommunity.com/profiles/76561198024933135 

It is reporting the following error: 

There was an unknown error during sync, please try again 

I have attempted to sync on Chrome, Edge and have deleted and re added the steam profile to the account. 

I have attempted to delete my collection to re-import my collection, but I am unable to delete the collection. 

Regards,

[Issue created by [deleted]: 2019-03-18]

**Comment by MarkitkaM** [comment]
I tried to sync, delete and sync again this collection. I could not reproduce the bug.
