### ISSUE TITLE
Devil May Cry 5 has 2 listings on ITAD

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1354]
There's https://isthereanydeal.com/game/devilmaycryv/info/ and https://isthereanydeal.com/game/devilmaycryvstandardedition/info/ which are the same
+ the first one doesn't have a game image.

Originally on Discord #bugs by Bobtree#5852

[Issue created by zelgaris: 2019-03-18]

**Comment by MarkitkaM** [comment]
Duplication of the #1389
