### ISSUE TITLE
Evolution page is holding two distinct games

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1364]
**SPLIT ENTRIES:**
"Evolution" and "Evolution : The Video Game" are two existing and distinct games and should have different pages in ITAD.
https://isthereanydeal.com/search/?q=evolution

[Issue created by [deleted]: 2019-04-05]

**Comment by MarkitkaM** [comment]
Entries to split #2323
