### ISSUE TITLE
Crusader Kings 2 DLC shouldn't have separate pages for each store

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1372]
Why CK2 dlc are separate for each store and not just all stores listed in one CK2 DLC page?
For example 
https://isthereanydeal.com/game/crusaderkingsiimonksandmystics/info/
https://isthereanydeal.com/game/crusaderkingsiimonksandmysticsdlc/info/
https://isthereanydeal.com/game/expansioncrusaderkingsiimonksandmystics/info/

[Issue created by gonsi_: 2019-04-13]

**Comment by MarkitkaM** [comment]
**MERGE ENTRIES**

**Comment by MarkitkaM** [comment]
Entries to merge #2324
