### ISSUE TITLE
Color coding/font styling not displaying correctly on game info pages

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1377]
Example: Katamari Damacy Reroll (https://isthereanydeal.com/#/page:game/info?plain=katamaridamacyreroll) is currently at a new historically lowest price of $11.94. Game info page reflects this price but displays in blue color with no font styling, making it more difficult to identify at a glance. Unsure if specific to certain games, my account's settings, or the site as a whole.

Additionally, there seems to be a discrepancy between color coding on the main page and color coding on game info pages. Example: Obra Dinn displays golden color with underline on main page for new historically lowest price; game info page lists this price in green with no font styling.

Many thanks!

[Issue created by [deleted]: 2019-04-22]

**Comment by MarkitkaM** [comment]
New web is comming soon. Won't fix.
