### ISSUE TITLE
Some packages as Devil may cry 5 Deluxe editon listed with incorrect price in steam store

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1389]
Hi, istheranydeal.com is reporting some prices of special editon games on steam store as if you already had that game and you are only buying the extra content in the edition (that's what i think). Devil may cry 5 Deluxe edition is listed in your page as on steam has a price of only 21,46 while if you check steam webpage its being sold for 71,25 witch is a hugue difference. This only happens with steam store, the rest of the stores list the correct price.

Greetings.

[Issue created by [deleted]: 2019-05-06]
[Last updated on bitbucket: 2019-07-05]

[Comment created by t_guerin: 2019-07-05]
Clone of #1345

**Comment by MarkitkaM** [comment]
**MERGE ENTRIES:**
https://isthereanydeal.com/game/devilmaycryv/info/
https://isthereanydeal.com/game/devilmaycryvstandardedition/info/

**Comment by MarkitkaM** [comment]
https://github.com/IsThereAnyDeal/IsThereAnyDeal-Issues/issues/2324
