### ISSUE TITLE
Mortal Kombat 11 Kombat Pack Steam page links to Mortal Kombat X's Kombat Pack using Augmented Steam

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1393]
As in the title, on the Steam page for [Mortal Kombat 11 Kombat Pack](https://store.steampowered.com/app/1054480/Mortal_Kombat_11_Kombat_Pack/) (The "season pass" for the game), Augmented Steam links to the [Mortal Kombat X Kombat Pack](https://store.steampowered.com/app/347880/Kombat_Pack/) when looking at current/lowest prices and 'Info' link.

The ITAD link for Mortal Kombat 11's Kombat Pack is https://isthereanydeal.com/game/mortalkombatiikombatpack/ (Which does not have Steam listed among the stores and prices)

The Steam page links to https://isthereanydeal.com/game/kombatpack/info/ (Which has two separate listings for Steam, both app/347880 and app/1054480)

app/347880 is MKX's Kombat Pack, and app/1054480 is the 'korrect' MK11 Kombat Pack

[Issue created by [deleted]: 2019-05-18]

**Comment by MarkitkaM** [comment]
https://store.steampowered.com/agecheck/app/1054480/
https://store.steampowered.com/agecheck/app/347880/

**Comment by MarkitkaM** [comment]
-> #2359
