### ISSUE TITLE
Multiple entries

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1396]
There are multiple entries which could possibly be fused for Okami HD and Divinity; Original Sin 2 (called Definitive Edition for GOG and still just D:OS 2 for Steam).

[Issue created by [deleted]: 2019-05-20]

**Comment by MarkitkaM** [comment]
**Okami HD**
https://isthereanydeal.com/game/okamihd/info/
Newegg - broken link http://www.qksrv.net/media/offers/?AID=10446076&PID=6305441&URL=https%3A%2F%2Fwww.newegg.com%2Fcapcom-okami-hd%2Fp%2FN82E16832233116&utm_medium=affiliates&utm_source=afc-IsThereAnyDeal+s.r.o.&cjevent=3d4c1c4b207f11ec8160f3d30a180510

Humble store - leads to the home page https://www.humblebundle.com/store/p/okamihd_switch_storefront

**Divinity; Original Sin 2**
https://isthereanydeal.com/game/divinityoriginalsiniidefinitiveedition/info/
- Humble store leads to the homepage https://www.humblebundle.com/store/p/divinity_originalsin2_definitiveedition_switch_storefront

**Comment by MarkitkaM** [comment]
**MERGE ENTRIES:**

**Okami HD**
https://isthereanydeal.com/game/okamihd/info/
https://isthereanydeal.com/game/okamihddashenjuejingban/info/

**Comment by MarkitkaM** [comment]
The rest moved to separated issues #2362 #2362 #2363 + Entries to split #2323
