### ISSUE TITLE
Two games named Osiris under one profile

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1398]
https://store.steampowered.com/app/402710/Osiris_New_Dawn/
https://store.steampowered.com/app/997000/OSIRIS/

Two different games have one profile on ITAD.

[Issue created by [deleted]: 2019-05-21]

**Comment by MarkitkaM** [comment]
https://isthereanydeal.com/game/osiris/info/

**Comment by MarkitkaM** [comment]
Entries to split #2323
Duplication #568
