### ISSUE TITLE
Keep getting alerts for games which are not on sale

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#142]
For the last week (and maybe longer) I have been getting email price alerts for games that have reached my minimum price in my waitlist. When I go to the game however they are never on sale.

The latest one is Legend of Grimrock 50% off at GOG. Its not on sale at all.
Yesterday I had Darkness Within: In Pursuit of Loath Nolder for 76p at Green Man. Not on sale. 
The bundle offers seem to be okay though. 
Is this a problem with my waitlist?

[Issue created by janner66: 2015-03-07]
[Last updated on bitbucket: 2018-11-10]

[Comment created by Bujno: 2018-11-10]
> E.g. for Tempest it is here: https://isthereanydeal.com/waitlist/#/page:game/wait?plain=tempest or you can see it in your Waitlist

![Image 006.png](https://bitbucket.org/repo/b6qGGA/images/2293465956-Image%20006.png)

![Image 007.png](https://bitbucket.org/repo/b6qGGA/images/1327453197-Image%20007.png)

[Comment created by tfedor: 2018-11-08]
Because of the "Notify about each price change", you are receiving notifications for games that are not on sale. Can you check what's your notificatino limit for the games that you have received notifications? E.g. for Tempest it is here: https://isthereanydeal.com/waitlist/#/page:game/wait?plain=tempest or you can see it in your Waitlist

[Comment created by Bujno: 2018-11-07]
"Notify me when price is" - "less than my notification limit"

"Notify about each price change" - on

[Comment created by tfedor: 2018-11-07]
Do you have this option turned on? https://isthereanydeal.com/settings/waitlist/?a=notifyNondeals

[Comment created by Bujno: 2018-11-07]
Neverwinter Nights: Enhanced Edition Digital Deluxe Edition - 1299 RUR

Tempest - 349 RUR

but

---------- Forwarded message ---------

From: IsThereAnyDeal.com

Date: Wed, 7 Nov 2018 at 16:40

Subject: Waitlist x2: Neverwinter Nights: Enhanced Edition Digital Deluxe Edition 52 p., Tempest: Pirate Action RPG 15 p.

Having troubles displaying email? See it on web.

Neverwinter Nights: Enhanced Edition Digital Deluxe Edition

52,09 p. (-0%) on GOG, DRM Free (Default)

Tempest: Pirate Action RPG

Historical low: 11,99 p. | Last: 14,99 p. | Best: 14,99 p.

14,99 p. (-0%) on GOG, DRM Free (Default)

[Comment created by Bujno: 2018-11-05]
Prices is [429](https://www.gog.com/game/legend_of_grimrock_2), [349](https://www.gog.com/game/screencheat), and [599](https://www.gog.com/game/wasteland_2_directors_cut_digital_classic_edition) RUR.

---------- Forwarded message ---------

From: IsThereAnyDeal.com <waitlist [dog] isthereanydeal.com>

Date: Mon, 5 Nov 2018 at 18:31

Subject: Waitlist x3: Legend of Grimrock II 24 p., Screencheat 15 p., Wasteland 2 Director's Cut Digital Classic Edition 40 p.

Legend of Grimrock II

Historical low: 23,99 p. | Last: 23,99 p. | Best: 23,99 p.

**23,99 p.** (-0%) on GOG, DRM Free (Default)

Screencheat

Historical low: 3,79 p. | Last: 14,99 p. | Best: 14,99 p.

**14,99 p.** (-0%) on GOG, DRM Free (Default)

Wasteland 2 Director's Cut Digital Classic Edition

Historical low: 149,00 p. | Last: 39,99 p. | Best: 39,99 p.

**39,99 p.** (-0%) on GOG, DRM Free (Default)

[Comment created by tfedor: 2015-03-13]
On hold until more details are provided.

[Comment created by tfedor: 2015-03-08]
I'm not sure unless you provide more details. Please report back with links from the notification emails so I can check.
As far as GOG goes, they are currently running "limited-stock" deals, so it is more than probable than when you got to the store the deal was already gone.

I'm not sure about GMG though.

**Comment by MarkitkaM** [comment]
Solved.
