### ISSUE TITLE
Vessel (2012) has a listing on itch.io which isn't the actual game

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1424]
The game Vessel \([https://isthereanydeal.com/game/vessel/info/](https://isthereanydeal.com/game/vessel/info/)\) has a listing on [itch.io](http://itch.io) which leads to some other game of the same name.

[Issue created by anups303: 2019-06-21]

**Comment by MarkitkaM** [comment]
Duplication of the #1808
