### ISSUE TITLE
Tales from the Borderlands / The Walking Dead: The Final Season

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1427]
These two games aren’t sold on Steam any more, but are still displayed with a Steam price at ITAD.

[https://isthereanydeal.com/game/talesfromborderlands/history/](https://isthereanydeal.com/game/talesfromborderlands/history/)

https://isthereanydeal.com/game/walkingdeadfinalseason/history/

[Issue created by pizzahut2: 2019-06-25]

**Comment by MarkitkaM** [comment]
Games are selling on Steam:

**Tales from borderlands**
https://store.steampowered.com/app/330830/Tales_from_the_Borderlands/

**Walking dead**
https://store.steampowered.com/app/866800/The_Walking_Dead_The_Final_Season/
