### ISSUE TITLE
Sky Hunter - 2 different games in profile

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1428]
**SPLIT ENTRIES:**
Sky Hunter is Helicopter Combat game sold on Steam. But in the ITAD profile of this game, there is also link to Itch.io distributor. But this is completely different game (some novel adaptation). 

See link:
https://isthereanydeal.com/waitlist/?by=price:asc#/page:game/info?plain=skyhunter

[Issue created by [deleted]: 2019-06-28]

**Comment by MarkitkaM** [comment]
Entries to split #2323
