### ISSUE TITLE
Euro symbols on graph axis displayed as &euro

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1431]
Euro symbols are not properly rendered on graphs like here: [/game/grandtheftautovpremiumonlineedition/history/#/chart:history](https://isthereanydeal.com/game/grandtheftautovpremiumonlineedition/history/#/chart:history)
![image](https://user-images.githubusercontent.com/88401908/135119270-49bb156e-0a57-4f76-b136-32aa81119e77.png)

[Issue created by [deleted]: 2019-07-03]

**Comment by MarkitkaM** [comment]
Fixed.
