### ISSUE TITLE
Forza Horizon 4 Standard Edition Not showing up

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1433]
The price is not showing up from the Windows Store, or anywhere for that matter. The game is currently being sold on the windows store at full price.

Just thought you guys might want to know.

https://www.microsoft.com/en-us/p/forza-horizon-4-standard-edition/9pnjxvcvwd4k?activetab=pivot%3aoverviewtab

[Issue created by [deleted]: 2019-07-04]

**Comment by MarkitkaM** [comment]
Microsoft is already tracked https://isthereanydeal.com/game/forzahorizonivstandardedition/info/
![image](https://user-images.githubusercontent.com/88401908/135116537-240abcc6-5a56-439a-8697-726485a57fde.png)
