### ISSUE TITLE
Party Hard 2 - incorrecly shown on the site

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1435]
SPLIT ENTRIES:
Party Hard 2 [https://isthereanydeal.com/game/partyhardii/info/](https://isthereanydeal.com/game/partyhardii/info/)

 has incorrectly shown pages on the site ... as seen in pictures

[Issue created by [deleted]: 2019-07-08]

**Comment by MarkitkaM** [comment]
Entries to split #2323
