### ISSUE TITLE
Three unrelated steam games on same listing

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1437]
**SPLIT ENTRIES:**

https://isthereanydeal.com/game/home/info/

Three steam games with "home" in title are in same listing

I suggest the following links

https://store.steampowered.com/app/215670/
https://www.humblebundle.com/store/p/home_storefront

be migrated to the existing duplicate listing

https://isthereanydeal.com/game/homeauniquehorroradventure/info/

[Issue created by [deleted]: 2019-07-10]

**Comment by MarkitkaM** [comment]
Entries to split #2323
