### ISSUE TITLE
"Gabriel Knight: Sins of the Fathers – 20th Anniversary Edition" misplaced

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1446]
In the page of Gabriel Knight: Sins of Fathers \(The original one from 1993\) [https://isthereanydeal.com/game/gabrielknightsinsoffathers/info/#/](https://isthereanydeal.com/game/gabrielknightsinsoffathers/info/#/) there is two Steam version, one of them should be in the page of 20th Anniversary Edition [https://isthereanydeal.com/game/gabrielknightsinsoffathersii0thanniversaryedition/info/](https://isthereanydeal.com/game/gabrielknightsinsoffathersii0thanniversaryedition/info/)  
  
Also there is another 20th Anniversary Edition [https://isthereanydeal.com/game/gabrielknightsinsoffatherii0thanniversaryedition/info/](https://isthereanydeal.com/game/gabrielknightsinsoffatherii0thanniversaryedition/info/) maybe should be merged with the other one \(if there isn’t any reason behind that\)

[Issue created by LukasThyWalls: 2019-07-21]

**Comment by MarkitkaM** [comment]
Entries to split #2323
Entries to merge #2324
