### ISSUE TITLE
No differentiation between Vertigo and Vertigo!

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1456]
I created a notification for Vertigo, but it is showing price alerts for Vertigo! also.

https://store.steampowered.com/app/465430/Vertigo/

https://store.steampowered.com/app/1059000/Vertigo/

[Issue created by [deleted]: 2019-08-09]

**Comment by MarkitkaM** [comment]
**SPLIT ENTRIES:**
https://isthereanydeal.com/game/vertigo/info/

**Comment by MarkitkaM** [comment]
Duplication of the #1514.
