### ISSUE TITLE
[Deals] Some games are missing in search results on the main page

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#146]
All this games are sold somewhere, but I can find them only from my waitlist. Some of these games were on sale when I searched, some weren't. I noticed this problem in the last couple of days.

The Ball
http://isthereanydeal.com/waitlist/#/page:game/info?plain=ball

DARK
http://isthereanydeal.com/waitlist/#/page:game/info?plain=dark

~~ Simon the Sorcerer 4: Chaos happens
http://isthereanydeal.com/waitlist/#/page:game/info?plain=simonsorcererivchaoshappens ~~

~~Worldshift
http://isthereanydeal.com/waitlist/#/page:game/info?plain=worldshift~~

Shad'O  - this one is not in my waitlist, I can access it only form enhanced steam link to the ITAD game info page
http://isthereanydeal.com/#/page:game/info?plain=shado

Maybe it's global and there are more games having this problem.

[Issue created by enchained: 2015-03-15]

[Comment created by tfedor: 2015-03-15]
ShadO changed to Shad'O

[Comment created by enchained: 2015-03-15]
Thank you, I will use this workaround for now.

Could you please change ShadO (http://isthereanydeal.com/#/page:game/info?plain=shado) game name to Shad'O, like on Steam, Desura, Amazon, Gamersgate? When I search for "#^shad'o" on ITAD, I can see it's collectors edition and soundtracks, and it looks like it is named "ShadO" only on GMG.

[Comment created by tfedor: 2015-03-15]
I was able to find both The Ball and DARK without an issue, but I think I see where the problem is.

If the game is on sale, it will be shown always when it matches search query. There shouldn't be a problem.

When it's not on sale, it might not be found as you mentioned because of how the results are sorted. I'm don't remember what was my reason to switch sorting for nondeal games from the total length of title to alphabet. I'll review my decision. Deals sorting will not be changed in the near future. The reason being that search is being considered just a special filter, and filters don't change sorting order.

A workaround for these issues might be to use "expanded search query" (which is the fancy name I just came out with for regexp). You can first click on the alphabet letter, e.g. "S", which will give you this search query: **#^s** and then write the rest of it, e.g. **#^shado** *(# at the start of search query changes from default comparision to regexps)*

[Comment created by enchained: 2015-03-15]
The issue seems to be fixed for non-steam games in my list, I crossed them out.

I think that maybe I've found the reason for others:

* They have a very common name.
* They are not on sale for a moment (not appearing in deals section of the results).
* The non-deals section of search results (below the blue dashed line) is sorted by alphabet.
* The non-deals section of search results is limited by first 75 games ("We have found more than 75 games. Please be more specific in your search").

Possible solution: default sorting by relevance in both deals and non-deals sections in the search results.

Not sure if it's true for DARK though, because other games starting with Dark and DARK are in those 75 results. In other two cases (The Ball, Shad'O/ShadO) the results are ending with letters that come way before T and S.

So either my hypothesis is true and results are somewhere there but not shown, or the reason is in something else.

**Comment by MarkitkaM** [comment]
Solved within the conversation.
