### ISSUE TITLE
Lonk's Adventure should be renamed and merged with Reventure

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1465]
Lonk's Adventure, on Steam, was renamed to "Reventure" prior to full release and ITAD wasn't updated to reflect that. The [game page on ITAD](https://isthereanydeal.com/game/lonksadventure/info/#/) still calls it Lonk's Adventure and there is a separate [game page for Reventure](https://isthereanydeal.com/game/reventure/info/). There is a rift in the Price History for the game because of this. The "Lonk's Adventure" page only includes the Price History from Steam while the "Reventure" page only includes the Price History from Fanatical and GOG.

[Issue created by [deleted]: 2019-08-23]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
