### ISSUE TITLE
Assassin's Creed Odyssey listing DLC price not actual game.

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1467]
[Assassins Creed Odyssey](https://isthereanydeal.com/game/assassinscreedodyssey/info/) has the lowest price on uplay at $19.99 usd this is the sale price of the season pass that doesn't include the game. Then uplay is listed again at the the correct sale price currently 29.99. 

The [season pass](https://isthereanydeal.com/game/assassinscreedodysseyseasonpass/info/) for odyssey on ITAD doesn't list the uplay store at all.

[Issue created by [deleted]: 2019-08-25]

**Comment by MarkitkaM** [comment]
Duplication of the #1475
