### ISSUE TITLE
Metro Exodus bad steam link

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1468]
https://isthereanydeal.com/game/metroexodus/info/ has a wrong Steam link
the Steam link in the game page targets DLC
Metro Exodus - The Two Colonels
https://store.steampowered.com/app/889920

[Issue created by [deleted]: 2019-08-26]

**Comment by MarkitkaM** [comment]
Duplication of the #1504
