### ISSUE TITLE
"Control" has "Humble Store" as only option

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1469]
`Control` at [here](https://isthereanydeal.com/game/control/history/) only has Humble Store as the only option. But it’s also on sale on at least the Epic Game Store.

[Issue created by GaryWKing: 2019-08-26]

**Comment by MarkitkaM** [comment]
https://isthereanydeal.com/game/control/info/

1. The original bug is probably old and fixed

2. **2game** - x listed the same link - https://2game.com/en-us/control-55827?ref=isthereanydeal&utm_source=Tapfiliate&utm_medium=referral&utm_campaign=isthereanydeal

**Comment by MarkitkaM** [comment]
ad2) moved to separated issue #2364
