### ISSUE TITLE
Giveaway Filter Broken (all specials?)

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1470]
I always liked being able to click on Giveaway as its own filter. This allowed me to keep tabs on items being given away. Currently this appears to be broken. At the home page, clicking on Giveaway for any of the specials results in a page 500 error. Even just clicking on All Specials ( https://isthereanydeal.com/specials/ ) results in a 500 error. While this might be something larger, I only found it by being prevented from keeping tabs on the Giveaways. Used to be able to have a really nice filter that showed only Giveaways. Please bring it back / fix it. If this does affect all filters from the specials, this would be a bigger issue.

[Issue created by [deleted]: 2019-08-28]

[Comment created by MeemicRG: 2019-08-28]
This turns out to only affect my Firefox. It shows up fine in Chrome. This can be changed to minor impact.

**Comment by MarkitkaM** [comment]
Could not reproduce 
![image](https://user-images.githubusercontent.com/88401908/135090671-9fc13233-ea5e-4a79-861d-1cbbf3883495.png)
