### ISSUE TITLE
[Greenlight] "Vote NOW!" banner is shown when the game page was deleted from greenlight.

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#148]
If the link is no longer leads to a greenlight page, there shouldn't be the same banner like if the game is going through greenlight.

Example:

Towers of Altrac on ITAD: http://isthereanydeal.com/#/page:game/info?plain=towersofaltrac

Bad greenlight link: http://steamcommunity.com/sharedfiles/filedetails/?id=185042970

Possible solution: remove banner after detecting bad greenlight links such as this one.

[Issue created by enchained: 2015-03-15]
[Last updated on bitbucket: 2019-02-01]

[Comment created by Knightw0lf: 2019-02-01]
greenlight yes still exist but i was mainly talking about the issue itself ``[Greenlight] "Vote NOW!" banner is shown when the game page was deleted from greenlight.``
it would be better if a new idea was implanted "please add link from steam to greenlight games or something" in enhancements , trival  

the reason i say that most games on steam don't even have a greenlight icon anywhere on there games. the greenlight games do just not the store side

* https://steamcommunity.com/sharedfiles/filedetails/?id=937734953
* https://store.steampowered.com/app/695490/Operation_Chromite_1950_VR/

[Comment created by Trislar: 2019-02-01]
Greenlight pages still exist.

[Comment created by Knightw0lf: 2019-02-01]
Greenlight is gone

this can be closed

[Comment created by Trislar: 2015-06-22]
I actually prefer to know, if a game was on greenlight at some point. Those GL pages shouldn't be even deletable on Steam as information gets lost that way.

ITAD could change to a note saying "was on greenlight" or similar.

**Comment by MarkitkaM** [comment]
Solved within the conersation.
