### ISSUE TITLE
Cube World confused with different game.

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1482]
**Page:** https://isthereanydeal.com/game/cubeworld/info/

**The game I was expecting:** https://store.steampowered.com/app/1128000/Cube_World/

**The game it links to, and gets prices from:** https://gamejolt.com/games/cube-world/210290

[Issue created by [deleted]: 2019-09-11]

**Comment by MarkitkaM** [comment]
Duplication of the #1501
