### ISSUE TITLE
Incorrect listing

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1488]
The game No Thing appears to be confused with and has some shared information with Nothing!

https://store.steampowered.com/app/444800/NO_THING/
https://store.steampowered.com/app/1014460/Nothing/

https://isthereanydeal.com/game/nothing/info/

[Issue created by [deleted]: 2019-09-18]

**Comment by MarkitkaM** [comment]
**SPLIT ENTRIES:**
These entries are mixed up here:
https://store.steampowered.com/app/672690/The_Nothing/
https://store.steampowered.com/app/444800/NO_THING/
https://store.steampowered.com/app/1534200/Nothing/

**Comment by MarkitkaM** [comment]
Entries to split #2323
