### ISSUE TITLE
Two "Quiet Sleeps"

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1489]
I had this game ("The Quiet Sleep") wishlisted/waitlisted on Steam : 

https://store.steampowered.com/app/724510/The_Quiet_Sleep/

But now this game ("Quiet Sleep") shows in my waitlist, and is the only game that comes up when you search "quiet sleep") 

https://store.steampowered.com/app/1061240/Quiet_Sleep/

They should have different listings...

[Issue created by [deleted]: 2019-09-19]

**Comment by MarkitkaM** [comment]
**SPLIT ENTRIES**
https://isthereanydeal.com/search/?q=The+Quiet+Sleep
https://isthereanydeal.com/game/quietsleep1/info/
https://isthereanydeal.com/game/quietsleep/info/

**Comment by MarkitkaM** [comment]
Entries to split #2323
