### ISSUE TITLE
Epic Games Store - Not blue in Collection

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1490]
![](https://i.imgur.com/r9QtRsO.png)

[Issue created by [deleted]: 2019-09-19]

**Comment by MarkitkaM** [comment]
Epic Game Store in the collection is still white
![chrome_XjJz7QgfOU](https://user-images.githubusercontent.com/88401908/135039508-5f589905-48d9-41bb-badf-39cd9bc646cb.png)

**Comment by MarkitkaM** [comment]
New websites are coming soon. Won't fix.
