### ISSUE TITLE
Battlefront II linking to wrong game

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1496]
https://isthereanydeal.com/#/page:game/info?plain=starwarsbattlefrontii

There is an existing issue, and it was resolved.

The game on AllYouPlay is the old one.

I almost bought this, thanks to the lazy UI of AllYouPlay.

[Issue created by [deleted]: 2019-09-22]

**Comment by MarkitkaM** [comment]
**SPLIT ENTRIES:**

Games from 2005
https://www.allyouplay.com/en/star-wars-battlefront-ii-row?utm_source=daisycon&utm_medium=affiliate&utm_campaign=IsThereAnyDeal
https://www.gamebillet.com/star-wars-battlefront-ii-g?affiliate=1c8adfeb-78f3-4d89-9a91-5b697ec73e37

**Comment by MarkitkaM** [comment]
Entries to split #2323
