### ISSUE TITLE
Add "RUSH" the VR game

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1498]
add
https://store.steampowered.com/app/844040/RUSH/

[Issue created by [deleted]: 2019-09-25]

**Comment by MarkitkaM** [comment]
1. Rush is added into the wrong entry https://isthereanydeal.com/game/rush/info/ -> https://store.steampowered.com/app/844040/RUSH/

2. **SPLIT ENTRIES:**

- https://store.steampowered.com/app/1540190/RUSH/
- https://store.steampowered.com/app/844040/RUSH/
- This one is correct in this entry https://store.steampowered.com/app/38720/RUSH/

**Comment by MarkitkaM** [comment]
Entries to split #2323
