### ISSUE TITLE
Duplicate of Barony

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1502]
Hi, it seems that they are duplicates

[https://isthereanydeal.com/game/barony/info/](https://isthereanydeal.com/game/barony/info/)

[https://isthereanydeal.com/game/baronyblessedaddition/info/](https://isthereanydeal.com/game/baronyblessedaddition/info/)

[Issue created by tuxayo: 2019-09-30]

**Comment by MarkitkaM** [comment]
**MERGE ENTRIES**

**Comment by MarkitkaM** [comment]
Entries to merge #2324
