### ISSUE TITLE
TC's The Division 2 shows as two separate pages for Epic Store and Uplay

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1513]
[https://isthereanydeal.com/game/tomclancysdivisionii/info/](https://isthereanydeal.com/game/tomclancysdivisionii/info/)

[https://new.isthereanydeal.com/game/divisionii/info/](https://new.isthereanydeal.com/game/divisionii/info/)

[Issue created by arseny92: 2019-10-16]

**Comment by MarkitkaM** [comment]
https://isthereanydeal.com/game/divisionii/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
