### ISSUE TITLE
(Vertigo) Missing Game and Wrong Game for DLC

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1514]
There are two games called Vertigo on Steam. 
https://store.steampowered.com/app/465430/Vertigo/
https://store.steampowered.com/app/1059000/Vertigo/

The first one is missing, and its soundtrack DLC is put under the wrong Vertigo.

[Issue created by [deleted]: 2019-10-22]

**Comment by MarkitkaM** [comment]
SPLIT ENTRIES:
https://isthereanydeal.com/game/vertigo/info/

**Comment by MarkitkaM** [comment]
Entries to split #2323
