### ISSUE TITLE
Borderlands GOTY Enhanced - duplicate entries

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1516]
Duplicate entries for the Borderline GOTY Enhanced edition:

https://isthereanydeal.com/game/borderlandsgameofyearenhanced/info/#/

https://isthereanydeal.com/game/borderlandsgameofyeareditionenhanced/info/#/

Different stores in the two editions (only overlap is Steam), but they're the same thing.

Thanks in advance!

[Issue created by [deleted]: 2019-10-23]

**Comment by MarkitkaM** [comment]
**MERGE ENTRIES**

**Comment by MarkitkaM** [comment]
Entries to merge #2324
