### ISSUE TITLE
Game Valley also checks price for a game called The Valley

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1518]
[Valley ](https://store.steampowered.com/app/378610/Valley/)and [The Valley](https://store.steampowered.com/app/1169500/The_Valley/) are different games, but end up in the same price check.  
This means you can get a waitlist notification for the wrong game.

[Issue created by Smannesman: 2019-10-23]

**Comment by MarkitkaM** [comment]
Duplication of the #2089
