### ISSUE TITLE
Game Chasm (incorrectly) includes a check for the game The Chasm

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1519]
[Chasm ](https://store.steampowered.com/app/312200/Chasm/)and [The Chasm](https://store.steampowered.com/app/1140900/The_Chasm/) are different games, but are considered the same game as far as the waitlist goes. This potentially means a user could get a notification for a price drop which has not actually occurred.

[Issue created by Smannesman: 2019-10-23]

**Comment by MarkitkaM** [comment]
Duplication of the #1626
