### ISSUE TITLE
Prices showing from old sales at Chrono.GG

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1520]
I found it when I was shopping for slay the spire but it could be happening with other games. This website's summer special is done but the sale is still showing.

[Issue created by [deleted]: 2019-10-25]

**Comment by MarkitkaM** [comment]
Chrono.GG does not exist anymore. But it is still visible in the history.

**Comment by MarkitkaM** [comment]
Chrono.GG no longer exists.
