### ISSUE TITLE
Different games grouped on the same page

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1538]
Articles and spaces in game names are meaningful.

[https://isthereanydeal.com/waitlist/#/page:game/info?plain=chasm](https://isthereanydeal.com/waitlist/#/page:game/info?plain=chasm) contains:

*  https://store.steampowered.com/app/1140900/The\_Chasm
* https://store.steampowered.com/app/312200/Chasm/
Duplication of the #1626
---

[https://isthereanydeal.com/waitlist/#/page:game/info?plain=downward](https://isthereanydeal.com/waitlist/#/page:game/info?plain=downward) contains:

* https://store.steampowered.com/app/904700/Down\_Ward/
* https://store.steampowered.com/app/506900/Downward/

‌

[Issue created by darkums: 2019-11-17]

**Comment by MarkitkaM** [comment]
Entries to split #2323

ad2) Moved to separated issue #2366
