### ISSUE TITLE
Ancestors: The Humankind Odyssey isn`t for steam (humble bundle and voidu)

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1540]
I got a price match for this title today, but it`s not on Steam yet.

[Issue created by [deleted]: 2019-11-22]

**Comment by MarkitkaM** [comment]
**2game** -> 404
https://2game.com/en/ancestors-the-humankind-odyssey-55257?ref=isthereanydeal&utm_source=Tapfiliate&utm_medium=referral&utm_campaign=isthereanydeal
https://2game.com/en/ancestors-the-humankind-odyssey-58422?
https://2game.com/en/ancestors-the-humankind-odyssey-55260?ref=isthereanydeal&utm_source=Tapfiliate&utm_medium=referral&utm_campaign=isthereanydealref=isthereanydeal&utm_source=Tapfiliate&utm_medium=referral&utm_campaign=isthereanydeal
https://2game.com/en/ancestors-the-humankind-odyssey-55269?ref=isthereanydeal&utm_source=Tapfiliate&utm_medium=referral&utm_campaign=isthereanydeal
https://2game.com/en/ancestors-the-humankind-odyssey-55272?ref=isthereanydeal&utm_source=Tapfiliate&utm_medium=referral&utm_campaign=isthereanydeal

**Comment by MarkitkaM** [comment]
Steam is tracked https://store.steampowered.com/app/536270/Ancestors_The_Humankind_Odyssey/
