### ISSUE TITLE
[Merge] Ghost Recon Wildlands DLCs

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1544]
Multiple pages for the main game and DLCs, many of them empty or no longer available.

Main Game:

* https://isthereanydeal.com/game/tomclancysghostreconwildlands/info/
* [no longer available] https://isthereanydeal.com/game/tomclancysghostreconwildlandsna/info/
* [no longer available] https://isthereanydeal.com/game/tomclancyasghostreconwildlands/info/
* [empty] https://isthereanydeal.com/game/tomclancysghostreconwildlandsuplaykey/info/

Fallen Ghosts:

* https://isthereanydeal.com/game/tomclancysghostreconwildlandsfallenghosts/info/
* https://isthereanydeal.com/game/tomclancysghostreconwildlandsfallenghost/info/
* [no longer available] https://isthereanydeal.com/game/ghostreconwildlandsfallenghost/info/
* [empty] https://isthereanydeal.com/game/ghostreconwildlandsfallenghosts/info/
* [empty, charset error] https://isthereanydeal.com/game/tomclancyasghostreconwildlandsfallenghost/info/
* [no longer available] https://isthereanydeal.com/game/dlctomclancysghostreconwildlandsfallenghosts/info/
* [empty] https://isthereanydeal.com/game/tomclancysghostreconwildlandsfallenghostsdlc/info/

Narco Road

* https://isthereanydeal.com/game/tomclancysghostreconwildlandsnarcoroad/info/
* [no longer available] https://isthereanydeal.com/game/tomclancysghostreconwildlandsdlcinarcoroad/info/
* [empty] https://isthereanydeal.com/game/ghostreconwildlandsnarcoroad/info/
* [empty] https://isthereanydeal.com/game/tomclancysghostreconwildlandsdlcinarcoroaduplaykey/info/

[Issue created by [deleted]: 2019-11-27]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
