### ISSUE TITLE
Shows price for wrong game

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1545]
The game silence has an itch.io store option that links to a different game with a similar title.

It is much cheaper than the game actually is causing it to seem like there is a good deal.

https://isthereanydeal.com/game/silence/info/

Thanks!

[Issue created by [deleted]: 2019-11-27]

**Comment by MarkitkaM** [comment]
**Split ENTRIES:**
https://8bitpxl.itch.io/the-silence

**Comment by MarkitkaM** [comment]
Duplication of the #1886
