### ISSUE TITLE
Site still unreachable via IPv6

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1549]
Trying to reach [isthereanydeal.com](http://isthereanydeal.com) via IPv6 when using MTU size < 1500 results in a timeout. \(e.g. using a PPPoE internet access which has a max MTU size of 1492\) This behavior can be traced back to the site not acknowledging ICMPv6 PTB \(Packet Too Big\) messages.

This problem can be demonstrated and reproduced with web based site tester [https://ipv6alizer.se/](https://ipv6alizer.se/) . This web based interface runs the command line utility **scamper** with the **tbit** command to test a webpage’s capability to respond to a PTB message. Here is a log from the tool:  

```plaintext
INFO: test started Thu Nov 28 20:28:43 CET 2019
INFO: isthereanydeal.com have 1 ipv6 address{es}
INFO: testing  at 2a05:d018:f48:8a00:b474:141c:35e2:7ff7 Thu Nov 28 20:28:43 CET 2019
INFO: running scamper  -I "tbit -M 1280 -t pmtud -S 2a07:1c80:102:193::190 -u https://isthereanydeal.com 2a05:d018:f48:8a00:b474:141c:35e2:7ff7"
INFO:  server-mss 1440, result: pmtud-fail
ERROR: https://isthereanydeal.com don't listen to PTB
tbit from 2a07:1c80:102:193::180 to 2a05:d018:f48:8a00:b474:141c:35e2:7ff7
 server-mss 1440, result: pmtud-fail
 app: http, url: https://isthereanydeal.com/
 [  0.050] TX SYN             64  seq = 0:0             
 [  0.093] RX SYN/ACK         64  seq = 0:1             
 [  0.100] TX                 60  seq = 1:1             
 [  0.149] TX                380  seq = 1:1(320)        
 [  0.192] RX                 60  seq = 1:321           
 [  0.194] RX               2940  seq = 1:321(2880)     
 [  0.194] RX                160  seq = 2881:321(100)   
 [  0.200] TX PTB           1280  mtu = 1280
 [  0.250] TX                 60  seq = 321:1           
 [  0.461] RX               1500  seq = 1:321(1440)     
 [  0.461] TX PTB           1280  mtu = 1280
 [  0.991] RX               1500  seq = 1:321(1440)     
 [  0.991] TX PTB           1280  mtu = 1280
 [  2.091] RX               1500  seq = 1:321(1440)     
 [  2.091] TX PTB           1280  mtu = 1280
 [  4.241] RX               1500  seq = 1:321(1440)
INFO: test ended Thu Nov 28 20:28:48 CET 2019
```

Here on _line 17_ the tool transmits a PTB message with _mtu=1280_ \(the minimum size allowed by IPv6\) requesting the server to send 1280 sized units, the server responds with a 1500 sized one on line 19, the tool tries again, but only receives 1500 sized packets.  
Compare this to the log from g[oogle.com:](http://google.com)

‌

```plaintext
INFO: test started Thu Nov 28 20:48:07 CET 2019
INFO: google.com have 1 ipv6 address{es}
INFO: testing  at 2a00:1450:400f:807::200e Thu Nov 28 20:48:07 CET 2019
INFO: running scamper  -I "tbit -M 1280 -t pmtud -S 2a07:1c80:102:193::129 -u https://google.com 2a00:1450:400f:807::200e"
INFO:  server-mss 1360, result: pmtud-success
NOTICE: https://google.com is responding to PTB correctly
tbit from 2a07:1c80:102:193::118 to 2a00:1450:400f:807::200e
 server-mss 1360, result: pmtud-success
 app: http, url: https://google.com/
 [  0.050] TX SYN             64  seq = 0:0             
 [  0.055] RX SYN/ACK         64  seq = 0:1             
 [  0.100] TX                 60  seq = 1:1             
 [  0.150] TX                372  seq = 1:1(312)        
 [  0.155] RX                 60  seq = 1:313           
 [  0.165] RX               3720  seq = 1:313(3660)     
 [  0.165] RX                189  seq = 3661:313(129)   
 [  0.200] TX PTB           1280  mtu = 1280
 [  0.250] TX                 60  seq = 313:1           
 [  0.415] RX               1280  seq = 1:313(1220)     
 [  0.415] TX                 60  seq = 313:1221        
 [  0.420] RX               1280  seq = 1221:313(1220)  
 [  0.420] TX FIN             60  seq = 313:2441        
 [  0.420] RX               1409  seq = 2441:313(1349)  
 [  0.420] TX FIN             60  seq = 313:3790        
 [  0.425] RX                 60  seq = 3790:314        
 [  0.425] RX FIN             60  seq = 3790:314        
 [  0.449] TX                 60  seq = 314:3791
INFO: test ended Thu Nov 28 20:48:08 CET 2019
```

Again on _line 17_ sending PTB with _mtu=1280_, on _line 19_ the server responds with the requested 1280 sized unit.

I realize issue #1020 and #1120 are describing the same problem however there does not seem to be any change regarding this for over a year. Right now the site is unreachable over IPv6 with an MTU size < 1500 as the site only seems to send out 1500 sized units. IPv6 support requires the handling of PTB messages, 1500 sized MTU for every connection is not viable.

I know you don’t block all ICMPv6 messages as I can ping the site via IPv6 \(ping -6\) so ICMPv6 Type 128 Echo Request is allowed through, but Type 2 is not.

If the site uses AWS for hosting you should check the security options as written in the AWS Docs \([https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/network\_mtu.html](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/network_mtu.html)\) :

> By default, security groups do not allow any inbound ICMP traffic. To ensure that your instance can receive this message and the packet does not get dropped, you must add a Custom ICMP Rule

The security group rules reference only describes ICMP IPv4 path MTU discovery settings \([https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/security-group-rules-reference.html#sg-rules-path-mtu](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/security-group-rules-reference.html#sg-rules-path-mtu)\). 

However ICMPv6 path MTU discovery should also be allowed, as I read the docs it should be ICMPv6 Protocol number 58 ICMP Type 2 ICMP Code 0 to allow Packet Too Big messages.

If you can’t/don’t want to solve this for some other reasons, why have IPv6 enabled for the site? Right now the only way I can access the site is if I disable IPv6 on my network interface to force an IPv4 connection, however I can access [amazon.com](http://amazon.com), [microsoft.com](http://microsoft.com) fine, as they don’t have an AAAA record and it all goes through IPv4.

Please either fix the PTB message handling for IPv6 or delete the AAAA records and disable IPv6 for the site or any visitors using IPv6 and an MTU size less than 1500 \(PPPoE internet connections, other tunneling\) will be unable to reach the site.

[Issue created by hix3r: 2019-11-28]

**Comment by MarkitkaM** [comment]
It is an old bug. We don't know, if it is still happening or not.
