### ISSUE TITLE
Make it easier to find the log page.

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#155]
Right now I can find the link to the log page only from Collection page. I think it should be in a visible place on the Waitlist page too, and settings, or maybe even on the main page, somewhere between Changes and Partners.

I even forgot that the log exists when I was asking question about re-adding wishlist import link. I forgot because I clearly don't see it enough on different pages of ITAD in my opinion

[Issue created by enchained: 2015-03-20]

**Comment by MarkitkaM** [comment]
The log is reachable from the main navigation, collection and waitlist.
