### ISSUE TITLE
Two different itch games.

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1550]
[https://isthereanydeal.com/game/possession/info/](https://isthereanydeal.com/game/possession/info/)

[Issue created by krai0: 2019-11-29]

**Comment by MarkitkaM** [comment]
Wrong entries for Steam and Itch.io
![chrome_gV1ntLgOU6](https://user-images.githubusercontent.com/88401908/134809690-e383bcf0-a718-4857-ac4c-4a9653a9214f.png)

**Comment by MarkitkaM** [comment]
Entries to split #2323

Duplication
