### ISSUE TITLE
GOG unbundling is interfering with import

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#158]
GOG.com is currently [in the process](http://www.gog.com/forum/general/important_notice_unbundling_games/post1) of breaking the 1:1 relationship between catalog entries and library entries so users can install single games from packs like "King's Quest 4+5+6".

This is, in theory, a good thing, since it means that the "packages -> games" arrangement will more closely match the records you scrape from places like Steam, but it has resulted in quite a few titles in the import list being ignored as "unknown".

Because they haven't done any internal reverse-referencing, they don't provide any kind of catalogue link I could scrape.

However, the creator of the [MaGog](http://www.an-ovel.com/pages/magog.php) search engine has expressed interest in making a mapping table and, given that he offers a [dump](http://www.an-ovel.com/downloads/magog.txt) of the data he already scrapes, I think he'd probably be receptive if you [asked](http://www.gog.com/forum/general/magog_a_search_engine_for_gog_games) to work with him to avoid duplicating effort.

[Issue created by ssokolow: 2015-03-22]
[Last updated on bitbucket: 2015-03-29]

[Comment created by ssokolow: 2015-03-29]
Names which appear identical but ITAD insists that the list-view version is in the collection but the shelf-view isn't:

* A New Beginning - Final Cut
* American Conquest + Fight Back
* Deponia 3: Goodbye Deponia
* Deus Ex: Game of the Year Edition
* FTL: Faster Than Light
* Icewind Dale 2 Complete
* Longest Journey, The
* Painkiller Black Edition
* Robin Hood: The Legend of Sherwood
* S2: Silent Storm Gold Edition
* Stronghold Crusader HD
* Stronghold HD
* Tom Clancy's Splinter Cell
* Whispered World, The

Mismatches between shelf and list view which need to be aliased if we can't determine a proper primary key to export: (importing one does not import the other and neither is unknown)

* `8th Wonder Of The World` **=** `Cultures: 8th Wonder of the World`
* `DRACULA 3 - THE PATH OF THE DRAGON` **=** `Dracula 3: The Path of the Dragon` (neither is "unknown", importing one does not import the other)
* `HEROES OF MIGHT AND MAGIC V + HAMMERS OF FATE` **=** `Heroes of Might And Magic V`
* `Northland` **=** `Cultures: Northland`

Listed as "unknown" in shelf view because converting the slug-style ID doesn't yield the title:

* Creatures 1
* Betrayal At Krondor Copy3
* Drod 1 King Dugans Dungeon
* Episode 1 The Blackwell Legacy
* Episode 2 Blackwell Unbound
* Episode 3 Blackwell Convergence
* Episode 4 Blackwell Deception
* Quest For Glory Vga Remake
* Ultima Vii The Black Gate The Forge Of Virtue

[Comment created by tfedor: 2015-03-29]
Okay, I relaxed conditions a little bit. Until now, game was "unknown" not only if it wasn't in my database, but also if it had no deal. Now I have started separately checking for unknown and for sale, so you may get both "unknown" or "no deal" notes.

Behaviour for unknown is left unchanged, so when there is unknown game it will not be checked by default. "No deal" will be checked if you are importing Collection but won't be checked if you are importing wishlist.

[Comment created by ssokolow: 2015-03-29]
I'm getting quite a few unknowns which should have been resolved by the MaGOG dump.

For example, "Castles" and "Castles 2" (shelf view) and "CASTLES" and "CASTLES 2" (list view) are listed as unknown but the MaGOG dump does have " CASTLES *** CASTLES 2 " as the value for the `unbundles_str` column on "Castles 1+2".

The shelf and list views dump the text of the unrecognized entries differently, since the shelf can't get GOG's title text without a lot of XMLHttpRequests (and currently generates a fallback title from game IDs so the entries won't be omitted entirely), so not all of them match MaGOG's dump, but the lists of unrecognized entries both contain things like the aforementioned Castles 1+2 issue.

I own somewhere between 2/3 and 3/4 of GOG's catalog and here are the unknowns I'm getting (a combined and deduped view of both the shelf-view and list-view dumps), with the shelf-view title's prettified capitalization used when both show up with the same spelling:

* Alien Breed
* Alien Breed Tower Assault Game
* ALIEN BREED: TOWER ASSAULT (GAME)
* American Mcgees Grimm Season 1
* American Mcgees Grimm Season 2
* American Mcgees Grimm Season 3
* AMERICAN MCGEE'S GRIMM - SEASON 1
* AMERICAN MCGEE'S GRIMM - SEASON 2
* AMERICAN MCGEE'S GRIMM - SEASON 3
* Avernum
* Avernum 2
* Avernum 3
* Battle Isle
* Battle Isle 2
* Battle Isle 3
* Ben There Dan That
* BEN THERE, DAN THAT!
* Betrayal At Krondor Copy3
* Betrayal In Antara
* Beyond Zork The Coconut Of Quendor
* BEYOND ZORK - THE COCONUT OF QUENDOR
* Blades Of Avernum
* Blitzkrieg 2
* Blitzkrieg 2 Fall Of The Reich
* Blitzkrieg 2 Liberation
* BLITZKRIEG 2 - FALL OF THE REICH
* BLITZKRIEG 2 - LIBERATION
* Castles
* Castles 2
* CREATURES
* Creatures 1
* Creatures 2
* Cultures 2
* Disciples 2 Dark Prophecy And Galleans Return
* DISCIPLES 2 - DARK PROPHECY AND GALLEAN'S RETURN
* Drod 1 King Dugans Dungeon
* Drod 2 Journey To Rooted Hold
* Drod 3 The City Beneath
* DROD 2: JOURNEY TO ROOTED HOLD
* DROD 3: THE CITY BENEATH
* Episode 1 The Blackwell Legacy
* Episode 2 Blackwell Unbound
* Episode 3 Blackwell Convergence
* Episode 4 Blackwell Deception
* Geneforge 5
* Gobliiins
* Gobliins 2 The Prince Buffoon
* Goblins Quest 3
* GOBLIINS 2 - THE PRINCE BUFFOON
* Heroes Chronicles Chapter 1 Warlords Of The Wasteland
* Heroes Chronicles Chapter 2 Conquest Of The Underworld
* Heroes Chronicles Chapter 3 Masters Of The Elements
* Heroes Chronicles Chapter 4 Clash Of The Dragons
* Heroes Chronicles Chapter 5 The World Tree
* Heroes Chronicles Chapter 6 The Fiery Moon
* Heroes Chronicles Chapter 7 Revolt Of The Beastmasters
* Heroes Chronicles Chapter 8 The Sword Of Frost
* HEROES CHRONICLES [CHAPTER 1] - WARLORDS OF THE WASTELAND
* HEROES CHRONICLES [CHAPTER 2] - CONQUEST OF THE UNDERWORLD
* HEROES CHRONICLES [CHAPTER 3] - MASTERS OF THE ELEMENTS
* HEROES CHRONICLES [CHAPTER 4] - CLASH OF THE DRAGONS
* HEROES CHRONICLES [CHAPTER 5] - THE WORLD TREE
* HEROES CHRONICLES [CHAPTER 6] - THE FIERY MOON
* HEROES CHRONICLES [CHAPTER 7] - REVOLT OF THE BEASTMASTERS
* HEROES CHRONICLES [CHAPTER 8] - THE SWORD OF FROST
* HEROES OF MIGHT AND MAGIC V + HAMMERS OF FATE
* Historyline 19141918
* HISTORYLINE 1914-1918
* Incoming
* Incubation
* Kings Quest 7 The Princeless Bride
* Kings Quest 8 Mask Of Eternity
* KING'S QUEST 7 - THE PRINCELESS BRIDE
* KING'S QUEST 8 - MASK OF ETERNITY
* Leisure Suit Larry 1 In The Land Of The Lounge Lizards
* Leisure Suit Larry 1 Vga In The Land Of The Lounge Lizards
* Leisure Suit Larry 2 Looking For Love In Several Wrong Places
* Leisure Suit Larry 3 Passionate Patti In Pursuit Of The Pulsating Pectorals
* Leisure Suit Larry 5 Passionate Patti Does A Little Undercover Work
* Leisure Suit Larry 6 Shape Up Or Slip Out
* Leisure Suit Larry 6 Vga Shape Up Or Slip Out
* LEISURE SUIT LARRY 1 (VGA) - IN THE LAND OF THE LOUNGE LIZARDS
* LEISURE SUIT LARRY 1 - IN THE LAND OF THE LOUNGE LIZARDS
* LEISURE SUIT LARRY 2 - LOOKING FOR LOVE (IN SEVERAL WRONG PLACES)
* LEISURE SUIT LARRY 3 - PASSIONATE PATTI IN PURSUIT OF THE PULSATING PECTORALS!
* LEISURE SUIT LARRY 5 - PASSIONATE PATTI DOES A LITTLE UNDERCOVER WORK!
* LEISURE SUIT LARRY 6 (VGA) - SHAPE UP OR SLIP OUT
* LEISURE SUIT LARRY 6 - SHAPE UP OR SLIP OUT
* Master Of Orion 2
* Might And Magic 1 Book I
* Might And Magic 2 Gates To Another World
* Might And Magic 3 Isles Of Terra
* Might And Magic 45 World Of Xeen
* Might And Magic Swords Of Xeen
* MIGHT AND MAGIC - SWORDS OF XEEN
* MIGHT AND MAGIC 1 - BOOK I
* MIGHT AND MAGIC 2 - GATES TO ANOTHER WORLD
* MIGHT AND MAGIC 3 - ISLES OF TERRA
* MIGHT AND MAGIC 4-5 - WORLD OF XEEN
* Pinball Dreams Deluxe
* Pinball Fantasies Deluxe
* Pinball Illusions
* Planetfall
* Police Quest 2 Vengeance
* Police Quest 3 The Kindred
* Police Quest 4 Open Season
* Police Quest In Pursuit Of The Death Angel
* Police Quest Swat
* Police Quest Swat 2
* POLICE QUEST - IN PURSUIT OF THE DEATH ANGEL
* POLICE QUEST - SWAT
* POLICE QUEST - SWAT 2
* POLICE QUEST 2 - VENGEANCE
* POLICE QUEST 3 - THE KINDRED
* POLICE QUEST 4 - OPEN SEASON
* Quest For Glory 2
* Quest For Glory 3
* Quest For Glory 5
* Quest For Glory Vga Remake
* QUEST FOR GLORY (INCLUDES VGA REMAKE)
* QUEST FOR GLORY 2
* QUEST FOR GLORY 3
* QUEST FOR GLORY 5
* Realms Of Arkania Star Trail
* REALMS OF ARKANIA: STAR TRAIL
* Return Of The Incredible Machine Contraptions
* Softporn Adventure
* Space Quest 1 The Sarien Encounter
* Space Quest 2 Vohauls Revenge
* Space Quest 3 The Pirates Of Pestulon
* Space Quest 4 Roger Wilco And The Time Rippers
* Space Quest 5 The Next Mutation
* Space Quest 6 Roger Wilco In The Spinal Frontier
* SPACE QUEST 1 - THE SARIEN ENCOUNTER
* SPACE QUEST 2 - VOHAUL'S REVENGE
* SPACE QUEST 3 - THE PIRATES OF PESTULON
* SPACE QUEST 4 - ROGER WILCO AND THE TIME RIPPERS
* SPACE QUEST 5 - THE NEXT MUTATION
* SPACE QUEST 6 - ROGER WILCO IN THE SPINAL FRONTIER
* Star Control
* Star Control 2
* Star Wars Tie Fighter 1994
* Star Wars Tie Fighter 1998
* Star Wars Xwing 1993
* Star Wars Xwing 1998
* STAR WARS®: TIE FIGHTER (1994)
* STAR WARS®: TIE FIGHTER (1998)
* STAR WARS®: X-WING (1993)
* STAR WARS®: X-WING (1998)
* Tex Murphy 1 Mean Streets
* Tex Murphy 2 Martian Memorandum
* TEX MURPHY 1 - MEAN STREETS
* TEX MURPHY 2 - MARTIAN MEMORANDUM
* The Even More Incredible Machine
* The Incredible Machine 3
* The Incredible Machine Even More Contraptions
* THE INCREDIBLE MACHINE - EVEN MORE CONTRAPTIONS
* Tropico 2
* Ultima 1
* Ultima 2
* Ultima 3
* Ultima Iv
* Ultima V
* Ultima Vi
* Ultima Vii Serpent Isle
* Ultima Vii The Black Gate The Forge Of Virtue
* ULTIMA I
* ULTIMA II
* ULTIMA III
* ULTIMA IV
* ULTIMA V
* ULTIMA VI
* ULTIMA VII - SERPENT ISLE
* ULTIMA VII - THE BLACK GATE + THE FORGE OF VIRTUE
* Wing Commander
* Wing Commander Prophecy
* Wing Commander Secret Ops
* WING COMMANDER
* WING COMMANDER PROPHECY
* WING COMMANDER SECRET OPS
* Wizardry 6
* Wizardry 7 Gold
* WIZARDRY 6
* WIZARDRY 7 GOLD
* Zork Ii The Wizard Of Frobozz
* Zork Iii The Dungeon Master
* Zork The Great Underground Empire
* Zork Zero The Revenge Of Megaboz
* ZORK - THE GREAT UNDERGROUND EMPIRE
* ZORK II - THE WIZARD OF FROBOZZ
* ZORK III - THE DUNGEON MASTER
* ZORK ZERO - THE REVENGE OF MEGABOZ

**NOTE:**

* Avernum 4, 5, and 6 are known, despite being listed in the same `unbundle_str` as 1, 2, 3, and Blades of Avernum, which are listed as unknown.
* Geneforge 1,2, and 3 are known, despite Geneforge 5 being unknown and listed in the same `unbundle_str`.
* Geneforge 4 and Quest for Glory 4 are missing from the dump entirely but, for all I know, that could be a GOG glitch causing the userscript to mess up. (I wouldn't put it past 'em)
* As MaGOG's dump shows, "Softporn Adventure" is part of the Leisure Suit Larry 1-6 bundle.
* If you haven't already, you may want to mention the "legally free and open-source except for the trademark" releases of Star Control 2 (The Ur-Quan Masters) and SimCity Classic for Linux (Micropolis) on ITAD.

Also, while examples like Castles 1+2 aren't recent unbundles, keep in mind that the unbundling is still an ongoing process, so you'll want to retrieve the MaGOG dump periodically to update your mappings as more games get unbundled.

[Comment created by tfedor: 2015-03-29]
It should work without unknown now. I've used MaGOGs data to add unrecognized titles and mark original games as packages. Please check if it works for you.

**Comment by MarkitkaM** [comment]
Solved within the conversation.
