### ISSUE TITLE
Combine "Workers & Resources: Soviet Republic" duplicates

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1582]
**MERGE ENTRIES:**
[https://isthereanydeal.com/game/workersandresourcessovietrepublic/info/](https://isthereanydeal.com/game/workersandresourcessovietrepublic/info/) and [https://isthereanydeal.com/game/workersresourcessovietrepublic/info/](https://isthereanydeal.com/game/workersresourcessovietrepublic/info/)

[Issue created by Bujno: 2019-11-30]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
