### ISSUE TITLE
Anno 1800 Season Pass duplicate and missing uplay

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1586]
Currently there are two entries for the Season Pass:

https://isthereanydeal.com/game/annoiviii00seasonpass/info/
https://isthereanydeal.com/game/dlcannoiviii00seasonpass/info/

Neither include the uplay price info and the second one is completely empty. They should be merged and uplay price info added if possible

[Issue created by [deleted]: 2019-12-07]

**Comment by MarkitkaM** [comment]
**MERGE ENTRIES.**

Uplay is already tracked.

**Comment by MarkitkaM** [comment]
Entries to merge #2324
