### ISSUE TITLE
Merge Soul Calibur VI & Ⅵ Season Pass

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1597]
**MERGE ENTRIES:**
For some reason there are two tracking using diffrent font family to write roman 6

SOULCALIBUR VI Season Pass  
[https://isthereanydeal.com/game/soulcaliburseasonpass/info/](https://isthereanydeal.com/game/soulcaliburseasonpass/info/)

SOULCALIBUR Ⅵ Season Pass  
[https://isthereanydeal.com/game/soulcaliburviseasonpass/info/](https://isthereanydeal.com/game/soulcaliburviseasonpass/info/)

[Issue created by Flamerion: 2019-12-15]
[Last updated on bitbucket: 2020-05-09]

**Comment by MarkitkaM** [comment]
**The font problem is also visible on Alphaweb:**
https://new.isthereanydeal.com/game/soulcaliburseasonpass/info/
https://new.isthereanydeal.com/game/soulcaliburviseasonpass/info/

![chrome_xanTN5rWAw](https://user-images.githubusercontent.com/88401908/134714220-b77b5cfd-2889-4d1f-b636-d3273d12c55b.png)
![chrome_tPHMX42v6S](https://user-images.githubusercontent.com/88401908/134714234-b6ade3a2-bdda-4ff3-b617-c8845d72b8cb.png)

**Comment by MarkitkaM** [comment]
Entries to merge #2324
