### ISSUE TITLE
2 games named Eidolon

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1601]
There are 2 games, at least on Steam, named Eidolon. They are combined under the same page on isthereanydeal.com, but they're two seperate and different games.

Maybe seperate them, since one of them is a F2P game.

[Issue created by [deleted]: 2019-12-20]
[Last updated on bitbucket: 2020-07-10]

[Comment created by anroth3: 2020-07-10]
This has caused a problem on my waitlist for a long time.

**Comment by MarkitkaM** [comment]
https://isthereanydeal.com/game/eidolon/info/
![chrome_bAQZ39PUM0](https://user-images.githubusercontent.com/88401908/134550537-3281a569-07e0-47f6-af93-2cb61793ec2e.png)

**Comment by MarkitkaM** [comment]
Entries to split #2323
