### ISSUE TITLE
Two different games with the same name.

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1608]
**SPLIT ENTRIES:**
On Steam, there are two games titled "Never Give Up". One is a visual novel, the other is a 2D platformer.

https://store.steampowered.com/app/555320/Never_give_up/
https://store.steampowered.com/app/609420/Never_Give_Up/

The visual novel is actually titled "Never give up!", only the N is capitalized and it has an exclamation mark.

Both are currently linked towards a single game page on ITAD. https://isthereanydeal.com/game/nevergiveup/info/

[Issue created by [deleted]: 2019-12-27]

**Comment by MarkitkaM** [comment]
ITCH.io is tracking two games as well:
![ApplicationFrameHost_KRYpf864h0](https://user-images.githubusercontent.com/88401908/134549412-51708ae9-33a9-4042-8cb5-7f8bc1a760d2.png)

**Comment by MarkitkaM** [comment]
Entries to split #2323
