### ISSUE TITLE
On wait list, can't change price under "I want to be notified when there is a deal with…"

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#161]
When I try to save a price I've entered under "I want to be notified when there is a deal with…," the spinner never goes away and the change is never completed.

[Issue created by [deleted]: 2015-03-25]

[Comment created by tfedor: 2015-03-25]
We had some problems with server today which is fixed now, I believe it has fixed this issue as well, please check it for me.

**Comment by MarkitkaM** [comment]
Solved within the conversation.
