### ISSUE TITLE
Display game title for voucher preview when voucher applies for 1 game only.

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#162]
> when a promo code is valid on a single game, is it possible to display the game name instead of “1 Game” 

[Issue created by tfedor: 2015-03-25]

**Comment by MarkitkaM** [comment]
Solved.
![image](https://user-images.githubusercontent.com/88401908/141064092-8d1e2ae9-8eff-4b52-8886-595bb5a0a43f.png)
