### ISSUE TITLE
Two "Basement" games confused

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1622]
https://isthereanydeal.com/game/basement/info/

The itch.io link is for another game.

[Issue created by [deleted]: 2020-01-09]
[Last updated on bitbucket: 2020-01-27]

[Comment created by karlcastle: 2020-01-27]
The linked bundle is for the Basement movie, not the game.

The Metacritic review is for a third Basement game \(“b-a-s-e-m-e-n-t”\) that’s not the itch or Steam ones.

**Comment by MarkitkaM** [comment]
Duplication of the #1841
