### ISSUE TITLE
One page, two games.

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1631]
**SPLIT ENTRIES:**
There are two different games for both Steam entries: https://isthereanydeal.com/game/fishy/info/#/

[Issue created by [deleted]: 2020-01-24]
[Last updated on bitbucket: 2020-01-25]

[Comment created by mathmark: 2020-01-25]
This is very similar to [https://bitbucket.org/tfedor/isthereanydeal.com/issues/1138](https://bitbucket.org/tfedor/isthereanydeal.com/issues/1138)

**Comment by MarkitkaM** [comment]
Entries to split #2323
