### ISSUE TITLE
Mixup between titles "TowerClimb" and "Tower Climb"

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1636]
**SPLIT ENTRIES:**
I received a notification that the game TowerClimb (https://store.steampowered.com/app/396640/TowerClimb/) was on sale, but the deal was in fact for the game Tower Climb (https://store.steampowered.com/app/1193780/Tower_Climb/) which is an entirely different game.

[Issue created by [deleted]: 2020-02-01]

**Comment by MarkitkaM** [comment]
https://isthereanydeal.com/game/towerclimb/info/
https://isthereanydeal.com/game/tower-climb/info/

**Comment by MarkitkaM** [comment]
Entries to split #2323
