### ISSUE TITLE
Wrong Steam price for Lightmatter

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1643]
[Lightmatter](https://isthereanydeal.com/game/lightmatterfreetotry/info/) is listed with a Steam price of 0.
This is not correct. Only the "Free to Try" version is free on Steam, the full version is not free. Listing the "Free To Try" version together with the regular versions from other stores makes it hard to track the price.

[Issue created by [deleted]: 2020-02-15]
[Last updated on bitbucket: 2020-03-16]

[Comment created by intgr: 2020-03-16]
Looks related: #1663

**Comment by MarkitkaM** [comment]
Entries to split #2323
