### ISSUE TITLE
Steam's "The Journey" and Epic's "Journey" are different games, but on the same info page.

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1644]
IsThereAnyDeal.com page:  
https://isthereanydeal.com/game/journey/info/

Steam game "The Journey"
https://store.steampowered.com/app/546240/The_Journey/

Epic Game Store's "Journey"
https://www.epicgames.com/store/en-US/product/journey/home/

[Issue created by [deleted]: 2020-02-17]
[Last updated on bitbucket: 2020-06-11]

[Comment created by Bujno: 2020-06-11]
Fixed. Now at [https://isthereanydeal.com/game/journey/info/](https://isthereanydeal.com/game/journey/info/) - [https://store.steampowered.com/app/638230/](https://store.steampowered.com/app/638230/) and [https://www.epicgames.com/store/ru/product/journey/home](https://www.epicgames.com/store/ru/product/journey/home). Great job!

[Comment created by Bujno: 2020-04-04]
See “[#1473: "Journey" and "The Journey" are different games but on the same info page](https://bitbucket.org/tfedor/isthereanydeal.com/issues/1473/journey-and-the-journey-are-different)“.

**Comment by MarkitkaM** [comment]
It was fixed within conversation on bitbucket.
