### ISSUE TITLE
The Longing is listed twice

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1653]
**MERGE ENTRIES:**
The Longing is listed twice, one for Humble Store and the other for Steam. It appears the title is slightly different between the two which may have caused the issue.

https://isthereanydeal.com/game/longing/info/
https://isthereanydeal.com/game/thelonging/info/

[Issue created by [deleted]: 2020-03-10]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
