### ISSUE TITLE
Merge duplicate of Shadow Tactics: Blades of the Shogun

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1665]
**MERGE ENTRIES:**

There is a duplicate entry of Shadow Tactics: Blades of the Shogun just called "Shadow Tactics" only showing the Epic Games store when it was free- but it is the same game \(as shown in the Epic Games library\)

![](https://bitbucket.org/repo/b6qGGA/images/3062921597-image.png)
‌

[https://isthereanydeal.com/game/shadowtacticsbladesofshogun/info/](https://isthereanydeal.com/game/shadowtacticsbladesofshogun/info/)

duplicate entry for epic games store: [https://isthereanydeal.com/game/shadowtactics/info/](https://isthereanydeal.com/game/shadowtactics/info/)

same game on epic games store [https://www.epicgames.com/store/en-US/product/shadow-tactics/home](https://www.epicgames.com/store/en-US/product/shadow-tactics/home)

[Issue created by saber-dan: 2020-03-20]

[Comment created by caeldom: 2020-03-20]
Used my wrong account to report the above issue, would it be possible to change the reporter to this account please?

‌

**Comment by MarkitkaM** [comment]
Entries to merge #2324
