### ISSUE TITLE
Basement - Wrong Game/Price

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1671]
When you go to the game Basement here:

https://isthereanydeal.com/waitlist/#/page:game/info?plain=basement

It shows that the game is $1.02 on Itch.io but that "Basement" is a different game than the "Basement" on my Waitlist and that's on Steam. Figured someone would want to correct and fix that.

I was very disappointed to see it was a different game.

[Issue created by [deleted]: 2020-03-23]

**Comment by MarkitkaM** [comment]
Duplication of the #1841
