### ISSUE TITLE
OneShot deal links to wrong game

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1673]
This is related to the previous issue:

[https://bitbucket.org/tfedor/isthereanydeal.com/issues/1002/oneshot-deal-page-links-to-the-wrong-game](https://bitbucket.org/tfedor/isthereanydeal.com/issues/1002/oneshot-deal-page-links-to-the-wrong-game)

The [itch.io](http://itch.io) “One Shot” was added to Steam in February so the ITAD OneShot page erroneously links to the new One Shot page again.

OneShot ITAD page:  [https://isthereanydeal.com/game/oneshot/info/](https://isthereanydeal.com/game/oneshot/info/)

[Issue created by mrwierzbicki: 2020-03-30]

**Comment by MarkitkaM** [comment]
Duplication of the #2171
