### ISSUE TITLE
Game labeled Gaia edition is wrong game, picture is from Gaia

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1678]
I keep getting notified that Gaia Edition is on sale, however even though the picture matches, the game is the wrong one. the actual game is called Gaia. There is a second version listed as GAIA that is the same game but only on stores other than steam.

Gaia edition is a package from a different game called Res Judicata: Vale of Myth

Here is the link to the bundle:
https://store.steampowered.com/bundle/6563/Gaia_Edition/

Gaia is a different game at this link:
https://store.steampowered.com/app/906790/Gaia/

[Issue created by [deleted]: 2020-04-03]
[Last updated on bitbucket: 2021-01-31]

[Comment created by Endler16: 2021-02-24]
Yes, the first one is the one I was thinking of. The one on
istheranydeal with the same logo is a completely different game.

Sincerely,
David Letts

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

[Comment created by Bujno: 2021-01-31]
[https://store.steampowered.com/app/906790](https://store.steampowered.com/app/906790) → [https://isthereanydeal.com/game/gaia/info/](https://isthereanydeal.com/game/gaia/info/)?

**Comment by MarkitkaM** [comment]
Entries to split #2323
