### ISSUE TITLE
Listing for Axiom Verge Is Mixed Up

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1687]
**SPLIT ENTRIES:**
ITAD’s listings for [Axiom Verge](https://store.steampowered.com/app/332200/Axiom_Verge/) and [Axiom Verge’s game \+ OST pack](https://store.steampowered.com/sub/70162/) are [fused into one](https://isthereanydeal.com/game/axiomverge/info/).  
The “Package Contents” field displays only the [OST](https://isthereanydeal.com/game/axiomvergeoriginalsoundtrack/info/), while the “Prices” field lists Axiom Verge on Steam twice \(one of them being the game \+ OST pack\).

My guess is that ITAD’s crawling of Steam must’ve bugged due to the developers \(Thomas Happ Games LLC\) listing the game \+ OST pack under the same name as the game itself.

[Issue created by denismattos: 2020-04-11]
[Last updated on bitbucket: 2020-05-01]

**Comment by MarkitkaM** [comment]
Entries to split #2323
