### ISSUE TITLE
Customize RSS feed

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#169]
I use RSS feeds a lot, because it's the best way to have a broad look at deals from all over the place, even for games that I wasn't aware off; currently though, the RSS feed sends unfiltered deals, and I couldn't see any obvious way to set it to only send RSS about, for example, deals at a minimum of 50% sale (while the website has this kind of filter). Is it possible to make a customizable RSS feed with the same filters on the website?

[Issue created by [deleted]: 2015-03-31]

[Comment created by tfedor: 2015-03-31]
Filters for RSS work exactly like for [widgets](http://isthereanydeal.com/api/widget/ref/).

For 50% minimum price cut you would want this:

http://isthereanydeal.com/rss/deals/eu2/?query=%2Ffilter:cut%2F50%2F100
(don't forget to change the region in URL)

**Comment by MarkitkaM** [comment]
Solved within the conversation.
