### ISSUE TITLE
how to change steam region not showing properly in augmented steam?

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1690]
how to change steam region not showing properly in augmented steam?

[Issue created by [deleted]: 2020-04-14]

[Comment created by ndnd: 2020-04-14]
successfully solved via discord

‌

[Comment created by ndnd: 2020-04-14]
can i somehow set the region for augmented steam?

[Comment created by ndnd: 2020-04-14]
why it constantly showing these strange numbers and i cannot fight that?

![](https://bitbucket.org/repo/b6qGGA/images/3417071467-CwsuE9H%5B1%5D.png)
‌

**Comment by MarkitkaM** [comment]
It was solved via conversation.
