### ISSUE TITLE
Add "Before We Leave" by Balancing Monkey Games

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1694]
[https://www.epicgames.com/store/en-US/product/before-we-leave/home](https://www.epicgames.com/store/en-US/product/before-we-leave/home?sessionInvalidated=true)

[Issue created by Bujno: 2020-04-17]

**Comment by MarkitkaM** [comment]
Added:
https://isthereanydeal.com/game/beforeweleave/info/
https://isthereanydeal.com/search/?q=Before+We+Leave
