### ISSUE TITLE
Punch Line! steam link is to the wrong game

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1696]
Punch Line!
https://isthereanydeal.com/game/punchline/info/

Steam link goes to the wrong game:
https://store.steampowered.com/app/1147390/

This is the correct link:
https://store.steampowered.com/app/766680/

[Issue created by [deleted]: 2020-04-20]

**Comment by MarkitkaM** [comment]
Duplication of the #1900.
