### ISSUE TITLE
Game CELLAR has incorrect itch.io link

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1698]
[https://isthereanydeal.com/game/cellar/info/](https://isthereanydeal.com/game/cellar/info/)  
Its pointing to completely different [itch.io](http://itch.io) game with same name.

[Issue created by dimon222: 2020-04-21]

**Comment by MarkitkaM** [comment]
If I compare all listed games with the logo of thumbnail here https://isthereanydeal.com/game/cellar/info/ then it looks it should be another game but I am not sure.
Itch.io and the first listed Steam are the same games.

![chrome_tbgQ45lSGk](https://user-images.githubusercontent.com/88401908/133901331-bd428138-a128-4245-9190-08ae9e63a240.png)

**Comment by MarkitkaM** [comment]
Entries to split #2323
