### ISSUE TITLE
WARRIORS Orochi 4 DLC attached to the game Call to Arms

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1700]
Call to Arms has an error where a DLC for WARRIORS Orochi 4 shows in the listing of Steam together with the actual game. The DLC is cheap so it steals the priority.

[Issue created by MechanoRealist: 2020-04-23]
[Last updated on bitbucket: 2021-03-03]

[Comment created by 75338: 2021-03-03]
Still there on 2021-03-03

**Comment by MarkitkaM** [comment]
![chrome_fdS0lNtUER](https://user-images.githubusercontent.com/88401908/133898622-34ce88cc-4499-489b-a977-cfde0c151e8e.png)

**Comment by MarkitkaM** [comment]
Entries to split #2323
