### ISSUE TITLE
DarkLight and Dark Light games have mixed entries

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1701]
Hence, DarkLight is currently on offer 60%, Dark Light is not.

[Issue created by JoeMcHansen: 2020-04-29]

**Comment by MarkitkaM** [comment]
Honestly, I can't find the wrong entries. I leave it open.

https://isthereanydeal.com/search/?q=darklight
https://isthereanydeal.com/game/darklight/info/

**Comment by MarkitkaM** [comment]
Entries to split #2323
