### ISSUE TITLE
[New Waitlist] The button to remove a game from your collection says "Add to Collection"

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1704]
![](https://bitbucket.org/repo/b6qGGA/images/197473910-itad%20new%20waitlist%20remove%20from%20collection.png)
‌

[Issue created by blacryu: 2020-05-03]

**Comment by MarkitkaM** [comment]
Fixed.
![chrome_OLjjDZYrAF](https://user-images.githubusercontent.com/88401908/133897738-7818a4c4-9f5c-42f3-b13d-430c80c3655c.png)
