### ISSUE TITLE
Add "Strategic Mind: Blitzkrieg" by Starni Games

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1709]
[https://store.steampowered.com/app/1200330](https://store.steampowered.com/app/1200330/Strategic_Mind_Blitzkrieg/)

[Issue created by Bujno: 2020-05-09]

[Comment created by Flamerion: 2020-05-09]
There isn’t any deal, it’s not out yet.

**Comment by MarkitkaM** [comment]
Added https://isthereanydeal.com/search/?q=Strategic+Mind%3A+Blitzkrieg
