### ISSUE TITLE
the Jump Force link for Itch.io is a completely different game

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1716]
your website shows Jump Force is free on Itch.io, however that is a completely different game. this is interfering with being able to track the lowest price for the more popular Jump Force game released in 2018.

https://isthereanydeal.com/waitlist/#/page:game/info?plain=jumpforce

[Issue created by [deleted]: 2020-05-12]

**Comment by MarkitkaM** [comment]
Duplication of the #1930
