### ISSUE TITLE
Need to merge Orwell

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1730]
**MERGE ENTRIES:**
I just bought the key from Humble linked to this:
https://isthereanydeal.com/game/orwell/info/

and after activating and syncing my collection, it was added to this:
https://isthereanydeal.com/game/orwellkeepinganeyeonyou/info/

[Issue created by [deleted]: 2020-05-20]

**Comment by MarkitkaM** [comment]
#1505 Related

**Comment by MarkitkaM** [comment]
Entries to merge #2324
