### ISSUE TITLE
Rename "Watchers" to "The Watchers"

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1734]
[https://isthereanydeal.com/game/watchers/info/](https://isthereanydeal.com/game/watchers/info/)

[https://store.steampowered.com/app/1112830](https://store.steampowered.com/app/1112830)

[Issue created by Bujno: 2020-05-26]

**Comment by MarkitkaM** [comment]
It must be a different game by the name and thumbnail i guess.

SPLIT ENTRIES?

**Comment by Korb** [comment]
I checked the links of several games with similar spellings.

ITAD card: "Watchers" (https://isthereanydeal.com/game/watchers/info/)
The link in the card leads to: "The Watchers" (https://store.steampowered.com/app/1112830/)
Should lead to: "Watchers" (https://store.steampowered.com/app/1124980/)

"The Watchers: DEVOUR" (https://isthereanydeal.com/game/watchersdevour/info/)
N/A
https://store.steampowered.com/news/app/1274570/view/2483120772741061295 — the card must be removed.

"The Watcher" (https://isthereanydeal.com/game/watcher/info/)
"The Watcher" (https://store.steampowered.com/app/1291710/)
OK

"The Watchers - Soundtrack" (https://isthereanydeal.com/game/watcherssoundtrack/info/)
"The Watchers - Soundtrack" (https://store.steampowered.com/app/1218160/)
OK

**Need to add to the ITAD**:
Watchers by Ecpa (https://ecpa.itch.io/watchers)
The Watchers by Dansodic (https://dansodic.itch.io/the-watchers)
The Watchers - (Play In Your Web Browser) by Jordan Winslow (https://jordanwinslow.itch.io/the-watchers-browser)
The Watchers by Jordan Winslow (https://jordanwinslow.itch.io/the-watchers)

**Comment by MarkitkaM** [comment]
> ITAD card: "Watchers" (https://isthereanydeal.com/game/watchers/info/)
> The link in the card leads to: "The Watchers" (https://store.steampowered.com/app/1112830/)
> Should lead to: "Watchers" (https://store.steampowered.com/app/1124980/)

Entries to split #2323

> "The Watchers: DEVOUR" (https://isthereanydeal.com/game/watchersdevour/info/)
> N/A
> https://store.steampowered.com/news/app/1274570/view/2483120772741061295 — the card must be removed.

Moved to the separated issue #2371

> Need to add to the ITAD:
> Watchers by Ecpa (https://ecpa.itch.io/watchers)
> The Watchers by Dansodic (https://dansodic.itch.io/the-watchers)
> The Watchers - (Play In Your Web Browser) by Jordan Winslow (https://jordanwinslow.itch.io/the-watchers-browser)
> The Watchers by Jordan Winslow (https://jordanwinslow.itch.io/the-watchers)

Moved to the separated issue #2370
