### ISSUE TITLE
Solstice - two games with the same name

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1740]
Currently on isthereanydeal.com there's a game listed as Solstice (https://store.steampowered.com/app/1063870), which is a strategy game. There is another game, a visual novel, named Solstice (https://store.steampowered.com/app/317280) which isn't listed on the website at all. In addition, bonus content for the Visual Novel Solstice (https://isthereanydeal.com/game/solsticeostplusbonuscontent/info/) is listed on the website as a DLC for the previously mentioned Strategy game Solstice. In order to properly fix this I suppose the Visual Novel Solstice needs to be added to the database, and the DLC should be listed under that game instead of the Strategy Solstice.

[Issue created by [deleted]: 2020-06-01]

**Comment by MarkitkaM** [comment]
**SPLI ENTRIES:**
Double listing for itch.io and Steam
https://isthereanydeal.com/game/solstice/info/
![image](https://user-images.githubusercontent.com/88401908/137633626-41dec659-885e-4446-be36-6f621bc5c651.png)

**Comment by MarkitkaM** [comment]
Entries to split #2323
