### ISSUE TITLE
wrong game showing on waitlist

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1747]
https://store.steampowered.com/app/1090800/Northern_Lights/

This game does not show up on your search, and if wishlisted another diferent game is shown.

[Issue created by [deleted]: 2020-06-06]

**Comment by MarkitkaM** [comment]
**SPLIT ENTRIES:**
3 different games are tracked from Steam, only one is correct. Itchi.io seems to be the correct game for this entry but not sure:
![chrome_HDZZiq3fFb](https://user-images.githubusercontent.com/88401908/133891318-ee2386c7-b1e4-4b57-b794-5e810064680b.png)

**Comment by MarkitkaM** [comment]
Entries to split #2323
