### ISSUE TITLE
Kerbal Space Program: Making History does not list GoG price

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1750]
* [https://isthereanydeal.com/game/kerbalspaceprogrammakinghistoryexpansion/info/](https://isthereanydeal.com/game/kerbalspaceprogrammakinghistoryexpansion/info/)
* [https://www.gog.com/game/kerbal\_space\_program\_making\_history](https://www.gog.com/game/kerbal_space_program_making_history)

‌

[Issue created by Beerbelott: 2020-06-07]

**Comment by MarkitkaM** [comment]
MERGE ENTRIES:
https://isthereanydeal.com/game/kerbalspaceprogrammakinghistory/info/
https://isthereanydeal.com/game/kerbalspaceprogrammakinghistoryexpansion/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
