### ISSUE TITLE
Kerbal Space Program: Breaking Ground does not list GoG price

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1751]
* [https://isthereanydeal.com/game/kerbalspaceprogrambreakinggroundexpansion/info/](https://isthereanydeal.com/game/kerbalspaceprogrambreakinggroundexpansion/info/)
* [https://www.gog.com/game/kerbal\_space\_program\_breaking\_ground](https://www.gog.com/game/kerbal_space_program_breaking_ground)

‌

[Issue created by Beerbelott: 2020-06-07]

**Comment by MarkitkaM** [comment]
MERGE ENTRIES:
https://isthereanydeal.com/game/kerbalspaceprogrambreakingground/info/
https://isthereanydeal.com/game/kerbalspaceprogrambreakinggroundexpansion/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
