### ISSUE TITLE
Banks in the US may not allow overseas transactions

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1755]
I feel there should be a feature that either allows the user to block seeing a certain store or that certain stores should be marked on the website if they run from overseas. Recently i bought Fallout NV and 3 and I used Gamebillet and my bank didn't allow me to make a purchase overseas for security reasons without calling them. I honestly spent 3 days trying to figure this out until I finally called them and found this out. I feel this would be an awesome feature for people who have banks like mine so that I can actually buy a game that is on sale without having to make a phone call during a specific time frame every time i want to buy a game on sale.

[Issue created by [deleted]: 2020-06-09]

**Comment by MarkitkaM** [comment]
That is the problem of the bank.
