### ISSUE TITLE
/search/ - "The Journey", /game/ - "Journey"

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1759]
![](https://bitbucket.org/repo/b6qGGA/images/301313877-2020-06-11_19-48-50.png)
[https://isthereanydeal.com/search/?q=Journey](https://isthereanydeal.com/search/?q=Journey)

![](https://bitbucket.org/repo/b6qGGA/images/687035269-2020-06-11_19-49-16.png)
[https://isthereanydeal.com/game/journey/info/](https://isthereanydeal.com/game/journey/info/)

[Issue created by Bujno: 2020-06-11]

**Comment by MarkitkaM** [comment]
In the name of the game is exthe "The".

**Comment by MarkitkaM** [comment]
https://isthereanydeal.com/game/journey/info/ ->
https://www.epicgames.com/store/en-US/p/journey?epic_affiliate=isthereanydeal&epic_gameId=lemur
https://store.steampowered.com/app/638230/Journey/

**Comment by MarkitkaM** [comment]
Duplication #2717
