### ISSUE TITLE
Wrong/Duplicate Entry for Civilization VI New Frontier Pass

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1762]
**MERGE ENTRIES and ADD a THUMBNAIL:**
The Epic Game Store listing for the New Frontier Pass is on its own listing under *sidmeierscivilizationvlnewfrontierpass*, as opposed to
*sidmeierscivilizationvinewfrontierpass*.

https://isthereanydeal.com/game/sidmeierscivilizationvlnewfrontierpass/info/

https://isthereanydeal.com/game/sidmeierscivilizationvinewfrontierpass/info/

There is also another entry omitting the 'Sid Meiers'.

https://isthereanydeal.com/game/civilizationvinewfrontierpass/info/

[Issue created by [deleted]: 2020-06-16]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
