### ISSUE TITLE
"The Forgotten Land" links to another game on waitlist

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1763]
If I try to add this game to my waitlist: https://store.steampowered.com/app/1099460/The_Forgotten_Land/

It instead adds this game: https://isthereanydeal.com/game/forgottenland/info/

[Issue created by [deleted]: 2020-06-17]

**Comment by MarkitkaM** [comment]
**SPLIT ENTRIES:**
https://isthereanydeal.com/game/forgottenland/info/
![chrome_XzJZyalA0K](https://user-images.githubusercontent.com/88401908/133482444-b6bd23d2-9fc0-4601-b55e-d585f2cd44a8.png)

**Comment by MarkitkaM** [comment]
Entries to split #2323
