### ISSUE TITLE
Two separate games with the same name (The Bunker) are sharing deal listings

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1766]
[The Bunker](https://www.pcgamingwiki.com/wiki/The_Bunker) \(Splendy Interactive & Wales Interactive\) is currently advertised for sale at [Itch.io](https://endless-studios.itch.io/the-bunker ) \(link to Endless Studios’s game\) on the front page for YesThereIsADeal. They are two different games.

[Issue created by MagikGimp: 2020-06-20]

**Comment by MarkitkaM** [comment]
**SPLIT ENTRIES**

**Wrong entries via screeenshot:**
![chrome_TL7Cwrh1yA](https://user-images.githubusercontent.com/88401908/133481415-b6d8d7cf-96c8-4c63-a91e-a7c328510d70.png)

**Comment by MarkitkaM** [comment]
Entries to split #2323
