### ISSUE TITLE
API features request

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#177]
I'm not sure if you have a public API planned, but it could be very useful.

For example, I'd like to make a browser extension that can create a link to ITAD add-to-waitlist page on different stores' game pages (plus checking if the game is already in Waitlist). Same with adding to the collection.

Some of those things I can do by scraping Public Waitlist page (or exported Waitlist and Collection files) and for every game there scraping ITAD game page for stores links, and keeping this data locally. But I really don't like the idea of "auto-downloading" ITAD pages, and don't even know what are the appropriate time intervals between http-requests (and there could be a lot of them so that can take a lot of time).

Is there anything that can be done in not-so-distant future? A simple API with an input of a game url or "store + store-specific game id" and output of ITAD game id would be perfect for a start.

[Issue created by enchained: 2015-04-20]
[Last updated on bitbucket: 2017-03-03]

[Comment created by fonk666: 2017-03-03]
Ok, thank you for your responses.

Is it possible to get steam ids of the ITAD collection games to be able to query Steam with them?

I think it would be possible to search the games by title but I think it would be slow and unreliable.

[Comment created by tfedor: 2017-03-02]
You should parse Steam for that, ITAD is not supposed to be a proxy to Steam's data.

[Comment created by fonk666: 2017-03-02]
Yes, they might be from another source but Steam tags are good. Being an example: Doom : FPS,Action,Gore,Demons,Shooter, etc...

[Comment created by tfedor: 2017-03-01]
What tags or categories do you mean? From Steam?

[Comment created by fonk666: 2017-03-01]
Hi, first, thanks for your awesome work!

Second, it would be nice to have a means to get tags or categories of a game or a set of games. Alternatively it will be nice to have the possibility of get the steam id of a game, with that it would be possible to query steam and get the game tags.
ITAD web indeed provides uris to steam pages of a game (and then the mentioned id) but I was unable to find this info through API. I am missing something? 

Thanks in advance

[Comment created by tfedor: 2015-07-12]
* added &optional=stores to Collection endpoint
* added endpoint which returns full list of games in user's Collection

[Comment created by tfedor: 2015-07-03]
Alright, I've added three new endpoints: `/game/plain/` for getting ITAD's game identifier from game id, url or title, `user/wait` for checking whether game is in user's Waitlist and `user/coll` similarly for Collection. It is now also live, so everything documented should work now.

For future updates I will try to add note if the endpoint is not yet live and I will also post here when new endpoints are added.

It would be great if you could [register your app](http://isthereanydeal.com/apps/new/) now with some description so I know what to focus on next.

Also note that `game/plain` endpoint will probably need updates, so I would like to see real-life scenarios to try to optimize it. I've tried to explain why getting plain via API is not really that straightforward in the docs.

[Comment created by bb34887: 2015-07-03]
@tfedor

Plain web forms only support GET and POST, even in HTML5, but this is an "API", which sort of implies programming, so requiring javascript doesn't seem onerous.

A more interesting question is regarding browser support for PUT and DELETE. There are questions on stackoverflow about it, but I couldn't find any that were very recent.

Maybe stick to GET and POST, to be on the safe side?

[Comment created by tfedor: 2015-07-02]
Documentation is being hosted here: http://docs.itad.apiary.io/

Everything I'm writing about there is not yet on production, the plan is to add 3 more endpoints before pushing to production: get plain from shop/game_id, title or URL, read waitlist and read collection. I'm hoping for weekend release.

In the meantime you can read docs I already have, the most general stuff about API should be done, if there's a problem with something let me know.

And I have a question: I'm thinking how should I approach future API endpoints that will require updates and delets. Should I do it correctly, RESTful, with all GET/POST/PUT/DELETE or rely only on GET/POST, since PUT/DELETE may be a bit harder to work with?

[Comment created by tfedor: 2015-06-26]
The basic foundations that i need to built to be able to have API are now done, so I can work on endpoints now. I hope the progress from now on will be much faster.

[Comment created by tfedor: 2015-06-18]
Alright, I'm starting working on API.

I wanted to post a rough roadmap here but I changed my mind, I'll update you as I go. I will require you to register your app and I will also built a sort of list of apps that use ITAD's API to give you some exposure.

I'll start with APIs which modify Waitlist and Collection. For that I need to be able to ask a user for permission, seems like the best would be to use an OAuth rather than reinventing the wheel, so I'm learning how to build a OAuth server now.

For documentation, I will most likely use Apiary.io, I'll update you as I'll go.

[Comment created by enchained: 2015-05-28]
> if there are any specific requests for endpoints it would be good time let me know now.

Endpoints I could think of right away: 

* Get the game id on itad 

> input: game url in store / game id in store + store id (single request about several games at once would be nice)

> output: itad id

* Search for games on itad

> -->  optional string (with special characters support to do exact name search, search with wildcard, etc) + filters (stores, on sale and others), maybe optional authorization to filter waitlist / collection

> <-- json with results list (id + name)

* Get the game info (maybe a few separate endpoints? for data from About section, stores, price history, bundles, DRM, reviews, DLCs, packages, etc)

> --> itad game id (single request about several games at once would be nice)

> <-- json with the infocard data (price data can be useful to generate charts for games in specific stores right on their pages)

***

Those I need to: check / add to ITAD games right from supported stores pages:

* Check if in waitlist / collection

> --> username (if public) or authorization, + game url in store / game id in store + store id / game name (single request about several games at once would be nice)

> <-- true/false + stores checked, price criteria and other related info like completion state

* Add to waitlist / collection 

> --> username (if public) or authorization, + game url in store / game id in store + store id / game name (single request about several games at once would be nice - for example if I want to import some games from my Steam inventory)

> <-- either POST with quickadd or url to "Add to" Itad page

***

* Get user's waitlist / collection

> --> username (if public) or authorization

> <-- json with details, like stores etc.

> Good for syncing my collection to 3rd party services.

I also want to use collection data to make some tool to choose what to play, with extended tags + genre + features filters, using additional info about games from co-optimus, howlongtobeat and other sites.

I see that there is maybe too much of easy accessible data listed, but API keys and giving access to certain detailed-output endpoints per individual request can eliminate the wrongful usage.

***

Also, did you finish all you've planned to do with specials for the moment? I remember discussing "My bundles collection" section. Endpoint answering to the question "from which bundle(s) do I own this game" could be really useful.

[Comment created by tfedor: 2015-05-27]
Public API is now on top of the TODO list, if there are any specific requests for endpoints it would be good time let me know now.

Copying from Steam group by Efreak:

> Endpoints for the following:
> 
>  * Convert steam appids, desura urls, ASINs, etc into internal appids, if using own database. Should return primary appid
>  * output game info & metadata (name, publisher, etc as well as store urls and steam metadata like early access, etc)
>  * output lowest current and historical prices for a game, and names of stores with said prices.
>  * Endpoint for the current cheapest game in database that isn't actually free. IE, the current $0.19 steam game.
>  * Input URL to supported store, output pricing information. I don't really expect to see this, but it would be nice.
> 
> 
> Can't really think of more at the moment. I wasn't expecting to get an API.
> Ideally all endpoints should have a switch to only look at popular stores (IE, steam)
> I don't really expect to see this, but it would be nice for all endpoints to accept game URLs from any store as an identifier. IE, someone can link to desura or steam or amazon, and you return the price.
If database calls and such are a problem, defaulting to only showing information from common stores is probably OK, with an optional parameter to show information on more obscure stores such as GamesRocket, ShinyLoot, etc. Requiring parameters to show information to show is annoying, but also understandable. 

[Comment created by tfedor: 2015-04-21]
I'll look at it when I'm done with bundle interface.

**Comment by MarkitkaM** [comment]
Solved.
