### ISSUE TITLE
2 Pathos on Steam. Current Best is linked to the wrong game

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1770]
**SPLIT ENTRIES:**
https://store.steampowered.com/app/679300/PATHOS/ this game has current best as 0. Clicking it directs to another game which is free:
https://store.steampowered.com/app/1064670/Pathos/

[Issue created by [deleted]: 2020-06-26]

**Comment by MarkitkaM** [comment]
Entries to split #2323
