### ISSUE TITLE
Sacrifice on Steam/GOG is not the same game as Sacrifice on itch.io

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1771]
Waitlist treats them as the same game, but this

https://store.steampowered.com/app/38440/Sacrifice/
https://www.gog.com/game/sacrifice

is different from this

https://earthshaking.itch.io/sacrifice

[Issue created by [deleted]: 2020-06-26]

**Comment by MarkitkaM** [comment]
Duplication of the #2010
