### ISSUE TITLE
Shift Quantum merge

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1772]
**MERGE ENTRIES:**
https://isthereanydeal.com/game/shiftquantumacybernoirpuzzleplatformer/info/
should be merged with
https://isthereanydeal.com/game/shiftquantum/info/

[Issue created by [deleted]: 2020-06-27]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
