### ISSUE TITLE
Duplicate listings for VA-11 HALL-A: Cyberpunk Bartender Action

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1777]
**MERGE ENTRIES:**
These two listings are duplicates of each other:

[https://isthereanydeal.com/game/vaiihalla/info/](https://isthereanydeal.com/game/vaiihalla/info/)

[https://isthereanydeal.com/game/vaiihallacyberpunkbartenderaction/info/](https://isthereanydeal.com/game/vaiihallacyberpunkbartenderaction/info/)

The second of these seems to be the most complete listing and reflects the game’s full official name.

[Issue created by jmclusky: 2020-07-03]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
