### ISSUE TITLE
AOW3 Eternal Lords (DLC) Multiple Entries

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#178]
http://isthereanydeal.com/#/page:game/info?plain=ageofwondersiiieternallordsexpansion
http://isthereanydeal.com/#/page:game/info?plain=eternallordsexpansion

There's also a GOG version
http://isthereanydeal.com/#/page:game/info?plain=ageofwondersiiieternallords

[Issue created by [deleted]: 2015-04-23]

**Comment by MarkitkaM** [comment]
Entries to merge  #2324
