### ISSUE TITLE
Final Battle Price is Linked to Another Game

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1780]
**SPLIT ENTRIES:**
The ITAD page for [Final Battle](https://isthereanydeal.com/game/finalbattle/info/) is linked to both game The Final Battle and Final Battle so it's displaying Current Best price for the wrong game:

![Final Battle](https://i.ibb.co/grJ7Mst/ITAD.png)

[Issue created by [deleted]: 2020-07-08]

**Comment by MarkitkaM** [comment]
Entries to split #2323
