### ISSUE TITLE
Shows prices way lower than they should be, unusable

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1786]
It seems i am shown prices for other countries/region, yet :
- it still shows in EUROS
- i still have EU1 and FRANCE ticked in my account
- for good measure i desactivated anti-tracking from firefox options and extensions

Still doesn't work.

[Issue created by [deleted]: 2020-07-17]

**Comment by MarkitkaM** [comment]
Not enough information.
