### ISSUE TITLE
Two games, one listing: The Path (older) and Path (newer)

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1787]
https://isthereanydeal.com/game/path/info/ is mixing up info for "The Path," a 2009 walking-sim horror game by Tale of Tales ([https://store.steampowered.com/app/27000/The_Path/](https://store.steampowered.com/app/27000/The_Path/)) and "Path," a 2019 abstract puzzle game by 
Y-Square Games G.K. ([https://store.steampowered.com/app/1208400/Path/](https://store.steampowered.com/app/1208400/Path/)).

Can they be split into two entries? The current page has info for The Path because it's been around for a while. I'm not sure if it'd need to renamed /thepath/ and that would throw off the people subscribed to updates for it, but even if that's the case, it's better than getting info for the wrong game.

[Issue created by [deleted]: 2020-07-18]

**Comment by MarkitkaM** [comment]
Entries to split #2323
