### ISSUE TITLE
[Split Game] Minotaur

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1794]
The entry for Minotaur \([https://new.isthereanydeal.com/game/minotaur/info/](https://new.isthereanydeal.com/game/minotaur/info/)\) contains 4 different games:

1. The Minotaur \([https://store.steampowered.com/app/412540/The\_Minotaur/](https://store.steampowered.com/app/412540/The_Minotaur/)\)

    * Same as: [https://www.indiegala.com/store/game/the-minotaur/412540](https://www.indiegala.com/store/game/the-minotaur/412540)
    
2. Minotaur \([https://store.steampowered.com/app/496660/Minotaur/](https://store.steampowered.com/app/496660/Minotaur/)\)

    * Same as: [https://www.indiegala.com/store/game/minotaur/496660](https://www.indiegala.com/store/game/minotaur/496660?ref=itad)
    
3. Minotaur \([https://store.steampowered.com/app/680590/Minotaur/](https://store.steampowered.com/app/680590/Minotaur/)\)

    * Same as: [https://www.gog.com/game/minotaur](https://www.gog.com/game/minotaur?pp=a93c168323147d1135503939396cac628dc194c5)
    * Same as: [https://gamejolt.com/games/minotaur/182778](https://gamejolt.com/games/minotaur/182778)
    * Same as: [https://u7committee.itch.io/minotaur](https://u7committee.itch.io/minotaur)
    
4. Minotaur \([https://morgot.itch.io/minotaur](https://morgot.itch.io/minotaur)\)

There are also two DLCs:

1. The Minotaur: Soundtrack \([https://new.isthereanydeal.com/game/minotaursoundtrack/info/](https://new.isthereanydeal.com/game/minotaursoundtrack/info/)\)

    * Is DLC for: The Minotaur \([https://store.steampowered.com/app/412540/The\_Minotaur/](https://store.steampowered.com/app/412540/The_Minotaur/)\)
    
2. Minotaur - Nod's route OST \([https://new.isthereanydeal.com/game/minotaurnodsrouteost/info/](https://new.isthereanydeal.com/game/minotaurnodsrouteost/info/)\)

    * Is DLC for: Minotaur \([https://store.steampowered.com/app/680590/Minotaur/](https://store.steampowered.com/app/680590/Minotaur/)\)
    

‌

[Issue created by metilli: 2020-07-28]

**Comment by MarkitkaM** [comment]
Duplication of the #1967

**Comment by MarkitkaM** [comment]
Entries to split #2323
