### ISSUE TITLE
1 Game Link 2 Different Games

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1795]
**SPLIT ENTRIES:**
There are 3 different games under "Clash". Steam has a free to play Sci-Fi game and GoG has a medieval strategy game.

IsThereAnyDeal Link:
https://isthereanydeal.com/game/clash/info/

GoG Link:
https://www.gog.com/game/clash?pp=a93c168323147d1135503939396cac628dc194c5

Steam Link 1:
https://store.steampowered.com/app/416040/CLASH/

Steam Link 2:
https://store.steampowered.com/app/1204950/Cecil_Run/

[Issue created by [deleted]: 2020-07-29]

**Comment by MarkitkaM** [comment]
Entries to split #2323
