### ISSUE TITLE
Horizon Zero Dawn Complete Edition missing Epic Game Store

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1796]
The listing for Horizon Zero Dawn Complete Edition needs to have Epic Game Store added to the Price - Activation/DRM section.

[https://www.epicgames.com/store/en-US/product/horizon-zero-dawn-complete-edition/home](https://www.epicgames.com/store/en-US/product/horizon-zero-dawn-complete-edition/home)

[Issue created by YabosMcGee: 2020-07-30]

**Comment by MarkitkaM** [comment]
Epic store is already tracked.
