### ISSUE TITLE
Can't share a waitlist category.

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1800]
When open a url to a category of a waitlist (isthereanydeal.com/u/awa2t/waitlist/39597/) a description page loads with this text.

"This is a Waitlist
Set up your notification limits and tell us what games you are waiting for
A better wishlist

There is no need to be tied to particular store to keep track of games you want to play. We will always show you the best price across wide variety of stores and help you decide if the price is good enough."

The sharing of the waitlist just works when you want to share the waitlist category you set as default and only through the general waitlist url (isthereanydeal.com/u/awa2t/waitlist)

[Issue created by [deleted]: 2020-08-09]

**Comment by MarkitkaM** [comment]
isthereanydeal.com/u/awa2t/waitlist/39597/
![image](https://user-images.githubusercontent.com/88401908/133038560-b47e1d8a-0ffe-4bfb-a2ab-d953e4d7b07c.png)

**Comment by MarkitkaM** [comment]
Possible to manage waitlist categories at the new websites already. There is possible to set up  if the category is public or not:
![chrome_MIr8GDFtmx](https://user-images.githubusercontent.com/88401908/133885078-2ee616ed-42c5-40cb-b996-f117d4537672.png)
![uz69olBPjN](https://user-images.githubusercontent.com/88401908/133885081-ecd8a0a5-4644-4ee6-b445-eab46c371674.png)
