### ISSUE TITLE
"Totem" games mixed information with same game name

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1801]
**SPLIT ENTRIES:**
https://isthereanydeal.com/game/totem/info

The information is about a 2D pixel-art Action RPG on Steam that seems to no longer exist.
Example video, first I found while searching: https://www.youtube.com/watch?v=FaV3Zcwxiqc

The sale information is on the itch.io game in 3D first-person eerie atmospheric game.
https://shakles.itch.io/totem

Both games are named Totem, but are different games.

[Issue created by [deleted]: 2020-08-13]

**Comment by MarkitkaM** [comment]
Entries to split #2323
