### ISSUE TITLE
EpicGames Color

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1802]
While looking at my collection I noticed that the text color of some of the game stores has changed. EpicGames used to be a blue color, but now it showing up as white.  
I also noticed that Blizzard has the same issue. All the other stores appear to be colored correctly.

[Issue created by DaedalEVE: 2020-08-13]

**Comment by MarkitkaM** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/88401908/133035966-5937bcda-a2ce-4f48-9c36-98780bf26d28.png)
![image](https://user-images.githubusercontent.com/88401908/133037681-392a1ace-1ffd-4c8f-bda5-a2f93bff178e.png)
