### ISSUE TITLE
IPv6 not working anymore

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1803]
Since a few days, the site doesn't reply anymore to IPv6 requests. IPv4 is still ok. I tried from different locations, so I can rule out a provider issue on my end.

telnet www.isthereanydeal.com 443
Trying 2a05:d018:f48:8a00:b474:141c:35e2:7ff7...
^C⏎                                                                                                                     
telnet -4 www.isthereanydeal.com 443
Trying 54.154.6.15...
Connected to www.isthereanydeal.com.
Escape character is '^]'.

[Issue created by [deleted]: 2020-08-14]
[Last updated on bitbucket: 2020-08-31]

[Comment created by windseeker3: 2020-08-31]
tested from external to rule out any problems on my side:

```
INFO: Looking for AAAA RR at isthereanydeal.com....
INFO: test started Mon Aug 31 10:53:16 CEST 2020
ERROR: can't connect over IPv6
INFO: Test ended Mon Aug 31 10:53:19 CEST 2020
```

[https://ipv6alizer.se/?address=https://isthereanydeal.com](https://ipv6alizer.se/?address=https://isthereanydeal.com)

[Comment created by windseeker3: 2020-08-21]
Confirmed. This is really annoying.  
It’s really hard to convince an IPv6 capable system to only use IPv4 to a host that has a AAAA record in DNS.

**Comment by MarkitkaM** [comment]
It is an old bug. We don't know, if it is still happening or not.
