### ISSUE TITLE
The itch.io link for the game vessel is for the wrong game (its a different game called vessel)

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1808]
**SPLIT ENTRIES:**

The info page for the game Vessel \([https://isthereanydeal.com/game/vessel/info/](https://isthereanydeal.com/game/vessel/info/)\) has a steam link and a [itch.io](http://itch.io) link but the [itch.io](http://itch.io) link is for a different game called Vessel

This is the Stream link for the actual game [https://store.steampowered.com/app/108500/Vessel/](https://store.steampowered.com/app/108500/Vessel/)

This is the [itch.io](http://itch.io) link for the different game [https://jackspinoza.itch.io/vessel](https://jackspinoza.itch.io/vessel)
![chrome_YfmJzefT1O](https://user-images.githubusercontent.com/88401908/132958891-7cbd3583-0dcb-4243-bb37-352f303d3b6d.png)

‌

Thank You

[Issue created by Funkypixie: 2020-08-20]

**Comment by MarkitkaM** [comment]
Entries to split #2323
