### ISSUE TITLE
Direct links for Specials are broken...

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1810]
...for example:
1-
https://isthereanydeal.com/specials/9058
2-
https://isthereanydeal.com/specials/#/filter:id/9058

1- was working before but isn't working now
2- it's working as intended

[Issue created by [deleted]: 2020-08-25]

**Comment by MarkitkaM** [comment]
Related #1822

**Comment by MarkitkaM** [comment]
It works.
