### ISSUE TITLE
Two different games mixed into one entry

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1811]
**SPLIT ENTRIES:**
https://isthereanydeal.com/game/crossroad/info/
This entry links to two different games, "Crossroad" on Steam and "Cross the Road" on itch.io.

![chrome_uB1QMFDw66](https://user-images.githubusercontent.com/88401908/132958665-0b1d88a0-864d-4ec3-9422-8fc32692637f.png)

[Issue created by [deleted]: 2020-08-26]

**Comment by MarkitkaM** [comment]
Entries to split #2323
