### ISSUE TITLE
Multiple games mixed up in the same entry

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1812]
https://isthereanydeal.com/game/haven/info/
The itch.io page, the IndieGala page, and the Steam page where the image was pulled from (which doesn't have a store link since it's not out yet) are three different games.

[Issue created by [deleted]: 2020-08-27]

**Comment by MarkitkaM** [comment]
Duplication of #1926. -> Already it was fixed
