### ISSUE TITLE
detail URLs in specials RSS feed not working

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1822]
The “see details“ URL in the specials RSS feeds are linking to the wrong pages.

currently when visiting the link only a 404 Not Found error is shown.

instead of this correct URL: [https://isthereanydeal.com/specials/#/filter:id/9118](https://isthereanydeal.com/specials/#/filter:id/9118)

this wrong URL is shown: [https://isthereanydeal.com/specials/9118/](https://isthereanydeal.com/specials/9118/)

[Issue created by fayer3: 2020-09-02]

**Comment by MarkitkaM** [comment]
Related #1810

**Comment by MarkitkaM** [comment]
This part will be completely new on the new website.
