### ISSUE TITLE
Dreamgame is Dead ("Maintenance")

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1823]
https://www.facebook.com/dreamgame/

It's messing with a lot of current lowest prices due to their maintenance and ITAD not being able to update prices from them. Anything past 2020-08-09 (using their FB post) from them should be 0% off.

[Issue created by [deleted]: 2020-09-04]

**Comment by MarkitkaM** [comment]
The store Dreamgame is no longer existing.
