### ISSUE TITLE
Flashback on itch.io - "totally" different game

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1827]
noticed "histrically low" on Steam https://store.steampowered.com/app/961620/Flashback/ pointing to https://guildcompounder.itch.io/flashback

[Issue created by [deleted]: 2020-09-07]
[Last updated on bitbucket: 2020-09-09]

[Comment created by 75338: 2020-09-09]
[https://isthereanydeal.com/game/flashback/info/](https://isthereanydeal.com/game/flashback/info/) has links to two different Steam games, and a third on [Itch.io](http://Itch.io) as noted above. All three games have the same name. what a _headache_

**Comment by MarkitkaM** [comment]
Duplication of the #1865
