### ISSUE TITLE
Star Wars Battlefront II - GameBillet listed but only offers classic

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1831]
GameBillet shouldn't be listed as offering the newer BattleFront II.  They only offer the classic version and their pricing skews the stats.

[Issue created by [deleted]: 2020-09-14]
[Last updated on bitbucket: 2020-11-03]

[Comment created by A_Salvo: 2020-11-03]
I noticed the same thing.  I bought it too, waste of almost $2, but to be fair, I spend more than that a day on snacks and drinks, and I always wanted a copy of that old 2005 game anyway.  That said, this should be fixed, ASAP.  The $2 Battlefront 2’s are probably both the old 2005 version, not the modern 2017 one.

https://isthereanydeal.com/game/starwarsbattlefrontii/info/
**->** https://www.gamebillet.com/star-wars-battlefront-ii-g?affiliate=1c8adfeb-78f3-4d89-9a91-5b697ec73e37
![image](https://user-images.githubusercontent.com/88401908/132951656-a5d1f5f3-1b81-43ec-8787-3e7980951e3b.png)

**Comment by MarkitkaM** [comment]
Entries to split #2323

**Comment by MarkitkaM** [comment]
Reported also at Discord  - Feedback
