### ISSUE TITLE
"The Elder Scrolls Online: Greymoor" has a lot different pages

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1836]
When searching on ITAD for The Elder Scrolls Online: Greymoor, there are a few double entries popping up with just slightly different names.

There are 4 different versions (excluding the regional versions for China and Russia) (listed with the entries on ITAD):

1. TESO: Greymoor (Standard Edition) => this version includes prior addons and is basically the starter pack for new players
 - https://isthereanydeal.com/game/elderscrollsonlinegreymoorstandardedition/info/
 - https://isthereanydeal.com/game/elderscrollsonlinegreymoor/info/

2. TESO: Greymoor (Collector's Edition) => like 1., but with the CE perks
 - https://isthereanydeal.com/game/elderscrollsonlinegreymoorcollectors/info/
 - https://isthereanydeal.com/game/elderscrollsonlinegreymoorcollectorsedition/info/
 - https://isthereanydeal.com/game/elderscrollsonlinegreymoordigitalcollectorsedition/info/

3. TESO: Greymoor Upgrade => this one is just the addon, it requires that you own a copy of TESO already
 - https://isthereanydeal.com/game/elderscrollsonlinegreymoorupgrade/info/
 - https://isthereanydeal.com/game/elderscrollsonlinegreymoordigitalupgrade/info/
 - https://isthereanydeal.com/game/elderscrollsonlinegreymoorstandardeditionupgrade/info/

4. TESO: Greymoor Upgrade (Collector's Edition) => like 3., but with the CE perks
 - https://isthereanydeal.com/game/elderscrollsonlinegreymoorcollectorseditionupgrade/info/
 - https://isthereanydeal.com/game/elderscrollsonlinegreymoorcollectorsupgrade/info/
 - https://isthereanydeal.com/game/elderscrollsonlinegreymoordigitalcollectorseditionupgrade/info/

These multiple entries are rather confusing, for obvious reasons. It would be neat to have a way to report them in the website directly.

Thanks!

[Issue created by [deleted]: 2020-09-21]

**Comment by MarkitkaM** [comment]
MERGE ENTRIES

**Comment by MarkitkaM** [comment]
Entries to merge #2324
