### ISSUE TITLE
game/basement/info/

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1841]
the "Itch.io" price and link is for the wrong game
https://isthereanydeal.com/game/basement/info/
 -> https://inurashii.itch.io/basement
 -> https://store.steampowered.com/app/340150/Basement/
 
![chrome_T7CTituB93](https://user-images.githubusercontent.com/88401908/132949154-dcd81416-903b-415b-a6d5-6c1375442ced.png)

[Issue created by [deleted]: 2020-10-03]

**Comment by MarkitkaM** [comment]
Entries to split #2323
