### ISSUE TITLE
Site unreachable from my ISP

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1843]
In the last few weeks, the site has been unreachable from my ISP.

I thought the problem was on my end, but my computer can resolve the DNS and also ping the server without issue. However, any connection to port 80 results in a timeout.

If I run ```nmap -sY isthereanydeal.com -p 80``` I get this:

```
Nmap scan report for isthereanydeal.com (54.154.6.15)
Host is up (0.061s latency).

PORT    STATE    SERVICE
80/sctp filtered http
```

It seems that the server is blocking my IP for some reason (my current IP range is 93.148.24.0/24). Could you please investigate? Thank you.

[Issue created by [deleted]: 2020-10-06]

[Comment created by MiTuBo: 2020-10-06]
I’m sorry about that. I maintain a private database of Steam games and used a bot to get some information from ITAD. If you would be so kind as to unblock my IP, I promise to stop using the bot. Thanks

[Comment created by tfedor: 2020-10-06]
Hi, we have detected high number of requests from your IP and you were automatically blocked. Did you run bots or something like that from your IP?

**Comment by MarkitkaM** [comment]
The user no longer answered.
