### ISSUE TITLE
Northern Lights Game not showing

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1846]
Hi,   
  
The Northern Lights game is not showing \([https://store.steampowered.com/app/1090800/](https://store.steampowered.com/app/1090800/)\)

The game has two similar named games.

‌

Thanks  

‌

[Issue created by wearewanaka: 2020-10-16]

**Comment by MarkitkaM** [comment]
SPLIT **ENTRIES:**
https://isthereanydeal.com/game/northernlights/info/
![chrome_GyrdfC4J3o](https://user-images.githubusercontent.com/88401908/132948609-a5c37b0e-8dbb-479d-8786-bcaf40b99447.png)

**Comment by MarkitkaM** [comment]
Entries to split #2323
