### ISSUE TITLE
Game mixup The Fire/Fire: Ungh’s Quest

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1847]
AppIDs 325520 and 1360580, respectively.
With the addon, both games' sites link to the same deal on MacGameStore.
It also looked like the waitlist had swapped the former for the latter, but since I rarely manage my Steam wishlist I could be mistaken.

[Issue created by [deleted]: 2020-10-17]

**Comment by MarkitkaM** [comment]
Duplication of the #1944
