### ISSUE TITLE
"ISLANDERS" & "Stranglehold" both contain links to completely different games

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1849]
1. Duplication of #1950
https://isthereanydeal.com/game/islanders/info/#/

2. **SPLIT ENTRIES AND ADD A THUMBNAIL**
https://isthereanydeal.com/game/stranglehold/info/#/

[Issue created by [deleted]: 2020-10-20]

**Comment by MarkitkaM** [comment]
Entries to split #2323
