### ISSUE TITLE
Don't include family-shared games in collection

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#185]
I have family sharing enabled, so have access to games from another account.  Some of these games are also on my wishlist, but they disappear from ITAD because it considers them part of my collection when they are played.

This may be a feature for some (as they don't intend on buying their own copy), but there some games for which I would like to purchase on my own account at some point.

[Issue created by OllieTerrance: 2015-05-07]
[Last updated on bitbucket: 2015-05-15]

[Comment created by tfedor: 2015-05-15]
This stems up from the way Steam shows your collection. If you play family shared games they will show up in your profile ( http://steamcommunity.com/id/tomas3333/games/?tab=all ). I don't think they are in any way marked as played via family sharing.

I'm not sure whether there's something I can do about it currently. For you I would advise to turn off deleting games from your Waitlist automatically: http://isthereanydeal.com/#/page:user/account/settings?section=collection&option=auto_waitlist_remove

**Comment by MarkitkaM** [comment]
Solved within the conversation.
