### ISSUE TITLE
Doom Eternal Steam price wrong

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1850]
[https://isthereanydeal.com/game/doometernal/info/](Link URL)

That links to this:
[https://store.steampowered.com/app/782330/DOOM_Eternal/](Link URL)

isthereanydeal says the current price for the game is $20 on Steam. It's actually $59.99.

[Issue created by [deleted]: 2020-10-20]

**Comment by MarkitkaM** [comment]
Duplication of the #1853
