### ISSUE TITLE
Doom eternal steam listing DLC price rather than actual game price

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1853]
Seems to be fine for any other site but its listing of steam price is the dlcs price. Not the games.

[Issue created by [deleted]: 2020-10-21]

**Comment by MarkitkaM** [comment]
Steam is not tracked anymore https://isthereanydeal.com/game/doometernal/info/, 

but probably should be tracked:
https://store.steampowered.com/app/782330/DOOM_Eternal/

**Comment by MarkitkaM** [comment]
Merge with https://isthereanydeal.com/game/doometernalstandardedition/info/
Entries to merge #2324
