### ISSUE TITLE
HOI4 - La Resistance DLC not showing Humble Store Price

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1854]
The Humble Store currently has it on sale and is the lowest price currently.

https://www.humblebundle.com/store/hearts-of-iron-iv-la-resistance-expansion

[Issue created by [deleted]: 2020-10-22]

**Comment by MarkitkaM** [comment]
**MERGE ENTRIES:**
https://isthereanydeal.com/search/?q=HEARTS+OF+IRON+IV%3A+LA+R%C3%89SISTANCE+EXPANSION

**Comment by MarkitkaM** [comment]
Entries to merge #2324
