### ISSUE TITLE
Sims 4 DLC being split into separate game pages

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1857]
**MERGE ENTRIES:**
Seems like for Sims 4 DLC, theyre not being correctly collected into the same game info page on site. So there are 2 separate pages to track for deals. It might be because of slight differences in the title of the same DLC on different store fronts.

https://isthereanydeal.com/search/?q=Sims+4+DLC

[Issue created by [deleted]: 2020-10-25]

**Comment by MarkitkaM** [comment]
Entries to merge #2324


- The SIMS 4 - Seasons Expansion Pack - Seasons DLC \| PC Origin Instant Access
- The SIMS 4 - Laundry Day Stuff DLC \| PC Origin Instant Access
- The SIMS 4 - My First Pet Stuff DLC \| PC Origin Instant Access
