### ISSUE TITLE
Just Cause Collection compares prices for different bundles

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1859]
SPLIT ENTRIES:
“Just Cause Collection”: [https://isthereanydeal.com/game/justcausecollection/info/](https://isthereanydeal.com/game/justcausecollection/info/)

The ITAD page seems to show the contents of the Steam bundle: Just Cause 1, 2, 3, _and 4_, and a bunch of DLC.

Square Enix, Humble, GMG: These bundles only include 1, 2, 3, and some DLC—_not Just Cause 4_

Gamesplanet US: Only includes Just Cause 1 and 2 and some DLC, _not 3 or 4_

So it seems like there’s three different Just Cause bundles:

* The Steam bundle
* The Square/Humble/GMG bundle
* The Gamesplanet bundle

For some reason I couldn’t follow the Newegg link, so I didn’t test that one.

I found this out just now when I bought the “Just Cause Collection” on Square Enix’s site, activated it on Steam, and noticed that I now only have Just Cause 1–3 but not Just Cause 4 on Steam’s bundle page.

Thank you for ITAD. :slight_smile:

[Issue created by dsedivec: 2020-10-26]

**Comment by MarkitkaM** [comment]
Entries to split #2323
