### ISSUE TITLE
Two games called STASIS

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1860]
https://isthereanydeal.com/game/stasis/info/

The Itch.io STASIS is a first person 3D game by Alexander Mastryukov

The GOG/Fanatical/Steam/Humble Store STASIS is a third person isometric game by THE BROTHERHOOD

[Issue created by [deleted]: 2020-10-28]

**Comment by MarkitkaM** [comment]
Itch.io is not tracked any more.

SPLIT ENTRIES according to the description.

**Comment by MarkitkaM** [comment]
Entries to split #2323
