### ISSUE TITLE
URGENT: I'm trying to change the user and email and I cannot

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1861]
I'm going to change my internet provider this evening, then my old email will be no longer available.

I changed it in Steam but when I try to update the data in the web isthereanydeal.com I cannot. I tried everything, I cannot modify my user name that is my old email by default neither I can update the mail, I log using steam login. Thank you in advance.

[Issue created by [deleted]: 2020-10-29]

**Comment by MarkitkaM** [comment]
Duplication of the #1862
