### ISSUE TITLE
ISLANDERS incorrect link

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1863]
ISLANDERS game page has two links, one is wrong. Probably because it links to a game with the same name but not written in all caps.
https://isthereanydeal.com/waitlist/?by=price:asc#/page:game/info?plain=islanders

Correct link: ISLANDERS on Steam
https://store.steampowered.com/app/1046030/ISLANDERS/

INCORRECT LINK: Islanders (different game) on itch
https://thisisanalt0117.itch.io/islanders

[Issue created by [deleted]: 2020-10-29]

**Comment by MarkitkaM** [comment]
Duplicarion of #1950
