### ISSUE TITLE
Flashback entry mixed with at least three different games

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1865]
[https://isthereanydeal.com/game/flashback/info/](https://isthereanydeal.com/game/flashback/info/)

It has mixed three games: Ultimate Flashback, Flashback and Flashback \(2013\).

In fact, it has repeated Steam links and others.

[Issue created by LukasThyWalls: 2020-10-30]

**Comment by MarkitkaM** [comment]
Totally Mixed up entries, not only for Steam. **SPLIT ENTRIES.**

**Comment by MarkitkaM** [comment]
Entries to split #2323
