### ISSUE TITLE
Waking the Tiger DLC split

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1866]
The HEarts of Iron 4 expansion/DLC "Waking the Tiger" is shown as two separate games; one sold only in steam, as "Expansion - Hearts of Iron IV: Waking the Tiger" and the other sold in many stores as "Hearts of Iron IV: Waking the Tiger".

https://isthereanydeal.com/search/?q=waking+the+tiger

[Issue created by [deleted]: 2020-10-30]

**Comment by MarkitkaM** [comment]
**MERGE ENTRIES:**
https://isthereanydeal.com/game/heartsofironivwakingtiger/info/
https://isthereanydeal.com/game/expansionheartsofironivwakingtiger/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
