### ISSUE TITLE
Incorrect prices on itch.io for items < $1.00

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1867]
There is, unfortunately, this:

![](https://bitbucket.org/repo/b6qGGA/images/1847952404-Screen%20Shot%202020-10-31%20at%202.23.15%20AM.png)
\(the minimum used to be $0.50 but now it’s $1.00 because greed I guess\)

There is no shopping cart or way to combine purchases into a single transaction, so the actual price of a paid game \(or non-game item\) is never less than $1.00 USD.

This does not apply to free items.

[Issue created by bb34887: 2020-10-30]
[Last updated on bitbucket: 2020-11-02]

[Comment created by JUMPhil: 2020-11-02]
I can confirm this, I saw that [Macbat 64](https://isthereanydeal.com/game/macbatviiv/info/) was on sale for $0.49, but you can’t actually buy it for that price. As soon as you click either payment method you immediately get the error that you have to pay at least $1:

![](https://bitbucket.org/repo/b6qGGA/images/2582589129-firefox_4sTZ07lBWB.png)
![](https://bitbucket.org/repo/b6qGGA/images/1664868161-firefox_cMEDEGJ1TX.png)
‌

**Comment by MarkitkaM** [comment]
Not a bug. Itch.io must solve this.
