### ISSUE TITLE
"Insane" page has different games listed

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1868]
**SPLIT ENTRIES:**
https://isthereanydeal.com/game/insane/info
![chrome_qwt38uNrwP](https://user-images.githubusercontent.com/88401908/132394148-6563bab5-00bb-4426-934a-0a668b7722ec.png)

[Issue created by [deleted]: 2020-10-30]

**Comment by MarkitkaM** [comment]
Entries to split #2323
