### ISSUE TITLE
Similar game titles being confused and improperly added to waitlist

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1874]
On my Steam wishlist I have *The* Citadel and when synced to ITAD it adds *Citadel*, a completely different game that I have no interest in. The former isn't on the site at all. This is especially confusing because *Citadel* can't even be purchased on Steam anymore.

https://isthereanydeal.com/game/citadel/info/

![chrome_UWhy8yrXDn](https://user-images.githubusercontent.com/88401908/132391618-581f9cc6-33f7-46af-b833-d8aaefa144ca.png)

[Issue created by [deleted]: 2020-11-07]

**Comment by MarkitkaM** [comment]
Entries to split #2323
