### ISSUE TITLE
waitlist RSS notification feed not found

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#188]
I'm able to open the link in firefox (37.0.2), but when trying to add it to feed readers (inoreader.com/firefox live bookmarks) they cannot open the feed. I tried making the waitlist public and waiting if it would begin working, but the problem still persists.

http://isthereanydeal.com/rss/waitlist/qf4n6:06858b631a56175a2939628b90dfd77c

Using the "public" RSS, but I guess it is not possible to filter out games not in your wishlist like this?
http://isthereanydeal.com/rss/deals/eu1/?query=%2Ffilter:price%2F0%2F10,%26inwaitlist

[Issue created by [deleted]: 2015-05-12]
[Last updated on bitbucket: 2015-05-15]

[Comment created by ttnk: 2015-05-15]
When I paste the feed to inoreader, it starts loading for a while and then says "no feeds found"
Also when moving the mouse cursor over the feed in firefox and opening it (from the top toolbar "bookmarks" menu) it loads for a while and instead of listing the articles, there is just one item that says "Live bookmark feed failed to load."

I also tried to add the feed to inoreader using my phone (chrome browser and the android app), but the same error appears.

I'm able to add other feeds just fine using both methods, even the main RSS feed works (http://isthereanydeal.com/rss/deals/eu1/?query=%2Ffilter:price%2F0%2F10).

I am able to open the rss feed page (http://isthereanydeal.com/rss/waitlist/qf4n6:06858b631a56175a2939628b90dfd77c) and see the feed entries, but one thing i noticed compared to the "public" feed is that the feed items seem to be in alphabetical order (and always the same games) instead of by date. They seem to have the correct date though.

[Comment created by tfedor: 2015-05-15]
Using inWaitlist filter in deals RSS won't work because that RSS feed has no info about your account.

When importing Waitlist feed to feed readers, do you get an error of some kind or something I can work with?

**Comment by MarkitkaM** [comment]
RSS funkcionality will be redo.
