### ISSUE TITLE
Mars 2030 game vs editor

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1882]
**SPLIT ENTRIES:**
[https://isthereanydeal.com/game/marsii0iii0/info/](https://isthereanydeal.com/game/marsii0iii0/info/)

This page includes two related but different items:

Mars 2030 - [https://store.steampowered.com/app/510850/Mars\_2030/](https://store.steampowered.com/app/510850/Mars_2030/)

Mars 2030 Editor - [https://store.epicgames.com/isthereanydeal/mars-2030](https://store.epicgames.com/isthereanydeal/mars-2030)

[Issue created by ehatherley: 2020-11-19]

**Comment by MarkitkaM** [comment]
![chrome_sh0URbWXyB](https://user-images.githubusercontent.com/88401908/132251466-efca6294-b4bb-4066-b360-1afe752ba902.png)

**Comment by MarkitkaM** [comment]
Entries to split #2323
