### ISSUE TITLE
Invalid link to "Outlast" steam

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1883]
**SPLIT ENTRIES:**
https://isthereanydeal.com/game/outlast/info/#/ on this page, the steam link points to the consonant game " Outlast : Journey of a Gladiator"
https://store.steampowered.com/app/1318840/
![chrome_YhYE6l5GJv](https://user-images.githubusercontent.com/88401908/132250770-df29b0e9-1589-4e20-85ae-37be152f5c63.png)

[Issue created by [deleted]: 2020-11-19]

**Comment by MarkitkaM** [comment]
Entries to split #2323
