### ISSUE TITLE
"Bounce" links are wrong

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1885]
**SPLIT ENTRIES:**
[https://isthereanydeal.com/game/bounce/info/](https://isthereanydeal.com/game/bounce/info/) links to the wrong game.

The correct link is  [https://store.steampowered.com/app/464400/Bounce/,](https://store.steampowered.com/app/464400/Bounce/,) but the links \(and so the prices\) are wrong:

1. [https://store.steampowered.com/app/1116300/Bounce/](https://store.steampowered.com/app/1116300/Bounce/)
2. [https://flashbackgamestudios.itch.io/bounce](https://flashbackgamestudios.itch.io/bounce)

‌

[Issue created by AndreTheHunter: 2020-11-21]

**Comment by MarkitkaM** [comment]
![chrome_FqmMqeO7of](https://user-images.githubusercontent.com/88401908/132249474-13c7c215-35d9-4915-ad6b-19612c7797d0.png)

**Comment by MarkitkaM** [comment]
Entries to split #2323
