### ISSUE TITLE
"Silence" link is wrong

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1886]
**SPLIT ENTRIES:**
[https://isthereanydeal.com/game/silence/info/](https://isthereanydeal.com/game/silence/info/) shows a link \(and so incorrect prices\) to [https://8bitpxl.itch.io/the-silence](https://8bitpxl.itch.io/the-silence) \(compare to steam link [https://store.steampowered.com/app/314790/Silence/](https://store.steampowered.com/app/314790/Silence/)\)

[Issue created by AndreTheHunter: 2020-11-21]
[Last updated on bitbucket: 2020-11-30]

[Comment created by Tafkae: 2020-11-30]
Ah yeah, I was about to submit this as well. It got my hopes up for a great deal, haha.

**Comment by MarkitkaM** [comment]
![chrome_reXwaUgFsC](https://user-images.githubusercontent.com/88401908/132249266-5dd43a4c-ba63-4950-92c2-ccbd9dd448e1.png)

**Comment by MarkitkaM** [comment]
Entries to split #2323
