### ISSUE TITLE
"Adrift" link is wrong

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1887]
**SPLIT ENTRIES:**
[https://isthereanydeal.com/game/adrift/info/](https://isthereanydeal.com/game/adrift/info/) shows an incorrect link \(and so incorrect price\) [https://cdunham.itch.io/adrift](https://cdunham.itch.io/adrift) \(compare to the steam page [https://store.steampowered.com/app/300060/ADR1FT/](https://store.steampowered.com/app/300060/ADR1FT/)\)

[Issue created by AndreTheHunter: 2020-11-21]
[Last updated on bitbucket: 2020-11-23]

[Comment created by ehatherley: 2020-11-23]
Also, as indicated by the Steam page link, it is not “Adrift” but rather “Adr1ft”

**Comment by MarkitkaM** [comment]
Entries to split #2323
