### ISSUE TITLE
Wishlisted Steam game "The Ascent", ITAD links to wrong game "Ascent"

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1888]
I added an unreleased cyperpunk action RPG game "The Ascent" to my Steam wishlist: https://store.steampowered.com/app/979690/The_Ascent/

My waitlist now links to this information page, which has the correct concept art:
https://isthereanydeal.com/game/ascent/info/

However the store link goes to a ecently-released 2D platformer game "Ascent":
https://store.steampowered.com/app/1464000/Ascent/

[Issue created by [deleted]: 2020-11-23]

**Comment by MarkitkaM** [comment]
Duplication of the #2202
