### ISSUE TITLE
Split game pages for Kentucky Route Zero

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1892]
**MERGE ENTRIES:**

The main Kentucky Route Zero page is here:

[https://isthereanydeal.com/game/kentuckyroutezero/info/](https://isthereanydeal.com/game/kentuckyroutezero/info/)

GoG sells the same game, but it’s listed under a separate page:

[https://isthereanydeal.com/game/kentuckyroutezeroseasonpass/info/](https://isthereanydeal.com/game/kentuckyroutezeroseasonpass/info/)

As far as I can tell, these are the exact same and would ideally be combined into one entry.

Just a cleanup nit. Thanks!

[Issue created by supermonkey: 2020-11-25]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
