### ISSUE TITLE
Duplicate listings for Horizon Zero Dawn Complete Edition

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1897]
These are the same game and can be merged:

* [https://isthereanydeal.com/game/horizonzerodawncompleteedition](https://isthereanydeal.com/game/horizonzerodawncompleteedition)
* [https://isthereanydeal.com/game/horizonzerodawncomplete](https://isthereanydeal.com/game/horizonzerodawncomplete)

‌

[Issue created by jmbarnes: 2020-11-26]

**Comment by MarkitkaM** [comment]
https://isthereanydeal.com/search/?q=Horizon+Zero+Dawn+Complete

**Comment by MarkitkaM** [comment]
Entries to merge #2324
