### ISSUE TITLE
"ECHO" link is wrong

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1898]
[https://isthereanydeal.com/game/echo/info/](https://isthereanydeal.com/game/echo/info/) shows an incorrect link \(and so incorrect price\) [https://rustam-razuvanov.itch.io/echo](https://rustam-razuvanov.itch.io/echo) \(compare to steam page [https://store.steampowered.com/app/551770/ECHO/](https://store.steampowered.com/app/551770/ECHO/)\)

[Issue created by AndreTheHunter: 2020-11-28]

**Comment by MarkitkaM** [comment]
not tracked for itch.io anymore

**Comment by MarkitkaM** [comment]
Duplication #2032
