### ISSUE TITLE
"Punch Line" is listed correctly on waitlist, but the page goes to some garbage with the same name

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1900]
[Issue created by [deleted]: 2020-12-01]

**SPLIT ENTRIES**
https://isthereanydeal.com/game/punchline/info/
The first steam leads to a different game. 
![chrome_c7eEhRgYd5](https://user-images.githubusercontent.com/88401908/132138044-76ec990f-1b60-487f-aabc-04562460f24a.png)

**Comment by MarkitkaM** [comment]
Entries to split #2323
