### ISSUE TITLE
Repeated entry for MONMUSU * FIGHT!

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1904]
[https://store.steampowered.com/app/804610/MONMUSU\_\_FIGHT/](https://store.steampowered.com/app/804610/MONMUSU__FIGHT/)

**MERGE:**
[https://isthereanydeal.com/game/monmusufight/info/](https://isthereanydeal.com/game/monmusufight/info/)
[https://isthereanydeal.com/game/monmusu\*fight/info/](https://isthereanydeal.com/game/monmusu*fight/info/)

[Issue created by Jotamide: 2020-12-03]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
