### ISSUE TITLE
Mark "Divinity: Original Sin Enhanced Edition - Official Soundtrack" as additional content

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1912]
[https://isthereanydeal.com/game/divinityoriginalsinenhancededitionofficialsoundtrack/info/](https://isthereanydeal.com/game/divinityoriginalsinenhancededitionofficialsoundtrack/info/)

[https://store.steampowered.com/app/409552/Divinity\_Original\_Sin\_Enhanced\_Edition\_\_Official\_Soundtrack/](https://store.steampowered.com/app/409552/Divinity_Original_Sin_Enhanced_Edition__Official_Soundtrack/)

[Issue created by Bujno: 2020-12-05]

**Comment by MarkitkaM** [comment]
Not a bug. The soundtrack should be additional content.

**Comment by Korb** [comment]
> The soundtrack should be additional content.

That's right, it should be labeled as DLC because it is DLC. But at the time the issue was posted, this OST on ITAD was unmarked as DLC.
