### ISSUE TITLE
"Demonheart" links to two different games and displays wrong price

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1917]
On Steam there is a game named "Demonheart", and a newer game named "Demon heart". Both are linked on isthereanydeal for "Demonheart." [Link](https://isthereanydeal.com/game/demonheart/info/)

It's showing that the current price on Steam is both $14.99 and $4.99 (the price of "Demon heart".) The historical low for "Demonheart" is also wrong. This game has never been $4.99 yet.

These prices are also displayed in Augmented Steam when I go to the Steam page of Demonheart. It's showing that the current best is $4.99 on Steam, which is the price of the other game. [Link](https://store.steampowered.com/app/578900/Demonheart/)

[Issue created by [deleted]: 2020-12-06]

**Comment by MarkitkaM** [comment]
https://isthereanydeal.com/game/demonheart/info/
![image](https://user-images.githubusercontent.com/88401908/138586524-73a5bd27-3b6e-49da-8a5b-aad5e2b62a13.png)

**Comment by MarkitkaM** [comment]
Entries to split #2323
