### ISSUE TITLE
CDKeys.com & Humble Store not included in comparison

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#192]
Hiya,
Your site (awesome as it is!) doesn't appear to look up CDKeys.com or the Humble Store. CDKeys often have CRAZY cheap deals and Humble Store does too. Any chance of these being added to the list? Thanks :) 

[Issue created by Addikt: 2015-05-19]
[Last updated on bitbucket: 2019-02-12]

[Comment created by Addikt: 2019-02-12]
Have you seen the other message on here? It proposed a solution to the UK prices for humble bundle. Also, CDKeys.com is very popular, it’s a shame you don’t support them. I’ve purchased probably 50 keys from them without an issue.

[Comment created by Knightw0lf: 2019-02-12]
this could be possible closed now

[Comment created by jimmalk: 2015-07-29]
What language are your parsing scripts Tomáš? I have a hosted Linux server or home Windows server based in the UK I could schedule imports for you from.

CDKeys.com is a brilliant site and have used them many times without issues. They do offer great prices. It's also worth noting they offer a 5% commission affiliate scheme. It would be well worth implementing in my opinion! 

[Comment created by tfedor: 2015-05-19]
CDKeys.com won't be added since they are CD key reseller. We don't cover those.

Humble Store is included for all regions except UK. Reason is that I have no way how to parse UK prices. Humble can't provide product feed for me nor allow to change country on store front (I have contacted them multiple times). Hence, until they change something or I pay for UK server just to parse Humble Store (which I don't plan to do in foreseeable future) they won't be included in UK region.

**Comment by MarkitkaM** [comment]
Solved within the conversation.
