### ISSUE TITLE
augmentedsteam.com Has Expired Certificate

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1920]
Appears to have expired in October. So have to dismiss the warning to visit the site.

[Issue created by [deleted]: 2020-12-08]
[Last updated on bitbucket: 2020-12-10]

[Comment created by IronHerald: 2020-12-10]
“Valid from 2020-11-25 to 2021-02-23”

It’s on your end mate - try updating your browser.

**Comment by MarkitkaM** [comment]
Already fixed.
