### ISSUE TITLE
Wrong listing for Haven

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1926]
https://isthereanydeal.com/waitlist/#/page:game/info?plain=haven
This game's Indiegala store link (https://www.indiegala.com/store/game/haven/508540?ref=itad) is pointing towards another game (with slightly different name "haeven") : https://store.steampowered.com/app/508540/Haeven/
Correct link is https://www.indiegala.com/store/game/haven/983970

[Issue created by [deleted]: 2020-12-12]
[Last updated on bitbucket: 2020-12-17]

[Comment created by Mote_: 2020-12-17]
The [itch.io](http://itch.io) store link is also wrong, pointing to [https://temerity-games.itch.io/haven](https://temerity-games.itch.io/haven)

**Comment by MarkitkaM** [comment]
I can't see the tracking of itch.io any more. IndieGala is tracked correctly.
