### ISSUE TITLE
Deus Ex Collection list incorrect Square Enix version.

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1929]
https://isthereanydeal.com/game/deusexcollection/info/

that collection lists the Square Enix bundle for $10.89, but the Square Enix bundle doesn't include Deus Ex: Mankind Divided or the corresponding Season Pass.

[Issue created by [deleted]: 2020-12-18]

**Comment by MarkitkaM** [comment]
1. The tracking of the Square Enix looks good https://isthereanydeal.com/game/deusexcollection/info/?country=US.

2. Add thumbnail to the detail of the game please

3. I am at Russion region https://isthereanydeal.com/game/deusexcollection/info/?country=RU
-> I click on History
-> ERROR 500 with the layout of the alpha

**Comment by MarkitkaM** [comment]
Ad1) #2695
Ad3) #2694
