### ISSUE TITLE
The Dark Room has both "Dark Room" and "The Dark Room" games from Steam store.

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1938]
**SPLIT ENTRIES:**
[The Dark Room](https://isthereanydeal.com/game/darkroom/info/) Links to both [The Dark Room](https://store.steampowered.com/app/918530/The_Dark_Room/) and [Dark Room](https://store.steampowered.com/app/1240730/Dark_Room/).

Dark Room is a separate game which needs its own entry and removing from The Dark Room's ITAD page. The Dark Room was imported from my Steam Wishlist, and so I'm getting waitlist notifications for discounts on Dark Room.

[Issue created by [deleted]: 2020-12-22]

**Comment by MarkitkaM** [comment]
Entries to split #2323
