### ISSUE TITLE
Game Mistitled, Duplicated

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1940]
It seems "Plebby Quest: The Crusades" is being mistitled as "Army and Strategy: The Crusades".  

Mistitled game for Steam store:
https://isthereanydeal.com/game/armyandstrategycrusades/info/

Properly titled game for other stores: 
https://isthereanydeal.com/game/plebbyquestcrusades/history/

These two game listings should be merged into one, titled "Plebby Quest: The Crusades"

[Issue created by [deleted]: 2020-12-23]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
