### ISSUE TITLE
[Incorrect Game Link] Remember Me

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1943]
Incorrect game link for itch.io

Game: Remember Me
URL: https://isthereanydeal.com/game/rememberme/info/
Wrong: https://bluestockings.itch.io/remember-me

**Fix**:
Website doesn’t have this game. Recommend removal of itch.io entry.

![chrome_w3AbRhjHF9](https://user-images.githubusercontent.com/88401908/132044269-8fa08200-ed6c-4c65-9dd6-b6d7947404f6.png)

[Issue created by [deleted]: 2020-12-24]

**Comment by MarkitkaM** [comment]
Entries to split #2323
