### ISSUE TITLE
Bug for Islanders game

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1950]
**SPLIT ENTRIES:**
The Islanders game is not the same on Steam and itch.io : https://isthereanydeal.com/game/islanders/info/

[Issue created by [deleted]: 2020-12-27]

**Comment by MarkitkaM** [comment]
Related #2017

**Comment by MarkitkaM** [comment]
Entries to split #2323
