### ISSUE TITLE
Amazing Cultivation Simulator game missing from database

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1951]
"Amazing Cultivation Simulator" game is missing from database

https://store.steampowered.com/app/955900/Amazing_Cultivation_Simulator/

[Issue created by [deleted]: 2020-12-27]

**Comment by MarkitkaM** [comment]
1. **MERGE ENTRIES:**
https://isthereanydeal.com/game/amazingcultivationsimulatori0/info/
https://isthereanydeal.com/game/amazingcultivationsimulator/info/

2. Add a thumbnail

**Comment by MarkitkaM** [comment]
Entries to merge #2324
