### ISSUE TITLE
Nancy Drew: Labyrinth of Lies listings are split

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1953]
The main listing is [Nancy Drew: Labyrinth of Lies](https://isthereanydeal.com/game/nancydrewlabyrinthoflies). I think [Nancy Drew®: Labyrinth of Lies PC](https://isthereanydeal.com/game/nancydrewlabyrinthofliespc) and [Nancy Drew®: Labyrinth of Lies (Mac)](https://isthereanydeal.com/game/nancydrewlabyrinthofliesmac) (discontinued?) should be merged with it.

[Issue created by [deleted]: 2020-12-29]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
