### ISSUE TITLE
Nancy Drew: Midnight in Salem listings are split

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1954]
The main listing is [Nancy Drew: Midnight in Salem](https://isthereanydeal.com/game/nancydrewmidnightinsalem). I think [Nancy Drew: Midnight in Salem Standard - PC](https://isthereanydeal.com/game/nancydrewmidnightinsalemstandardpc) and [Nancy Drew: Midnight in Salem Standard - Mac](https://isthereanydeal.com/game/nancydrewmidnightinsalemstandardmac) should be merged with it.

[Issue created by TyWMick: 2020-12-29]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
