### ISSUE TITLE
Minecraft Dungeons Hero Edition listings split

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1955]
The prices for Minecraft Dungeons Hero Edition are split into 3 different listings with one of them being empty entirely. Should be merged together.  
[https://new.isthereanydeal.com/game/minecraftdungeonsheroedition/info/](https://new.isthereanydeal.com/game/minecraftdungeonsheroedition/info/)  
[https://new.isthereanydeal.com/game/minecraftdungeonsheroeditionwindowsi0/info/](https://new.isthereanydeal.com/game/minecraftdungeonsheroeditionwindowsi0/info/) \(Empty\)  
[https://new.isthereanydeal.com/game/minecraftdungeonsheroeditionwindowsi0pcdownloadcode/info/](https://new.isthereanydeal.com/game/minecraftdungeonsheroeditionwindowsi0pcdownloadcode/info/)

Related #1956

[Issue created by arm0ured_dev1l: 2020-12-29]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
