### ISSUE TITLE
BIGFOOT listing error

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1958]
The Itch.io link leads to the wrong game, [IsThereAnyDeal link](https://isthereanydeal.com/game/bigfoot/info/)  [Itch.io link](https://philosoftwares.itch.io/big-foot)

[Issue created by [deleted]: 2020-12-30]

**Comment by MarkitkaM** [comment]
Already fixed. Itch.io is not listed there anymore.
![chrome_sIu4tudSyq](https://user-images.githubusercontent.com/88401908/131900259-2599da0d-eb64-4f08-ab7d-33a9da3b3d07.png)
