### ISSUE TITLE
Superliminal missing Steam page

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1959]
Read title. Game is out on Steam, page on ITAD however disregards it.

[Issue created by [deleted]: 2020-12-30]

**Comment by MarkitkaM** [comment]
The game is already there even tracked from Steam. https://isthereanydeal.com/game/superliminal/info/
![chrome_VFeFOLIj4U](https://user-images.githubusercontent.com/88401908/131899392-ad5eb604-21a4-463a-a8c9-6b4e5df3c1eb.png)
