### ISSUE TITLE
Duplicate games

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#196]
I found two games that have the wrong game tracked on itch.io, Haven and Islanders

1.
https://isthereanydeal.com/game/haven/info/

2. Duplication of #1950
https://isthereanydeal.com/game/islanders/info/

[Issue created by [deleted]: 2021-02-07]

**Comment by MarkitkaM** [comment]
ad1) itch.io is not tracked any more
