### ISSUE TITLE
Sync Issue - Waitlist is fine, Collection however does not sync

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1962]
Profile in question:
http://steamcommunity.com/profiles/76561197973009892

- Deleted Steam profile and re-added it.
- Waitlist syncs without an issue.
- Collection sync responds with : "Nothing found on profile"

My supposition is that his is due the the sheer number of items that it has to sync via my profile.

16,423 Games Owned -and-  6,395 DLC Owned.

When attempting to sync my profile with other sites and tools, everything appears to working.
I have also validated that my privacy options are all set to public as well - per attachment.

[Issue created by [deleted]: 2021-01-02]

**Comment by MarkitkaM** [comment]
duplication of the #2013

I am adding info from this issue to the #2013
