### ISSUE TITLE
ITAD alpha does not work

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1963]
[new.isthereanydeal.com](https://new.isthereanydeal.com) has page title `Internal Server Error` and just says:
```
oops 500
It's embarassing but something's broken!
Please try again in a bit.
```

I tried multiple browsers on desktop and Android, but they all show the same error.

[Issue created by [deleted]: 2021-01-02]

**Comment by MarkitkaM** [comment]
Now works well https://new.isthereanydeal.com/
