### ISSUE TITLE
Missing game "Minotaur"

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1967]
Price history for https://store.steampowered.com/app/680590/Minotaur/ cannot be found on isthereanydeal, instead links to https://isthereanydeal.com/game/minotaur/history/. The bundle and DLC is tracked though.

[Issue created by [deleted]: 2021-01-08]

**Comment by MarkitkaM** [comment]
SPLIT ENTRIES:
https://isthereanydeal.com/game/minotaur/info/
![chrome_XNNwx1h7xt](https://user-images.githubusercontent.com/88401908/137523774-d5e8db04-f47d-4cbb-8468-1496f8466636.png)

**Comment by MarkitkaM** [comment]
Duplication of the #1794
