### ISSUE TITLE
Scott Pilgrim Vs The World Complete Edition showing as 3 separate results

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1976]
**MERGE ENTRIES:**

Scott Pilgrim Vs The World: The Game Complete Edition showing as 3 different listings instead of 1

[Issue created by [deleted]: 2021-01-18]

**Comment by HYBRID-BEING** [comment]
Links for someone who will be fixing this:
https://isthereanydeal.com/game/scottpilgrimvsworldgamecompleteedition/info/
https://isthereanydeal.com/game/scottpilgrimvsworldgamecomplete/info/
https://isthereanydeal.com/game/scottpilgrimvsworldgame/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
