### ISSUE TITLE
"Might and Magic 7: For Blood and Honor" @ Uplay - "did not pass your settings" wrong waitlist status

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1977]
[https://isthereanydeal.com/waitlist/?by=price:asc#/page:game/info?plain=mightandmagicviiforbloodandhonor](https://isthereanydeal.com/waitlist/?by=price:asc#/page:game/info?plain=mightandmagicviiforbloodandhonor)

![](https://bitbucket.org/repo/b6qGGA/images/676495770-2021-01-20_15-27-56.png)
‌

[Issue created by Bujno: 2021-01-20]
[Last updated on bitbucket: 2021-03-09]

[Comment created by Bujno: 2021-03-09]
Again the same game with a price below the notification price is displayed with the same status: 62,25 p. \(-75%\) ≤99,00 p. - "did not pass your settings".

**Comment by MarkitkaM** [comment]
The price is not the only value what is possible to check.

**Comment by Korb** [comment]
> The price is not the only value what is possible to check.

Explain, please, what exactly did you mean?

**Comment by MarkitkaM** [comment]
Please check the **Info** on the left side via screenshot. There are all information about settings for the game in your waitlist. Possibly there is some value which makes "did not pass your settings" yet. 
![msedge_0NgRu82wa5](https://user-images.githubusercontent.com/88401908/132126521-971b9231-5ce1-4822-aee5-14514a6757ba.png)

If there is everything allright, please send screenshot with complete information.

My apologize for belated reply.

**Comment by Korb** [comment]
@MarkitkaM, you were right, Uplay has been removed from the list of watched stores.

Perhaps it makes sense to discuss the possibility of displaying the "current minimum price" taking into account the selected set of stores?

**Comment by MarkitkaM** [comment]
@Korb Create a new issue with the new suggestion, please. This bug is already closed.
