### ISSUE TITLE
[Merge] Two entries for AKIBA'S TRIP: Undead & Undressed

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1978]
**MERGE ENTRIES:**

Probably because of ampersand.

One for Steam:

[https://isthereanydeal.com/game/akibastripundeadundressed/info/](https://isthereanydeal.com/game/akibastripundeadundressed/info/)

One for GOG:

[https://isthereanydeal.com/game/akibastripundeadandundressed/info/](https://isthereanydeal.com/game/akibastripundeadandundressed/info/)

[Issue created by HYBRID_BEING: 2021-01-21]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
