### ISSUE TITLE
[Merge] Real Heroes: Firefighter

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1979]
**MERGE ENTRIES:**

GOG/IndieGala/Fanatical: [https://isthereanydeal.com/game/realheroesfirefighter/info/](https://isthereanydeal.com/game/realheroesfirefighter/info/)

Steam/Amazon: [https://isthereanydeal.com/game/realheroesfirefighterhd/info/](https://isthereanydeal.com/game/realheroesfirefighterhd/info/)

Unknown \(no store\): [https://isthereanydeal.com/game/realheroesfirefighterde/info/](https://isthereanydeal.com/game/realheroesfirefighterde/info/)

Amazon version may be a different one.

[Issue created by HYBRID_BEING: 2021-01-21]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
