### ISSUE TITLE
[Merge] Two entries for Stellaris: Ancient Relics Story pack

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1980]
**MERGE ENTRIES:**
Primary entry: https://isthereanydeal.com/game/stellarisancientrelicsstorypack/info/#/
Superfluous entry: https://isthereanydeal.com/game/stellarisancientrelics/info/

[Issue created by [deleted]: 2021-01-23]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
