### ISSUE TITLE
HTTPS redirect to GamersGate website is not available

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1982]
Secure Connection Not Available

A HTTPS version of [www.dpbolvw.net](http://www.dpbolvw.net) is not available.

What could be causing this?

* Most likely, the web site simply does not support HTTPS.
* It’s also possible that an attacker is involved. If you decide to visit the web site, you should not enter any sensitive information like passwords, emails, or credit card details.

> --------- Forwarded message ---------
>
> From: IsThereAnyDeal.com  
> Date: Thu, 28 Jan 2021 at 02:32  
> Subject: Waitlist: Dungeons 97 p.
>
> Having troubles displaying email? See it on web.  
> Dungeons  
> Historical low: 13,99 p. | Last: 97,00 p. | Best: 49,00 p.  
> 97,00 p. \(-80%\) on [GamersGate](http://www.dpbolvw.net/click-6305441-10785951?URL=https%3A%2F%2Fru.gamersgate.com%2FDD-DUNGEONS-STEAM%2Fdungeons%3Fcaff%3D3964022), activates on Steam \(Default\)  
> Remove from Waitlist

‌

[Issue created by Bujno: 2021-01-28]

**Comment by MarkitkaM** [comment]
Now it is redirecting correctly https://www.gamersgate.com/product/dungeons/
