### ISSUE TITLE
Yakuza Remastered Collection has 2 entries

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1985]
**MERGE ENTRIES:**

Yakuza Remastered Collection has 2 entries instead of one:
https://isthereanydeal.com/game/yakuzaremasteredcollection/info/
https://isthereanydeal.com/game/yakuzaremasteredcollectionbundle/info/

The Humble Bundle entry has an extra collection in the title.

[Issue created by [deleted]: 2021-01-29]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
