### ISSUE TITLE
Singularity linking to a wrong game on Steam

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1986]
The Steam link for Singularity (2010) is linking to a free to play game with the same name (released in 2020). Because of this the original game appears to be sold for free, when in truth it costs 19,99€ on Steam.

[Issue created by [deleted]: 2021-01-30]

**Comment by MarkitkaM** [comment]
Duplication of #2158 and #1973
