### ISSUE TITLE
Mark of the Ninja: Remastered's price shown is of the upgrade, not the full game

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1991]
* The prices are in Brazilian Real.

The price of **Mark of the Ninja: Remastered** on IsThereAnyDeal is currently R$ 2.72 on Steam. On Steam that is the price of the upgrade from the base version to those who own it, while the full game price is R$ 15.19. The screenshots attached show the prices on both ITAD and Steam for comparison.

![chrome_8kUVMtDWOX](https://user-images.githubusercontent.com/88401908/131235732-6a43ba40-ffca-4bc2-87b4-584c3436ab36.png)
![chrome_S7GntwTeSg](https://user-images.githubusercontent.com/88401908/131235734-9e110c6e-b829-4cfa-8eae-e20565368a0a.png)

[Issue created by [deleted]: 2021-02-06]

**Comment by MarkitkaM** [comment]
Duplication of #2002
