### ISSUE TITLE
The BoX & BOX are different games

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1995]
**SPLIT ENTRIES:**

https://isthereanydeal.com/game/box/info/
There are two different games, both on Steam, appearing at this URL.

The BoX – Steam appid: 424750

BOX – Steam appid: 1181070 -> Steam + itch.io
https://store.steampowered.com/app/1181070/BOX/
https://elzaigames.itch.io/box

![chrome_k0Vke5vJAE](https://user-images.githubusercontent.com/88401908/131236441-75896735-8ce1-43d7-98a9-dca7d247c829.png)

[Issue created by [deleted]: 2021-02-12]

**Comment by MarkitkaM** [comment]
Entries to split #2323
