### ISSUE TITLE
The Evil Within and Rise of the Tomb Raider 20 Year celebration show the Steam prices of their Season Passes

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1998]
Seeing this happen often recently, some Steam games will show the prices of the item at the top of the page and not the one corresponding to the game itself. I provide examples for [The Evil Within](https://isthereanydeal.com/game/evilwithin/info/) and [Rise of the Tomb Raider 20 Year Celebration](https://isthereanydeal.com/game/riseoftombraiderii0yearcelebration/info/), showing the prices of their season passes instead of the games in itad. It's not such a bother, but it could become misleading for future reference of the prices.

Thanks for your work, the web is awesome!

[Issue created by [deleted]: 2021-02-12]

**Comment by MarkitkaM** [comment]
**The price is fixed already via screeenshots:**
![msedge_6PVhjn5HbM](https://user-images.githubusercontent.com/88401908/131258829-8d808d51-0096-417f-92ba-2904eb786980.png)
![ShareX_WV2Rct8Wgk](https://user-images.githubusercontent.com/88401908/131258826-04e5f1d7-9a0f-4da9-9ee5-e21ea053b222.png)
