### ISSUE TITLE
Mixed entry

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1999]
**SPLIT ENTRIES:**
The page https://isthereanydeal.com/game/demonheart/info/ links to two Steam games: "Demonheart" and "Demon heart". It's showing the wrong current price and all-time low for the more expensive game, which most people are interested in.

![chrome_1X4MTr2PHB](https://user-images.githubusercontent.com/88401908/131225104-963433a0-39b3-4437-91f7-db1014c9945c.png)

[Issue created by [deleted]: 2021-02-13]

**Comment by MarkitkaM** [comment]
Entries to split #2323
