### ISSUE TITLE
"The Horror Of Salazar House" game splitted

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2001]
The Enigma of Salazar House [https://isthereanydeal.com/game/enigmaofsalazarhouse/info/](https://isthereanydeal.com/game/enigmaofsalazarhouse/info/) \(Only Steam\)

and

The Enigma in Salazar House [https://isthereanydeal.com/game/enigmainsalazarhouse/info/](https://isthereanydeal.com/game/enigmainsalazarhouse/info/) \(Only Itch.io\)

They are the same game. In fact, the game now is “The Horror of Salazar House”. It’s seems the other names were early names.

Thanks.

[Issue created by LukasThyWalls: 2021-02-14]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
