### ISSUE TITLE
"Current Best" is a DLC package that don't contain the base game !

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2008]
[https://isthereanydeal.com/game/dusk/info/](https://isthereanydeal.com/game/dusk/info/)  
  
**Issue :**

Current Best is set to Steam at 8.00€ by buying the package “DUSK - Intruder Edition Upgrade” \(sub/328008\) but the said package _only contain the OST and DLC_ \(apps 994820 and 994821\).

The real price is 16,99€ by buying sub/329111 wich grant acces to app 519860.

**Fix :**

Check if package grant acces to the base game before taking it into account as potential buy option.

[Issue created by Zeper: 2021-02-26]

**Comment by MarkitkaM** [comment]
Duplication #2012
