### ISSUE TITLE
Stalker listing incorrect

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2009]
**SPLIT ENTRIES:**
https://isthereanydeal.com/game/stalker/info/

Steam is linking to https://store.steampowered.com/app/1243580/
![chrome_jAejZkSTi1](https://user-images.githubusercontent.com/88401908/131220612-31c612f9-9576-4b27-a2e2-23eb71ff2d28.png)

[Issue created by [deleted]: 2021-02-27]

**Comment by MarkitkaM** [comment]
Entries to split #2323
