### ISSUE TITLE
Bundle page: MacGameStore -> WinGameStore

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#201]
* http://www.wingamestore.com/pay-what-you-want/
* http://www.macgamestore.com/pay-what-you-want/
*
*
* http://isthereanydeal.com/specials/#/search:#:2097;/option:pending

and the DLC is duplicated

**Pirates of Black Cove: Origins**

* http://isthereanydeal.com/#/page:game/info?plain=piratesofblackcovedlc_0i

* http://isthereanydeal.com/#/page:game/info?plain=piratesofblackcoveorigins

* http://isthereanydeal.com/#/page:game/info?plain=piratesofblackcoveoriginsdlc

**Pirates of Black Cove Gold**

* http://isthereanydeal.com/#/page:game/info?plain=piratesofblackcovegold

* http://isthereanydeal.com/#/page:game/info?plain=piratesofblackcovegoldedition

[Issue created by Klumb3r: 2015-06-06]

[Comment created by tfedor: 2015-06-06]
Isn't MacGameStore and WinGameStore the same store but with different URL?

**Comment by MarkitkaM** [comment]
+ Duplicated Steam entries:
https://isthereanydeal.com/#/page:game/info?plain=piratesofblackcoveorigins

**Comment by MarkitkaM** [comment]
**ad Pirates of Black Cove: Origins)** Entries to merge #2324 and #2700

**ad Pirates of Black Cove Gold)** Entries to merge #2324

**ad** http://isthereanydeal.com/specials/#/search:#:2097;/option:pending )

- http://www.wingamestore.com/pay-what-you-want/
- http://www.macgamestore.com/pay-what-you-want/
-> Bundle is not active and not a bug i guess
