### ISSUE TITLE
"Sacrifice" itch.io listing incorrect

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2010]
**SPLIT ENTRIES:**

https://isthereanydeal.com/game/sacrifice/info/

This game (by Shiny / Interplay) is not available on itch.io, the site includes a link to a different game by the same name (by Shaker): https://earthshaking.itch.io/sacrifice

![image](https://user-images.githubusercontent.com/88401908/131220774-3511ce89-0462-4868-bd23-42988b811bcf.png)

[Issue created by [deleted]: 2021-02-27]

**Comment by MarkitkaM** [comment]
Entries to split #2323
