### ISSUE TITLE
"Bomber Crew Deluxe" is a redundant entry for "Bomber Crew - Deluxe Edition"

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2011]
This: [https://isthereanydeal.com/game/bombercrewdeluxe/info/](https://isthereanydeal.com/game/bombercrewdeluxe/info/)

… should be merged with this: [https://isthereanydeal.com/game/bombercrewdeluxeedition/info/](https://isthereanydeal.com/game/bombercrewdeluxeedition/info/)

[Issue created by KeronCyst: 2021-03-01]

**Comment by MarkitkaM** [comment]
Maybe also merge with that https://isthereanydeal.com/game/bombercrewdeluxeeditiongameplusseasonpass/info/?
-> (https://isthereanydeal.com/search/?q=bomber+crew+deluxe)

Add **thumbnail** aswell.
![image](https://user-images.githubusercontent.com/88401908/131219657-765d0a57-5e06-4e48-be7c-c95ecbd03863.png)

**Comment by MarkitkaM** [comment]
Entries to merge #2324
