### ISSUE TITLE
Dusk, basic edition, wrong price on Steam

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2012]
https://isthereanydeal.com/waitlist/#/page:game/info?plain=dusk

base game currently listed with the price of the dlc upgrade

PS: thanks for your work

[Issue created by [deleted]: 2021-03-02]

**Comment by MarkitkaM** [comment]
I think it is already fixed via screenshots:
![chrome_KMuQA7Dwt8](https://user-images.githubusercontent.com/88401908/131219329-5ca4a1ce-48ce-43ce-9b93-d9c25e4289bb.png)
![firefox_HXzlamSfkU](https://user-images.githubusercontent.com/88401908/131219331-e45d78ce-3a6d-4e54-be26-fefe2cb3bba7.png)

**Comment by MarkitkaM** [comment]
Duplication #2008 with a better description.

The issue was already fixed.
