### ISSUE TITLE
Steam price for "Serious Sam 4" is wrong

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2014]
IsThereAnyDeal shows 10,00€ as the current price for Serious Sam 4  
https://new.isthereanydeal.com/game/serioussamiv/info/  
In reality the price should be 39,99€  
https://store.steampowered.com/app/257420/Serious_Sam_4/  
It seems that IsThereAnyDeal  is looking at the "Buy Serious Sam 4 Deluxe Edition Upgrade" offer which is indeed 10€

[Issue created by [deleted]: 2021-03-04]

**Comment by MarkitkaM** [comment]
Already fixed.
![chrome_P4ryG54ayx](https://user-images.githubusercontent.com/88401908/131217249-83a7f2b7-a27b-4181-b5d3-ceea8906b29f.png)
![chrome_hlXckOOvyg](https://user-images.githubusercontent.com/88401908/131217252-f798307e-8506-4961-8d9a-191923320b75.png)
