### ISSUE TITLE
Need to merge game pages (Ageless)

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2016]
Not the most popular game out there, but it's in the current month Humble Choice so I'm assuming there will be a large # of people adding this to their collection.

Correct (does not include Steam store):
https://isthereanydeal.com/game/ageless/info/

Incorrect (only has Steam store, and title is puzzling):
https://isthereanydeal.com/game/projectbirthday/info/

I added Ageless to collection via bundle, but after redeeming the Steam key and refreshing data sync, "Project Birthday" was added to my collection.

[Issue created by [deleted]: 2021-03-08]

**Comment by MarkitkaM** [comment]
According to me the main issue is fixed.

But:
**1. Newegg - leads to the dead link** -> http://www.qksrv.net/media/offers/?AID=10446076&PID=6305441&URL=https%3A%2F%2Fwww.newegg.com%2Fteam-17-digital-ageless-pc%2Fp%2FN82E16832751088&utm_medium=affiliates&utm_source=afc-Tomas+Fedor&cjevent=7ffc76f4069911ec8326d20a0a18050c

**2. Add the thumbnail of the game** ->
![chrome_yceP5bf31K](https://user-images.githubusercontent.com/88401908/131015510-d170a1b3-b700-4df4-a71d-3d27a254aacb.png)

**Comment by MarkitkaM** [comment]
ad1) moved to #2690
