### ISSUE TITLE
Islanders page links to a wrong Islanders game

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2017]
The city builder & puzzle game Islanders (regular price 4,99€ on Steam) has a link to the wrong game on itch.io with the same name on it's page.

**1. The first Steam link leads to the wrong game** -> https://store.steampowered.com/app/843780/City_Builder/

**2. The last itch.io link leads to the dead link** -> https://apple-made.itch.io/city-builder

![chrome_7wYc4NigQk](https://user-images.githubusercontent.com/88401908/131012994-152e771d-b0c1-4ddd-9014-ef001e86d73f.png)

[Issue created by [deleted]: 2021-03-09]

**Comment by MarkitkaM** [comment]
Related #1950

**Comment by MarkitkaM** [comment]
Entries to split #2323
