### ISSUE TITLE
Incorrect link in the card "Half-Life: Alyx"

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2019]
[https://isthereanydeal.com/game/halflifealyx/info/](https://isthereanydeal.com/game/halflifealyx/info/) - “[Half-Life: Alyx - Final Hours](https://store.steampowered.com/sub/477386/)“ is not “[Half-Life: Alyx](https://store.steampowered.com/sub/134870/)“.

![](https://bitbucket.org/repo/b6qGGA/images/3829058456-Half-Life%20Alyx%20at%20IsThereAnyDeal.png)
‌

[Issue created by Bujno: 2021-03-11]

**Comment by MarkitkaM** [comment]
Seems like it is fixed already https://isthereanydeal.com/game/halflifealyx/info/
![chrome_Z7URATzo6c](https://user-images.githubusercontent.com/88401908/131009301-837a2166-3be4-48eb-bd01-1d7250871934.png)
