### ISSUE TITLE
[Old steam names need a cleanup maintenance] If the steam beta had different name, ITAD still uses it for the appid and entries are split in 2

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2021]
Towaga: Among Shadows was named Inlight during beta (see steamdb history)
This is the entry linked to steam:
https://isthereanydeal.com/game/inlight/info/
This is the steam page:
https://store.steampowered.com/app/907600/Towaga_Among_Shadows/
This is the splitted entry with other stores with the correct name:
https://isthereanydeal.com/game/towagaamongshadows/info/

This needs to be merged, but looks like it's a common issue:
https://bitbucket.org/tfedor/isthereanydeal.com/issues/2019/need-to-merge-game-pages-ageless
Ageless was named Project Birthday during beta.
https://isthereanydeal.com/game/projectbirthday/info/
https://store.steampowered.com/app/1210150/Ageless/
https://isthereanydeal.com/game/ageless/info/

[Issue created by [deleted]: 2021-03-13]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
