### ISSUE TITLE
On the page for the game "Clutch", the itch.io link leads to a different game than the other links

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2023]
**WRONG ENTRY**

https://isthereanydeal.com/game/clutch/info/ leadst to wrong game -> https://magresta.itch.io/clutch

![chrome_YQor0wsvNH](https://user-images.githubusercontent.com/88401908/131005923-51aef837-bc9e-4c5c-8b97-f20871f5143d.png)

Can't see the same game on itch.io -> https://itch.io/search?q=clutch

[Issue created by [deleted]: 2021-03-16]

**Comment by MarkitkaM** [comment]
Entries to split #2323
