### ISSUE TITLE
Fix "Ignore" option

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2024]
There's a couple of garbage games that keep appearing in my tagged deals pictured at top and I can't ignore because on the game window the ignore/collection/waitlist portion of the window is missing. Item is Hentai Jigsaw Alison and Hentai Wallpapers. Both are complete garbage so please fix them when you get a chance.

[Issue created by [deleted]: 2021-03-17]

**Comment by MarkitkaM** [comment]
The user did not add any screenshots. Maybe there was a visual bug that time but not anymore as I tried on desktop resolution even shrank it into the mobile resolution.

All are properly visible.
![7ClPUYAYKq](https://user-images.githubusercontent.com/88401908/130917606-dd16ec28-2821-4179-848e-a0927e936fc5.png)
![chrome_71A39sAwKV](https://user-images.githubusercontent.com/88401908/130917615-0b290f98-9ad4-4126-bbb3-be1cb39d8812.png)
![chrome_RzsO3GglXN](https://user-images.githubusercontent.com/88401908/130917619-4b89bc84-98e3-4ead-97ae-8cb317122e63.png)
