### ISSUE TITLE
Waitlist is broken for DLC's and some games

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2043]
Steps:

Go to: [https://isthereanydeal.com/game/marstotalwarfareannualplayerupgradeii0ii0/info/](https://isthereanydeal.com/game/marstotalwarfareannualplayerupgradeii0ii0/info/#/page:game/wait?plain=marstotalwarfareannualplayerupgradeii0ii0)

Click “Wait for better price”

Nothing happens.

‌

9 more examples: 

[https://isthereanydeal.com/game/holodriveearlyaccesssupporterpack/info/](https://isthereanydeal.com/game/holodriveearlyaccesssupporterpack/info/)

[https://isthereanydeal.com/game/deepgamedarkestcave/info/](https://isthereanydeal.com/game/deepgamedarkestcave/info/)

[https://isthereanydeal.com/game/deepgamecosmeticsexpansionpack/info/](https://isthereanydeal.com/game/deepgamecosmeticsexpansionpack/info/)

[https://isthereanydeal.com/game/beyondenemylinesiionlinebattlepass/info/#/page:game/wait?plain=beyondenemylinesiionlinebattlepass](https://isthereanydeal.com/game/beyondenemylinesiionlinebattlepass/info/#/page:game/wait?plain=beyondenemylinesiionlinebattlepass)

[https://isthereanydeal.com/game/beyondenemylinesiionlinexpboost/info/#/page:game/wait?plain=beyondenemylinesiionlinexpboost](https://isthereanydeal.com/game/beyondenemylinesiionlinexpboost/info/#/page:game/wait?plain=beyondenemylinesiionlinexpboost)

[https://isthereanydeal.com/game/beyondenemylinesiionlineweaponpass/info/#/page:game/wait?plain=beyondenemylinesiionlineweaponpass](https://isthereanydeal.com/game/beyondenemylinesiionlineweaponpass/info/#/page:game/wait?plain=beyondenemylinesiionlineweaponpass)

[https://isthereanydeal.com/game/monstersandmortalssilenthill/info/#/page:game/wait?plain=monstersandmortalssilenthill](https://isthereanydeal.com/game/monstersandmortalssilenthill/info/#/page:game/wait?plain=monstersandmortalssilenthill)

 [https://isthereanydeal.com/game/marstotalwarfareannualplayerupgradeii0ii0/info/#/page:game/wait?plain=marstotalwarfareannualplayerupgradeii0ii0](https://isthereanydeal.com/game/marstotalwarfareannualplayerupgradeii0ii0/info/#/page:game/wait?plain=marstotalwarfareannualplayerupgradeii0ii0) 

[https://isthereanydeal.com/game/marstotalwarfareannualsupervisorupgradeii0ii0/info/#/page:game/wait?plain=marstotalwarfareannualsupervisorupgradeii0ii0](https://isthereanydeal.com/game/marstotalwarfareannualsupervisorupgradeii0ii0/info/#/page:game/wait?plain=marstotalwarfareannualsupervisorupgradeii0ii0)

[Issue created by froggy__1234: 2021-03-24]

[Comment created by froggy__1234: 2021-03-24]
Out of 40 DLC’s for this game, 35\+ does not work, but oddly enough, 2 does work.

‌

Does not work:

[https://isthereanydeal.com/game/crazypuzzleroadlandscapes/info/#/page:game/wait?plain=crazypuzzleroadlandscapes](https://isthereanydeal.com/game/crazypuzzleroadlandscapes/info/#/page:game/wait?plain=crazypuzzleroadlandscapes)

[https://isthereanydeal.com/game/crazypuzzleparis/info/#/page:game/wait?plain=crazypuzzleparis](https://isthereanydeal.com/game/crazypuzzleparis/info/#/page:game/wait?plain=crazypuzzleparis)

[https://isthereanydeal.com/game/crazypuzzlemusicalinstruments/info/#/page:game/wait?plain=crazypuzzlemusicalinstruments](https://isthereanydeal.com/game/crazypuzzlemusicalinstruments/info/#/page:game/wait?plain=crazypuzzlemusicalinstruments)

[https://isthereanydeal.com/game/crazypuzzlemilan/info/#/page:game/wait?plain=crazypuzzlemilan](https://isthereanydeal.com/game/crazypuzzlemilan/info/#/page:game/wait?plain=crazypuzzlemilan)

[https://isthereanydeal.com/game/crazypuzzlelondon/info/#/page:game/wait?plain=crazypuzzlelondon](https://isthereanydeal.com/game/crazypuzzlelondon/info/#/page:game/wait?plain=crazypuzzlelondon)

[https://isthereanydeal.com/game/crazypuzzlefood/info/#/page:game/wait?plain=crazypuzzlefood](https://isthereanydeal.com/game/crazypuzzlefood/info/#/page:game/wait?plain=crazypuzzlefood)

[https://isthereanydeal.com/game/crazypuzzlewindmills/info/#/page:game/wait?plain=crazypuzzlewindmills](https://isthereanydeal.com/game/crazypuzzlewindmills/info/#/page:game/wait?plain=crazypuzzlewindmills)

[https://isthereanydeal.com/game/crazypuzzlebridges/info/#/page:game/wait?plain=crazypuzzlebridges](https://isthereanydeal.com/game/crazypuzzlebridges/info/#/page:game/wait?plain=crazypuzzlebridges)

[https://isthereanydeal.com/game/crazypuzzleturtles/info/#/page:game/wait?plain=crazypuzzleturtles](https://isthereanydeal.com/game/crazypuzzleturtles/info/#/page:game/wait?plain=crazypuzzleturtles)

[https://isthereanydeal.com/game/crazypuzzletokyo/info/#/page:game/wait?plain=crazypuzzletokyo](https://isthereanydeal.com/game/crazypuzzletokyo/info/#/page:game/wait?plain=crazypuzzletokyo)

[https://isthereanydeal.com/game/crazypuzzlepalms/info/#/page:game/wait?plain=crazypuzzlepalms](https://isthereanydeal.com/game/crazypuzzlepalms/info/#/page:game/wait?plain=crazypuzzlepalms)

[https://isthereanydeal.com/game/crazypuzzlecanadalandscapes/info/#/page:game/wait?plain=crazypuzzlecanadalandscapes](https://isthereanydeal.com/game/crazypuzzlecanadalandscapes/info/#/page:game/wait?plain=crazypuzzlecanadalandscapes)

[https://isthereanydeal.com/game/crazypuzzlebrazillandscapes/info/#/page:game/wait?plain=crazypuzzlebrazillandscapes](https://isthereanydeal.com/game/crazypuzzlebrazillandscapes/info/#/page:game/wait?plain=crazypuzzlebrazillandscapes)

[https://isthereanydeal.com/game/bicycles/info/#/page:game/wait?plain=bicycles](https://isthereanydeal.com/game/bicycles/info/#/page:game/wait?plain=bicycles)

[https://isthereanydeal.com/game/crazypuzzlebeaches/info/#/page:game/wait?plain=crazypuzzlebeaches](https://isthereanydeal.com/game/crazypuzzlebeaches/info/#/page:game/wait?plain=crazypuzzlebeaches)

[https://isthereanydeal.com/game/crazypuzzlerurallandscapes/info/#/page:game/wait?plain=crazypuzzlerurallandscapes](https://isthereanydeal.com/game/crazypuzzlerurallandscapes/info/#/page:game/wait?plain=crazypuzzlerurallandscapes)

[https://isthereanydeal.com/game/crazypuzzleaeriallandscapes/info/#/page:game/wait?plain=crazypuzzleaeriallandscapes](https://isthereanydeal.com/game/crazypuzzleaeriallandscapes/info/#/page:game/wait?plain=crazypuzzleaeriallandscapes)

[https://isthereanydeal.com/game/crazypuzzlemountainlandscapes/info/#/page:game/wait?plain=crazypuzzlemountainlandscapes](https://isthereanydeal.com/game/crazypuzzlemountainlandscapes/info/#/page:game/wait?plain=crazypuzzlemountainlandscapes)

[https://isthereanydeal.com/game/crazypuzzlemacronature/info/#/page:game/wait?plain=crazypuzzlemacronature](https://isthereanydeal.com/game/crazypuzzlemacronature/info/#/page:game/wait?plain=crazypuzzlemacronature)

[https://isthereanydeal.com/game/crazypuzzlelakeslandscapes/info/#/page:game/wait?plain=crazypuzzlelakeslandscapes](https://isthereanydeal.com/game/crazypuzzlelakeslandscapes/info/#/page:game/wait?plain=crazypuzzlelakeslandscapes)

[https://isthereanydeal.com/game/crazypuzzleunderwaterlife/info/#/page:game/wait?plain=crazypuzzleunderwaterlife](https://isthereanydeal.com/game/crazypuzzleunderwaterlife/info/#/page:game/wait?plain=crazypuzzleunderwaterlife)

[https://isthereanydeal.com/game/crazypuzzletoys/info/#/page:game/wait?plain=crazypuzzletoys](https://isthereanydeal.com/game/crazypuzzletoys/info/#/page:game/wait?plain=crazypuzzletoys)

[https://isthereanydeal.com/game/crazypuzzlesummer/info/#/page:game/wait?plain=crazypuzzlesummer](https://isthereanydeal.com/game/crazypuzzlesummer/info/#/page:game/wait?plain=crazypuzzlesummer)

[https://isthereanydeal.com/game/crazypuzzlespring/info/#/page:game/wait?plain=crazypuzzlespring](https://isthereanydeal.com/game/crazypuzzlespring/info/#/page:game/wait?plain=crazypuzzlespring)

[https://isthereanydeal.com/game/crazypuzzlesealandscapes/info/#/page:game/wait?plain=crazypuzzlesealandscapes](https://isthereanydeal.com/game/crazypuzzlesealandscapes/info/#/page:game/wait?plain=crazypuzzlesealandscapes)

[https://isthereanydeal.com/game/crazypuzzleriverlandscapes/info/#/page:game/wait?plain=crazypuzzleriverlandscapes](https://isthereanydeal.com/game/crazypuzzleriverlandscapes/info/#/page:game/wait?plain=crazypuzzleriverlandscapes)

[https://isthereanydeal.com/game/crazypuzzlepandas/info/#/page:game/wait?plain=crazypuzzlepandas](https://isthereanydeal.com/game/crazypuzzlepandas/info/#/page:game/wait?plain=crazypuzzlepandas)

[https://isthereanydeal.com/game/crazypuzzlewaterfalls/info/#/page:game/wait?plain=crazypuzzlewaterfalls](https://isthereanydeal.com/game/crazypuzzlewaterfalls/info/#/page:game/wait?plain=crazypuzzlewaterfalls)

[https://isthereanydeal.com/game/crazypuzzleelephants/info/#/page:game/wait?plain=crazypuzzleelephants](https://isthereanydeal.com/game/crazypuzzleelephants/info/#/page:game/wait?plain=crazypuzzleelephants)

[https://isthereanydeal.com/game/crazypuzzlewinter/info/#/page:game/wait?plain=crazypuzzlewinter](https://isthereanydeal.com/game/crazypuzzlewinter/info/#/page:game/wait?plain=crazypuzzlewinter)

[https://isthereanydeal.com/game/crazypuzzleguns/info/#/page:game/wait?plain=crazypuzzleguns](https://isthereanydeal.com/game/crazypuzzleguns/info/#/page:game/wait?plain=crazypuzzleguns)

[https://isthereanydeal.com/game/crazypuzzlemoscow/info/#/page:game/wait?plain=crazypuzzlemoscow](https://isthereanydeal.com/game/crazypuzzlemoscow/info/#/page:game/wait?plain=crazypuzzlemoscow)

[https://isthereanydeal.com/game/crazypuzzleicedlandscapes/info/#/page:game/wait?plain=crazypuzzleicedlandscapes](https://isthereanydeal.com/game/crazypuzzleicedlandscapes/info/#/page:game/wait?plain=crazypuzzleicedlandscapes)

[https://isthereanydeal.com/game/crazypuzzlefastcars/info/#/page:game/wait?plain=crazypuzzlefastcars](https://isthereanydeal.com/game/crazypuzzlefastcars/info/#/page:game/wait?plain=crazypuzzlefastcars)

[https://isthereanydeal.com/game/crazypuzzlecats/info/#/page:game/wait?plain=crazypuzzlecats](https://isthereanydeal.com/game/crazypuzzlecats/info/#/page:game/wait?plain=crazypuzzlecats)

[https://isthereanydeal.com/game/crazypuzzlenorthemlights/info/#/page:game/wait?plain=crazypuzzlenorthemlights](https://isthereanydeal.com/game/crazypuzzlenorthemlights/info/#/page:game/wait?plain=crazypuzzlenorthemlights)

[https://isthereanydeal.com/game/crazypuzzlehorses/info/#/page:game/wait?plain=crazypuzzlehorses](https://isthereanydeal.com/game/crazypuzzlehorses/info/#/page:game/wait?plain=crazypuzzlehorses)

[https://isthereanydeal.com/game/crazypuzzlebigcities/info/#/page:game/wait?plain=crazypuzzlebigcities](https://isthereanydeal.com/game/crazypuzzlebigcities/info/#/page:game/wait?plain=crazypuzzlebigcities)

‌

Works:

[https://isthereanydeal.com/game/crazypuzzlemotorcycles/info/#/page:game/wait?plain=crazypuzzlemotorcycles](https://isthereanydeal.com/game/crazypuzzlemotorcycles/info/#/page:game/wait?plain=crazypuzzlemotorcycles)

[https://isthereanydeal.com/game/crazypuzzleautumn/info/#/page:game/wait?plain=crazypuzzleautumn](https://isthereanydeal.com/game/crazypuzzleautumn/info/#/page:game/wait?plain=crazypuzzleautumn)

**Comment by MarkitkaM** [comment]
It is ok already. I tried to add the most of examples above to my waitlist and it works well.

![chrome_Svx0iqcM6Y](https://user-images.githubusercontent.com/88401908/130364387-becd9183-eaca-4929-8604-a1cfc20fa08e.png)
