### ISSUE TITLE
Wingpan (Steam) mixed up with Wingspan for TTS (Steam)

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2047]
Hi,
You correctly have two different items in your DB, one is Wingspan, and the other is Tabletop Simulator (TTS) Wingspan.
* https://isthereanydeal.com/game/wingspan/info/
* https://isthereanydeal.com/game/tabletopsimulatorwingspan/info/

The current issue is that the Steam offer price currently associated with Wingspan in your DB, is instead the price of the TTS Wingspan.

Thanks for your website.
Kind Regards
Ze

[Issue created by [deleted]: 2021-03-26]
[Last updated on bitbucket: 2021-06-30]

[Comment created by adamnoffie: 2021-06-30]
Duplicate of 2170  
Duplicate of 2053

**Comment by MarkitkaM** [comment]
Duplication of #2050
