### ISSUE TITLE
Epic Games sometimes have separate entry

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2048]
**MERGE ENTRIES:**

When I'm entering my Epic Games to the collection, I find quite a lot of titles are created with Epic Games as the sole vendor while there are already an existing item for the title.

E.g:
https://isthereanydeal.com/game/strangerthingsiiigame/info/
https://isthereanydeal.com/game/strangerthingsiii/info/

I recommend filtering these titles (with Epic Games as the sole vendor) out have have a review

[Issue created by [deleted]: 2021-03-26]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
