### ISSUE TITLE
[Duplicate Entries] Paradise Lost: 3 Different Steam Links

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2054]
**SPLIT ENTRIES:**
https://isthereanydeal.com/game/paradiselost/info/

Tracks:

https://store.steampowered.com/app/752030/Paradise_Lost_FPS_Cosmic_Horror_Game/
An Spec Ops team was sent to a planet to investigate a disappearance of a research team. What lies beneath this god-forsaken planet?
ALL REVIEWS: 8 user reviews
RELEASE DATE: Jan 15, 2016

https://store.steampowered.com/app/982720/Paradise_Lost/
It's winter, 1980. Szymon, a boy raised in a post-apocalyptic wasteland, finds an abandoned Nazi bunker. Will he find what he’s looking for? Play Paradise Lost and explore an underground world, where Slavic mythology mixes with retrofuturistic technology. Discover the last story on Earth.
ALL REVIEWS: Mostly Positive (299)
RELEASE DATE: Mar 24, 2021

https://store.steampowered.com/app/1555890/Paradise_Lost/
Shooting games. Shoot monsters and have fun.
ALL REVIEWS: No user reviews
RELEASE DATE: Feb 16, 2021

[Issue created by [deleted]: 2021-03-29]
[Last updated on bitbucket: 2021-06-25]

[Comment created by Mugros: 2021-06-25]
This is highly annoying because it messes up the wait list.  

And it has been reported 3 months ago. There should be a better way to report wrong data.

![chrome_WCguOFM1EW](https://user-images.githubusercontent.com/88401908/130362400-d6b4d30f-1ff9-4d67-b249-39f6c6da3e1a.png)

**Comment by MarkitkaM** [comment]
Entries to split #2323
