### ISSUE TITLE
BOXVR uses wrong price

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2055]
https://isthereanydeal.com/game/boxvr/info/#/

BOXVR is 27.99e https://store.steampowered.com/app/641960/BOXVR/

But the price is taken from "THE BOX VR" at 1.95 https://store.steampowered.com/app/756650/THE_BOX_VR/

[Issue created by [deleted]: 2021-03-29]

**Comment by MarkitkaM** [comment]
**Duplication of the #2060.**

![chrome_tJHIDEp5fr](https://user-images.githubusercontent.com/88401908/130362123-60c35a9b-7e52-4c61-b0e6-e031a59a7507.png)
![chrome_iDOVf2Czdv](https://user-images.githubusercontent.com/88401908/130362125-4b926053-f853-4265-bc78-b26e9bdcb3c4.png)
