### ISSUE TITLE
Steam link for Metamorphosis refers to another game

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2056]
[https://isthereanydeal.com/game/metamorphosis/info/](https://isthereanydeal.com/game/metamorphosis/info/)

[https://store.steampowered.com/app/1259960/](https://store.steampowered.com/app/1259960/)

[Issue created by witchcatcher: 2021-03-30]
[Last updated on bitbucket: 2021-04-27]

[Comment created by Seyker: 2021-04-27]
It seems it gets both info from “Metamorphosis” and “THE Metamorphosis” games at the same time.

[Comment created by witchcatcher: 2021-03-30]
correct link:

[https://store.steampowered.com/app/1025410/Metamorphosis/](https://store.steampowered.com/app/1025410/Metamorphosis/)

**Comment by MarkitkaM** [comment]
Duplication of the issue #2152.
