### ISSUE TITLE
Ghostrunner DLC incorrectly listed as the full game

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2057]
https://isthereanydeal.com/#/page:game/info/?plain=ghostrunner

The page is showing (and comparing) two different Steam prices: one for the full game and one for its DLC.

[Issue created by [deleted]: 2021-03-30]
[Last updated on bitbucket: 2021-04-05]

[Comment created by marky1125: 2021-04-05]
The Steam link points to the Ghostrunner - Winter Pack DLC.

**Comment by MarkitkaM** [comment]
I can't see the second steam link in any region anymore.

**Comment by MarkitkaM** [comment]
Entries to split #2323
