### ISSUE TITLE
"Colonists" and "The Colonists" mix up

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2059]
**MOVE ENTRIES:**

The "The Colonists" entry does not list any current prices, although it is available on most big stores.
[https://isthereanydeal.com/game/thecolonists/info/](https://isthereanydeal.com/game/thecolonists/info/)

The "Colonists" entry, on the other hand, has 5 wrong entries, linking to "The Colonists" instead. While this game is probably only available on [Itch.io](http://Itch.io)
[https://isthereanydeal.com/game/colonists/info/](https://isthereanydeal.com/game/colonists/info/)

![chrome_JrkFq00Zt8](https://user-images.githubusercontent.com/88401908/130361042-8955b988-7e17-40e7-8f44-ec1e0f02af17.png)

[Issue created by Notiz_Me: 2021-04-01]

**Comment by MarkitkaM** [comment]
Entries to split #2323

**Comment by forenta** [comment]
Still not fixed.
