### ISSUE TITLE
BOXVR Game definition contains "THE BOX VR" and "BOXVR" in the same comparison entry

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2060]
**SPLIT ENTRIES:**
Needs regex adjustment: https://isthereanydeal.com/game/boxvr/info/#/

https://store.steampowered.com/app/756650/THE_BOX_VR/
https://store.steampowered.com/app/641960/BOXVR/
![chrome_3M9RrLP4WV](https://user-images.githubusercontent.com/88401908/130360867-27e74822-d958-41b0-96e5-af6446607d4e.png)

Thanks for the great job isthereanydeal does! It's a wonderful site, love it! Brings me so much joy with some alerts

[Issue created by [deleted]: 2021-04-01]

**Comment by MarkitkaM** [comment]
**Related to #2055**

**Comment by MarkitkaM** [comment]
Entries to split #2323
