### ISSUE TITLE
Mixed games - "(The) Island"

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2066]
**SPLIT ENTRIES:**
[https://isthereanydeal.com/game/island/info/](https://isthereanydeal.com/game/island/info/)

https://store.steampowered.com/app/1625450/Muck/
[https://store.steampowered.com/app/857450/ISLAND/](https://store.steampowered.com/app/857450/ISLAND/)
[https://store.steampowered.com/app/1377590/The\_Island/](https://store.steampowered.com/app/1377590/The_Island/)

![ShareX_U5UKze7XBS](https://user-images.githubusercontent.com/88401908/130357813-ac5235b6-e3ae-402c-85b4-5e0f82f8688f.png)

[Issue created by HYBRID_BEING: 2021-04-04]
[Last updated on bitbucket: 2021-04-10]

**Comment by MarkitkaM** [comment]
duplications #1908 and #1960

**Comment by MarkitkaM** [comment]
Entries to split #2323
