### ISSUE TITLE
OneShot: Duplicate Steam store links of same-named game

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2067]
https://isthereanydeal.com/game/oneshot/info/

Should have two pages, but both are listed on one due to having the same names.

https://store.steampowered.com/app/420530/OneShot/
https://store.steampowered.com/app/1221330/One_Shot/

[Issue created by [deleted]: 2021-04-06]

**Comment by MarkitkaM** [comment]
Duplication of the #2171

**Comment by MarkitkaM** [comment]
Duplication of the #2171
