### ISSUE TITLE
"Lost Words: Beyond the Page" is split across multiple listings

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2073]
[This](https://isthereanydeal.com/game/lostwords/info/) and [this](https://isthereanydeal.com/game/lostwordsbeyondpage/info/) are the same game. One of them shows the Steam listing and the other shows everywhere else.

**MERGE THEM TOGETHER.**

[Issue created by [deleted]: 2021-04-07]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
