### ISSUE TITLE
Split entries - "Postal 4: No Regerts"

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2076]
**MERGE ENTRIES TOGETHER:**
[https://isthereanydeal.com/game/postalivnoregerts/info/](https://isthereanydeal.com/game/postalivnoregerts/info/)

[https://isthereanydeal.com/game/postaliv/info/](https://isthereanydeal.com/game/postaliv/info/)

Also, note that game should have **EA tag**, atm.

[Issue created by HYBRID_BEING: 2021-04-09]
[Last updated on bitbucket: 2021-04-10]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
