### ISSUE TITLE
wrong price for syberia on Voidu (EU)

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2078]
The EU price for Syberia from Voidu shows as 0,64€ (historical low). When following the link, the price is actually 4,99€.

[Issue created by [deleted]: 2021-04-10]

[Comment created by tfedor: 2021-04-10]
This is misreported in the product feed, I’m contacting Voidu.

**Comment by MarkitkaM** [comment]
As the user said there was a bug on Voidu.
