### ISSUE TITLE
Split entries - "Space Colony"

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2080]
**MERGE ENTRIES TTOGETHER:**
[https://isthereanydeal.com/game/spacecolony/info/](https://isthereanydeal.com/game/spacecolony/info/)

[https://isthereanydeal.com/game/spacecolonysteamedition/info/](https://isthereanydeal.com/game/spacecolonysteamedition/info/)

[Issue created by HYBRID_BEING: 2021-04-11]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
