### ISSUE TITLE
Split entries - "Terraforming Earth"

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2081]
**MERGE ENTRIES TOGETHER:**
[https://isthereanydeal.com/game/terraformingearthxmasaccess/info/](https://isthereanydeal.com/game/terraformingearthxmasaccess/info/)

[https://isthereanydeal.com/game/terraformingearth/info/](https://isthereanydeal.com/game/terraformingearth/info/)

[Issue created by HYBRID_BEING: 2021-04-11]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
