### ISSUE TITLE
Mixed games - MEAT

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2083]
https://isthereanydeal.com/game/meat/info/#/

The actual page is for the Steam game, which is correct, but other other two store links go to totally different games.

--
SPLIT ENTRIES:
![chrome_nC2svxiruL](https://user-images.githubusercontent.com/88401908/130346773-c4dbf970-36ac-4060-9a06-e6be0cf70976.png)

[Issue created by [deleted]: 2021-04-13]

**Comment by MarkitkaM** [comment]
Entries to split #2323
