### ISSUE TITLE
Ghostrunner Steam Price incorrect

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2084]
https://isthereanydeal.com/game/ghostrunner/info/ It has it listed as $1.99 but that is for a DLC. The full game is like $15.99 or something.

[Issue created by [deleted]: 2021-04-14]
[Last updated on bitbucket: 2021-04-15]

[Comment created by heyscotty: 2021-04-15]
Cheers lad

[Comment created by tfedor: 2021-04-14]
Fixed

[Comment created by heyscotty: 2021-04-14]
Noticed this too

**Comment by Omnisilver** [comment]
Hi, this bug seems to be alive again
