### ISSUE TITLE
Resident Evil 7 missing Steam price info

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2085]
Last known Steam price for Resident Evil 7 is from 3/30/2021, then it was dropped. Game’s still on the store.

RE7: [https://isthereanydeal.com/game/residentevilviibiohazard/history/](https://isthereanydeal.com/game/residentevilviibiohazard/history/)  
Possible dupe: [https://bitbucket.org/tfedor/isthereanydeal.com/issues/398/a-lot-of-games-are-now-missing-steam-price](https://bitbucket.org/tfedor/isthereanydeal.com/issues/398/a-lot-of-games-are-now-missing-steam-price)

[Issue created by pearah: 2021-04-14]

[Comment created by pearah: 2021-04-14]
I think it’s a “split entry”. When I started tracking it in Steam, ITAD created an association with the “Biohazard” listing. However, this entry still has Steam info: [https://isthereanydeal.com/game/residentevilvii/info/](https://isthereanydeal.com/game/residentevilvii/info/)

---
**MERGE ENTRIES:**
https://isthereanydeal.com/game/residentevilvii/info/
https://isthereanydeal.com/game/residentevilviibiohazard/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
