### ISSUE TITLE
Prices on homepage displayed in wrong currency

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2086]
On the new website, on the homepage, the prices are displayed without conversion to the currency I've set my account to (Au$). I swear it used to display in AUD. When I go to a specific game page there is no issue

I don't know what severity this should be so I'm going to leave it at default. It's very irritating. I've reset cookies and tried in chrome and firefox to the same result.

[Issue created by [deleted]: 2021-04-18]

**Comment by MarkitkaM** [comment]
Already fixed
