### ISSUE TITLE
Tales of Vesperia

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2088]
**1.** https://isthereanydeal.com/game/talesofvesperiadefinitiveedition/info/#/
you didn't add fanatical store for this game
https://www.fanatical.com/en/game/tales-of-vesperia-definitive-edition

**2. SPLIT ENTRIES:** 
For kindergarten, the second store "MacGameStore: is another game with the same name.
https://isthereanydeal.com/game/kindergarten/info/

[Issue created by [deleted]: 2021-04-19]

**Comment by MarkitkaM** [comment]
**ad1) ALREADY FIXED**
![chrome_DJJxY7N5sz](https://user-images.githubusercontent.com/88401908/130332870-d8337792-0854-470e-ba3e-08162553eb03.png)

**Comment by MarkitkaM** [comment]
Entries to split #2323
