### ISSUE TITLE
Mergable Duplicates

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2090]
**MERGE ENTRIES:**
Multiple entries for same game/release:

https://isthereanydeal.com/game/swordsandsoulsneverseen/info/
https://isthereanydeal.com/game/swordssoulsneverseen/info/

https://isthereanydeal.com/game/blacksad/info/
https://isthereanydeal.com/game/blacksadunderskin/info/

https://isthereanydeal.com/game/horizonzerodawn/info/
https://isthereanydeal.com/game/horizonzerodawncompleteedition/info/

https://isthereanydeal.com/game/pillarsofeternityiideadfire/info/
https://isthereanydeal.com/game/pillarsofeternityiideadfirestandardedition/info/

https://isthereanydeal.com/game/atomrpg/info/
https://isthereanydeal.com/game/atomrpgpostapocalypticindiegame/info/

https://isthereanydeal.com/game/legendsofamberland/info/
https://isthereanydeal.com/game/legendsofamberlandforgottencrown/info/

https://isthereanydeal.com/game/akibastripundeadundressed/info/
https://isthereanydeal.com/game/akibastripundeadandundressed/info/

https://isthereanydeal.com/game/atelierarlandseriesdeluxepackatoriearandonolianjinshushidx/info/
https://isthereanydeal.com/game/atelierarlandseriesdeluxepack/info/
https://isthereanydeal.com/game/atelierarlanddeluxepack/info/

https://isthereanydeal.com/game/atelierdusktrilogydeluxepackatoriehuanghunnolianjinshushitorirojidx/info/
https://isthereanydeal.com/game/atelierdusktrilogydeluxepack/info/

https://isthereanydeal.com/game/atelierfirisalchemistandmysteriousjourneyfirisunoatoriebusiyinalunolianjinshushi/info/
https://isthereanydeal.com/game/atelierfirisalchemistandmysteriousjourney/info/

https://isthereanydeal.com/game/atelierluluathescionofarlandruruanoatoriearandonolianjinshushi/info/
https://isthereanydeal.com/game/atelierluluascionofarland/info/
https://isthereanydeal.com/game/atelierluluathescionofarland/info/

https://isthereanydeal.com/game/atelierlydieandsuellethealchemistsandmysteriouspaintings/info/
https://isthereanydeal.com/game/atelierlydiesuellethealchemistsandmysteriouspaintings/info/
https://isthereanydeal.com/game/atelierlydieandsuellealchemistsandmysteriouspaintings/info/

https://isthereanydeal.com/game/atelierryzaiilostlegendsandsecretfairy/info/
https://isthereanydeal.com/game/atelierryzaiilostlegendssecretfairy/info/

https://isthereanydeal.com/game/atelierryzaeverdarknessandsecrethideout/info/
https://isthereanydeal.com/game/atelierryzaeverdarknesssecrethideout/info/

https://isthereanydeal.com/game/dragonfangzroseanddungeonoftime/info/
https://isthereanydeal.com/game/dragonfangz/info/

https://isthereanydeal.com/game/kwaidanazumamanorstory/info/
https://isthereanydeal.com/game/kwaidan/info/

https://isthereanydeal.com/game/nelkeandlegendaryalchemistsateliersofnewworldneruketoyunshuonolianjinshushitachixintanadadenoatorie/info/
https://isthereanydeal.com/game/nelkelegendaryalchemistsateliersofnewworld/info/
https://isthereanydeal.com/game/nelkeandlegendaryalchemistsateliersofnewworld/info/
https://isthereanydeal.com/game/nelkeandlegendaryalchemists/info/

https://isthereanydeal.com/game/nightsofazureiibrideofnewmoonyorunonaikunixinyuenohuajia/info/
https://isthereanydeal.com/game/nightsofazureiibrideofnewmoon/info/
https://isthereanydeal.com/game/nightsofazureii/info/

https://isthereanydeal.com/game/niohcompleteedition/info/
https://isthereanydeal.com/game/niohcompleteeditionrenwangcompleteedition/info/

https://isthereanydeal.com/game/phoenixwrightaceattorneytrilogynizhuancaipaniiiiiichengbutangserekushon/info/
https://isthereanydeal.com/game/phoenixwrightaceattorneytrilogy/info/

https://isthereanydeal.com/game/vestariasagaiwarofscions/info/
https://isthereanydeal.com/game/vestariasaga/info/

https://isthereanydeal.com/game/shidaowaiyunkatanakami/info/
https://isthereanydeal.com/game/katanakamiawayofsamuraistory/info/

Thanks very much!

[Issue created by [deleted]: 2021-04-20]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
