### ISSUE TITLE
Mixed games - "Hard Work"

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2092]
**SPLIT ENTRIES:**
[https://isthereanydeal.com/game/hardwork/info/](https://isthereanydeal.com/game/hardwork/info/)

[https://store.steampowered.com/app/845520/](https://store.steampowered.com/app/845520/)

[https://store.steampowered.com/app/942800/](https://store.steampowered.com/app/942800/)
![chrome_PZIteyuazh](https://user-images.githubusercontent.com/88401908/130331077-b2d1929c-670b-4122-8d42-14859ac3e490.png)

[Issue created by HYBRID_BEING: 2021-04-21]

**Comment by MarkitkaM** [comment]
Entries to split #2323
