### ISSUE TITLE
fake animal crossing new horizons game on microsoft store

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2097]
There's a crappy game on the microsoft store titled Animal Crossing New Horizons that costs about $4. This is not the real Animal Crossing New Horizons game but is shows up when you search for it, making it hard to keep track of if the real game goes on sale.
https://isthereanydeal.com/waitlist/#/page:game/info?plain=animalcrossingnewhorizons

[Issue created by [deleted]: 2021-04-30]
[Last updated on bitbucket: 2021-05-03]

[Comment created by NimbleField: 2021-05-03]
This is true. Needs to be taken down.

**Comment by MarkitkaM** [comment]
Duplication #2101
