### ISSUE TITLE
Split listing - Control

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2100]
**MERGE ENTRIES TOGETHER:**
both appear to be the ultimate edition
https://isthereanydeal.com/game/controlultimateedition/info/
https://isthereanydeal.com/game/control/info/

[Issue created by [deleted]: 2021-04-30]

**Comment by MarkitkaM** [comment]
Related to #2058, #1858 and #1816

**Comment by MarkitkaM** [comment]
Entries to merge #2324
