### ISSUE TITLE
Incorrect listing for Oneshot

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2102]
**SPLIT THESE ENTRIES:**
The ITAD page for the game OneShot ([https://isthereanydeal.com/game/oneshot/info/](https://isthereanydeal.com/game/oneshot/info/)) shows deals for, and links to, an unrelated game called "One Shot," whereas it should link here: [https://store.steampowered.com/app/420530/OneShot/](https://store.steampowered.com/app/420530/OneShot/)

The first Stem in the price list is linked to the different game -> https://store.steampowered.com/app/1221330/One_Shot/
![chrome_jTnZJu9MJB](https://user-images.githubusercontent.com/88401908/130273181-b3e1b06d-2793-4e5b-a55c-d0260b41790d.png)

[Issue created by [deleted]: 2021-05-07]

**Comment by MarkitkaM** [comment]
Duplication of the #2171
