### ISSUE TITLE
Two different unrelated games called Stranded listed on same page

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2103]
**1. SPLIT THESE ENTRIES:**
https://isthereanydeal.com/game/stranded/info/
**Steam** is linked to the different game https://store.steampowered.com/app/1470550/Stranded/

**2. Newegg -  Broken link** -> http://www.qksrv.net/media/offers/?AID=10446076&PID=6305441&URL=https%3A%2F%2Fwww.newegg.com%2Fcurve-digital-stranded%2Fp%2FN82E16832847018&utm_medium=affiliates&utm_source=afc-Tomas+Fedor&cjevent=193d942001dd11ec832f00560a180510

![chrome_4CVxpkS9j5](https://user-images.githubusercontent.com/88401908/130272744-7a582373-6899-4f65-97be-8ac776894567.png)

[Issue created by [deleted]: 2021-05-07]

**Comment by MarkitkaM** [comment]
ad1) Entries to split #2323
ad2) #2677
