### ISSUE TITLE
Split entries - "Stellaris: Starter Pack"

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2108]
**MERGE ENTRIES:**
[https://isthereanydeal.com/game/stellarissummersalestarterpack/info/](https://isthereanydeal.com/game/stellarissummersalestarterpack/info/)

[https://isthereanydeal.com/game/stellarisstarterpack/info/](https://isthereanydeal.com/game/stellarisstarterpack/info/)

[Issue created by HYBRID_BEING: 2021-05-09]

**Comment by MarkitkaM** [comment]
Entries to merge #2324 

#2612
