### ISSUE TITLE
Detention links to a wrong itch.io game

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2114]
Detention is a somewhat notable indie game on various stores. Someone on itch.io has created a dummy game with the same name and is selling it for pennies (possibly as a scam?). ITAD treats it as the same game.

https://store.steampowered.com/app/555220/Detention/
https://biiiy.itch.io/detention

[Issue created by [deleted]: 2021-05-16]

**Comment by MarkitkaM** [comment]
Duplication #2207
