### ISSUE TITLE
Can't import my wishlists after clearing

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2115]
Hi. I can't import any items into my wishlist from steam. The problem happened after I cleared my waitlist. I then go into profiles and data sources and hit "sync" on steam. It'll say something like "28 found 0 added 0 removed", but no games will show up on my waitlist when I view it. My waitlist remains empty.

[Issue created by [deleted]: 2021-05-18]
[Last updated on bitbucket: 2021-07-13]

[Comment created by Raldor: 2021-07-13]
In case anyone else has the same issue and finds this post, here’s how I got around it:

I unlinked my Steam account, and then linked it again.  After that, sync started working again.

[Comment created by Raldor: 2021-07-10]
I have this same issue, also after clearing my waitlist today.  Now I import, it says 588 found, 0 added, 0 removed.

I added another game to my Steam wishlist, and synced again, and get 589 found, 1 added, 0 removed.

So - games I add to the Steam wishlist _after_ clearing ITAD list are found and added to ITAD list when syncing.  Games that were already present on my Steam wishlist _before_ clearing my ITAD list are found when I sync, but are not added to the ITAD list.  So maybe there’s a hidden record of the cleared games that prevents them from being added again?

[Comment created by operand: 2021-05-18]
**Well this seems to have fixed itself! You can delete this. I no longer have this problem!**

[Comment created by operand: 2021-05-18]
I just logged in to say that I created this issue. If you need more info, let me know! Thanks.

**Comment by MarkitkaM** [comment]
I have no Steam accounts of users.. but one of them said that it got fixed by itself.
