### ISSUE TITLE
feature request on Augmented Steam: on store page, under Includes x Steam Achievements:

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2116]
Hello. The Contact page said to use the issue tracker for feature requests. 

On the store page under the 'Includes x Steam Achievements' along the right side column it currently shows a link to Astats. 

1. Would it be possible to add our own options similar to how we can on the profile page? 
2. Or would it be possible to add links to SteamHunters & Completionists.me sometime? 

Astats is currently the only option there, and it has been down a few days due to hardware problems with no ETA. But, even before this, I thought it could be nice to easily click here to get more information available at these other sites versus just the one. Even if it was just SH as they have links at the top of the profile to quickly get to a few of the other tracking sites.

Thanks for your time and all you do!

[Issue created by [deleted]: 2021-05-19]

**Comment by MarkitkaM** [comment]
Copied to AugmentedSteam bug tracker via https://github.com/tfedor/AugmentedSteam/issues/1244
