### ISSUE TITLE
Page has extra steam link to another game

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2118]
https://isthereanydeal.com/game/blightofimmortals/info/

**SPLIT THESE ENTRIES:**
https://store.steampowered.com/app/1408290/Lawless_Lands_Unrest/
https://store.steampowered.com/app/494220/Blight_of_the_Immortals/
![chrome_GxR0a0OvB2](https://user-images.githubusercontent.com/88401908/129481385-6faf23c0-91ec-4cf1-a1c0-c2c42d8fbc6f.png)

[Issue created by [deleted]: 2021-05-20]

**Comment by MarkitkaM** [comment]
Entries to split #2323
