### ISSUE TITLE
Game episodes should be referenced differently than the season it belongs to

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#212]
Go here: http://isthereanydeal.com/waitlist/#/search:life%20is%20strange;/scroll:%23gamelist
Click on "Life is strange"

In the popup, this is what appears:

Current deals:
Store	Price Cut	Current Price	Lowest Recorded	Regular Price
Square Enix	-0%	$4.99	$4.99	$4.99
Steam	-0%	$4.99	$4.99	$4.99
GetGames	-15%	$16.99	$16.99	$19.99

This is confusing. The first two lines point to a single episode of the game (which has 5):
http://store.steampowered.com/app/319630/?snr=1_7_7_230_150_175
http://store.na.square-enix.com/product/282531/life-is-strange-pc-download

...while the last link points to the whole season:
http://www.getgamesgo.com/product/life-is-strange-complete

The game should either be listed on IsThereAnyDeal.com as:
Life is strange - Season
Life is strange - Episode 1
...
Life is strange - Episode 5

Or this information should appear in the popup that appears when you click on the game.

[Issue created by AllInOneMighty: 2015-06-12]

**Comment by MarkitkaM** [comment]
https://isthereanydeal.com/waitlist/?country=FR#/filter:&search/life%20is%20strange
The original issue is probably not valid anymore. Names are different.


Double listing for Steam:
https://isthereanydeal.com/game/lifeisstrangetruecolorsalexoutfitpack/info/

One of the Steam links does not exist
https://isthereanydeal.com/game/lifeisstrangetruecolors/info/
![image](https://user-images.githubusercontent.com/88401908/140637106-4e88611a-4c5f-4905-a42b-e4f49b255ad8.png)

**Comment by MarkitkaM** [comment]
**ad Double listing for Steam:**  #2701
**ad One of the Steam links does not exist:** #2702
