### ISSUE TITLE
Games on sale still show 0% cut on isthereanydeal EU2

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2120]
Hello,

my country'd be in EU2 and that's what's set in my isthereanydeal profile. 

I noticed that a few games currently on sale are still listed at 0%, this seem to be hitting at least several games in the Annapurna Interactive sales that started yesterday. Games I've personally confirmed are Sayonara Wild Hearts, Ashen, Unfinished Swan, Donut County and I Am Dead but there are probably more...other games like Flower or Outer Wilds show the correct sale.

EU1 seems to be showing the correct prices/sales so I've switched to that for now.

**Annapurna interactive classics**
EU2 - https://isthereanydeal.com/game/annapurnainteractiveclassics/info/?country=IT
EU1 - https://isthereanydeal.com/game/annapurnainteractiveclassics/info/?country=FR

**Annapurna interactive collection**
EU2 - https://isthereanydeal.com/game/annapurnainteractivecollection/info/?country=IT
EU1 - https://isthereanydeal.com/game/annapurnainteractivecollection/info/?country=FR

[Issue created by [deleted]: 2021-05-21]

**Comment by MarkitkaM** [comment]
FIXED
