### ISSUE TITLE
Two Steam entries for "Just Cause 4: Expansion Pass" in email

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2123]
**1.** Entries are the same, but for some reason there are two of them.

![](https://bitbucket.org/repo/b6qGGA/images/1517135698-%D0%B8%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5.png)
‌(E-MAIL NOTIFICATION)

+ 

**2. MERGE THESE ENTRIES:**
https://isthereanydeal.com/game/justcauseivreloadedexpansionpass/info/
https://isthereanydeal.com/game/justcauseivexpansionpass/compare/

[Issue created by HYBRID_BEING: 2021-05-21]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
Two steam entries #2683
