### ISSUE TITLE
Split entries - "Just Cause 4 Complete Edition"

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2124]
**MERGE these entries:**
[https://isthereanydeal.com/game/justcauseivcompleteedition/info/](https://isthereanydeal.com/game/justcauseivcompleteedition/info/)

[https://isthereanydeal.com/game/justcauseivcompleteeditionsteam/info/](https://isthereanydeal.com/game/justcauseivcompleteeditionsteam/info/)

**Also, this two, but there are no stores:**
[https://isthereanydeal.com/game/justcauseivreloadedjustcauseivcompleteedition/info/](https://isthereanydeal.com/game/justcauseivreloadedjustcauseivcompleteedition/info/) -> **Epic game store listed. Merge it too for sure.**
[https://isthereanydeal.com/game/justcauseivcompleteeditioncompleteeditionpccodesteam/info/](https://isthereanydeal.com/game/justcauseivcompleteeditioncompleteeditionpccodesteam/info/) -> **Looks like a dead link.**

[Issue created by HYBRID_BEING: 2021-05-21]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
