### ISSUE TITLE
Split entries - "Just Cause 4" Standard and Reloaded editions

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2125]
**MERGE these entries:**
[https://isthereanydeal.com/game/justcauseivreloaded/info/](https://isthereanydeal.com/game/justcauseivreloaded/info/)

[https://isthereanydeal.com/game/justcauseivreloadedjustcauseivstandardedition/info/](https://isthereanydeal.com/game/justcauseivreloadedjustcauseivstandardedition/info/)

[https://isthereanydeal.com/game/justcauseivreloadededition/info/](https://isthereanydeal.com/game/justcauseivreloadededition/info/)

[https://isthereanydeal.com/game/justcauseivreloadedsteam/info/](https://isthereanydeal.com/game/justcauseivreloadedsteam/info/)

[https://isthereanydeal.com/game/justcauseivedition/info/](https://isthereanydeal.com/game/justcauseivedition/info/) \(not sure if this one is Reloaded or Standard - if Standard, should be renamed and screenshot should be replaced\)

**And two dead pages:**
[https://isthereanydeal.com/game/justcauseiv/info/](https://isthereanydeal.com/game/justcauseiv/info/)
[https://isthereanydeal.com/game/justcauseivstandardedition/info/](https://isthereanydeal.com/game/justcauseivstandardedition/info/)

[Issue created by HYBRID_BEING: 2021-05-21]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
