### ISSUE TITLE
Split entries - "Just Cause 4 Gold Edition"

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2126]
[https://isthereanydeal.com/game/justcauseivgoldedition/info/](https://isthereanydeal.com/game/justcauseivgoldedition/info/)

[https://isthereanydeal.com/game/justcauseivreloadedgoldeditionsteam/info/](https://isthereanydeal.com/game/justcauseivreloadedgoldeditionsteam/info/)

4 dead entries:

[https://isthereanydeal.com/game/justcauseivreloadedgoldedition/info/](https://isthereanydeal.com/game/justcauseivreloadedgoldedition/info/)

[https://isthereanydeal.com/game/justcauseivreloadedjustcauseivgoldedition/info/](https://isthereanydeal.com/game/justcauseivreloadedjustcauseivgoldedition/info/)

[https://isthereanydeal.com/game/justcauseivgoldeditiongoldeditionpccodesteam/info/](https://isthereanydeal.com/game/justcauseivgoldeditiongoldeditionpccodesteam/info/)

[https://isthereanydeal.com/game/justcauseivgoldeditionpreload/info/](https://isthereanydeal.com/game/justcauseivgoldeditionpreload/info/)

[Issue created by HYBRID_BEING: 2021-05-21]

**Comment by MarkitkaM** [comment]
**I checked dead entries meant by user:**
1. https://isthereanydeal.com/game/justcauseivreloadedgoldedition/info/ - listed Newegg but link does not exist anymore.

2. https://isthereanydeal.com/game/justcauseivreloadedjustcauseivgoldedition/info/ - Listed Epic Games and link does exist. 

3. https://isthereanydeal.com/game/justcauseivgoldeditiongoldeditionpccodesteam/info/ - Empty entry.

4. https://isthereanydeal.com/game/justcauseivgoldeditionpreload/info/ - mpty entry.

**MERGE these entries ->**
https://isthereanydeal.com/game/justcauseivreloadedjustcauseivgoldedition/info/
https://isthereanydeal.com/game/justcauseivgoldedition/info/
https://isthereanydeal.com/game/justcauseivreloadedgoldeditionsteam/info/

[Issue created by HYBRID_BEING: 2021-05-21]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
