### ISSUE TITLE
War Thunder has second Steam store link to wrong game

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2129]
* Visit: https://isthereanydeal.com/game/warthunder/info/#/
* Click the second Steam store link
* You'll end up at this game: https://store.steampowered.com/app/783590/Age_of_Gladiators_II_Rome/

SPLIT ENTRIES.

[Issue created by [deleted]: 2021-05-24]

**Comment by MarkitkaM** [comment]
Entries to split #2323
