### ISSUE TITLE
Duplicate Steam entries - "Saint's Row: Gat Out of Hell - Devil's Workshop Pack"

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2134]
[https://isthereanydeal.com/game/saintsrowgatoutofhelldevilsworkshoppack/info/](https://isthereanydeal.com/game/saintsrowgatoutofhelldevilsworkshoppack/info/)

[Issue created by HYBRID_BEING: 2021-05-27]

**Comment by MarkitkaM** [comment]
Can't see the duplication of entries.
