### ISSUE TITLE
Mixed games - "Games&Girls" / "Games and Girls"

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2138]
A bit complicated mix up here, so let me explain.

First there are two games with similar names \(similar enough to get ITAD confused, at least\):

[https://store.steampowered.com/app/1573170/Games\_and\_Girls/](https://store.steampowered.com/app/1573170/Games_and_Girls/)

[https://store.steampowered.com/app/610750/GamesGirls/](https://store.steampowered.com/app/610750/GamesGirls/)

Both are actually linked to \(as in, despite different steamId, both Augmented Steam’s “View on IsThereAnyDeal” buttons lead to\) a single ITAD page:

[https://isthereanydeal.com/game/gamesandgirls/info/](https://isthereanydeal.com/game/gamesandgirls/info/)

which has a cover image from the second game, but store link only for the first one. But there is also another ITAD page:

[https://isthereanydeal.com/game/gamesgirls/info/](https://isthereanydeal.com/game/gamesgirls/info/)

Now, this one links to the second game \(which again, in turn, leads to a different ITAD page\).

‌

So, it should be decided which ITAD page is dedicated to which game, and then all links and cover images should be fixed accordingly.

SPLIT ENTRIES PROPERLY.

[Issue created by HYBRID_BEING: 2021-05-28]

**Comment by MarkitkaM** [comment]
Entries to split #2323
