### ISSUE TITLE
3 different games called "Arena" combined

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2140]
[https://isthereanydeal.com/game/arena/info/](https://isthereanydeal.com/game/arena/info/)

**1.** The Steam links are 3 different games.
**2.** The IndieGala link is the same game as the third Steam link.

SPLIT ENTRIES.

![chrome_3HKfaFZ7fD](https://user-images.githubusercontent.com/88401908/129470857-638338ba-030b-439e-b6ab-7d466f6a1b7c.png)

[Issue created by joshg253: 2021-06-03]

**Comment by MarkitkaM** [comment]
Entries to split #2323
