### ISSUE TITLE
Buttons dot displaying properly

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2141]
Hello,

When visiting the website all the buttons like "x" for closing and "-" or "+" are not displaying properly (on both Google Chrome and Edge). I'm not really sure why this happened since a week ago it still worked.

![chrome_TVozCuFIVp](https://user-images.githubusercontent.com/88401908/129470551-cc18f65a-1797-46af-8704-f8038aa2da1c.png)
![chrome_vNgax1H6Hu](https://user-images.githubusercontent.com/88401908/129470571-6dec2465-5a85-4bea-a203-ee5f309d3a9d.png)

[Issue created by [deleted]: 2021-06-04]

**Comment by MarkitkaM** [comment]
Already fixed.
