### ISSUE TITLE
Store link missing - "OkunoKA Madness"

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2144]
[https://isthereanydeal.com/game/okunokamadness/info/](https://isthereanydeal.com/game/okunokamadness/info/)

[https://store.steampowered.com/app/969200/OkunoKA\_Madness/](https://store.steampowered.com/app/969200/OkunoKA_Madness/)

[Issue created by HYBRID_BEING: 2021-06-10]

**Comment by MarkitkaM** [comment]
The game is here: https://isthereanydeal.com/#/page:game/info?plain=okunoka

Possible rename the game or merge it.

**Comment by MarkitkaM** [comment]
Entries to merge #2324
