### ISSUE TITLE
The page for Overboard contains data for two different games

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2145]
https://isthereanydeal.com/game/overboard/info/
![chrome_XlBZuEZKUp](https://user-images.githubusercontent.com/88401908/129455298-98740f8b-dbbf-4f6d-b546-7104cf1b9b7b.png)

This page simultaneously has pricing info for both Overboard, a murder mystery game, and Overboard, a VR shark-fighting game. They should probably have two separate pages.

**SPLIT ENTRIES.**

[Issue created by [deleted]: 2021-06-11]

**Comment by tdnzr** [comment]
There's an identical issue with the games ROLL! and Roll. More generally, it seems that when isthereanydeal parses Steam titles, it strips off (some) punctuation. As these titles show, this causes issues.

https://isthereanydeal.com/game/roll/info/
![chrome_r1gMNuEAa0](https://user-images.githubusercontent.com/88401908/129455455-0d29bdef-74cf-4946-ab7c-8e84d3b232be.png)

**SPLIT THOSE ENTRIES ASWELL.**

**Comment by Ceiyne** [comment]
Overboard still has this issue as of January 31, 2022. 

ITAD link: https://isthereanydeal.com/game/overboard/info/
Steam game 1: https://store.steampowered.com/app/1546920/Overboard/ (this is the game I have wishlisted on Steam)
Steam game 2: https://store.steampowered.com/app/1144080/Overboard/ (I did not wishlist this game on Steam)

**Comment by Ceiyne** [comment]
Marvel Puzzle Quest has a similar issue.

ITAD link: https://isthereanydeal.com/game/marvelpuzzlequest/info/
Correct Steam link: https://store.steampowered.com/app/234330/MARVEL_Puzzle_Quest/
ITAD also links to this unrelated game: https://store.steampowered.com/app/778810/Soul_for_two/

**Comment by Ceiyne** [comment]
Also Subverse.

ITAD link: https://isthereanydeal.com/game/subverse/info/
Steam link for the game I wishlisted: https://store.steampowered.com/app/1034140/Subverse/
Steam link for an unrelated movie: https://store.steampowered.com/app/1001630/

**Comment by MarkitkaM** [comment]
Entries to split #2323

ad SUBVERSE #2681

**Comment by lewisohn** [comment]
The game [Overboard!](https://store.steampowered.com/app/1546920/Overboard/) is missing from ITAD. When synced from Steam, it incorrectly creates a waitlist entry for Overboard, no exclamation mark.
