### ISSUE TITLE
Trying to reach mainpage will redirect me to domain.com

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#215]
Since a few days i will alway be redirectet to domain.com when i try to acess the main page. all other pages seems to work fine though. 

[Issue created by [deleted]: 2015-06-15]
[Last updated on bitbucket: 2015-06-16]

[Comment created by tfedor: 2015-06-15]
We had some issues setting up new servers, if you clear your browser's cache it should work for you.

**Comment by MarkitkaM** [comment]
Solved.
