### ISSUE TITLE
Split entries - "Kotodama"

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2151]
[https://isthereanydeal.com/game/kotodamaviimysteriesoffujisawa/info/](https://isthereanydeal.com/game/kotodamaviimysteriesoffujisawa/info/)
[https://isthereanydeal.com/game/kotodama/info/](https://isthereanydeal.com/game/kotodama/info/)

**Merge together.**

[Issue created by HYBRID_BEING: 2021-06-16]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
