### ISSUE TITLE
Wrong Steam-link for game Metamorphosis

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2152]
https://isthereanydeal.com/#/page:game/info?plain=metamorphosis
![chrome_WQTTMgC2GF](https://user-images.githubusercontent.com/88401908/129452431-c649f606-d46b-431f-a38e-0a583cf8ef42.png)

The Steam-link there is for the wrong game. Currently and wrong:

https://store.steampowered.com/app/1259960/The_Metamorphosis/

Right game and link: https://store.steampowered.com/app/1025410/Metamorphosis/

[Issue created by [deleted]: 2021-06-17]

**Comment by MarkitkaM** [comment]
The duplicating issue #2056 closed.

**Comment by MarkitkaM** [comment]
Entries to split #2323
