### ISSUE TITLE
Erroneous and/or double listings for games with same title

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2158]
**1.** I personally can only attest to the two games in my waitlist (the game is called "Singularity"), but you guys are lumping in some games that have the same title under a single listing. In the Singularity case, the lower priced game is free, while the more popular game is priced at $29.99. Thus, the more expensive game is listed as perpetually free when it is not. I've seen this error for two years and I guess no one ever got around to reporting it. 

https://isthereanydeal.com/game/singularity/info/
![chrome_65vpJpgi8C](https://user-images.githubusercontent.com/88401908/129448825-678ac0a4-4401-4e84-8caf-a68406cb14ab.png)

**2.** Also, there appear to be multiple listings for the exact same game. Mount and Blade: Bannerlord has two listings for the same product ..

SPLIT ENTRIES:
https://isthereanydeal.com/game/mountandbladeiibannerlord/info/
https://isthereanydeal.com/game/mountbladeiibannerlord/info/

**3.** ..and so does the complete edition of Necrovision. 
https://isthereanydeal.com/game/necrovision/info/

Not sure if your algorithm needs an IQ test or if that is a human error, but you need to more closely examine game titles to make sure there isn't errors like this because it defeats the entire purpose of the site.

[Issue created by [deleted]: 2021-06-22]

**Comment by MarkitkaM** [comment]
**ad1)** duplication #1986 and #1973

**Comment by swiehr** [comment]
For 2. I can add these 3 games (seems a general issue with titles having an Ampersand in the title):
https://isthereanydeal.com/game/mountandbladewithfireandsword/info/
https://isthereanydeal.com/game/mountbladewithfiresword/info/

https://isthereanydeal.com/game/mountandblade/info/
https://isthereanydeal.com/game/mountblade/info/

https://isthereanydeal.com/game/mountandbladewarband/info/
https://isthereanydeal.com/game/mountbladewarband/info/

**Comment by MarkitkaM** [comment]
ad1) Entries to split #2323
ad2) Entries to merge #2324

**Comment by MarkitkaM** [comment]
@swiehr 
Hello, 
thank you for your feedback. 
Fixing the above issues is in order. We apologize for the inconvenience.

Can you please specify what is wrong with point 3? 
ad3)
> 3. ..and so does the complete edition of Necrovision.
> https://isthereanydeal.com/game/necrovision/info/

Thank you very much.

**Comment by swiehr** [comment]
> Can you please specify what is wrong with point 3? ad3)
> 
> > 3. ..and so does the complete edition of Necrovision.
> >    https://isthereanydeal.com/game/necrovision/info/

That was stated by the original author @tfedor - I don't know anything about this, just added my findings on "Mount & Blade" games

**Comment by MarkitkaM** [comment]
ad3) moved to #2727
