### ISSUE TITLE
Base price and discount information about Borderlands 3: Ultimate Edition is grossly wrong (in BRL)

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2159]
As can be seen in the below screenshot, ITAD is not getting the price correctly. On the website, it also shows this package has a 0% cut, which means it’s getting neither the price, nor the cut.

BTW, this also affects the historical best, so it’s another thing to be fixed when this issue is taken care of.

![](https://bitbucket.org/repo/b6qGGA/images/3363298222-image.png)
‌

[Issue created by fabiorfreitas: 2021-06-22]

**Comment by MarkitkaM** [comment]
It was already fixed.

https://isthereanydeal.com/game/borderlandsiiiultimateedition/info/
![chrome_WssGRrWzJ0](https://user-images.githubusercontent.com/88401908/129448075-571d24fb-436a-4131-975d-6e0c7658970f.png)

https://store.steampowered.com/bundle/16675/Borderlands_3_Ultimate_Edition/
![chrome_3uxlWGRkoJ](https://user-images.githubusercontent.com/88401908/129448086-38ffcb4c-8952-49b6-ba39-ffd91927ce49.png)
