### ISSUE TITLE
Mixed entries - "Axiom Verge"

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2160]
Same game, but bundle is mixed with a game itself.

[https://isthereanydeal.com/game/axiomverge/info/](https://isthereanydeal.com/game/axiomverge/info/)

Bundle: [https://store.steampowered.com/sub/70162/](https://store.steampowered.com/sub/70162/)

Store page: [https://store.steampowered.com/app/332200/Axiom\_Verge/](https://store.steampowered.com/app/332200/Axiom_Verge/)

[Issue created by HYBRID_BEING: 2021-06-24]

**Comment by MarkitkaM** [comment]
Entries to split #2323
