### ISSUE TITLE
Companion / The Companion confusion

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2161]
If "[The Companion](https://store.steampowered.com/app/1392780/The_Companion/)" is in the Steam's wish list, ITAD notifies about another game called "[Companion](https://store.steampowered.com/app/1392780/The_Companion/)".

Merged entries of ITAD Game "Companion". Second listed Steam is linked to the game "The Companion"
https://isthereanydeal.com/game/companion/info/
![chrome_TgCq4L87bF](https://user-images.githubusercontent.com/88401908/129446352-116f4668-b8ce-48f2-9ff9-ef6ce027823e.png)

[Issue created by [deleted]: 2021-06-25]

**Comment by MarkitkaM** [comment]
Entries to split #2323
