### ISSUE TITLE
Star Wars Jedi Fallen Order - Steam sale price not showing

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2163]
Star Wars Jedi Fallen Order is currently on Steam sale for $15.99 (60% off). It is appearing as $39.99 (no price cut) on IsThereAnyDeal.

ITAD link:
https://isthereanydeal.com/game/starwarsjedifallenorder/info/

Steam link:
https://store.steampowered.com/app/1172380/STAR_WARS_Jedi_Fallen_Order/

Thank you!
------
ITAD
![chrome_wcx8QYKcb7](https://user-images.githubusercontent.com/88401908/129403985-6e8e8b96-28ea-4988-9a97-7c8e607c78dd.png)

STEAM:
![chrome_B9Dnz1tw08](https://user-images.githubusercontent.com/88401908/129404054-a3788158-2a7d-4a2f-a899-bf8ae36abcb7.png)

[Issue created by [deleted]: 2021-06-26]

**Comment by MarkitkaM** [comment]
Solved.
