### ISSUE TITLE
Broken symbols all over the site.

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2165]
Various symbols are broken on every page I’ve visited.
Screenshot by user:
![image](https://user-images.githubusercontent.com/88401908/129396820-b60b724a-544f-483b-8071-ca0bee1bdd14.png)

[Issue created by fatcatonmars: 2021-06-26]

**Comment by MarkitkaM** [comment]
Screenshot from today:
![chrome_bcSxVBWaIV](https://user-images.githubusercontent.com/88401908/129399317-7a47853b-b7dc-4e3b-aeb2-af2b29982647.png)

Actually, it seems to be ok. I went through random pages and cross-browser and didn't find any broken symbols at all.

NOT A BUG.
