### ISSUE TITLE
Fix the wrong Wingpan entry of TTS in the standalone game entry

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2167]
Fix this existing issue: Wingpan (Steam) mixed up with Wingspan for TTS (Steam)

https://bitbucket.org/tfedor/isthereanydeal.com/issues/2050/wingpan-steam-mixed-up-with-wingspan-for
>"Hi, You correctly have two different items in your DB, one is Wingspan, and the other is Tabletop Simulator (TTS) Wingspan. * >https://isthereanydeal.com/game/wingspan/info/ * https://isthereanydeal.com/game/tabletopsimulatorwingspan/info/
>The current issue is that the Steam offer price currently associated with Wingspan in your DB, is instead the price of the TTS >Wingspan."

Could it take more than 5 minutes to delete the TTS entry and make it its own page?

Remove this TTS link https://store.steampowered.com/app/610703

[Issue created by [deleted]: 2021-06-27]
[Last updated on bitbucket: 2021-06-30]

[Comment created by adamnoffie: 2021-06-30]
\+1 for this

**Comment by MarkitkaM** [comment]
Duplication of #2050
