### ISSUE TITLE
[Incorrect] Remember me

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2168]
Remember Me by Dontnod Entertainment is not sold on itch.io

https://isthereanydeal.com/game/rememberme/info/
--
Three different games under 1 entry. Split it.

[Issue created by [deleted]: 2021-06-28]

**Comment by MarkitkaM** [comment]
Entries to split #2323

**Comment by MarkitkaM** [comment]
Duplication #1943
