### ISSUE TITLE
Card City Nights listing soundtrack as game

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2169]
https://isthereanydeal.com/game/cardcitynights/info/

There are now two listings for Steam on the page, the regularly $0.99 one is the soundtrack which used to be under DLC. 
Got an email alert for the game which was actually the soundtrack

[Issue created by [deleted]: 2021-06-28]

**Comment by MarkitkaM** [comment]
Entries to split #2323
