### ISSUE TITLE
Games merged into same entry. Wrong data.

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2171]
Both entries for "Oneshot" and "Heartbeat" contain two different games, priced differently. We can't track deals properly because the data seems to always refer to the cheaper game.

https://store.steampowered.com/app/420530/OneShot/
https://store.steampowered.com/app/1221330/One_Shot/

https://store.steampowered.com/app/1386710/The_HeartBeat/
https://store.steampowered.com/app/984560/HEARTBEAT/

[Issue created by [deleted]: 2021-06-30]

**Comment by MarkitkaM** [comment]
Oneshot
https://isthereanydeal.com/game/oneshot/info/

Heartbeat
https://isthereanydeal.com/game/heartbeat/info/

**Comment by MarkitkaM** [comment]
Entries to split #2323
