### ISSUE TITLE
did not receive any notifications for waitlist items when steam summer sale started

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2174]
Had a few qualify, no email was received.  Checked spam folder.

[Issue created by [deleted]: 2021-06-30]

[Comment created by tfedor: 2021-06-30]
What’s your username on ITAD and what games were you suppoed to be emailed about, so I can check?

**Comment by MarkitkaM** [comment]
The user didn't replied.
