### ISSUE TITLE
The Ascent has a link to the incorrect game on Steam

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2176]
The Ascent is showing a very cheap price on Steam, but the link goes to a different game called Ascent on Steam.

[Issue created by [deleted]: 2021-07-01]

**Comment by MarkitkaM** [comment]
Duplicate https://github.com/IsThereAnyDeal/IsThereAnyDeal-Issues/issues/2202 .
