### ISSUE TITLE
Several Steam sales deals not showing up in either the games pages, nor in the alerts for deals

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2177]
Hello, 
I noticed several big games like 

- **Need For Speed Heat** 
https://isthereanydeal.com/game/needforspeedheat/info/

- & **Forza Horizon 4** 
https://isthereanydeal.com/game/forzahorizoniv/info/

have their best ever prices now available on Steam, 
but, in the game page with stores, Steam doesn't even appear !! 

So, the best price on Steam doesn't appear, 
And the games don't show in the notifications

![chrome_8DnNwyClNm](https://user-images.githubusercontent.com/88401908/128632629-80c6ca6a-bf6e-478f-bf6f-88edd8686189.png)
![chrome_EJqslQStM3](https://user-images.githubusercontent.com/88401908/128632644-de27b74d-e9c0-43c4-9a8b-a0fc0e402523.png)

[Issue created by [deleted]: 2021-07-03]

**Comment by MarkitkaM** [comment]
Is Forza Horizon 4 this one https://isthereanydeal.com/game/forzahorizonivstandardedition/info/ ?

**Comment by MarkitkaM** [comment]
**Need for Speed™ Heat** -> #2684

**Forza Horizon 4** 
https://isthereanydeal.com/game/forzahorizonivstandardedition/info/
https://isthereanydeal.com/game/forzahorizoniv/info/
-> Entries to merge #2324
