### ISSUE TITLE
Wrong games (with same name) are regularly linked in notification emails.

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2178]
Today, I got a sale notification for 30XX, which is on my wishlist. Great!

However, the game ITAD linked is https://store.steampowered.com/app/1576140/30XX/ rather than the game on my wishlist, which is https://store.steampowered.com/app/1029210/30XX/

This is happening more and more with ITAD, to the point I don't feel like ITAD is nearly as useful as it used to be. I'm missing sales because it thinks the wrong game is on my wishlist.

[Issue created by [deleted]: 2021-07-04]
[Last updated on bitbucket: 2021-07-18]

[Comment created by kriswilk: 2021-07-18]
I came here having the same problem as OP, with the same game…30XX. Not even a very obscure game. ITAD’s page has two steam associations \(this is always a tip-off that something is wonky\), only the second is correct. Annoying because it throws off all the pricing history and notifications.

[Comment created by aliendave: 2021-07-06]
Two different games on Itch \([https://bluestockings.itch.io/remember-me](https://bluestockings.itch.io/remember-me) and [https://collectivegee.itch.io/remember-me-final](https://collectivegee.itch.io/remember-me-final) \) were incorrectly linked to [https://isthereanydeal.com/game/rememberme/info/](https://isthereanydeal.com/game/rememberme/info/)

**Comment by MarkitkaM** [comment]
Entries to split #2323
