### ISSUE TITLE
Split entries - "Schizm 2"

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2184]
[https://isthereanydeal.com/game/schizmii/info/](https://isthereanydeal.com/game/schizmii/info/)

[https://isthereanydeal.com/game/schizmiichameleon/info/](https://isthereanydeal.com/game/schizmiichameleon/info/)

[Issue created by HYBRID_BEING: 2021-07-09]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
