### ISSUE TITLE
Merge 'Ticket to Ride' at GamesPlanet

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2185]
[https://isthereanydeal.com/game/tickettoride/info/](https://isthereanydeal.com/game/tickettoride/info/)

[https://isthereanydeal.com/game/tickettoridelesaventuriersdurail/info/](https://isthereanydeal.com/game/tickettoridelesaventuriersdurail/info/)

[https://isthereanydeal.com/game/tickettoridezugumzug/](https://isthereanydeal.com/game/tickettoridezugumzug/info/?currency=EUR)

Each is the same game, but GamesPlanet adds the titles of the board game in the local language.

-> Merge them together.

[Issue created by miranka: 2021-07-09]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
