### ISSUE TITLE
Merge requests for multiple items

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2186]
I recently looked at my ITAD Waitlist and found it odd, that apparently some games were no longer sold online.  
Upon checking them manually, I turned out that some of the items imported from my Steam Wishlist \(a long time ago\) now link to dead ITAD pages.  
Here are the items I identified and probably should be merged:

| **old \(broken\)** |
| --- |
| [https://isthereanydeal.com/game/achairinaroomgreenwater/info/](https://isthereanydeal.com/game/achairinaroomgreenwater/info/)  
[https://isthereanydeal.com/game/callofdutyghostsweaponmaverick/info/](https://isthereanydeal.com/game/callofdutyghostsweaponmaverick/info/)  
[https://isthereanydeal.com/game/callofdutyghostsweaponripper/info/](https://isthereanydeal.com/game/callofdutyghostsweaponripper/info/)  
[https://isthereanydeal.com/game/cohiibritishcommanderspecialweaponsregiment/info/](https://isthereanydeal.com/game/cohiibritishcommanderspecialweaponsregiment/info/)  
[https://isthereanydeal.com/game/cohiibritishcommanderspecialweaponsregiment/info/](https://isthereanydeal.com/game/cohiibritishcommanderspecialweaponsregiment/info/)  
[https://isthereanydeal.com/game/cohiibritishcommandertacticalsupportregiment/info/](https://isthereanydeal.com/game/cohiibritishcommandertacticalsupportregiment/info/)  
[https://isthereanydeal.com/game/cohiibritishcommandertacticalsupportregiment/info/](https://isthereanydeal.com/game/cohiibritishcommandertacticalsupportregiment/info/)  
[https://isthereanydeal.com/game/cohiibritishcommandervanguardoperationsregiment/info/](https://isthereanydeal.com/game/cohiibritishcommandervanguardoperationsregiment/info/)  
[https://isthereanydeal.com/game/cohiibritishcommandervanguardoperationsregiment/info/](https://isthereanydeal.com/game/cohiibritishcommandervanguardoperationsregiment/info/)  
[https://isthereanydeal.com/game/cohiigermancommanderencirclementdoctrine/info/](https://isthereanydeal.com/game/cohiigermancommanderencirclementdoctrine/info/)  
[https://isthereanydeal.com/game/cohiigermancommanderencirclementdoctrine/info/](https://isthereanydeal.com/game/cohiigermancommanderencirclementdoctrine/info/)  
[https://isthereanydeal.com/game/cohiigermancommanderfortifiedarmordoctrine/info/](https://isthereanydeal.com/game/cohiigermancommanderfortifiedarmordoctrine/info/)  
[https://isthereanydeal.com/game/cohiigermancommanderfortifiedarmordoctrine/info/](https://isthereanydeal.com/game/cohiigermancommanderfortifiedarmordoctrine/info/)  
[https://isthereanydeal.com/game/cohiigermancommanderjointoperationsdoctrine/info/](https://isthereanydeal.com/game/cohiigermancommanderjointoperationsdoctrine/info/)  
[https://isthereanydeal.com/game/cohiigermancommanderjointoperationsdoctrine/info/](https://isthereanydeal.com/game/cohiigermancommanderjointoperationsdoctrine/info/)  
[https://isthereanydeal.com/game/cohiigermancommanderlightningwardoctrine/info/](https://isthereanydeal.com/game/cohiigermancommanderlightningwardoctrine/info/)  
[https://isthereanydeal.com/game/cohiigermancommanderlightningwardoctrine/info/](https://isthereanydeal.com/game/cohiigermancommanderlightningwardoctrine/info/)  
[https://isthereanydeal.com/game/cohiigermancommanderluftwaffesupplydoctrine/info/](https://isthereanydeal.com/game/cohiigermancommanderluftwaffesupplydoctrine/info/)  
[https://isthereanydeal.com/game/cohiigermancommanderspearheaddoctrine/info/](https://isthereanydeal.com/game/cohiigermancommanderspearheaddoctrine/info/)  
[https://isthereanydeal.com/game/cohiigermancommanderspearheaddoctrine/info/](https://isthereanydeal.com/game/cohiigermancommanderspearheaddoctrine/info/)  
[https://isthereanydeal.com/game/cohiiokwcommanderscavengedoctrine/info/](https://isthereanydeal.com/game/cohiiokwcommanderscavengedoctrine/info/)  
[https://isthereanydeal.com/game/cohiisovietcommanderantiinfantrytactics/info/](https://isthereanydeal.com/game/cohiisovietcommanderantiinfantrytactics/info/)  
[https://isthereanydeal.com/game/cohiisovietcommanderantiinfantrytactics/info/](https://isthereanydeal.com/game/cohiisovietcommanderantiinfantrytactics/info/)  
[https://isthereanydeal.com/game/cohiisovietcommandertankhuntertactics/info/](https://isthereanydeal.com/game/cohiisovietcommandertankhuntertactics/info/)  
[https://isthereanydeal.com/game/cohiisovietcommanderterrortactics/info/](https://isthereanydeal.com/game/cohiisovietcommanderterrortactics/info/)  
[https://isthereanydeal.com/game/fivenightsatfreddysvrhelpwanted/info/](https://isthereanydeal.com/game/fivenightsatfreddysvrhelpwanted/info/)  
[https://isthereanydeal.com/game/infra/info/](https://isthereanydeal.com/game/infra/info/)  
[https://isthereanydeal.com/game/innocentvr/info/](https://isthereanydeal.com/game/innocentvr/info/)  
[https://isthereanydeal.com/game/nierautomata/info/](https://isthereanydeal.com/game/nierautomata/info/)  
[https://isthereanydeal.com/game/totalwarromeiiempiredividedcampaignpack/info/](https://isthereanydeal.com/game/totalwarromeiiempiredividedcampaignpack/info/)  
[https://isthereanydeal.com/game/yearoneupgrade/info/](https://isthereanydeal.com/game/yearoneupgrade/info/) |

| **new \(current\)** |
| --- |
| [https://isthereanydeal.com/game/achairinaroom/info/](https://isthereanydeal.com/game/achairinaroom/info/)  
[https://isthereanydeal.com/game/callofdutyghostsmaverick/info/](https://isthereanydeal.com/game/callofdutyghostsmaverick/info/)  
[https://isthereanydeal.com/game/callofdutyghostsripper/info/](https://isthereanydeal.com/game/callofdutyghostsripper/info/)  
[https://isthereanydeal.com/game/companyofheroesiibritishforcesspecialweaponsregiment/info/](https://isthereanydeal.com/game/companyofheroesiibritishforcesspecialweaponsregiment/info/)  
[https://isthereanydeal.com/game/companyofheroesiibritishforcesspecialweaponsregiment/info/](https://isthereanydeal.com/game/companyofheroesiibritishforcesspecialweaponsregiment/info/)  
[https://isthereanydeal.com/game/companyofheroesiibritishcommandersupportregiment/info/](https://isthereanydeal.com/game/companyofheroesiibritishcommandersupportregiment/info/)  
[https://isthereanydeal.com/game/companyofheroesiibritishcommandersupportregiment/info/](https://isthereanydeal.com/game/companyofheroesiibritishcommandersupportregiment/info/)  
[https://isthereanydeal.com/game/companyofheroesiibritishforcesvanguardregiment/info/](https://isthereanydeal.com/game/companyofheroesiibritishforcesvanguardregiment/info/)  
[https://isthereanydeal.com/game/companyofheroesiibritishforcesvanguardregiment/info/](https://isthereanydeal.com/game/companyofheroesiibritishforcesvanguardregiment/info/)  
[https://isthereanydeal.com/game/companyofheroesiigermancommanderencirclementdoctrine/info/](https://isthereanydeal.com/game/companyofheroesiigermancommanderencirclementdoctrine/info/)  
[https://isthereanydeal.com/game/companyofheroesiigermancommanderencirclementdoctrine/info/](https://isthereanydeal.com/game/companyofheroesiigermancommanderencirclementdoctrine/info/)  
[https://isthereanydeal.com/game/companyofheroesiigermancommanderfortifiedarmordoctrine/info/](https://isthereanydeal.com/game/companyofheroesiigermancommanderfortifiedarmordoctrine/info/)  
[https://isthereanydeal.com/game/companyofheroesiigermancommanderfortifiedarmordoctrine/info/](https://isthereanydeal.com/game/companyofheroesiigermancommanderfortifiedarmordoctrine/info/)  
[https://isthereanydeal.com/game/companyofheroesiigermancommanderjointoperationsdoctrine/info/](https://isthereanydeal.com/game/companyofheroesiigermancommanderjointoperationsdoctrine/info/)  
[https://isthereanydeal.com/game/companyofheroesiigermancommanderjointoperationsdoctrine/info/](https://isthereanydeal.com/game/companyofheroesiigermancommanderjointoperationsdoctrine/info/)  
[https://isthereanydeal.com/game/companyofheroesiigermancommanderlightningwardoctrine/info/](https://isthereanydeal.com/game/companyofheroesiigermancommanderlightningwardoctrine/info/)  
[https://isthereanydeal.com/game/companyofheroesiigermancommanderlightningwardoctrine/info/](https://isthereanydeal.com/game/companyofheroesiigermancommanderlightningwardoctrine/info/)  
[https://isthereanydeal.com/game/companyofheroesiigermancommanderluftwaffesupplydoctrine/info/](https://isthereanydeal.com/game/companyofheroesiigermancommanderluftwaffesupplydoctrine/info/)  
[https://isthereanydeal.com/game/companyofheroesiigermancommanderspearheaddoctrine/info/](https://isthereanydeal.com/game/companyofheroesiigermancommanderspearheaddoctrine/info/)  
[https://isthereanydeal.com/game/companyofheroesiigermancommanderspearheaddoctrine/info/](https://isthereanydeal.com/game/companyofheroesiigermancommanderspearheaddoctrine/info/)  
[https://isthereanydeal.com/game/cohiiokwcommanderscavengedoctrin/info/](https://isthereanydeal.com/game/cohiiokwcommanderscavengedoctrin/info/)  
[https://isthereanydeal.com/game/companyofheroesiisovietcommanderantiinfantrytactics/info/](https://isthereanydeal.com/game/companyofheroesiisovietcommanderantiinfantrytactics/info/)  
[https://isthereanydeal.com/game/companyofheroesiisovietcommanderantiinfantrytactics/info/](https://isthereanydeal.com/game/companyofheroesiisovietcommanderantiinfantrytactics/info/)  
[https://isthereanydeal.com/game/companyofheroesiisovietcommandertankhuntertactics/info/](https://isthereanydeal.com/game/companyofheroesiisovietcommandertankhuntertactics/info/)  
[https://isthereanydeal.com/game/companyofheroesiisovietcommanderterrortactics/info/](https://isthereanydeal.com/game/companyofheroesiisovietcommanderterrortactics/info/)  
[https://isthereanydeal.com/game/fivenightsatfreddyshelpwanted/info/](https://isthereanydeal.com/game/fivenightsatfreddyshelpwanted/info/)  
[https://isthereanydeal.com/game/infracompleteedition/info/](https://isthereanydeal.com/game/infracompleteedition/info/)  
[https://isthereanydeal.com/game/innocent/info/](https://isthereanydeal.com/game/innocent/info/)  
[https://isthereanydeal.com/game/nierautomatagameofyorhaedition/info/](https://isthereanydeal.com/game/nierautomatagameofyorhaedition/info/)  
[https://isthereanydeal.com/game/totalwarromeiiempiredivided/info/](https://isthereanydeal.com/game/totalwarromeiiempiredivided/info/)  
[https://isthereanydeal.com/game/dirtvyeariupgrade/info/](https://isthereanydeal.com/game/dirtvyeariupgrade/info/) |

I’m not sure, why this happened.  
Manually syncing the Steam Waitlist to ITAD didn’t fix the problem.

[Issue created by tehl0wBoB: 2021-07-11]

[Comment created by tehl0wBoB: 2021-07-11]
added multiple items out of sync to be merged

**Comment by MarkitkaM** [comment]
Entries to merge #2324
