### ISSUE TITLE
A total mess with entries - "Resident Evil 7"

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2189]
Oh boy, where do i start.

Well, first, there are a lot of dead pages \(some might have price history for stores, though\):

[https://isthereanydeal.com/game/residentevilviiteaserbeginninghour/info/](https://isthereanydeal.com/game/residentevilviiteaserbeginninghour/info/)

[https://isthereanydeal.com/game/residentevilviigold/info/](https://isthereanydeal.com/game/residentevilviigold/info/)

[https://isthereanydeal.com/game/preorderresidentevilviibiohazardbiohazardviiresidentevil/info/](https://isthereanydeal.com/game/preorderresidentevilviibiohazardbiohazardviiresidentevil/info/)

[https://isthereanydeal.com/game/residentevilviibiohazardgold/info/](https://isthereanydeal.com/game/residentevilviibiohazardgold/info/)

[https://isthereanydeal.com/game/residentevilviideluxeedition/info/](https://isthereanydeal.com/game/residentevilviideluxeedition/info/)

[https://isthereanydeal.com/game/residentevilviibiohazarddigitaldeluxeedition/info/](https://isthereanydeal.com/game/residentevilviibiohazarddigitaldeluxeedition/info/)

[https://isthereanydeal.com/game/residentevilviibiohazarddeluxeedition/info/](https://isthereanydeal.com/game/residentevilviibiohazarddeluxeedition/info/)

[https://isthereanydeal.com/game/residentevilviibiohazardgoldeditionxboxonewini0pcdownloadcode/info/](https://isthereanydeal.com/game/residentevilviibiohazardgoldeditionxboxonewini0pcdownloadcode/info/)

And then, there are split entries.

Resident Evil 7:

[https://isthereanydeal.com/game/residentevilvii/info/](https://isthereanydeal.com/game/residentevilvii/info/)

[https://isthereanydeal.com/game/residentevilviibiohazardbiohazardviiresidentevil/info/](https://isthereanydeal.com/game/residentevilviibiohazardbiohazardviiresidentevil/info/)

Resident Evil 7 Gold Edition:

[https://isthereanydeal.com/game/residentevilviigoldedition/info/](https://isthereanydeal.com/game/residentevilviigoldedition/info/)

[https://isthereanydeal.com/game/residentevilviibiohazardgoldedition/info/](https://isthereanydeal.com/game/residentevilviibiohazardgoldedition/info/)

Season Pass:

[https://isthereanydeal.com/game/residentevilviiseasonpass/info/](https://isthereanydeal.com/game/residentevilviiseasonpass/info/)

[https://isthereanydeal.com/game/residentevilviibiohazardviiseasonpass/info/](https://isthereanydeal.com/game/residentevilviibiohazardviiseasonpass/info/)

[https://isthereanydeal.com/game/residentevilviibiohazardseasonpass/info/](https://isthereanydeal.com/game/residentevilviibiohazardseasonpass/info/)

Banned Footage Vol.1:

[https://isthereanydeal.com/game/residentevilviibiohazardbannedfootagevoli/info/](https://isthereanydeal.com/game/residentevilviibiohazardbannedfootagevoli/info/)

[https://isthereanydeal.com/game/bannedfootagevoli/info/](https://isthereanydeal.com/game/bannedfootagevoli/info/)

Banned Footage Vol.2:

[https://isthereanydeal.com/game/residentevilviibiohazardbannedfootagevolii/info/](https://isthereanydeal.com/game/residentevilviibiohazardbannedfootagevolii/info/)

[https://isthereanydeal.com/game/bannedfootagevolii/info/](https://isthereanydeal.com/game/bannedfootagevolii/info/)

[Issue created by HYBRID_BEING: 2021-07-12]

**Comment by MarkitkaM** [comment]
Dead links #2709

Split entries -> Entries to merge #2324
