### ISSUE TITLE
Indie Bundle for Palestinian Aid Not Showing Up

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#2195]
[Itch.io](http://Itch.io) did another megabundle for a targeted charity, and it doesn’t show up in the lists when searching for the full name or any significant subset I could think of.  Not sure if these are being put in manually or scraped, but I am up for helping either way.

[Issue created by Nightsmaiden: 2021-07-23]

**Comment by MarkitkaM** [comment]
Not a bug.

It is possible to search for the Indie Bundle for Palestinian Aid by filters of the Specials section -> https://isthereanydeal.com/specials/#/filter:&search/palestinian%20aid

via screenshot
![chrome_wor4ApyHHU](https://user-images.githubusercontent.com/88401908/128599583-97de3143-0c65-421a-b04c-6cb01a6de3da.png)

On the new website will be the search improved.
