### ISSUE TITLE
Love Esquire - Multiple duplicate entries

### ISSUE THREAD

**Issue by MagikGimp** [IsThereAnyDeal/IsThereAnyDeal-Issues#2200]
- [https://isthereanydeal.com/game/loveesquiredatingsimrpgvisualnovel/info/](https://isthereanydeal.com/game/loveesquiredatingsimrpgvisualnovel/info/) - Main listing for base game (does not have thumbnail).
- [https://isthereanydeal.com/game/loveesquire/info/](https://isthereanydeal.com/game/loveesquire/info/) - Links to Deluxe edition on IndieGala but is named as base game.
- [https://isthereanydeal.com/game/loveesquirerpgdatingsimvisualnovel/info/](https://isthereanydeal.com/game/loveesquirerpgdatingsimvisualnovel/info/) - Base game duplicate, no Steam link.
- [https://isthereanydeal.com/game/loveesquiredeluxeedition/info/](https://isthereanydeal.com/game/loveesquiredeluxeedition/info/) - Deluxe edition, Steam only, no thumbnail.

- [https://isthereanydeal.com/game/loveesquiredigitalartbook/info/](https://isthereanydeal.com/game/loveesquiredigitalartbook/info/) - Digital Artbook.
- [https://isthereanydeal.com/game/loveesquireartbook/info/](https://isthereanydeal.com/game/loveesquireartbook/info/) - Duplicate for Digital Artbook above (wording omits "Digital".)

**Comment by MarkitkaM** [comment]
Entries to merge #2324
