### ISSUE TITLE
"The Ascent" linking to wrong specials, game and pages.

### ISSUE THREAD

**Issue by PhloopGarou** [IsThereAnyDeal/IsThereAnyDeal-Issues#2202]
I have **The Ascent** on my wishlist, which is this one:
https://store.steampowered.com/app/979690/The_Ascent/

However, the ITAD page links to both **Ascent** (https://store.steampowered.com/app/1682620/Ascent/) and **Ascent** (https://store.steampowered.com/app/1464000/Ascent/), which is notifying me that a game on my waitlist is discounted.

I know that this is likely because the names are the same and it's not your fault, but maybe updating the database entry to point to the correct one only would help.
----------------------------------------------------
https://isthereanydeal.com/game/ascent/info/
![chrome_9650j0bKDz](https://user-images.githubusercontent.com/88401908/128602954-8161d258-ad71-4ee8-bde6-6c14121c460e.png)

Change links to the propper game "The Ascent".

**Comment by thestonehead** [comment]
It would be less of a problem if "Lowest" category was grouped by steam link instead of the store.

**Comment by LesterCovax** [comment]
The fact that it's linking to a game called "Ascent" is troubling, as it implies the backend is searching via title (while ignoring `the` in whatever sed/grep'esque query). For steam games it should be using the appid from steamdb's catalogue. As a backup, it could could compare the expected publisher/developer, and even compare the game cover art via some ML/CV.  This could be applicable for all storefronts.  The biggest red-flag IMO is if there's more than one listing for any single game, and there are currently three false-positives.

**Comment by tfedor** [comment]
Fixed

**Comment by HYBRID-BEING** [comment]
Hmm, wrong games are not linked anymore, but now i have two links to the same correct Steam store page (https://store.steampowered.com/app/979690/The_Ascent/). For some reason, one of them shows price cut, but there is no price cut at the moment.
![изображение](https://user-images.githubusercontent.com/1691231/134075987-41fb0fa2-329f-41a9-9716-676bd1b0cec3.png)

**Comment by tfedor** [comment]
Fixed that too now.
