### ISSUE TITLE
Wrong link on Steam page - "IN-VERT: Definitive Edition"

### ISSUE THREAD

**Issue by HYBRID-BEING** [IsThereAnyDeal/IsThereAnyDeal-Issues#2204]
Link leads to https://isthereanydeal.com/game/invert/info/, while correct link is https://isthereanydeal.com/game/invertdefinitiveedition/info/.
Page https://isthereanydeal.com/game/invert/info/ should be merged into the newer one.

**Comment by MarkitkaM** [comment]
Entries to split #2323
