### ISSUE TITLE
"Detention" itch.io store link leads to wrong game with the same name

### ISSUE THREAD

**Issue by CosminBirjoveanu** [IsThereAnyDeal/IsThereAnyDeal-Issues#2207]
If u navigate to https://new.isthereanydeal.com/game/detention/info/ or https://isthereanydeal.com/game/detention/info/ and click the "Buy" button corresponding to the itch.io store, it will lead to  https://biiiy.itch.io/detention  which is another free game with the same name.

![chrome_ngSllPKWne](https://user-images.githubusercontent.com/88401908/130188857-e2303d3f-1ec7-4430-96da-d56bbc905aa1.png)

**Actual game:**
![Screenshot_60](https://user-images.githubusercontent.com/48485136/129633692-70dbb501-f0ed-4b4d-806c-794eeb62d84d.png)

**The itch.io link game**
![Screenshot_59](https://user-images.githubusercontent.com/48485136/129633551-bd93ea60-0677-40e0-8a2a-194cd6fb3905.png)

**Comment by MarkitkaM** [comment]
Duplicated issue closed #2114

**Comment by MarkitkaM** [comment]
Entries to split #2323
