### ISSUE TITLE
Merge "HUMANKIND™" and "HUMANKIND™ Standard Edition"

### ISSUE THREAD

**Issue by arkhovansky** [IsThereAnyDeal/IsThereAnyDeal-Issues#2210]
**1. MERGE ENTRIES**
"HUMANKIND™" (https://isthereanydeal.com/game/humankind/) and "HUMANKIND™ Standard Edition" (https://isthereanydeal.com/game/humankindstandardedition/) represent the same thing and should be merged.

**2. FIX LINKS in regions  EU1, EU2, UK**
Please note that some of the store links from https://isthereanydeal.com/game/humankind/ erroneously leads to Digital Deluxe edition.

**404 in the region EU1, EU2, UK** <- https://2game.com/en-hk/humankindtm-64455?ref=isthereanydeal&utm_source=Tapfiliate&utm_medium=referral&utm_campaign=isthereanydeal
![chrome_siZ9ZcW95w](https://user-images.githubusercontent.com/88401908/130187708-dd9c3890-c5e3-4dd7-8ac9-e32ad2ccd47a.png)

**Digital Deluxe Edition** <- https://www.humblebundle.com/store/humankind
![chrome_lwAu4FYNT7](https://user-images.githubusercontent.com/88401908/130187520-daa7f8c8-70a4-4171-9716-5dda41348fb1.png)

**Comment by MarkitkaM** [comment]
ad1) Entries to merge #2324
ad2) Moved to separates issue #2689
