### ISSUE TITLE
Merge "Pathfinder: Kingmaker - Imperial Edition Bundle" and "Pathfinder: Kingmaker - Imperial Edition"

### ISSUE THREAD

**Issue by arkhovansky** [IsThereAnyDeal/IsThereAnyDeal-Issues#2213]
Merge
Pathfinder: Kingmaker - Imperial Edition Bundle (https://isthereanydeal.com/game/pathfinderkingmakerimperialeditionbundle/)
Pathfinder: Kingmaker - Imperial Edition (https://isthereanydeal.com/game/pathfinderkingmakerimperialedition/)

**Comment by MarkitkaM** [comment]
Will be merged and represented as a bundle.

Entries to merge #2324
