### ISSUE TITLE
Represent "Pathfinder: Kingmaker - Imperial Edition" as a bundle

### ISSUE THREAD

**Issue by arkhovansky** [IsThereAnyDeal/IsThereAnyDeal-Issues#2214]
"Pathfinder: Kingmaker - Imperial Edition" is a bundle of base game and DLCs, so its page on ITAD should represent it as such (i.e. should show its contents).

Page is whichever stays after merging according to #2213:
https://isthereanydeal.com/game/pathfinderkingmakerimperialeditionbundle/
https://isthereanydeal.com/game/pathfinderkingmakerimperialedition/

**Comment by MarkitkaM** [comment]
Will be merged and represented as a bundle.

Entries to merge #2324
