### ISSUE TITLE
[Waitlist] Add stores info to "Last sale" and "Historical Low"

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#222]
***
Backstory:

I live in Russia, and until recently games were twice as cheap on Steam than anywhere else in foreign currency. Now, because of ruble cost drop, it is 4 times more expensive for me to buy almost anywhere else. Then some stores started to offer ruble prices close to Steam ones - GOG and GMG for example.

ITAD doesn't yet support RU region, which means this info is pretty useless for me right now:

Last sale: $2.99 (70% off) | 5 months ago

Historical low: $1.99 (80% off) | 11 months ago

***

What I'd like to see:

Last sale: $2.99 (70% off) | 5 months ago | GOG

Historical low: $1.99 (80% off) | 11 months ago | GMG

And I want to see only the info about stores I do not ignore.

***

There is still one specific problem: when GMG started supporting rubles, it just disabled purchase option for what feels like 80% of it's games catalog. And only about a quarter of what's left has prices like on Steam. Still, that's something. But that means when I see this:

Historical low: $1.99 (80% off) | 11 months ago | GMG

I still have to manually check if that game is available for me and if it has Steam-like price.
If it is - I set waitlist cut to 80%. If not, I need to see what was lowest on Steam or leave my default setting of 70% cut.

I know it probably can be fixed by ITAD's RU region support in some distant future, but right now it will be nice to see all other un-ignored stores listed for the same historical low. For example, in this case I set my waitlist cut to 80%:

Historical low: $1.99 (80% off) | 11 months ago | GMG | Also: Steam, Uplay, Origin.

This can be combined with lowest price tooltip on hover for any store. Then in case of this:

Historical low: $1.99 (80% off) | 11 months ago | GMG

I can hover over Steam to see its lowest, and set my cut accordingly.

***

I think it can be useful for other people from cheaper regions, who buy from specific stores and prefer % cut info over $ price.

[Issue created by enchained: 2015-06-21]

**Comment by MarkitkaM** [comment]
Russian region is now supported.
