### ISSUE TITLE
Page for The Ascent is showing some wrong games on Steam

### ISSUE THREAD

**Issue by adamnoffie** [IsThereAnyDeal/IsThereAnyDeal-Issues#2220]
**SPLIT ENTRIES:**

The deals page for "The Ascent" here:
https://isthereanydeal.com/game/ascent/info/

... has prices ruining the results from two cheap games on Steam called simply "Ascent":
https://store.steampowered.com/app/1464000/Ascent/
https://store.steampowered.com/app/1682620/Ascent/

![msedge_3iuZWrMye4](https://user-images.githubusercontent.com/88401908/131235277-aba64609-15b9-42b8-a757-8fe46ea6cd81.png)

**Comment by MarkitkaM** [comment]
Duplication of the #2202
