### ISSUE TITLE
Merge "Galactic Civilizations II: Ultimate Edition" and "Galactic Civilizations® II"

### ISSUE THREAD

**Issue by arkhovansky** [IsThereAnyDeal/IsThereAnyDeal-Issues#2222]
Merge
Galactic Civilizations II: Ultimate Edition - https://isthereanydeal.com/game/galacticcivilizationsiiultimateedition/
Galactic Civilizations® II - https://isthereanydeal.com/game/galacticcivilizationsii/ (it is Ultimate Edition too)

**Comment by MarkitkaM** [comment]
Entries to merge #2324
