### ISSUE TITLE
Sprocket page links are different games with the same name

### ISSUE THREAD

**Issue by Greybird3339** [IsThereAnyDeal/IsThereAnyDeal-Issues#2224]
The page is for a tank creation game.  The historical prices are a robot game.

https://isthereanydeal.com/game/sprocket/info/

**Comment by MarkitkaM** [comment]
![chrome_gTZaUivFBy](https://user-images.githubusercontent.com/88401908/131890174-c7d70aad-5cbc-4ab9-b1fd-d93480ae5ca5.png)

**Comment by MarkitkaM** [comment]
Entries to split #2323

**Comment by candela97** [comment]
Is this issue fixed? I'm still seeing the same thing on ITAD.
