### ISSUE TITLE
Bloodstained Iga DLC listed with AdVenture Capitalist

### ISSUE THREAD

**Issue by Blastinburn** [IsThereAnyDeal/IsThereAnyDeal-Issues#2227]
The [Iga DLC for Bloodstained](https://store.steampowered.com/app/1041460/Bloodstained_Ritual_of_the_Night__Igas_Back_Pack_DLC/) links to the ITAD page for AdVenture Capitalist instead of the correct page, as a result showing the wrong lowest price.

https://isthereanydeal.com/game/adventurecapitalist/info/

**Comment by MarkitkaM** [comment]
![chrome_oYf7k4hb85](https://user-images.githubusercontent.com/88401908/132388772-c4e71409-5ba9-49cd-8641-42f5797f2e76.png)

**Comment by MarkitkaM** [comment]
Entries to split #2323
