### ISSUE TITLE
Root showing as not on sale anywhere

### ISSUE THREAD

**Issue by bcol80** [IsThereAnyDeal/IsThereAnyDeal-Issues#2228]
The board game adaption Root is showing as not on sale on ITAD but it is on Steam at the very least. I think the problem is that there's two games called Root, the boardgame adaption Root and then some FPS called ROOT in all capital letters. The Steam page for Root is showing price tracking info from ITAD but for ROOT instead.

Root: https://isthereanydeal.com/game/root1/info/ and https://store.steampowered.com/app/965580/Root/
ROOT: https://isthereanydeal.com/game/root/info/ and https://store.steampowered.com/app/393610/ROOT/

**Comment by MarkitkaM** [comment]
Entries to split #2323
