### ISSUE TITLE
Crawl game page has wrong itch.io link

### ISSUE THREAD

**Issue by zelgaris** [IsThereAnyDeal/IsThereAnyDeal-Issues#2229]
https://isthereanydeal.com/game/crawl/info/
The 0,84 EUR itch.io link is a different game

**Comment by MarkitkaM** [comment]
![chrome_kWbR7HuU02](https://user-images.githubusercontent.com/88401908/133921635-6bebce39-f6f2-441e-9893-8755be92a6a4.png)

**Comment by MarkitkaM** [comment]
Entries to split #2323
