### ISSUE TITLE
"Columns" has wrong game on Itch.io, correct game on Steam

### ISSUE THREAD

**Issue by MakeStuffWithAI** [IsThereAnyDeal/IsThereAnyDeal-Issues#2234]
https://isthereanydeal.com/?by=price:asc#/page:game/info?plain=columns

uses the Sega Genesis / MegaDrive Collection game on Steam : https://store.steampowered.com/app/34285/

but has a different game on itch.io  https://virtuaworlds.itch.io/columns

These are not the same, they have different release dates, content, etc. They just unfortunately have the same title / name. Please break them into separate deal trackers. I personally have been trying to find a deal on Columns Genesis/MD for a long while and was frustrated when it came up as free today on itch.io

**Comment by MarkitkaM** [comment]
Entries to split #2323
