### ISSUE TITLE
Grid Cartographer - Duplicate entry

### ISSUE THREAD

**Issue by MagikGimp** [IsThereAnyDeal/IsThereAnyDeal-Issues#2238]
- [https://isthereanydeal.com/game/gridcartographer/info/](https://isthereanydeal.com/game/gridcartographer/info/) - The entry tracking prices.
- [https://isthereanydeal.com/game/gridcartographeriv/info/](https://isthereanydeal.com/game/gridcartographeriv/info/) - The duplicate, although GC is currently at version 4 so this is the full title which also appears with a Google search. Furthermore, this is the entry that is linked to from the [app's website](https://gridcartographer.com/compare/).

**Comment by MarkitkaM** [comment]
MERGE ENTRIES together.

**Comment by MagikGimp** [comment]
Yes, I assume that's what should be done. Are you saying there's a way for us users to do this? Have I posted in the wrong place?

**Comment by MarkitkaM** [comment]
Hi, I am sorry for the misunderstanding. "MERGE ENTRIES" is a message for a developer. It is gonna be fixed but it probably takes some time.
Thank you for letting us know.
We apologize for any inconvenience caused by this problem.

**Comment by MagikGimp** [comment]
No worries and thanks for letting me know.
I briefly read the recent Reddit AMA about the site's development so I'm somewhat aware of the current problems. ITAB is a fantastic site so wishing all the best with things.

**Comment by MarkitkaM** [comment]
Entries to merge #2324
