### ISSUE TITLE
"The Ascent" links to prices for both correct game and incorrect games

### ISSUE THREAD

**Issue by coined** [IsThereAnyDeal/IsThereAnyDeal-Issues#2239]
"The Ascent" (https://isthereanydeal.com/game/ascent/info/) was released in 2021 and retails for $29.99. It is being properly listed with the exception of two Steam links to other games, both called "Ascent", which retail for $3.99 and $4.99. Not a major issue but it does make it hard to include on a waitlist.

![Screen Shot 2021-09-20 at 12 51 32 PM](https://user-images.githubusercontent.com/788033/134066082-18ea5b6f-43fb-49af-b6c6-53c24a3cfcba.png)

**Comment by tfedor** [comment]
Fixed
