### ISSUE TITLE
Add "Sheltered 2" by Unicube (2021)

### ISSUE THREAD

**Issue by Korb** [IsThereAnyDeal/IsThereAnyDeal-Issues#2241]
https://store.steampowered.com/app/1289380/

**Comment by arkhovansky** [comment]
It does exist: https://isthereanydeal.com/game/shelteredii/.

**Comment by Korb** [comment]
@arkhovansky, at the time of the posting, there was no game offer on ITAD yet. The proposal can be considered fulfilled.
