### ISSUE TITLE
Merge three "Legend of Keepers"

### ISSUE THREAD

**Issue by Aerowen** [IsThereAnyDeal/IsThereAnyDeal-Issues#2242]
Game title: Legend of Keepers: Career of a Dungeon Master

Main one: https://isthereanydeal.com/game/legendofkeeperscareerofadungeonmaster/info/
Steam/Epic: https://isthereanydeal.com/game/legendofkeepers/info/
Gamesplanet: https://isthereanydeal.com/game/legendofkeeperscareerofadungeonmanager/info/

All three are the same, for some reason gameplanet has a mistake in the title (manager instead of master).

**Comment by MarkitkaM** [comment]
Entries to merge #2324
