### ISSUE TITLE
"Dyson Sphere Program" duplicate entries

### ISSUE THREAD

**Issue by a60wattfish** [IsThereAnyDeal/IsThereAnyDeal-Issues#2243]
"Dyson Sphere Program" has duplicate entries on ITAD:

https://isthereanydeal.com/game/dysonsphereprogram/info/
https://isthereanydeal.com/game/dysonsphereprogramdaisenqiujihua/info/

The wishlist sync from Steam links to the second entry, however ITAD only has the price on the first entry. Wishlist entry is for https://store.steampowered.com/app/1366540/Dyson_Sphere_Program/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
