### ISSUE TITLE
"Billion Road" has duplicate entries

### ISSUE THREAD

**Issue by a60wattfish** [IsThereAnyDeal/IsThereAnyDeal-Issues#2244]
"Billion Road" has duplicate entries on ITAD:

https://isthereanydeal.com/game/billionroad/info/
https://isthereanydeal.com/game/billionroadyiwanfuwengzhilu/info/

The wishlist sync from Steam links to the second entry, however ITAD only has the price on the first entry. Wishlist entry is for https://store.steampowered.com/app/1163040/Billion_Road/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
