### ISSUE TITLE
"STAR OCEAN - THE LAST HOPE" duplicate entries

### ISSUE THREAD

**Issue by a60wattfish** [IsThereAnyDeal/IsThereAnyDeal-Issues#2245]
"STAR OCEAN™ - THE LAST HOPE -™ 4K & Full HD Remaster" has duplicate entries on ITAD:

https://isthereanydeal.com/game/staroceanlasthopeivkfullhdremaster/info/
https://isthereanydeal.com/game/staroceanlasthopeivkandfullhdremaster/info/

The wishlist sync from Steam links to the second entry, however ITAD only has the price on the first entry. Wishlist entry is for https://store.steampowered.com/app/609150/STAR_OCEAN__THE_LAST_HOPE__4K__Full_HD_Remaster/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
