### ISSUE TITLE
"ToeJam & Earl: Back in the Groove!" duplicate entries

### ISSUE THREAD

**Issue by a60wattfish** [IsThereAnyDeal/IsThereAnyDeal-Issues#2247]
"ToeJam & Earl: Back in the Groove!" has duplicate entries on ITAD:

https://isthereanydeal.com/game/toejamearlbackingroove/info/
https://isthereanydeal.com/game/toejamandearlbackingroove/info/

The wishlist sync from Steam links to the second entry, however ITAD only has the price on the first entry. Wishlist entry is for https://store.steampowered.com/app/516110/ToeJam__Earl_Back_in_the_Groove/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
