### ISSUE TITLE
"Pid" page has Steam link to different game with similar title

### ISSUE THREAD

**Issue by GatesDA** [IsThereAnyDeal/IsThereAnyDeal-Issues#2252]
The image and most of the links on https://isthereanydeal.com/game/pid/info/ are for the version by Might and Delight.  While it does have the [proper Steam link](https://store.steampowered.com/app/218740/) listed it also has a [second Steam link](https://store.steampowered.com/app/1388260/) that goes to "P.I.D." published by AMDI Studios.

**Comment by MarkitkaM** [comment]
Entries to split #2323
