### ISSUE TITLE
Add "Final Fantasy IV (3D Remake)" game

### ISSUE THREAD

**Issue by Korb** [IsThereAnyDeal/IsThereAnyDeal-Issues#2256]
https://store.steampowered.com/app/312750
![Screenshot 2021-10-03 at 22-02-30 Search Results for final fantasy iv 3d remake ](https://user-images.githubusercontent.com/3509797/135767808-1c4e0ef2-c6f6-4837-8b9c-a6492c97a382.png)
/

**Comment by MarkitkaM** [comment]
The game is here https://isthereanydeal.com/game/finalfantasyiv/info/ so it needs to be split Entries to split #2323.
