### ISSUE TITLE
Back 4 Blood on Steam linking to Leylines on IsThereAnyDeal

### ISSUE THREAD

**Issue by Neighthanael** [IsThereAnyDeal/IsThereAnyDeal-Issues#2258]
Steam site:
https://store.steampowered.com/app/924970/Back_4_Blood/

Extention is showing prices and linking to:
https://isthereanydeal.com/game/leylines/info/

Expected:
https://isthereanydeal.com/game/backivblood/info/

Additionally Back 4 Blood on IsThereAnyDeal does not show any price tracking for Steam
https://isthereanydeal.com/game/backivblood/info/

**Comment by Neighthanael** [comment]
Back 4 Blood Deluxe and Back 4 Blood Ultimate appear to be working correctly for steam, although there are no prices shown for any other sites for those versions of the game.

(https://isthereanydeal.com/game/backivblooddeluxe/info/ and https://isthereanydeal.com/game/backivbloodultimate/info/)

**Comment by MarkitkaM** [comment]
Entries to split #2323
