### ISSUE TITLE
Split entries - "Stubbs the Zombie in Rebel Without a Pulse"

### ISSUE THREAD

**Issue by HYBRID-BEING** [IsThereAnyDeal/IsThereAnyDeal-Issues#2260]
https://isthereanydeal.com/game/stubbszombieinrebelwithoutapulse/info/
https://isthereanydeal.com/game/stubbszombie/info/
https://isthereanydeal.com/game/stubbszombieinrebelwithoutapulsegog/info/

Strangely enough, first page was added to my waitlist via Steam wishlist, but Steam is now linked to the second page. Does that mean Steam link was split into the second page at some point after i wishlisted it (i think it's not the first time i notice that)?

**Comment by MarkitkaM** [comment]
Entries to merge #2324
