### ISSUE TITLE
Split entries - "Balloon Azuna"

### ISSUE THREAD

**Issue by HYBRID-BEING** [IsThereAnyDeal/IsThereAnyDeal-Issues#2261]
I'm not sure what's with the first link but i can't find it on ITAD via search (it came up in Similar Games). 9 people waiting for it aside pretty much a dead entry.
https://isthereanydeal.com/game/balloonazunaballoonazuna/info/
https://isthereanydeal.com/game/balloonazuna/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
