### ISSUE TITLE
Alpha - Search for Cyberpunk returns no results

### ISSUE THREAD

**Issue by jpjonte** [IsThereAnyDeal/IsThereAnyDeal-Issues#2266]
Searching for Cyberpunk on the Alpha site returns 0 results:
https://new.isthereanydeal.com/search/?q=cyberpunk

But the listing itself is present:
https://new.isthereanydeal.com/game/cyberpunkii0viivii/info/

Search works fine on the normal site:
https://isthereanydeal.com/search/?q=cyberpunk

**Comment by mhoogcarspel** [comment]
Seems like search is broken for a few days on alpha in general, getting very little results 

https://isthereanydeal.com/search/?q=splinter
https://new.isthereanydeal.com/search/?q=splinter

https://isthereanydeal.com/search/?q=civilization
https://new.isthereanydeal.com/search/?q=civilization

**Comment by BrendanatorX** [comment]
Also been getting no search results for many things, a few examples are:
Pillars of Eternity
Pathfinder
Mortal Shell
New World (lists Tortuga: pirates of the new world, but not amazon's new flagship game)
Half Dead
Original Sin
Honestly the list goes on, most searches result in a page saying: There were no games found for "xyz searched game here"
