### ISSUE TITLE
Steam listing for Train Life sim absorbed by Sketchfab VR

### ISSUE THREAD

**Issue by dgw** [IsThereAnyDeal/IsThereAnyDeal-Issues#2267]
https://isthereanydeal.com/game/sketchfabvr/info/ lists two Steam prices, one (correct) for [appid 464940](https://store.steampowered.com/app/464940/) and one (incorrect) for [appid 1330660](https://store.steampowered.com/app/1330660/)—this is a different game, [Train Life - A Railway Simulator](https://isthereanydeal.com/game/trainlifearailwaysimulator/info/).

Bonus issue: Train Life is listed separately, [without the subtitle](https://isthereanydeal.com/game/trainlife/info/), with only Epic as a seller.

**Comment by MarkitkaM** [comment]
Entries to split #2323
