### ISSUE TITLE
"OneShot" game page — wrong Steam link

### ISSUE THREAD

**Issue by valdean** [IsThereAnyDeal/IsThereAnyDeal-Issues#2270]
Today [this game](https://store.steampowered.com/app/1221330/One_Shot/) (1221330) went on sale and IsThereAnyDeal sent an email notification about it. However, [this game](https://store.steampowered.com/app/420530/OneShot/) (420530) is the right OneShot, and it's not on sale.

How to fix:
• Remove Steam ID 1221330 from [this page](https://isthereanydeal.com/game/oneshot/info/). 
• Add Steam ID 1221330 to [this page](https://isthereanydeal.com/game/one-shot/info/).

<img width="971" alt="OneShot_-_Info_-_IsThereAnyDeal_🔊" src="https://user-images.githubusercontent.com/611993/137794011-e2dc33ef-7780-40d3-81b8-eb6feac39bc3.png">

**Comment by MarkitkaM** [comment]
Thank you for letting us know. This issue was already reported at #2171.
