### ISSUE TITLE
Identical store links - "Beholder - Blissful Sleep"

### ISSUE THREAD

**Issue by HYBRID-BEING** [IsThereAnyDeal/IsThereAnyDeal-Issues#2272]
https://isthereanydeal.com/game/beholderblissfulsleep/info/ lists two identical Steam store links (at least in RU region, if that matters).
Also, there are two Gamebillet links, though one of them activates in RU region, other - doesn't. Not sure if both links should be listed in such a case.

**Comment by MarkitkaM** [comment]
https://store.steampowered.com/agecheck/app/616950/
![image](https://user-images.githubusercontent.com/88401908/138608099-554ea6ab-118b-48f7-8e9f-9878690c0d4a.png)

**Comment by HYBRID-BEING** [comment]
Well, seems to be fixed now.
