### ISSUE TITLE
BeamNG.drive does not appear in search

### ISSUE THREAD

**Issue by BrooksAz** [IsThereAnyDeal/IsThereAnyDeal-Issues#2273]
Even with exact spelling it doesn't show up, have to manually enter URL.

**Comment by MarkitkaM** [comment]
Hi, you can try to search by filters in Deals section:
![image](https://user-images.githubusercontent.com/88401908/138607989-3b78e8a6-83aa-48a7-8a16-824f2e9e8ae9.png)
