### ISSUE TITLE
Castlevania Advance Collection - Duplicate entry

### ISSUE THREAD

**Issue by MagikGimp** [IsThereAnyDeal/IsThereAnyDeal-Issues#2274]
1. [Castlevania Advance Collection/悪魔城ドラキュラ Advance Collection](https://isthereanydeal.com/game/castlevaniaadvancecollectionemochengdorakyuraadvancecollection/info/) (Steam only)
2. [Castlevania Advance Collection](https://isthereanydeal.com/game/castlevaniaadvancecollection/info/) (All other stores)

**Comment by MarkitkaM** [comment]
Entries to merge #2324
