### ISSUE TITLE
JoyBuggy wrong redirect

### ISSUE THREAD

**Issue by Korb** [IsThereAnyDeal/IsThereAnyDeal-Issues#2286]
https://isthereanydeal.com/game/mightandmagicheroesviifullpack/info/ -> https://jf79.net/c/?si=16135&li=1693291&wi=349740&ws=&dl=

> Error 1020 Ray ID: 6a5436930af61604 • 2021-10-28 12:37:02 UTC
> Access denied
> What happened?
> This website is using a security service to protect itself from online attacks.
> Cloudflare Ray ID: 6a5436930af61604 • Your IP: 178.236.131.4 • Performance & security by Cloudflare

![Screenshot 2021-10-28 at 15-36-08 Might Magic® Heroes® VII Full Pack - Info](https://user-images.githubusercontent.com/3509797/139256343-9074e417-35bf-4eef-9d4a-8403b761042c.png)

![2021-10-28_15-37-54](https://user-images.githubusercontent.com/3509797/139256660-028d45b1-ad2a-4259-8e80-5152e2a49b7a.png)

**Comment by arkhovansky** [comment]
The same for https://isthereanydeal.com/game/crusaderkingsiii/.

The Cloudflare error is due to Russian IP, I believe.

But the redirect is wrong anyway - it leads to main page.

Also there is no chance these products cost zero (as ITAD shows).
