### ISSUE TITLE
morningstar points to the wrong game on steam

### ISSUE THREAD

**Issue by matthewdias** [IsThereAnyDeal/IsThereAnyDeal-Issues#2288]
https://isthereanydeal.com/game/morningstar/info/#/

**Comment by MarkitkaM** [comment]
Actual incorrect link https://store.steampowered.com/app/339130/Morningstar_Descent_to_Deadrock/
Correct link https://store.steampowered.com/app/878690/Morning_Star/

**Comment by MarkitkaM** [comment]
Entries to split #2323
