### ISSUE TITLE
Add "UNDER the WATER - an ocean survival game" (IndieMax, 2021)

### ISSUE THREAD

**Issue by Korb** [IsThereAnyDeal/IsThereAnyDeal-Issues#2289]
![Screenshot 2021-10-30 at 16-14-50 Search Results for under the water ](https://user-images.githubusercontent.com/3509797/139534198-f5a38892-a967-4c7f-9fb8-afe436d60db9.png)
https://store.steampowered.com/app/1745380

**Comment by HYBRID-BEING** [comment]
The entry is there, but for some reason it doesn't come up in search. Also, name is doubled.
https://isthereanydeal.com/game/underwaterunderwater/info/
