### ISSUE TITLE
UNDEFINED and {Undefined} are different games listed together

### ISSUE THREAD

**Issue by veebles** [IsThereAnyDeal/IsThereAnyDeal-Issues#2291]
{Undefined} needs a separate listing https://store.steampowered.com/app/1548130/Undefined/

**Comment by MarkitkaM** [comment]
https://isthereanydeal.com/game/undefined/info/
![image](https://user-images.githubusercontent.com/88401908/140620539-80ed010d-523a-42a6-bd64-ecc16462cdcf.png)

**Comment by MarkitkaM** [comment]
Entries to split #2323
