### ISSUE TITLE
dotAGE (upcoming indie game) confused with AGE (adventure game creation software)

### ISSUE THREAD

**Issue by j4nw** [IsThereAnyDeal/IsThereAnyDeal-Issues#2294]
Hey, I added this upcoming Steam game to my wishlist:

https://store.steampowered.com/app/638510/dotAGE/

And now I have an entry called ".Age" on top of my ITAD waitlist listed at $0, using dotAGE's capsule art, but linking to this:

https://store.steampowered.com/app/848340/AGE/

**Comment by MarkitkaM** [comment]
Entries to split #2323
