### ISSUE TITLE
Rename "Siege of Dragonspear Enhanced Edition Official Soundtrack"

### ISSUE THREAD

**Issue by Korb** [IsThereAnyDeal/IsThereAnyDeal-Issues#2295]
... to "Baldur's Gate: Siege of Dragonspear Enhanced Edition Official Soundtrack".

https://isthereanydeal.com/game/siegeofdragonspearenhancededitionofficialsoundtrack/info/
https://www.gog.com/game/siege_of_dragonspear_enhanced_edition_official_soundtrack

or merge with https://isthereanydeal.com/game/baldursgatesiegeofdragonspeardigitalsoundtrack/info/ and https://isthereanydeal.com/game/baldursgatesiegeofdragonspearofficialsoundtrack/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
