### ISSUE TITLE
Final Fantasy® Xiv Online Complete Edition On Sale

### ISSUE THREAD

**Issue by Snuggerdog** [IsThereAnyDeal/IsThereAnyDeal-Issues#2296]
The subject game title us on sale on the Square Enix website, but is reflected in its corresponding isthereanydeal page.

**Comment by MarkitkaM** [comment]
**$23.99** https://store.na.square-enix-games.com/en_US/product/564956/final-fantasy-xiv-online-complete-edition-pc-download
**$59.99** https://isthereanydeal.com/game/finalfantasyxivonlinecompleteedition/info/

----
Additional bug:

**MERGE ENTRIES TOGETHER**
https://isthereanydeal.com/game/finalfantasyxivonlinecompleteeditionna/info/
https://isthereanydeal.com/game/finalfantasyxivonlinecompleteedition/info/

https://isthereanydeal.com/search/?q=Final+Fantasy%C2%AE+Xiv+Online+Complete+Edition

**Comment by MarkitkaM** [comment]
Entries to split #2323

Multiplied Steam deadlinks #2672

+ The original price bug is not valid anymore -> 404 https://store.na.square-enix-games.com/en_US/product/564956/final-fantasy-xiv-online-complete-edition-pc-download
