### ISSUE TITLE
Split entries - "Graveyard Keeper - Better Save Soul"

### ISSUE THREAD

**Issue by HYBRID-BEING** [IsThereAnyDeal/IsThereAnyDeal-Issues#2297]
https://isthereanydeal.com/game/graveyardkeeperbettersavesoulgraveyardkeeperbettersavesoul/info/
https://isthereanydeal.com/game/graveyardkeeperbettersavesoul/info/
Throwing guesses at the wall here, but maybe it has something to do with Steam page (first link has no stores, but it has image from Steam) being up for long before it was finally released.

**Comment by MarkitkaM** [comment]
Entries to merge #2324
