### ISSUE TITLE
Different games named 'Last Stop' mixed together

### ISSUE THREAD

**Issue by C4nnyKumqu4t** [IsThereAnyDeal/IsThereAnyDeal-Issues#2302]
https://isthereanydeal.com/game/laststop/info/ 
![LastStop](https://user-images.githubusercontent.com/93869581/140648049-0ac4bb9d-2457-4401-b708-94ce06d824a0.png)
The game on itch.io is not the same as the other two - hence the price difference

**Comment by MarkitkaM** [comment]
Entries to split #2323
