### ISSUE TITLE
Grand Theft Auto V: Premium Edition - Wrong Current Price

### ISSUE THREAD

**Issue by hwalker928** [IsThereAnyDeal/IsThereAnyDeal-Issues#2303]
The Steam price is incorrect, as seen below.
![image](https://user-images.githubusercontent.com/63236817/140964553-7cf8f13a-a65e-4978-b00a-0fc02272ac6d.png)

**Comment by MarkitkaM** [comment]
£12.58 https://isthereanydeal.com/game/grandtheftautovpremiumonlineedition/info/?country=GB
