### ISSUE TITLE
Merged games Savior and The Savior

### ISSUE THREAD

**Issue by therksius** [IsThereAnyDeal/IsThereAnyDeal-Issues#2320]
Unreleased game on Steam (on my wishlist) **Savior**:
https://store.steampowered.com/app/1093810/Savior/

Game on Itch.io, **The Savior**:
https://ammashdev.itch.io/the-savior

Thumbnail is from Steam game **Savior**, Itch.io link is to **The Savior**.
 @https://isthereanydeal.com/game/savior/info/

![image](https://user-images.githubusercontent.com/52346746/141345049-ee58bd27-8ad4-48c2-b661-fe3bdfcfd143.png)

**Comment by MarkitkaM** [comment]
Entries to split #2323
