### ISSUE TITLE
Merge "The Elder Scrolls V: Skyrim Anniversary Edition Upgrade" and "The Elder Scrolls V: Skyrim Anniversary Upgrade" DLCs

### ISSUE THREAD

**Issue by Korb** [IsThereAnyDeal/IsThereAnyDeal-Issues#2326]
https://isthereanydeal.com/game/elderscrollsvskyrimanniversaryeditionupgrade/info/
https://isthereanydeal.com/game/elderscrollsvskyrimanniversaryupgrade/info/
![Screenshot 2021-11-15 at 23-31-56 Search Results for the elder scrolls skyrim anniversary upgrade ](https://user-images.githubusercontent.com/3509797/141849747-b5f8fd1e-e433-4751-814c-686c70475ab9.png)

**Comment by MarkitkaM** [comment]
Entries to merge #2324
