### ISSUE TITLE
Rename "Dragon Age: Inquisition" to "Dragon Age: Inquisition -Standard Edition"

### ISSUE THREAD

**Issue by Korb** [IsThereAnyDeal/IsThereAnyDeal-Issues#2333]
...and merge with https://isthereanydeal.com/waitlist/?by=price:asc#/page:game/info?plain=dragonageinquisitionstandardeditionpc

https://isthereanydeal.com/waitlist/?by=price:asc#/page:game/info?plain=dragonageinquisition
![Screenshot 2021-11-19 at 21-41-00 Waitlist](https://user-images.githubusercontent.com/3509797/142674706-a2d0f432-5beb-4c54-b18e-2e93ab5a02b0.png)

https://www.origin.com/rus/en-us/store/dragon-age/dragon-age-inquisition/interstitial
![Screenshot 2021-11-19 at 21-39-48 Origin](https://user-images.githubusercontent.com/3509797/142674583-3ffdcbde-64a4-4386-b0a6-0eb5191b17c9.png)

**Comment by MarkitkaM** [comment]
Moved to "Entries to merge #2324" (also with the renaming of the game)
