### ISSUE TITLE
Wishlist games not showing up in wishlist search results

### ISSUE THREAD

**Issue by Korb** [IsThereAnyDeal/IsThereAnyDeal-Issues#2334]
![Screenshot 2021-11-19 at 22-02-14 Waitlist](https://user-images.githubusercontent.com/3509797/142677303-e11fa760-60ab-4caf-8c81-6c19edb31939.png)

https://isthereanydeal.com/waitlist/#/filter:&search/warhammer%20mechanicus
![Screenshot 2021-11-19 at 22-02-57 Waitlist](https://user-images.githubusercontent.com/3509797/142677761-2d40d586-e1a2-4b97-b177-b997f0c957f4.png)

Mozilla Firefox 95.0b8 (64-bit)

**Comment by arkhovansky** [comment]
@Korb
"Filter by title" treats entered text as single string (i.e. does not divide it into separate terms).
You can achieve your goal by using regular expression: "!warhammer.+mechanicus". This feature is described [here](https://isthereanydeal.com/about/filters/master/).

**Comment by Korb** [comment]
> You can achieve your goal by using regular expression: "`!warhammer.+mechanicus`".

Thanks! Indeed, a request in this form works as I need it to. But the syntax is quite complex and not intuitive. I hope that all alternative options for forming the query "all search words in any order" were discussed, and were rejected as even more difficult to use.

**Comment by arkhovansky** [comment]
I'm not a dev, so I only describe current state.
Maybe it's ok to request that feature with search semantics too. But then one would have to deal with two similar fields having different behavior.

In any case, I think it's better to leave this issue open because the problem is present - the semantics of subject field is indeed unclear.

**Comment by Korb** [comment]
> I think it's better to leave this issue open because the problem is present - the semantics of subject field is indeed unclear.

@tfedor, @MarkitkaM, what is your opinion on this matter?

**Comment by Korb** [comment]
https://isthereanydeal.com/waitlist/
![Screenshot 2021-11-24 at 23-18-25 Waitlist](https://user-images.githubusercontent.com/3509797/143307832-3b56493e-3d39-4d63-a5e4-228a218450df.png)

Search `dragon age inquisition`
![Screenshot 2021-11-24 at 23-18-54 Waitlist](https://user-images.githubusercontent.com/3509797/143307850-0bbc103f-98c3-43fd-a4bd-bb9c4907d88a.png)

This is absolutely abnormal behavior, and something needs to be done about it.
