### ISSUE TITLE
Filter for the waitlist — "current discount of at least (...) percent" (the value is entered manually)

### ISSUE THREAD

**Issue by Korb** [IsThereAnyDeal/IsThereAnyDeal-Issues#2338]
Currently, I have to choose whether to sort games by current price or discount amount? If I add a filter to hide all games that have less than a specified percentage of the current discount, then when I sort the list of games on my wishlist by price, it’s easier for me to choose what to buy.

**Comment by arkhovansky** [comment]
@Korb You can do that, though not on the Waitlist tab, but on the main page (Deals tab).
Example: https://isthereanydeal.com/?by=price:asc#/filter:&wait,&cut/60/100

**Comment by Korb** [comment]
> You can do that, though not on the Waitlist tab, but on the main page (Deals tab).

And again you help me out with valuable advice! However, in this case, I don't understand why one of the waitlist processing functions should be moved outside the waitlist screen? In addition, the list displayed with such a processing does not show which discount I am counting on (notification threshold for each lot).

**Comment by arkhovansky** [comment]
I agree, it would be good to have all filters in the waitlist too.
