### ISSUE TITLE
Different games named "Cookie Clicker" under the same ITAD entry

### ISSUE THREAD

**Issue by staticvariablejames** [IsThereAnyDeal/IsThereAnyDeal-Issues#2342]
The entry <https://isthereanydeal.com/game/cookieclicker/info/> links to <https://store.steampowered.com/app/1454400/Cookie_Clicker/> and <https://the-silent-house-studio.itch.io/cookie-clicker>, but these are two different, unrelated games.

**Comment by MarkitkaM** [comment]
Entries to split #2323
