### ISSUE TITLE
Merge and fix store prices, for 3 Gold Editions of Ubisoft games

### ISSUE THREAD

**Issue by Siegfriedmk** [IsThereAnyDeal/IsThereAnyDeal-Issues#2344]
Hello, I just would like to report this little issue.
Watch Dogs Legion Gold Edition has 2 different entries:
https://isthereanydeal.com/game/watchdogslegiongold/info/
https://isthereanydeal.com/game/watchdogslegiongoldedition/info/
And both of them, are missing the price from Ubisoft Store.

Assassin's Creed Odyssey Gold Edition, has 2 different entries, and still, both of them **lack the price of Ubisoft Store**
https://isthereanydeal.com/game/assassinscreedodysseygold/info/
https://isthereanydeal.com/game/assassinscreedodysseygoldedition/info/
*Oddly, ITAD seems to not find the game if you only search for "Odyssey"

Immortal Fenyx Rising - Gold Edition has 3 different entries 
https://isthereanydeal.com/game/immortalsfenyxrisinggold/info/
https://isthereanydeal.com/game/immortalsfenyxrisingimmortalsfenyxrisinggoldedition/info/
https://isthereanydeal.com/game/immortalsfenyxrisinggoldedition/info/
The 3rd entry, seems to show "ubisoft store" as lowest price ever, but also seems to not track it anymore.

**Comment by MarkitkaM** [comment]
All entries moved into the google document for merging entries via "Entries to merge #2324". We will process them all together.

> *Oddly, ITAD seems to not find the game if you only search for "Odyssey"

Possible to find in the Deals sections https://isthereanydeal.com/game/assassinscreedodysseygoldedition/info/
![image](https://user-images.githubusercontent.com/88401908/143731432-4f759e24-e1dc-4142-9c37-ad512eed64e8.png)
![image](https://user-images.githubusercontent.com/88401908/143731446-f7648a7f-bcbf-4a35-9d35-ee1a108e0399.png)

**Comment by MarkitkaM** [comment]
> https://isthereanydeal.com/game/watchdogslegiongold/info/
> https://isthereanydeal.com/game/watchdogslegiongoldedition/info/
> And both of them, are missing the price from Ubisoft Store.

Moved to separated issue #2355

> https://isthereanydeal.com/game/immortalsfenyxrisinggoldedition/info/
> The 3rd entry, seems to show "ubisoft store" as lowest price ever, but also seems to not track it anymore.

Moved to separated issue #2354

This issue is going to be closed.
