### ISSUE TITLE
track.adtraction.com — "Server Not Found"

### ISSUE THREAD

**Issue by Korb** [IsThereAnyDeal/IsThereAnyDeal-Issues#2349]
https://isthereanydeal.com/game/mortalkombativ/info/ -> https://track.adtraction.com/t/t?a=1578845458&as=1605593256&t=2&tk=1&url=http%3A%2F%2Fwww.gog.com%2Fgame%2Fmortal_kombat_4

Mozilla Firefox 95.0b12 (64-bit):

> Hmm. We’re having trouble finding that site.
> We can’t connect to the server at track.adtraction.com.
> If that address is correct, here are three other things you can try:
> Try again later.
> Check your network connection.
> If you are connected but behind a firewall, check that Firefox has permission to access the Web.

Google Chrome 92.0.4515.131 (Official Build) (64-bit):

> This site can’t be reached
> Check if there is a typo in track.adtraction.com.
> If spelling is correct, try running Windows Network Diagnostics.
> DNS_PROBE_FINISHED_NXDOMAIN

Microsoft Edge 96.0.1054.34 (Официальная сборка) (64-разрядная версия)

> Не удается открыть эту страницу
> Проверьте, нет ли опечатки в track.adtraction.com.
> Если ошибок нет, попробуйте запустить диагностику сетей Windows.
> DNS_PROBE_FINISHED_NXDOMAIN

**Comment by MarkitkaM** [comment]
Reproduced just once for RU region https://isthereanydeal.com/game/mortalkombativ/info/?country=RU

Now it seems to be alright. 

@Korb Could you try it again please?

**Comment by Korb** [comment]
> @Korb Could you try it again please?

I tried resetting browser caches - no change. Also, cleared the local DNS cache (`ipconfig /flushdns`). The errors I quoted above are still displayed.
