### ISSUE TITLE
Can you add deals from Retroism.com? They offer bundle deals as well as lowest price deal

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#235]
Retroism.com Independence Day Deal link: [http://retroism.com/july-4th-sale/](http://retroism.com/july-4th-sale/)

[Issue created by [deleted]: 2015-07-02]
[Last updated on bitbucket: 2015-07-07]

[Comment created by tfedor: 2015-07-07]
For some reason that page doesn't load for me, so I can't say whether it will be added or not at this point.

**Comment by MarkitkaM** [comment]
Related to #338
