### ISSUE TITLE
"Mortal Kombat 1 + 2 + 3" is not displayed when prompted for "mortal kombat"

### ISSUE THREAD

**Issue by Korb** [IsThereAnyDeal/IsThereAnyDeal-Issues#2350]
https://isthereanydeal.com/search/?q=mortal+kombat
![Screenshot 2021-11-27 at 20-55-36 Search Results for mortal kombat ](https://user-images.githubusercontent.com/3509797/143691791-7c01b4ce-7bc0-4f20-8499-f0dac847dfe0.png)

https://isthereanydeal.com/game/mortalkombatiplusiiplusiii/info/#/
![Screenshot 2021-11-27 at 20-56-07 Mortal Kombat 1+2+3 - Info](https://user-images.githubusercontent.com/3509797/143691770-49c3c39b-d89c-44a4-b31d-d0673122b3c4.png)

**Comment by arkhovansky** [comment]
This is a manifestation of #2223.

**Comment by MarkitkaM** [comment]
The same at the alpha web https://new.isthereanydeal.com/search/?q=mortal%20kombat

**Comment by arkhovansky** [comment]
I want to stress again that this is not a separate bug, but a particular case of the general bug #2223.
