### ISSUE TITLE
IsThereAnyDeal isn't showing a sale and isn't notifying me of a sale for The Forest.

### ISSUE THREAD

**Issue by gaveitatry2** [IsThereAnyDeal/IsThereAnyDeal-Issues#2351]
I signed up for IsThereAnyDeal some months ago because I wanted to buy The Forest when there was a 50% (or more) sale and the game was less than or equal to $10.  I believed that the website would notify me of the sale, since it is on my WaitList.  But today, I found out that The Forest is on sale on Steam for $7.99, and I haven't been notified.  When I go to my WaitList on IsThereAnyDeal, the game says "did not pass your settings".

I don't get it.  My notification settings are "price below or equals $10,00", "activates on Steam", "is sold on one of 38 stores (including Steam)".

When I look at the Price and Price History for The Forest on IsThereAnyDeal, it says that the last sale was February 2021.  But that's not true.  There is a sale right now in November 2021.

So I'm wondering why I created a IsThereAnyDeal account in the first place when it isn't doing what I want.  What's the point of it if it isn't aware of ongoing sales and won't notify me of them?

**Comment by arkhovansky** [comment]
This is because there are two entries for The Forest on ITAD. Steam's game ID is linked to https://isthereanydeal.com/game/theforest/info/, but this entry itself does not track Steam. The other one does: https://isthereanydeal.com/game/forest/info/.

This is a bug and it is already in the "Entries to merge" list.

**Comment by MarkitkaM** [comment]
@arkhovansky Thanks for the note.

It will be processed within the issue "Entries to merge #2324".

This issue is gonna be closed.
