### ISSUE TITLE
Two different games in OneShot

### ISSUE THREAD

**Issue by juhavt** [IsThereAnyDeal/IsThereAnyDeal-Issues#2353]
[OneShot](https://isthereanydeal.com/game/oneshot/info/) page refers to two different games in Steam:

- [OneShot](https://store.steampowered.com/app/420530/OneShot/)
- [One Shot](https://store.steampowered.com/app/1221330/One_Shot/)

**Comment by MarkitkaM** [comment]
Duplication of the #2171

Entries to split #2323
