### ISSUE TITLE
Clicking on a voucher drops 404 dialog

### ISSUE THREAD

**Issue by wzol** [IsThereAnyDeal/IsThereAnyDeal-Issues#2374]
![111](https://user-images.githubusercontent.com/11561358/144296038-be6c61ee-b38b-4c24-a54d-fa06d0f8f122.jpg)
![222](https://user-images.githubusercontent.com/11561358/144296045-6508357b-e9dd-4fb6-88dd-8016cb6ace28.jpg)

**Comment by MarkitkaM** [comment]
TEST OK.
