### ISSUE TITLE
Football Manager 2012 page links to 2021

### ISSUE THREAD

**Issue by cjgeist** [IsThereAnyDeal/IsThereAnyDeal-Issues#2375]
https://isthereanydeal.com/game/footballmanagerii0iii/info/
All the store links (except Newegg, which seems to be a broken link) are for Football Manager 2021. These store links are missing from the correct page here:
https://isthereanydeal.com/game/footballmanager2021/info/

**Comment by MarkitkaM** [comment]
Can't see Newegg anymore.

Entries to split #2323
