### ISSUE TITLE
Space Pirates and Zombies - Duplicate entry

### ISSUE THREAD

**Issue by MagikGimp** [IsThereAnyDeal/IsThereAnyDeal-Issues#2380]
[https://isthereanydeal.com/game/spacepiratesandzombies/info/](https://isthereanydeal.com/game/spacepiratesandzombies/info/) - GOG, Fanatical. _Steam, Metacritic, Metascore reviews._
[https://isthereanydeal.com/game/spacepiratesandzombiesspaz/info/](https://isthereanydeal.com/game/spacepiratesandzombiesspaz/info/) - Steam, Humble Store. _Steam reviews._

**Comment by MarkitkaM** [comment]
Duplicated #1022
