### ISSUE TITLE
Wrong entry on OneShot price list

### ISSUE THREAD

**Issue by 4drian** [IsThereAnyDeal/IsThereAnyDeal-Issues#2385]
[OneShot](https://isthereanydeal.com/game/oneshot/info/#/) price list has 2 steam entries, one of them redirecting to the wrong game: https://store.steampowered.com/app/1221330/ as opposed to the correct one https://store.steampowered.com/app/420530/

**Comment by MarkitkaM** [comment]
Duplicated #2171
