### ISSUE TITLE
Wolfpack best price entry error

### ISSUE THREAD

**Issue by Langolyers** [IsThereAnyDeal/IsThereAnyDeal-Issues#2386]
Best price for Wolfpack (https://store.steampowered.com/app/490920/Wolfpack/) shows current best price is for this entry, Wolf Pack: https://store.steampowered.com/sub/418/.

**Comment by MarkitkaM** [comment]
https://isthereanydeal.com/game/wolfpack/info/
https://isthereanydeal.com/game/wolfpack1/info/

-> Entries to split #2323
