### ISSUE TITLE
Merge entries: WorldBox - God Simulator

### ISSUE THREAD

**Issue by arkhovansky** [IsThereAnyDeal/IsThereAnyDeal-Issues#2397]
https://store.steampowered.com/app/1206560/WorldBox__God_Simulator/ links to https://isthereanydeal.com/game/worldboxgodsimulator (via Augmented Steam), which tracks no stores.
https://isthereanydeal.com/game/superworldbox does track stores.

**Comment by MarkitkaM** [comment]
Entries to merge #2324
