### ISSUE TITLE
F.E.A.R. redirects to the wrong game on the current lowest price (Dec. 17th 2021)

### ISSUE THREAD

**Issue by u2020bullet** [IsThereAnyDeal/IsThereAnyDeal-Issues#2431]
ITAD Link: https://isthereanydeal.com/game/fear/info/

Current lowest price redirects to https://store.steampowered.com/app/1673140/FEAR_background/ which has nothing to do with the actual game the ITAD page is showcasing.

**Comment by MarkitkaM** [comment]
Entries to split #2323

**Comment by gbakeman** [comment]
Just want to report that this is still a problem for the Steam association. Right now, it seems to point to some kind of fan made game. I'm not sure F.E.A.R is even for sale anymore.
