### ISSUE TITLE
Typos in the Waitlist page

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#246]
http://isthereanydeal.com//waitlist/

The sentence "You may think about Waitlist as better wishlist." is missing an "a" before the word "better."

The sentence "You can say you want to be notified only about better price than the last one was." is also missing an "a" before the word "better."

[Issue created by karasuhebi: 2015-07-17]
[Last updated on bitbucket: 2015-11-18]

[Comment created by karasuhebi: 2015-11-18]
Sounds good. Thanks for the update! :)

[Comment created by tfedor: 2015-11-18]
It's not critical issue so I'll fix that when I'll be doing something around Waitlists.

[Comment created by karasuhebi: 2015-11-18]
Any news on this?

**Comment by MarkitkaM** [comment]
duplication of the #869
