### ISSUE TITLE
Cookie Clicker connected with itch game with the same name

### ISSUE THREAD

**Issue by eduardog3000** [IsThereAnyDeal/IsThereAnyDeal-Issues#2460]
[Cookie Clicker](https://isthereanydeal.com/game/cookieclicker/info/) is listed as being on two storefronts, [Steam](https://store.steampowered.com/app/1454400/Cookie_Clicker/) and [itch.io](https://the-silent-house-studio.itch.io/cookie-clicker). As you can see they are different games and the latter is a lower quality clone.

**Comment by MarkitkaM** [comment]
Duplication #2342
