### ISSUE TITLE
Duplicate title listing

### ISSUE THREAD

**Issue by Phaltan** [IsThereAnyDeal/IsThereAnyDeal-Issues#2462]
Listing is duplicated and does not show any pricing: 
Sword of the Stars: The Pit 2 Sword of the Stars: The Pit 2

**Comment by MarkitkaM** [comment]
@Phaltan
Thank you for your feedback and we apologize for the inconvenience caused by this issue. 

Could you please send me links to both duplicated entries, I could find only this one  https://isthereanydeal.com/game/swordofstarspitii/info/

**Comment by Phaltan** [comment]
https://isthereanydeal.com/waitlist/#/page:game/info?plain=swordofstarspitiiswordofstarspitii

**Comment by MarkitkaM** [comment]
Entries to merge #2324
