### ISSUE TITLE
Duplicate entries for multiple Total War: WARHAMMER II paid DLCs

### ISSUE THREAD

**Issue by candela97** [IsThereAnyDeal/IsThereAnyDeal-Issues#2463]
https://isthereanydeal.com/search/?q=The+Silence+%26+The+Fury
https://isthereanydeal.com/search/?q=The+Twisted+%26+The+Twilight
https://isthereanydeal.com/search/?q=The+Warden+%26+The+Paunch
https://isthereanydeal.com/search/?q=The+Shadow+%26+The+Blade+warhammer
https://isthereanydeal.com/search/?q=The+Hunter+%26+The+Beast+warhammer
https://isthereanydeal.com/search/?q=The+Prophet+%26+The+Warlock
https://isthereanydeal.com/search/?q=Curse+of+the+Vampire+Coast+warhammer
https://isthereanydeal.com/search/?q=The+Queen+%26+The+Crone
https://isthereanydeal.com/search/?q=Rise+of+the+Tomb+Kings+warhammer
https://isthereanydeal.com/search/?q=Blood+for+the+Blood+God+II+warhammer

Related to #1367 (which is added already, just as a duplicate entry).

**Comment by MarkitkaM** [comment]
Entries to merge #2324
