### ISSUE TITLE
usurper merge conflict

### ISSUE THREAD

**Issue by Sicher2008** [IsThereAnyDeal/IsThereAnyDeal-Issues#2466]
https://new.isthereanydeal.com/game/usurper/info/ - in IsThereAnyDeal wait list, but in steam game collection
https://new.isthereanydeal.com/game/skautfoldusurper/info/ - same as upper game, need merge
https://new.isthereanydeal.com/game/usurpersoulbound/info/ - in real waitlist, need trecker price

**Comment by MarkitkaM** [comment]
> https://new.isthereanydeal.com/game/usurper/info/ - in IsThereAnyDeal wait list, but in steam game collection
> https://new.isthereanydeal.com/game/skautfoldusurper/info/ - same as upper game, need merge

Entries to merge #2324

> https://new.isthereanydeal.com/game/usurpersoulbound/info/ - in real waitlist, need trecker price

Moved to the separated issue #2712 you can check it out.
