### ISSUE TITLE
Merge entries: 12 "Dead By Daylight" DLCs

### ISSUE THREAD

**Issue by SatchQ** [IsThereAnyDeal/IsThereAnyDeal-Issues#2467]
Portrait of a Murder
https://isthereanydeal.com/game/deadbydaylightportraitofamurder/info/
https://isthereanydeal.com/game/deadbydaylightportraitofamurderchapter/info/

Hour of the Witch
https://isthereanydeal.com/game/deadbydaylighthourofwitchchapter/info/
https://isthereanydeal.com/game/deadbydaylighthourofwitchchapterdeadbydaylighthourofwitchchapter/info/

Hellraiser
https://isthereanydeal.com/game/deadbydaylighthellraiserchapter/info/
https://isthereanydeal.com/game/deadbydaylighthellraiserchapterdeadbydaylighthellraiserchapter/info/

A Binding of Kin
https://isthereanydeal.com/game/deadbydaylightabindingofkin/info/
https://isthereanydeal.com/game/deadbydaylightabindingofkinchapter/info/
https://isthereanydeal.com/game/deadbydaylightchapterxviiiabindingofkin/info/

Chains of Hate
https://isthereanydeal.com/game/deadbydaylightchainsofhate/info/
https://isthereanydeal.com/game/deadbydaylightchainsofhatechapter/info/
https://isthereanydeal.com/game/deadbydaylightchapterxvchainsofhate/info/

Cursed Legacy
https://isthereanydeal.com/game/deadbydaylightcursedlegacy/info/
https://isthereanydeal.com/game/deadbydaylightcursedlegacychapter/info/
https://isthereanydeal.com/game/deadbydaylightchapterxivcursedlegacy/info/

Demise of the Faithful
https://isthereanydeal.com/game/deadbydaylightdemiseoffaithful/info/
https://isthereanydeal.com/game/deadbydaylightdemiseoffaithfulchapter/info/

Shattered Bloodline
https://isthereanydeal.com/game/deadbydaylightshatteredbloodline/info/
https://isthereanydeal.com/game/deadbydaylightshatteredbloodlinechapter/info/

Darkness Among Us
https://isthereanydeal.com/game/deadbydaylightdarknessamongus/info/
https://isthereanydeal.com/game/deadbydaylightdarknessamonguschapter/info/

Curtain Call
https://isthereanydeal.com/game/deadbydaylightcurtaincall/info/
https://isthereanydeal.com/game/deadbydaylightcurtaincallchapter/info/

Spark of Madness
https://isthereanydeal.com/game/deadbydaylightsparkofmadness/info/
https://isthereanydeal.com/game/deadbydaylightsparkofmadnesschapter/info/

Of Flesh and Mud
https://isthereanydeal.com/game/deadbydaylightoffleshandmud/info/
https://isthereanydeal.com/game/deadbydaylightoffleshandmudchapter/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
