### ISSUE TITLE
Waitlist games disappearance, yet still getting emails about deals

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#250]
I cleared my steam wishlist completely, and afterwards while checking the waitlist on isthereanydeal the waitlist was empty.

I'm still getting emails about the deals for the games that disappeared from my waitlist, yet I cannot delete the games that I already bought or change any of their settings.

Recreating steam wishlist didn't solve the problem. When added new games to waitlist they appear on the list and everything can be changed about them, yet I'm still getting emails for the "disappeared" game, which do not show on the waitlist any more.

[Issue created by [deleted]: 2015-07-23]

[Comment created by tfedor: 2015-07-23]
I bet you have Waitlist created in two regions. You should see info about that when you visit your Waitlist. If you provide an email, username or your ID I can check it for you, but that should not be neccessary.

**Comment by MarkitkaM** [comment]
Solved.
