### ISSUE TITLE
ITAD displays incorrect price of "Rise of the Tomb Raider: 20 Year Celebration" on the Epic Store

### ISSUE THREAD

**Issue by Korb** [IsThereAnyDeal/IsThereAnyDeal-Issues#2500]
https://www.epicgames.com/store/en-US/p/rise-of-the-tomb-raider — free
https://isthereanydeal.com/game/riseoftombraiderii0yearcelebration/info/ — "950 руб"

![Screenshot 2021-12-30 at 19-15-29 Rise of the Tomb Raider 20 Year Celebration Download and Buy Today - Epic Games Store](https://user-images.githubusercontent.com/3509797/147769240-a2e3d805-36b7-47c9-8258-b57c05e3d0a1.png)
![Screenshot 2021-12-30 at 19-15-45 Rise of the Tomb Raider 20 Year Celebration - Info](https://user-images.githubusercontent.com/3509797/147769247-2ad52ae6-19d2-4c4a-8dfd-8b527792081f.png)

**Comment by MarkitkaM** [comment]
Related #982 #2132
