### ISSUE TITLE
Merge entries: Hearts of Iron IV

### ISSUE THREAD

**Issue by SatchQ** [IsThereAnyDeal/IsThereAnyDeal-Issues#2501]
Cadet Edition
https://isthereanydeal.com/game/heartsofironivcadetedition/info/
https://isthereanydeal.com/game/heartsofironivcadeteditiondigital/info/
https://isthereanydeal.com/game/heartsofironivcadeteditionnew/info/
https://isthereanydeal.com/game/heartsofironivcadeteditionde/info/

La Resistance DLC
https://isthereanydeal.com/game/heartsofironivlaresistance/info/
https://isthereanydeal.com/game/prepurchaseexpansionheartsofironivlaresistance/info/
https://isthereanydeal.com/game/heartsofironivlaresistanceexpansion/info/
https://isthereanydeal.com/game/heartsofironivlaresistancenew/info/
https://isthereanydeal.com/game/expansionheartsofironivlaresistance/info/
https://isthereanydeal.com/game/heartsofironivlarasistancelatam/info/
https://isthereanydeal.com/game/heartsofironivlarsistance/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
