### ISSUE TITLE
ITAD - Viticulture and Viticulture Essential Edition link to the wrong Steam game

### ISSUE THREAD

**Issue by thedraken** [IsThereAnyDeal/IsThereAnyDeal-Issues#2520]
https://store.steampowered.com/app/1325800/Viticulture_Essential_Edition/ links to https://isthereanydeal.com/game/viticulture/info/

However so does the Tabletop simulator DLC: https://store.steampowered.com/app/468733/Tabletop_Simulator__Viticulture/

There is a separate page for the essential edition, but it links to no Steam page:
https://isthereanydeal.com/game/viticultureessentialedition/info/

**Comment by MarkitkaM** [comment]
Entries to split #2323
