### ISSUE TITLE
Game page for ‘ECHO’ links to Steam page of ‘Echoes’

### ISSUE THREAD

**Issue by Kissaki** [IsThereAnyDeal/IsThereAnyDeal-Issues#2524]
https://new.isthereanydeal.com/game/echo/info/

Links to both [ECHO](https://store.steampowered.com/app/551770/ECHO/) and [Echoes](https://store.steampowered.com/app/1610060/Echoes/) steam pages. The Echoes one is wrong. That’s a different game.

**Comment by MarkitkaM** [comment]
Entries to split #2323
