### ISSUE TITLE
HumbleBundle filter game title words

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#253]
Some games don't import on ITAD because HumbleBundle adds "Steam Key", "Origin Key" or just "Key" as suffix to their names. Try to filter them out on matching the name.

Examples:

* Battlefield 3 ~~Origin Key~~
* Burnout Paradise: The Ultimate Box ~~Origin Key~~
* Burnout Paradise: The Ultimate Box ~~Steam Key~~
* Humble Frozenbyte Bundle ~~Desura Key~~
* Humble Frozenbyte Bundle ~~Steam Key~~
* The Sims 3 ~~Key~~

[Issue created by lkraider: 2015-07-25]
[Last updated on bitbucket: 2015-07-27]

[Comment created by lkraider: 2015-07-27]
I agree it is prone to breaking. Try to match both, with and without "Key"?

[Comment created by tfedor: 2015-07-27]
What if HumbleBundle will start selling game ending with "Key"?

[Comment created by lkraider: 2015-07-27]
Maybe filter "Key" suffix only when it is imported from HumbleBundle?

[Comment created by tfedor: 2015-07-27]
I've added rule to get rid of "Steam|Desura|Origin Key", but not the "Key" alone, since I think it may appear as a title of the game. Right now it seems like there's only one game which ends at Key, and of a dubious quality, but who knows... http://isthereanydeal.com/#/page:game/info?plain=elementalsmagickey

**Comment by MarkitkaM** [comment]
Solved.
