### ISSUE TITLE
Cannot refresh collection

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#254]
I'm trying to refresh my steam collection for some days now, but i'm still getting the same message: We were not able to refresh your Collection, please try again
Loader: Loader Locked

[Issue created by [deleted]: 2015-07-26]

[Comment created by tfedor: 2015-07-26]
Hm, this issue has been coming up a lot lately, before I get to check it to properly fix it I have turned off the locking so it should work each time now.

**Comment by MarkitkaM** [comment]
Solved within the conversation.
