### ISSUE TITLE
Release date in the games' info page

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#257]
That's something that it's always good to see, because sometimes you don't really know the game and the release date is a factor to measure good/bad prices.

[Issue created by exterminating: 2015-07-27]

**Comment by MarkitkaM** [comment]
Already there
![image](https://user-images.githubusercontent.com/88401908/140634560-8938f90d-45f7-41f8-8347-0ab04037227d.png)
