### ISSUE TITLE
Page "Resonance" links two different games with same name 

### ISSUE THREAD

**Issue by CoronaV** [IsThereAnyDeal/IsThereAnyDeal-Issues#2590]
https://isthereanydeal.com/game/resonance/info/

This page apparently refers to the game released on Steam in 2012 for the full price of €9,99, but the page's itch.io store link links to an unrelated game called Resonance that was released on 27th January this year for the full price of $2.49.

**Comment by MarkitkaM** [comment]
Entries to split #2323
