### ISSUE TITLE
Citadel - Two games merged, neither of which is game shown

### ISSUE THREAD

**Issue by MagikGimp** [IsThereAnyDeal/IsThereAnyDeal-Issues#2604]
[https://isthereanydeal.com/game/citadel/info/](https://isthereanydeal.com/game/citadel/info/)
Games incorrectly merged:
1. [Citadel, The](https://store.steampowered.com/app/1378290/The_Citadel/) (prices for this game shown, needs its own new entry)
2. [Citadel: Forged with Fire](https://store.steampowered.com/app/487120/Citadel_Forged_with_Fire/) (actual ITAD page- [https://isthereanydeal.com/game/citadelforgedwithfire/info/](https://isthereanydeal.com/game/citadelforgedwithfire/info/)

**Actual game shown: [Citadel](https://store.steampowered.com/app/485590/Citadel/) (not currently for sale?)**

**Comment by MarkitkaM** [comment]
> Games incorrectly merged:

Duplication #1874 -> Entries to split #2323

> Actual game shown: [Citadel](https://store.steampowered.com/app/485590/Citadel/) (not currently for sale?)

Added to the separated issue #2715
