### ISSUE TITLE
Your Sword Is So Big - Duplicate entry, plugin links to wrong one

### ISSUE THREAD

**Issue by MagikGimp** [IsThereAnyDeal/IsThereAnyDeal-Issues#2605]
Game- [https://store.steampowered.com/app/1756120/Your_Sword_Is_So_Big](https://store.steampowered.com/app/1756120/Your_Sword_Is_So_Big)
Links to (incorrectly)- [https://isthereanydeal.com/game/yourswordissobigyourswordissobig/info/](https://isthereanydeal.com/game/yourswordissobigyourswordissobig/info/) (dead entry, does have banner)
Correct entry- [https://isthereanydeal.com/game/yourswordissobig/info/](https://isthereanydeal.com/game/yourswordissobig/info/) (no banner)

**Comment by MarkitkaM** [comment]
Entries to merge #2324
