### ISSUE TITLE
Amazing Frog? - Microsoft Store link is for different game masquerading as this title

### ISSUE THREAD

**Issue by MagikGimp** [IsThereAnyDeal/IsThereAnyDeal-Issues#2607]
[Listing](https://isthereanydeal.com/game/amazingfrog/info/)
[Microsoft Store game](https://www.microsoft.com/en-gb/p/amazing-frog/9ngblhsh62gt?cid=msft_web_chart&activetab=pivot:overviewtab) (unrelated, stolen assets, is affecting listing price of real game)

**Comment by MarkitkaM** [comment]
Entries to split #2323
