### ISSUE TITLE
Attempting to remove an item from the waitlist produces an invisible dialogue box.

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#262]
I was removing some items from my waitlist manually, and when I clicked the "remove selected games" button, the browser acts as if it's frozen. I hit the enter key to accept any dialogue that may be present and the window refreshed and updated with my changes.

I believe a dialogue box is being called, but for some reason it doesn't render.

[Issue created by jesman1: 2015-07-30]
[Last updated on bitbucket: 2015-08-01]

[Comment created by jesman1: 2015-08-01]
After testing again today the issue seems to have been resolved. I assume that this must have been an isolated incident as no others reported issues.

[Comment created by tfedor: 2015-07-30]
Nothing which would help here. I'm calling normal javascript's confirm there and I can see it in both Firefox and Chrome.

[Comment created by jesman1: 2015-07-30]
I reproduced the issue in chrome earlier. When I get a chance I can try other browsers. Do you have any debug info printing out to the JavaScript console? I can forward anything from there if so.

[Comment created by tfedor: 2015-07-30]
Yes, there should be the javascript confirm box. What browser are you using?

**Comment by MarkitkaM** [comment]
Resolved.
