### ISSUE TITLE
STEAM - Eternal Threads/Second Chance confusion

### ISSUE THREAD

**Issue by Kiyos** [IsThereAnyDeal/IsThereAnyDeal-Issues#2629]
I’ve been using IsThereAnyDeal for many years now, and it’s awesome. Some time ago I wishlisted an upcoming title called Eternal Threads to be released on Steam this year: https://store.steampowered.com/app/1046790/Eternal_Threads/
IsThereAnyDeal thinks it’s a completely different game called Second Chance (https://store.steampowered.com/app/1415110/Second_Chance/) and regularly notifies me of its price drop via e-mail.
The process of synchronizing my public Steam wishlist with my IsThereAnyDeal waitlist is happening automatically by your service.
This is what IsThereAnyDeal thinks of the game:

![second_chance_threads](https://user-images.githubusercontent.com/5103155/152986198-109f516a-28d0-487d-8b44-6ef81c73b697.jpg)

Title: wrong (should be Eternal Threads)
Release date: correct
Image: correct
Store links and prices: all for different games
Reviews metric: incorrect

And this is what happens if I try to search for Eternal Threads:

![threads_search](https://user-images.githubusercontent.com/5103155/152987496-e5c817f1-aa2e-4409-9433-280952468c05.jpg)

**Comment by MarkitkaM** [comment]
All links of Second Chance games should be split -> Entries to split #2323	
Eternal Threads added to separated issue #2716
