### ISSUE TITLE
2 games in one entry / confusion of 2 games with close name

### ISSUE THREAD

**Issue by Jeanpierregi** [IsThereAnyDeal/IsThereAnyDeal-Issues#2634]
Hi,
In the past I sent some emails for this kind of bug not yeat treated but I may have not made the right choice and rather i think i should have posted here.

So, repeating here :

1)  "Journey" the game ( https://isthereanydeal.com/game/journey/info/ )  appears as "the journey" in the game list (after searching "journey" on the website ISTAD).

2) "Silence" game ( https://isthereanydeal.com/game/silence/info/ ) collides with "The silence" on itch only ( https://8bitpxl.itch.io/the-silence ) and the price of itch version of this game "silence" are in fact prices of "the silence" on itch. (From my search there are many "silence" game on itch and i'm not sure that the "silence" game is really on itch among all those games...)

**Comment by MarkitkaM** [comment]
ad1) Moved into the separated issue #2717
ad2) Duplication of the #1886 -> Entries to split #2323
