### ISSUE TITLE
HEARTBEAT - Various errors

### ISSUE THREAD

**Issue by MagikGimp** [IsThereAnyDeal/IsThereAnyDeal-Issues#2636]
[Link to game](https://store.steampowered.com/app/984560/HEARTBEAT/)
[Link to ISAD listing](https://isthereanydeal.com/game/heartbeat/info/) (Correct banner, correct name, one of the listed prices is for incorrect game affecting average price which is...)
...[This game](https://store.steampowered.com/app/1386710/The_HeartBeat/) (The Heartbeat)

[HEARTBEAT Original Soundtrack](https://store.steampowered.com/app/985110/HEARTBEAT_Original_Soundtrack/)
[Listing](https://isthereanydeal.com/game/heartbeatoriginalsoundtrack/info/) (No prices)
[Duplicate](https://isthereanydeal.com/game/heartbeatsoundtrack/info/) (No banner, incorrect name)

**Comment by MarkitkaM** [comment]
ad Heartbeat) Duplication of the #2171
ad HEARTBEAT Original Soundtrack) Entries to merge #2324
