### ISSUE TITLE
Add a "only if the game can be activated on Steam" for origin

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#265]
I don't mind buying games that are exclusive to origin. So another check box on the waitlist would be nice (maybe even some more for other platforms)

[Issue created by CodeNameUrf: 2015-08-05]

**Comment by MarkitkaM** [comment]
![image](https://user-images.githubusercontent.com/88401908/140633943-7b0cd30f-57d6-4246-b7bf-deac12a9cbc4.png)
