### ISSUE TITLE
Neverwinter Nights: Enhanced Edition doesn't track the one sold by Steam

### ISSUE THREAD

**Issue by AlexWFreitas** [IsThereAnyDeal/IsThereAnyDeal-Issues#2654]
I wanted to track deals on Neverwinter Nights Enhanced Edition, but on the website, it doesn't show Steam as a possible Store to buy the game.

https://isthereanydeal.com/game/neverwinternightsenhancededition/info/

https://store.steampowered.com/app/704450/Neverwinter_Nights_Enhanced_Edition/

![image](https://user-images.githubusercontent.com/6776230/153731352-a6e048c9-47d2-44a6-85ff-cfab87929e87.png)

If this could be fixed, it would be nice, thanks.

**Comment by MarkitkaM** [comment]
"Neverwinter Nights: Enhanced Edition" on Steam is tracked under the incorrect name "[NEVERWINTER NIGHTS...](https://isthereanydeal.com/game/neverwinternights/info/)" - It will be merged.

-> Entries to merge #2324
