### ISSUE TITLE
Let us use multiple groups for Connect the Dots

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#267]
Right now, there's just A is the same as B, for individually marking a game with two listings. It would be easier to be able to use multiple groups to be able to mark several listings as identical all at once. The list is very long and it can be quite tedious to mark identical listings one at a time. You could even use different letter pairs for each group (A is B, C is D, etc.)

[Issue created by DigChrono: 2015-08-07]

**Comment by MarkitkaM** [comment]
The dots are no longer existing.
