### ISSUE TITLE
Wrong price for Kena: Bridge of Spirits (Epic Games)

### ISSUE THREAD

**Issue by jpjonte** [IsThereAnyDeal/IsThereAnyDeal-Issues#2671]
ITAD page: https://isthereanydeal.com/game/kenabridgeofspirits/info/
Epic Games page: https://www.epicgames.com/store/p/kena-bridge-of-spirits

ITAD says the game currently costs 27,99€ on Epic Games, but the actual current price is 39,99€.

**Comment by jpjonte** [comment]
This seems to apply to many games on EGS:

Witcher 3 GOTY
ITAD: https://isthereanydeal.com/game/witcheriiiwildhuntgameofyearedition/info/ (9,99€)
EGS: https://www.epicgames.com/store/en-US/p/the-witcher-3-wild-hunt (49,96€)

Read Dead Redemption 2
ITAD: https://isthereanydeal.com/game/reddeadredemptionii/info/ (29,99€)
EGS: https://www.epicgames.com/store/en-US/p/red-dead-redemption-2 (59,99€)

Cyberpunk 2077
ITAD: https://isthereanydeal.com/game/cyberpunkii0viivii/info/ (29,99€)
EGS: https://www.epicgames.com/store/en-US/p/cyberpunk-2077 (59,99€)

Assassin's Creed Valhalla Gold
ITAD: https://isthereanydeal.com/game/assassinscreedvalhallagoldedition/info/ (49,99€)
EGS: https://www.epicgames.com/store/en-US/p/assassins-creed-valhalla--gold-edition (99,99€)

**Comment by KeshiaRose** [comment]
I'm also seeing this. More examples (US/USD):

Horizon Zero Dawn™ Complete Edition
https://isthereanydeal.com/game/horizonzerodawncompleteedition/info/ ($24.99)
https://www.epicgames.com/store/en-US/p/horizon-zero-dawn-complete-edition ($49.99)

Frostpunk: Game of the Year Edition
https://isthereanydeal.com/game/frostpunkgameofyearedition/info/ ($16.19)
https://www.epicgames.com/store/en-US/p/frostpunk--game-of-the-year-edition ($44.99)

**Comment by MarkitkaM** [comment]
**Moved to separated issues:**
Kena: Bridge of Spirits #2719
Witcher 3 GOTY #2720
Red Dead Redemption 2 #2721
Cyberpunk 2077 #2722
Assassin's Creed Valhalla Gold #2723
Horizon Zero Dawn™ Complete Edition #2724
Frostpunk: Game of the Year Edition #2725
