### ISSUE TITLE
Entry to split: Wanderer

### ISSUE THREAD

**Issue by C4nnyKumqu4t** [IsThereAnyDeal/IsThereAnyDeal-Issues#2675]
https://isthereanydeal.com/game/wanderer/info/ contains two different games:
The Wanderer: 

- https://store.steampowered.com/app/530860/The_Wanderer/ 

Wanderer:

- https://store.steampowered.com/app/1599560/Wanderer/
- https://www.humblebundle.com/store/agecheck/wanderer
- https://www.greenmangaming.com/games/wanderer-pc/

**Comment by MarkitkaM** [comment]
Entries to split #2323
Incorrect name #2726
