### ISSUE TITLE
Osiris: New Dawn linked to wrong game on ITAD

### ISSUE THREAD

**Issue by fakkkun** [IsThereAnyDeal/IsThereAnyDeal-Issues#2676]
Osiris: New Dawn - https://store.steampowered.com/app/402710/Osiris_New_Dawn/

linked to Osiris - https://isthereanydeal.com/game/osiris/info/#/

Osiris: New Dawn not linked to anywhere on steam. Therefore this game has not been tracked since March 21, 2019 on price history.

**Comment by MarkitkaM** [comment]
Duplication #568
Entries to split #2323
