### ISSUE TITLE
SUBVERESE - Dead Steam link

### ISSUE THREAD

**Issue by MarkitkaM** [IsThereAnyDeal/IsThereAnyDeal-Issues#2681]
**Steps to reproduce:**
1. Go to https://isthereanydeal.com/game/subverse/info/
2. Click on the Steam listing with a higher price https://store.steampowered.com/agecheck/app/1034140/

**Actual Result:** Seems like the page is not existing anymore "OOPS, SORRY!"

**Expected result:** Remove this listing

fyi @Ceiyne

**Comment by Ceiyne** [comment]
When I follow your steps the Subverse page on Steam comes up.  

The higher priced listing on Steam goes to the game page (which is what this ITAD entry should be linked to): https://store.steampowered.com/app/1034140/Subverse/

The lower priced listing on Steam goes to an unrelated movie that just happens to have the same name (the ITAD page should not link to this): https://store.steampowered.com/app/1001630/

**Comment by MarkitkaM** [comment]
Thank you for your information. 

The Subverse has been assigned to the list "Entries to split #2323"
