### ISSUE TITLE
Bloodstained: Ritual of the Night - "Iga's Back Pack" DLC prices combined with AdVenture Capitalist

### ISSUE THREAD

**Issue by Ponggoleechee** [IsThereAnyDeal/IsThereAnyDeal-Issues#2682]
[https://isthereanydeal.com/game/adventurecapitalist/info/](https://isthereanydeal.com/game/adventurecapitalist/info/)

For some reason these two seem to share a page.

**Comment by MarkitkaM** [comment]
Duplication #2227
Entries to split #2323
