### ISSUE TITLE
either Bug or Store Spam

### ISSUE THREAD

**Issue by Ble3azy** [IsThereAnyDeal/IsThereAnyDeal-Issues#2687]
For some reason I am recieveing 20+ emails a day for multiple consecutive days on a particular item sale, completely cloggin up my inbox 
The game is Monster Sanctuary at store AllYouPlay, there is no change to the price in any of the notifications. 
My settings are such that I should not recieve further emails unless there is a price change. 
As this has never happened before I suspect AllYouPlay may be gaming your system, either way I'd like to know if I should put this store on the blacklist. 

Thanks for your time, 
Ben.

**Comment by tfedor** [comment]
Hi, and this happens **only** for AllYouPlay?

**Comment by tfedor** [comment]
I have tried something, you may receive one or two more emails if there's one already queued, but it should stop after that. If it doesn't please reopen this issue.

**Comment by Ble3azy** [comment]
I'm not 100% but I think it may be the first time AllYouPlay have 'qualified' anything on my wishlist so it's hard to be certain, but this is the only time it's ever happened. 

Thanks for the help. 
B
