### ISSUE TITLE
Game / MonCage : no price

### ISSUE THREAD

**Issue by gaeld** [IsThereAnyDeal/IsThereAnyDeal-Issues#2688]
There is no price listed on https://isthereanydeal.com/game/moncagelongzhongkuimeng/info/
But the game is available on Steam.

Thanks Best Regards

**Comment by MarkitkaM** [comment]
The game is listed here with the Steam price tracking https://isthereanydeal.com/game/moncage/info/ -> 
https://store.steampowered.com/app/1195290/_Moncage/

Entries to merge #2324
