### ISSUE TITLE
The Sacred Stone[: A Story Adventure] - Duplicate entries because of name change

### ISSUE THREAD

**Issue by MagikGimp** [IsThereAnyDeal/IsThereAnyDeal-Issues#2696]
[Link to game's ITAD entry](https://isthereanydeal.com/game/sacredstone/info/) (no tracked stores)
[Link to duplicate entry](https://isthereanydeal.com/game/sacredstoneastoryadventure/info/) (Old name i.e not how is displayed on Steam now but still is for [Steam Community](https://steamcommunity.com/app/432410), Steam prices tracked)

**Comment by MarkitkaM** [comment]
Entries to merge #2324
