### ISSUE TITLE
Sacred Gold - Dreamgame listed separately

### ISSUE THREAD

**Issue by MagikGimp** [IsThereAnyDeal/IsThereAnyDeal-Issues#2699]
[Main ITAD listing](https://isthereanydeal.com/game/sacredgoldedition/info/) ("Sacred Gold Edition")
[Listing with only Dreamgame link](https://isthereanydeal.com/game/sacredgold/info/) ("Sacred Gold")

**Comment by MarkitkaM** [comment]
Entries to merge #2324
