### ISSUE TITLE
GMG is listing things that are not available for sale or presale and I'm getting notifications about it.

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#270]
Hello.

When I wishlist something that's not out yet I typically leave the price blank so that I'll get a notification when the thing is available. Lately all the notifications I've been getting show that the game is available on GMG, but following the link leads to a "coming soon" page with no purchase option.

It's not just an annoyance, though. If there's no release discount then it means that I have no way to get a notification when the game actually does become available.

[Issue created by [deleted]: 2015-08-09]

**Comment by MarkitkaM** [comment]
"former user"
