### ISSUE TITLE
ITAD page links to two different games

### ISSUE THREAD

**Issue by daangamz** [IsThereAnyDeal/IsThereAnyDeal-Issues#2704]
https://isthereanydeal.com/game/roll/info/
has two steam entries, linking two games called ROLL! and Roll

- a 3D platform game https://store.steampowered.com/app/938280/ROLL/
- a dice rolling game https://store.steampowered.com/app/1585910/Roll/

The other link for itch links to ROLL!, the 3D platform game

**Comment by MarkitkaM** [comment]
Duplication #2145
Entries to split #2323
