### ISSUE TITLE
'30XX' game link/tracker points to '2002XX' on Steam

### ISSUE THREAD

**Issue by lborl** [IsThereAnyDeal/IsThereAnyDeal-Issues#2710]
So shows inaccurate price information.

**2002XX** RRP £0.79 [https://store.steampowered.com/app/1576140/2002X](url)
**30XX** RRP £15.49 [https://store.steampowered.com/app/1029210/30XX](url)

**Comment by MarkitkaM** [comment]
Entries to split #2323
