### ISSUE TITLE
Mercenary Kings: Reloaded Edition - Duplicate entries

### ISSUE THREAD

**Issue by MagikGimp** [IsThereAnyDeal/IsThereAnyDeal-Issues#2711]
[Listing with banner & correct name](https://isthereanydeal.com/game/mercenarykingsreloadededition/info/) (Steam link absent)
[Duplicate](https://isthereanydeal.com/game/mercenarykings/info/) (Steam link, Humble Store / Widgets link broken)

**Comment by MarkitkaM** [comment]
Entries to merge #2324
