### ISSUE TITLE
Echo Tokyo: An Intro - Dead duplicates, incorrect name

### ISSUE THREAD

**Issue by MagikGimp** [IsThereAnyDeal/IsThereAnyDeal-Issues#2718]
[Link to game on Steam](https://store.steampowered.com/app/345700/Echo_Tokyo_An_Intro/)
[Main ITAD entry](https://isthereanydeal.com/game/echotokyointro/info/) ("Echo Tokyo: Intro", no banner)
[Duplicate with correct name and banner](https://isthereanydeal.com/game/echotokyoanintro/info/)
[A dead entry with a similar name](https://isthereanydeal.com/game/echotokyo/info/) ("Echo Tokyo")

**Comment by MarkitkaM** [comment]
Entries to merge #2324
