### ISSUE TITLE
Getting Notifications For Stores I Have Not Selected

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#272]
I have selected only a handful of stores that I want to get notifications from, yet I am constantly receiving e-mails with notifications for stores I have not selected.

For example, I just got a notification about a sale on Get Games. I don't use Get Games, and  I have not selected to receive notifications about their sales. I have double checked, and Get Games is not selected.

[Issue created by [deleted]: 2015-08-10]

[Comment created by tfedor: 2015-08-10]
Please check you have only stores you want selected in your Default Waitlist settings http://isthereanydeal.com/#/page:user/wait/defaults and click "save and update". Notification settings work on per-game basis, so you can select different stores for different games. If you update your defaults, games which are already in your Waitlist won't be automatically updated. You can see notification settings for each game in your Waitlist.

**Comment by MarkitkaM** [comment]
Solved within the conversation.
