### ISSUE TITLE
Game Missing

### ISSUE THREAD

**Issue by FunkyPixie** [IsThereAnyDeal/IsThereAnyDeal-Issues#2728]
There's no page for the VR game thats called Wanderer 

Heres the steam page https://store.steampowered.com/app/1599560/Wanderer
![772e61ca5d559c4deeb8c94e092e7561](https://user-images.githubusercontent.com/5890200/157120916-aee49719-e5c9-4e5b-abff-7cec006702ff.jpg)

**Comment by MarkitkaM** [comment]
Hello, 
Thank you for your feedback.

The game you are searching for is erroneously listed at the entry together with a similarly named game The Wanderer as well.
You can find it here https://isthereanydeal.com/game/wanderer/info/ as one of the listed Steam links.
![image](https://user-images.githubusercontent.com/88401908/157185764-0001502a-b96e-470f-8a3d-4c97caf5c90e.png)

We apologize for the inconvenience this issue has caused.

Related  issue #2675
