### ISSUE TITLE
Risk of Rain 2: Survivors of the Void - duplicate entry

### ISSUE THREAD

**Issue by awesomeocelot** [IsThereAnyDeal/IsThereAnyDeal-Issues#2731]
Entry 1: https://isthereanydeal.com/game/riskofrainiisurvivorsofvoid/info/
Entry 2: https://isthereanydeal.com/game/riskofrainiiexpansioni/info/

Note that if you click the Steam link in entry 2, the name matches that of entry 1. I would also recommend updating the game title itself to match the Steam entry "Risk of Rain 2: Survivors of the Void"

**Comment by MarkitkaM** [comment]
Entries to merge #2324
