### ISSUE TITLE
ECHO Duplicate Entry

### ISSUE THREAD

**Issue by fakkkun** [IsThereAnyDeal/IsThereAnyDeal-Issues#2732]
Go to: https://isthereanydeal.com/game/echo/info/

There are two steam link to go two different games (steam ids: 551770, 1610060)

It's must show just this game's link.
https://store.steampowered.com/app/551770/ECHO/

**Comment by MarkitkaM** [comment]
Duplication https://github.com/IsThereAnyDeal/IsThereAnyDeal-Issues/issues/2032
Entries to split #2323
