### ISSUE TITLE
VenusBlood FRONTIER International - Merge

### ISSUE THREAD

**Issue by Mereck13579** [IsThereAnyDeal/IsThereAnyDeal-Issues#2740]
https://isthereanydeal.com/game/venusbloodfrontierinternational/info/
https://isthereanydeal.com/game/venusbloodfrontier/info/
Those two entries are for the same game, I suspect the second one (that only has Steam) got its name changed but the ITAD entry wasn't changed accordingly.

**Comment by MarkitkaM** [comment]
Entries to merge #2324
