### ISSUE TITLE
Patrick's Parabox - itchio link missing in the game page

### ISSUE THREAD

**Issue by zelgaris** [IsThereAnyDeal/IsThereAnyDeal-Issues#2937]
https://isthereanydeal.com/game/patricksparabox/info/
only contains the Steam link, while the game is also purchasable on itch for few days already

https://patricktraynor.itch.io/patricks-parabox

**Comment by MarkitkaM** [comment]
I can see it there already for each region https://isthereanydeal.com/game/patricksparabox/info/
![image](https://user-images.githubusercontent.com/88401908/163398326-34ed483b-243c-4b0e-81ac-0cd64a467e2d.png)
