### ISSUE TITLE
Wanderer VR is incorrectly categorised under The Wanderer (or vice versa)

### ISSUE THREAD

**Issue by pacsuta** [IsThereAnyDeal/IsThereAnyDeal-Issues#2943]
There are 2 separate games on the ["Wanderer" ITAD page](https://isthereanydeal.com/game/wanderer/info/), one is [Wanderer, a VR game](https://store.steampowered.com/app/1599560/Wanderer/), the other is [The Wanderer, a very different game](https://store.steampowered.com/app/530860/The_Wanderer/).
![image](https://user-images.githubusercontent.com/47948998/161819602-776685ac-9166-4d95-910f-067195d8cfb6.png)

This makes it hard to browse ITAD for Wanderer VR as it shows up under The Wanderer. This also breaks waitlist email notifications for Wanderer VR when the notification limit is the historical lowest price. It also messes with Augmented Steam, displaying the current and historical lowest prices for The Wanderer on Wanderer VR's store page.
![image](https://user-images.githubusercontent.com/47948998/161819706-24b772e8-76fc-4e5c-adc9-d2efbdc6aeea.png)

Please either move The Wanderer to a "The Wanderer" page, or Wanderer to a "Wanderer (VR)" (or similarly named) page.

Thank you.

**Comment by MarkitkaM** [comment]
Duplication #2675

Entries to split #2323
