### ISSUE TITLE
Plants vs. Zombies

### ISSUE THREAD

**Issue by MagikGimp** [IsThereAnyDeal/IsThereAnyDeal-Issues#2944]
- [Original game](https://isthereanydeal.com/game/plantsvszombies/info/) (no stores sell this version any more)
- [Duplicate of above](https://isthereanydeal.com/game/plantsvszombiesbr/info/) (dead)
- [Game of the Year Edition](https://isthereanydeal.com/game/plantsvszombiesgameofyearedition/info/) (Origin only, banner present)
- [Also GOTY](https://isthereanydeal.com/game/plantsvszombiesgotyedition/info/) (Steam only, banner missing)

**Comment by MarkitkaM** [comment]
Entries to merge #2324
