### ISSUE TITLE
Half-Life: Source - Entries to be merged

### ISSUE THREAD

**Issue by MagikGimp** [IsThereAnyDeal/IsThereAnyDeal-Issues#2949]
[Original listing](https://isthereanydeal.com/game/halflifesource/info/) (Missing any stores, banner intact)
["Half-Life 1: Source"](https://isthereanydeal.com/game/halflifeisource/info/) (Steam link, missing banner)

**Comment by MarkitkaM** [comment]
Entries to merge #2324
