### ISSUE TITLE
"Pay what you want" on v2 humble widget was not detected as a deal

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#295]
Groundskeeper 2 gone to Pay What You Want model for a week [recently](https://twitter.com/OrangePixel/status/638721145689272320). 

$1 is just a suggested price, actually you can set it less or bigger, starting from $0.01.
http://www.orangepixel.net/2014/04/18/groundskeeper2/

But when I filter ITAD by widgets deals, this game is not listed: http://isthereanydeal.com/#/filter:humblewidgets;/scroll:%23gamelist

From what I can see, suggested $1 price was wrongfully detected as a regular price via permanent price drop (which is not the case). 
http://isthereanydeal.com/#/page:game/info?plain=groundskeeperii

**Is there any way to detect such deals as actual deals (instead of permanent price drops)?**

***

It looks like https://github.com/calvein/humble-games/ supports only v1 widgets, and v1 version for this game https://www.humblebundle.com/store/groundskeeper2/pmjkpjmpEIue399 really looks like it's a permanent price drop to fixed $1. 

And the only difference I see between it and the ["regular sale" v1 widget](https://www.humblebundle.com/store/apotheon/JUEwMIoTCgFx) is the absence of the element with "hs-regular-price" id.

***

Here is the [separate link to v2 widget](https://www.humblebundle.com/widget/v2/product/groundskeeper2/pmjkpjmpEIue399?theme=light), offered on game site.

When compared to [regular v2 widgets](https://www.humblebundle.com/widget/v2/product/ftlfasterthanlight/pending?theme=dark)  main grey price is hidden, and editable PWYW price is actually the tip (green), but in Groundskeeper 2 it's not optional.

***

Not sure if anything can be done with it on ITAD's side, but still decided to post it.

[Issue created by enchained: 2015-09-03]
[Last updated on bitbucket: 2015-09-04]

[Comment created by tfedor: 2015-09-04]
Dunno, it looks like price drop to me. Nothing shows that it should go back to the previous price. (btw, I didn't know about v2 widgets, thanks)

**Comment by MarkitkaM** [comment]
Solved within the conversation.
