### ISSUE TITLE
Crunch Element is avilable on Steam, but ITAD shows no stores selling the game

### ISSUE THREAD

**Issue by romano21A** [IsThereAnyDeal/IsThereAnyDeal-Issues#2950]
[ITAD](https://isthereanydeal.com/game/crunchelementvrinfiltration/info/) shows no stores selling the game, but it is available on [Steam](https://store.steampowered.com/app/1090250/Crunch_Element/)

**Comment by MarkitkaM** [comment]
The game is listed in this entry https://isthereanydeal.com/game/crunchelement/info/

Entries to merge #2324
