### ISSUE TITLE
[Bug] the phrase "The" is being ignored

### ISSUE THREAD

**Issue by Flameruin** [IsThereAnyDeal/IsThereAnyDeal-Issues#2954]
I have reported this before but can't see it

Latest example I have is this 2 games, Wanderer is getting linked to The Wanderer
https://store.steampowered.com/app/530860/The_Wanderer/
https://store.steampowered.com/app/1599560/Wanderer/

**Comment by MarkitkaM** [comment]
Duplication #2726
