### ISSUE TITLE
Monster Hunter Rise: Sunbreak split into two pages

### ISSUE THREAD

**Issue by Atzerkins** [IsThereAnyDeal/IsThereAnyDeal-Issues#2956]
https://isthereanydeal.com/game/monsterhunterrisesunbreak/info/
https://isthereanydeal.com/game/monsterhunterrisesunbreakprepurchase/info/

Same with the deluxe edition:
https://isthereanydeal.com/game/monsterhunterrisesunbreakdeluxeedition/info/
https://isthereanydeal.com/game/monsterhunterrisesunbreakdeluxeeditionprepurchase/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
