### ISSUE TITLE
Game TItle Doubled from SteamAppID

### ISSUE THREAD

**Issue by Dave247** [IsThereAnyDeal/IsThereAnyDeal-Issues#2957]
When trying to visit The Stanley Parable Ultra deluxe on the site through it's appid, the game title will double up leading to the incorrect entry.

- **ITAD appid URL:** https://isthereanydeal.com/steam/app/1703340/ 
- **Incorrect ITAD URL:** https://isthereanydeal.com/game/stanleyparableultradeluxestanleyparableultradeluxe/info/#/
- **Corrected URL:** https://isthereanydeal.com/game/stanleyparableultradeluxe/info/#/

- **Steam URL:** https://store.steampowered.com/app/1703340/The_Stanley_Parable_Ultra_Deluxe/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
