### ISSUE TITLE
Fake game entry : Russia vs Ukraine

### ISSUE THREAD

**Issue by Atzerkins** [IsThereAnyDeal/IsThereAnyDeal-Issues#2964]
https://isthereanydeal.com/#/page:game/info?plain=russiavsukraine

This is not a real game but a simple web page with a fake poll, it isn't even a real poll as it shows random numbers for the score. I'm guessing it should be removed from ITAD.

**Comment by HYBRID-BEING** [comment]
Now, while a fake (because it uses randomized numbers) and rigged (because Ukraine gets a higher multiplier) poll doesn't do a bit of justice to Ukraine, is there a rule that states that web games hosted on itch.io don't count for ITAD?
Maybe it's better to report it on itch.io directly?

**Comment by tfedor** [comment]
I have removed the whole entry, can't see it on itch anymore either.
