### ISSUE TITLE
Many Steam game entries breaks at 2021-03-27

### ISSUE THREAD

**Issue by no1xsyzy** [IsThereAnyDeal/IsThereAnyDeal-Issues#2966]
It must be due to some Steam update that day. Is it possible to batch fixing them all?

Some examples:
(#2960)
https://isthereanydeal.com/game/endlessroad/info/
https://isthereanydeal.com/game/wujinzhilu/info/

(#2961)
https://isthereanydeal.com/game/nullandpeta/info/
https://isthereanydeal.com/game/nullpetainvasionofqueenbug/info/

https://isthereanydeal.com/game/niohcompleteedition/info/
https://isthereanydeal.com/game/niohcompleteeditionrenwangcompleteedition/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
