### ISSUE TITLE
Tin Can - Merge duplicate named entry

### ISSUE THREAD

**Issue by Dave247** [IsThereAnyDeal/IsThereAnyDeal-Issues#2974]
The game seemingly goes by two seperate names, one that includes a subtitle but is only used on GOG, while Steam excludes it, thus generating two separate entries.

ITAD Listing: https://isthereanydeal.com/game/tincan/
https://isthereanydeal.com/game/tincanescapepodsimulator/

Steam page: https://store.steampowered.com/app/1315980/Tin_Can/

GOG page: https://www.gog.com/en/game/tin_can_escape_pod_simulator

**Comment by MarkitkaM** [comment]
Entries to merge #2324
