### ISSUE TITLE
Search for "The Forest" game is wrong

### ISSUE THREAD

**Issue by kastaldi** [IsThereAnyDeal/IsThereAnyDeal-Issues#2975]
If you search for "The Forest" game the results are wrong.
The first result is a version with two stores but thumbnail is correct.
The second one is a version with Steam, clicking on the empty thumbnail shows two games, one of them is "Forest" and is not the same game while the other is the right one.
I'm EU2.

**Comment by PseudoNymNZL** [comment]
I noticed this issue today also.  There are two separate games on Steam: The Forest and Forest.  One of the Steam offer links is associated with the wrong listing on isthereanydeal.com

**Comment by MarkitkaM** [comment]
Thank you for your report it was already reported #2351 and moved to lists of entry bugs "Entries to split #2323" and  "Entries to merge #2324".
