### ISSUE TITLE
Games with doubled names not linking to any sale page (including Steam)

### ISSUE THREAD

**Issue by raycornwall** [IsThereAnyDeal/IsThereAnyDeal-Issues#2981]
Hacker Simulator:
https://isthereanydeal.com/search/?q=Hacker%20Simulator
should link to this game:
https://store.steampowered.com/app/1754840/Hacker_Simulator/
But it looks like it's tracking to this game on itch.io with a similar name:
https://skepistudio15.itch.io/hacker-simulator6252

Ghostlore:
https://isthereanydeal.com/game/ghostloreghostlore/info/#/
is incorrect link
https://isthereanydeal.com/game/ghostlore/info/#/
is correct link, but doesn't have game art

Other links with doubled names:

https://isthereanydeal.com/game/gearofglasseolarnswargearofglasseolarnswar/info/
vs
https://isthereanydeal.com/game/gearofglasseolarnswar/info/

**Comment by MarkitkaM** [comment]
The "Hacker Simulator" will be split with the "Hacker Simulator [UPDATED]" via -> Entries to split #2323

The "Ghostlore" and the "Gear of Glass: Eolarn's war" will be merged with their duplicated entries with duplicated names via -> Entries to merge #2324
