### ISSUE TITLE
Game Mismatch- Wanderer

### ISSUE THREAD

**Issue by Faedelity** [IsThereAnyDeal/IsThereAnyDeal-Issues#2983]
I have this game in my wishlist on Steam:
https://store.steampowered.com/app/1599560/Wanderer/

This is the game it brought up on my waitlist:
https://isthereanydeal.com/game/wanderer/info/

I don't see the game I actually want anywhere on ITAD, so I suspect it isn't in the database at all, possibly due to the matching names. I have noticed a few like this (didn't have time to report at the time), so it looks like some work on the matching when a common name is used might be in order.

**Comment by MarkitkaM** [comment]
https://isthereanydeal.com/game/wanderer/info/ -> The price list contains also the game you meant on Steam 
https://store.steampowered.com/app/1599560/Wanderer/. This is a bug. Games will be split via "Entries to split #2323"

Duplicated #2675
