### ISSUE TITLE
Duplicate entry - Gloomhaven Jaws of the Lion DLC

### ISSUE THREAD

**Issue by awesomeocelot** [IsThereAnyDeal/IsThereAnyDeal-Issues#2984]
https://isthereanydeal.com/game/gloomhavenjawsoflionexpansion/info/

https://isthereanydeal.com/game/gloomhavenjawsoflion/info/

I recommend merging the first entry into the second, since the second URL I posted has the DLC name that matches the official Steam listing, whereas the first does not.

**Comment by MarkitkaM** [comment]
It will be merged -> Entries to merge #2324.
