### ISSUE TITLE
Conflated Games: Assembly and The Assembly

### ISSUE THREAD

**Issue by Faedelity** [IsThereAnyDeal/IsThereAnyDeal-Issues#2985]
These two games are treated by ITAD as if they are one game:

https://store.steampowered.com/app/373650/The_Assembly/

https://store.steampowered.com/app/1777560/Assembly/

There are other stores listed; I did not check them all, but there are two distinct price points.

**Comment by MarkitkaM** [comment]
The games will be split and merged with proper entry -> Entries to split #2323 and Entries to merge #2324

Duplicated https://github.com/IsThereAnyDeal/IsThereAnyDeal-Issues/issues/568
