### ISSUE TITLE
Zool Redimensioned - Entries to be merged

### ISSUE THREAD

**Issue by MagikGimp** [IsThereAnyDeal/IsThereAnyDeal-Issues#2993]
[Entry with prices](https://isthereanydeal.com/game/zoolredimensioned/info/) (Correct title, no marque)
[Entry with no prices](https://isthereanydeal.com/game/zoolredimensionedzoolredimensioned/info/) (Incorrect title, marque present, plugin links to this one)

**Comment by MarkitkaM** [comment]
Entries to merge #2324
