### ISSUE TITLE
Stray (game), and The Stray (streaming video), currently share the same ITAD page.

### ISSUE THREAD

**Issue by B5F** [IsThereAnyDeal/IsThereAnyDeal-Issues#2994]
Stray
https://store.steampowered.com/app/1332010/Stray/

The Stray
https://store.steampowered.com/app/713400/The_Stray/

Both use the same ITAD page: https://isthereanydeal.com/game/stray/info/

**Comment by MatthewZDaniel** [comment]
Came here to report the same issue.

**Comment by MarkitkaM** [comment]
Entries to split #2323
