### ISSUE TITLE
N++ - Entries to be merged

### ISSUE THREAD

**Issue by MagikGimp** [IsThereAnyDeal/IsThereAnyDeal-Issues#2996]
A sponsored game that was recently on the front page no less!
[Clicking on that ad would take you here.](https://isthereanydeal.com/game/nplusplusnplusplus/info/) (No tracked stores!)
[The actual entry](https://isthereanydeal.com/game/nplusplus/info/) ("Ultimate Edition" on marquee.)

**Comment by MarkitkaM** [comment]
Entries to merge #2324
