### ISSUE TITLE
"The Takeover" itch.io entry is a different game

### ISSUE THREAD

**Issue by stkb** [IsThereAnyDeal/IsThereAnyDeal-Issues#2997]
Entry for "The Takeover" https://isthereanydeal.com/game/takeover/info/

The steam link is correct, but the itch.io entry linked is a different game, "Takeover" https://kiani-games.itch.io/httpswwwkianigamescomproduct-pagetakeover

**Comment by MarkitkaM** [comment]
Entries to split #2323
