### ISSUE TITLE
[Incorrect Game Link] Remember Me

### ISSUE THREAD

**Issue by jkrehm** [IsThereAnyDeal/IsThereAnyDeal-Issues#2999]
Incorrect game link for itch.io

Game: Remember Me
URL: https://isthereanydeal.com/game/rememberme/info/
Wrong: https://collectivegee.itch.io/remember-me-final

Fix:
Website doesn’t have this game. Recommend removal of itch.io entry.

**Comment by MarkitkaM** [comment]
Duplication #1943

**Comment by jkrehm** [comment]
For what it's worth, that ticket is for a different game on Itch than the one that I reported.

**Comment by MarkitkaM** [comment]
Yes, your right, anyway we have noted the game from your report already Entries to split #2323

**Comment by jkrehm** [comment]
Thank you!
