### ISSUE TITLE
"Stay Safe" has one wrong entry.

### ISSUE THREAD

**Issue by ancient-animal** [IsThereAnyDeal/IsThereAnyDeal-Issues#3000]
This game has two links to the "itch.io" website:
[https://isthereanydeal.com/game/staysafe/info/](https://isthereanydeal.com/game/staysafe/info/)

This one is for a different game, so it should be removed:
[https://lancelol.itch.io/stay-safe](https://lancelol.itch.io/stay-safe)

This one is the correct one that shouldn't be removed:
[https://plug-in-digital.itch.io/stay-safe](https://plug-in-digital.itch.io/stay-safe)

**Comment by MarkitkaM** [comment]
Entries to split #2323
