### ISSUE TITLE
The Forest Game Page also links to a wrong game called "Forest" on Steam

### ISSUE THREAD

**Issue by JerwinModavi** [IsThereAnyDeal/IsThereAnyDeal-Issues#3002]
The Forest links to 2 games on Steam. The correct "The Forest" game and a wrong game called "Forest".
This prevents the ability to setup a waitlist notification because the wrong game "Forest" is $2 even at full price.

Game Page Link:
https://isthereanydeal.com/game/forest/info/

**Comment by MarkitkaM** [comment]
Thank you for your report it was already reported https://github.com/IsThereAnyDeal/IsThereAnyDeal-Issues/issues/2351 and moved to lists of entry bugs "Entries to split https://github.com/IsThereAnyDeal/IsThereAnyDeal-Issues/issues/2323" and "Entries to merge https://github.com/IsThereAnyDeal/IsThereAnyDeal-Issues/issues/2324".
