### ISSUE TITLE
Oneshot is not the same as One Shot

### ISSUE THREAD

**Issue by RockyKev** [IsThereAnyDeal/IsThereAnyDeal-Issues#3003]
https://store.steampowered.com/app/420530/OneShot/
vs
https://store.steampowered.com/app/1221330/One_Shot/

https://isthereanydeal.com/game/oneshot/info/ 
is pointing to One_Shot

**Comment by MarkitkaM** [comment]
Duplication #1000 -> Entries to split #2323
