### ISSUE TITLE
Luminary and Luminary Online are not the same game

### ISSUE THREAD

**Issue by CyberOrdnance** [IsThereAnyDeal/IsThereAnyDeal-Issues#3004]
The game "Luminary" (https://store.steampowered.com/app/1648360/Luminary/) has the wrong steam link and price.  It is pointing to a different game with a similar name: "Luminary Online: Rise of the GoonZu" (https://store.steampowered.com/app/1685530/Luminary_Online_Rise_of_the_GoonZu/). Thanks.

**Comment by MarkitkaM** [comment]
Entries to split #2323
