### ISSUE TITLE
Elden Ring - incorrect/invalid entry

### ISSUE THREAD

**Issue by cdxemu** [IsThereAnyDeal/IsThereAnyDeal-Issues#3005]
Elden Ring was synced to my waitlist (from my Steam wishlist) as "ELDEN RING ELDEN RING" instead of "Elden Ring". It links to an [invalid entry](https://isthereanydeal.com/game/eldenringeldenring/info/) with no pricing info.

**Comment by MarkitkaM** [comment]
Entries to merge #2324
