### ISSUE TITLE
"30XX" - wrong price and wrong game linked

### ISSUE THREAD

**Issue by DeathDragonAW** [IsThereAnyDeal/IsThereAnyDeal-Issues#3006]
https://isthereanydeal.com/game/iii0xx/info/

Instead of linking to `https://store.steampowered.com/app/1029210/30XX/`
the ITAD page links to this game: `https://store.steampowered.com/app/1576140/2002XX/` ("2002XX")

**Comment by MarkitkaM** [comment]
Duplication #2710 -> Entries to split #2323
