### ISSUE TITLE
House Flipper DLC entries need merged (multiple per DLC)

### ISSUE THREAD

**Issue by Faedelity** [IsThereAnyDeal/IsThereAnyDeal-Issues#3015]
So, here's some for the Merge list, probably because of the "DLC" in the titles.

https://isthereanydeal.com/game/houseflipperpets/info/
https://isthereanydeal.com/game/houseflipperpetsdlc/info/

https://isthereanydeal.com/game/houseflipperhgtv/info/
https://isthereanydeal.com/game/houseflipperhgtvdlc/info/

Also, Garden and Apocalypse don't have an entry with a picture that shows up when searching "House Flipper", and do not have an entry I am seeing that includes the price on Steam. Apocalypse is free, but Garden is not. So I think there is something missing there.

**Comment by MarkitkaM** [comment]
The duplicated links of the games "House Flipper .." were added to the list of Entries to merge #2324

Could you please create new issues for the rest of your report separately for each game with their links?
Thank you
