### ISSUE TITLE
Hearts of Iron IV: No Step Back - Duplicated Entry

### ISSUE THREAD

**Issue by Dave247** [IsThereAnyDeal/IsThereAnyDeal-Issues#3022]
Original ITAD link: https://isthereanydeal.com/game/heartsofironivnostepback/info/

Duplicated ITAD link: https://isthereanydeal.com/game/expansionheartsofironivnostepbackexpansionheartsofironivnostepback/info/

Issue probably caused due to listing name change at some point in the past.

**Comment by MarkitkaM** [comment]
Entries to merge #2324
