### ISSUE TITLE
[Idol Hands] Two different games in one

### ISSUE THREAD

**Issue by ghost** [IsThereAnyDeal/IsThereAnyDeal-Issues#3025]
Title: Idol Hands
App ID: 1745310
Platform: Steam
IsThereAnyDeal URL: https://isthereanydeal.com/game/idolhands/info/
Issue: Two different games in one

<details>
  <summary>Screenshots</summary>
<img src="https://user-images.githubusercontent.com/89172246/177532802-22fa9e1c-aea4-4800-9af2-95768bf30d5f.png">
<img src="https://user-images.githubusercontent.com/89172246/177534450-7c219ae1-9222-4af3-993f-3d81b5bb5151.png">
<img src="https://user-images.githubusercontent.com/89172246/177534723-77cd87ed-aa60-40ba-9fa5-59c8748cdfef.png">
</details>

**Comment by MarkitkaM** [comment]
Entries to split #2323
