### ISSUE TITLE
Final Fantasy 4 Page Combines Two Versions

### ISSUE THREAD

**Issue by burnpsy** [IsThereAnyDeal/IsThereAnyDeal-Issues#3027]
https://isthereanydeal.com/game/finalfantasyiv/info/

The listing for Final Fantasy 4 combines the listings for the Pixel Remaster and the 3D Remake. These should be split up.

Issue #2256 mistakes this as the 3D Remake not having a page for itself.

**Comment by MarkitkaM** [comment]
Entries to split #2323
