### ISSUE TITLE
Typo in Tiny Tina's Wonderlands Epic Store entry

### ISSUE THREAD

**Issue by SoWhy** [IsThereAnyDeal/IsThereAnyDeal-Issues#3028]
https://isthereanydeal.com/game/tinytinaswodnerlands/info/ has a typo ("Wodnerlands" instead of "Wonderlands") and should be merged into https://isthereanydeal.com/game/tinytinaswonderlands/info/#/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
