### ISSUE TITLE
Site confuses two games with similar names (The Wanderer vs. Wanderer)

### ISSUE THREAD

**Issue by BlueRaja** [IsThereAnyDeal/IsThereAnyDeal-Issues#3030]
[Wanderer](https://store.steampowered.com/app/1599560/Wanderer/)  
[The Wanderer](https://store.steampowered.com/app/530860/The_Wanderer/)  

I have the former on my waitlist, but was emailed about a sale for the latter.

**Comment by MarkitkaM** [comment]
Duplication #2675
Entries to split #2323
