### ISSUE TITLE
[Adabana Odd Tales] no price found on Steam

### ISSUE THREAD

**Issue by ghost** [IsThereAnyDeal/IsThereAnyDeal-Issues#3031]
Title: Adabana Odd Tales
App ID: 1094820
Platform: Steam
Currency: Turkish Lira (TL)
IsThereAnyDeal URL: https://isthereanydeal.com/game/adabanaoddtales/info/
Issue: No price found

**Comment by MarkitkaM** [comment]
The price is here https://isthereanydeal.com/game/tuhuayitanadabanaoddtales/info/?country=TR - it needs to be merged -> Entries to merge #2324
