### ISSUE TITLE
[BLUE REFLECTION: Second Light] no price found on Steam

### ISSUE THREAD

**Issue by ghost** [IsThereAnyDeal/IsThereAnyDeal-Issues#3032]
Title: BLUE REFLECTION: Second Light
App ID: 1423600
Platform: Steam
Currency: Turkish Lira (TL)
IsThereAnyDeal URL: https://isthereanydeal.com/game/bluereflectionsecondlightbluereflectionsecondlight/info/
Issue: No price found

**Comment by MarkitkaM** [comment]
The price is here https://isthereanydeal.com/game/bluereflectionsecondlight/info/, it needs to be merged -> Entries to merge #2324
