### ISSUE TITLE
[MONSTER HUNTER RISE] no price found on Steam

### ISSUE THREAD

**Issue by ghost** [IsThereAnyDeal/IsThereAnyDeal-Issues#3033]
Title: MONSTER HUNTER RISE
App ID: 1446780
Platform: Steam
Currency: Turkish Lira (TL)
IsThereAnyDeal URL: https://isthereanydeal.com/game/monsterhunterrisemonsterhunterrise/info/
Issue: No price found

**Comment by MarkitkaM** [comment]
The price is here https://isthereanydeal.com/game/monsterhunterrise/info/, it needs to be merged -> Entries to merge #2324
