### ISSUE TITLE
[Europa Universalis IV: El Dorado] no price found on Steam

### ISSUE THREAD

**Issue by ghost** [IsThereAnyDeal/IsThereAnyDeal-Issues#3034]
Title: Europa Universalis IV: El Dorado
App ID: 338160
Platform: Steam
Currency: Turkish Lira (TL)
IsThereAnyDeal URL: https://isthereanydeal.com/game/expansioneuropauniversalisiveldorado/info/
Issue: No price found

**Comment by MarkitkaM** [comment]
The price is here https://isthereanydeal.com/game/europauniversalisiveldorado/info/, it needs to be merged -> Entries to merge #2324
