### ISSUE TITLE
[Mass Effect™: Andromeda] no price found on Steam

### ISSUE THREAD

**Issue by ghost** [IsThereAnyDeal/IsThereAnyDeal-Issues#3035]
Title: Mass Effect™: Andromeda
App ID: 1238000
Platform: Steam
Currency: Turkish Lira (TL)
IsThereAnyDeal URL: https://isthereanydeal.com/game/masseffectandromeda/info/
Issue: No price found

**Comment by MarkitkaM** [comment]
The price is here https://isthereanydeal.com/game/masseffectandromedadeluxeedition/info/, it needs to be merged -> Entries to merge #2324
