### ISSUE TITLE
[HoneyHoneyHoney!] no price found on Steam

### ISSUE THREAD

**Issue by ghost** [IsThereAnyDeal/IsThereAnyDeal-Issues#3036]
Title: HoneyHoneyHoney!
App ID: 1709590
Platform: Steam
Currency: Turkish Lira (TL)
IsThereAnyDeal URL: https://isthereanydeal.com/game/honeyhoneyhoneyhoneyhoneyhoney/info/
Issue: No price found

**Comment by MarkitkaM** [comment]
The price on Steam is here https://isthereanydeal.com/game/honeyhoneyhoney/info/-> it needs to be merged -> Entries to merge #2324
