### ISSUE TITLE
[The Callisto Protocol] no price found on Steam

### ISSUE THREAD

**Issue by ghost** [IsThereAnyDeal/IsThereAnyDeal-Issues#3037]
Title: The Callisto Protocol
App ID: 1544020
Platform: Steam
Currency: Turkish Lira (TL)
IsThereAnyDeal URL: https://isthereanydeal.com/game/callistoprotocol/info/
Issue: No price found

**Comment by MarkitkaM** [comment]
The price is here https://isthereanydeal.com/game/callistoprotocoldigitaldeluxeedition/info/, it needs to be merged -> Entries to merge #2324
