### ISSUE TITLE
[Forza Horizon 5] no price found on Steam

### ISSUE THREAD

**Issue by ghost** [IsThereAnyDeal/IsThereAnyDeal-Issues#3038]
Title: Forza Horizon 5
App ID: 1551360
Platform: Steam
Currency: Turkish Lira (TL)
IsThereAnyDeal URL: https://isthereanydeal.com/game/forzahorizonv/info/
Issue: No price found

**Comment by MarkitkaM** [comment]
The price is here https://isthereanydeal.com/game/forzahorizonvstandardedition/info/, it needs to be merged -> Entries to merge #2324
