### ISSUE TITLE
[FINAL FANTASY XIV: Endwalker] no price found on Steam

### ISSUE THREAD

**Issue by ghost** [IsThereAnyDeal/IsThereAnyDeal-Issues#3039]
Title: FINAL FANTASY XIV: Endwalker
App ID: 1592500
Platform: Steam
Currency: Turkish Lira (TL)
IsThereAnyDeal URL: https://isthereanydeal.com/game/finalfantasyxivendwalker/info/
Issue: No price found

**Comment by MarkitkaM** [comment]
The price is here https://isthereanydeal.com/game/finalfantasyxivendwalkercollectorsedition/info/ and https://isthereanydeal.com/game/finalfantasyxivendwalkerstandardedition/info/, it needs to be merged -> Entries to merge #2324
