### ISSUE TITLE
Cannot update collection

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#304]
Hey there!

I'm new to ITAD and yesterday I linked my [Steam](http://steamcommunity.com/id/tkd21/) account to the site.Problem is : I can't update my collection and I don't think automatic updates work either. I get the following error: 

"The requested content cannot be loaded.
Please try again later."

[Issue created by [deleted]: 2015-09-17]

[Comment created by tfedor: 2015-09-17]
I'm working on a full Collection revamp, it will fix this issue as well.

**Comment by MarkitkaM** [comment]
The account is private.
