### ISSUE TITLE
[God of War] no price found on Steam

### ISSUE THREAD

**Issue by ghost** [IsThereAnyDeal/IsThereAnyDeal-Issues#3044]
Title: God of War
App ID: 1593500
Platform: Steam
Currency: Turkish Lira (TL)
IsThereAnyDeal URL: https://isthereanydeal.com/game/godofwargodofwar/info/
Issue: No price found

**Comment by MarkitkaM** [comment]
I found it here https://isthereanydeal.com/game/godofwar/info/ it must be merged -> Entries to merge #2324
