### ISSUE TITLE
Orcs Must Die! 3 - Cold as Eyes DLC appears three times

### ISSUE THREAD

**Issue by SoWhy** [IsThereAnyDeal/IsThereAnyDeal-Issues#3055]
https://isthereanydeal.com/game/orcsmustdieiiicoldaseyes/info/#/
https://isthereanydeal.com/game/orcsmustdieiiicoldaseyesexpansion/info/
https://isthereanydeal.com/game/orcsmustdieiiicoldaseyesdlcorcsmustdieiiicoldaseyes/info/#/

need to be merged into a single entry

**Comment by MarkitkaM** [comment]
Entries to merge #2324
