### ISSUE TITLE
The game eden* is missing its Steam link

### ISSUE THREAD

**Issue by Keiyuu** [IsThereAnyDeal/IsThereAnyDeal-Issues#3058]
https://isthereanydeal.com/game/edenasterisk/info/
This game should link to https://store.steampowered.com/app/315810/eden/

Edit:
Looks like it's linked to a wrong profile: https://isthereanydeal.com/game/eden/info/
Faiths End is a different game: https://store.steampowered.com/app/888020/Faiths_End__2D_Survival_Horror/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
