### ISSUE TITLE
The Saboteur - wrong games listed

### ISSUE THREAD

**Issue by kabamaru** [IsThereAnyDeal/IsThereAnyDeal-Issues#3062]
The "The Saboteur" entry includes games that have similar but not the same title. It should only list the 2009 game by Pandemic Studios / EA, called "The Saboteur". The games "Saboteur" and "Saboteur!" should have separate entries.

**Comment by MarkitkaM** [comment]
I created a new issue with a detailed description. Follow it over there, please #3066 .
