### ISSUE TITLE
Sale reported for other game with similar name: "OneShot" versus "One Shot"

### ISSUE THREAD

**Issue by Fyren** [IsThereAnyDeal/IsThereAnyDeal-Issues#3064]
I have "OneShot" on my Steam wishlist and ITAD set to report sales from it.  The Steam store page for the game on my wishlist is https://store.steampowered.com/app/420530/OneShot/.  It's not currently on sale.

I received an e-mail for a sale reporting it as currently $2 with "Historical low: $2.39 | Last: $4.99 | Best: $4.99."  The name shown in the e-mail is "OneShot" and the image is the same as the above game.  However, the Steam link in the e-mail goes to https://store.steampowered.com/app/1221330/One_Shot/, which is a different game and is actually currently $2.  The name at the top of the Steam store page is "One Shot" with a space, but next to the buy link, it's "OneShot" with no space.  I do not have this game on my wishlist.

Searching for "OneShot" on ITAD, the main game listing is https://isthereanydeal.com/game/oneshot/info/, which has _both_ games listed as on Steam.  Searching for "One Shot" with a space has https://isthereanydeal.com/game/one-shot/info/, which does not show any Steam links, but does have price history.

**Comment by MarkitkaM** [comment]
Duplication #1000
