### ISSUE TITLE
Total War: Warhammer 3 Lists Bundle That Doesn't Contain It

### ISSUE THREAD

**Issue by burnpsy** [IsThereAnyDeal/IsThereAnyDeal-Issues#3069]
For some reason, the page for [Total War: Warhammer III](https://isthereanydeal.com/game/totalwarwarhammeriii/info/) lists [this bundle of I & II on it](https://store.steampowered.com/bundle/9505/Total_War_WARHAMMER_I__II/). The error pushes down the historical low for the game on Steam in an inaccurate manner.

**Comment by Jinxtah** [comment]
Yeah please fix this one.

**Comment by MarkitkaM** [comment]
Entries to split #2323
