### ISSUE TITLE
Empty duplicate: Citizens: Far Lands

### ISSUE THREAD

**Issue by forenta** [IsThereAnyDeal/IsThereAnyDeal-Issues#3076]
Please merge 2 entries for 'Citizens: Far Lands'

Steam ID leads to entry [1] called 'Citizens Citizens' without offers, entry [2] leads to the correct steam offer but title is incomplete, no cover, etc.

[1] https://isthereanydeal.com/game/citizenscitizens/info/
[2] https://isthereanydeal.com/game/citizens/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
