### ISSUE TITLE
Duplicate entries for NIS America titles

### ISSUE THREAD

**Issue by twerner** [IsThereAnyDeal/IsThereAnyDeal-Issues#3079]
Newer titles seem to be grouped together properly. 

https://isthereanydeal.com/game/soulnomadandworldeaters/info/
https://isthereanydeal.com/game/soulnomadworldeaters/info/

https://isthereanydeal.com/game/soulnomadandworldeatersdigitaldeluxeedition/info/
https://isthereanydeal.com/game/soulnomadworldeatersdigitaldeluxeedition/info/

https://isthereanydeal.com/game/soulnomadandworldeatersdigitalartboo/info/
https://isthereanydeal.com/game/soulnomadworldeatersdigitalartbook/info/

https://isthereanydeal.com/game/prinnypresentsnisclassicsvolumeiphantombravehermudatriangleremasteredsoulnomadandworldeaters/info/
https://isthereanydeal.com/game/prinnypresentsnisclassicsvolumeiphantombravepcsoulnomadworldeatersdigitaldeluxeedition/info/

https://isthereanydeal.com/game/phantombravepcdigitalchromaedition/info/
https://isthereanydeal.com/game/phantombravepcdigitalchromaeditionfantomubureibupcdejitaruxiandingbangameplusartbook/info/

https://isthereanydeal.com/game/disgaeavcompletedigitaldoodedition/info/
https://isthereanydeal.com/game/disgaeavcompletedigitaldoodeditionmojiezhanjidisugaiavdejitaruxiandingbangameplusartbook/info/

https://isthereanydeal.com/game/disgaeavcompletemojiezhanjidisugaiav/info/
https://isthereanydeal.com/game/disgaeavcomplete/info/

https://isthereanydeal.com/game/disgaeaivcomplete/info/
https://isthereanydeal.com/game/disgaeaivcompleteplus/info/

https://isthereanydeal.com/game/disgaeaivcompleteplusdigitaldoodedition/info/
https://isthereanydeal.com/game/disgaeaivcompleteplusdigitaldoodeditiongameplusartbook/info/

https://isthereanydeal.com/game/disgaeapc/info/
https://isthereanydeal.com/game/disgaeapcmojiezhanjidisugaiapc/info/

https://isthereanydeal.com/game/disgaeapcdigitaldoodedition/info/
https://isthereanydeal.com/game/disgaeapcdigitaldoodeditionmojiezhanjidisugaiapcdejitaruxiandingbangameplusartbook/info/

https://isthereanydeal.com/game/disgaeaiipc/info/
https://isthereanydeal.com/game/disgaeaiipcmojiezhanjidisugaiaiipc/info/

https://isthereanydeal.com/game/disgaeaiipcdigitaldoodedition/info/
https://isthereanydeal.com/game/disgaeaiipcdigitaldoodeditionmojiezhanjidisugaiaiipcdejitaruxiandingbangameplusartbook/info/

https://isthereanydeal.com/game/disgaeaipcplusdisgaeaiipcdigitaldoodseditiongamesplusartbooks/info/
https://isthereanydeal.com/game/disgaeaipcplusdisgaeaiipcdigitaldoodseditionmojiezhanjidisugaiapcmojiezhanjidisugaiaiipcdejitaruxiandingbangamesplusartbooks/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
