### ISSUE TITLE
Ready Or Not - Wrong game listed as on sale

### ISSUE THREAD

**Issue by nullReaction** [IsThereAnyDeal/IsThereAnyDeal-Issues#3080]
https://isthereanydeal.com/game/readyornot/info/     

Ready or Not sale page is listing ( https://store.steampowered.com/app/2057370/Midnight_Memories_First_Chapter/ )  under its sale section.

**Comment by TH3-5L0TH** [comment]
It appears the wrong Steam appid is being used.

Currently it's using
https://store.steampowered.com/app/2057370

When it should be using
https://store.steampowered.com/app/1144200

**Comment by MarkitkaM** [comment]
Now it seems to be correct, Steam is linked to https://store.steampowered.com/app/1144200/Ready_or_Not/
