### ISSUE TITLE
The game you have listed as Sequence is now called "Before The Echo".

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#309]
The game you have listed as Sequence is now called "Before The Echo". This is confirmed in the Steam blurb on the store page

[Issue created by ShandyAndy: 2015-09-22]

**Comment by MarkitkaM** [comment]
Before The Echo -> correct -> https://isthereanydeal.com/game/beforeecho/info/

Sequence -> empty entry https://isthereanydeal.com/game/sequence/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
