### ISSUE TITLE
Incorrect synced game: Ancient: Legacy of Azul

### ISSUE THREAD

**Issue by CubeTheThird** [IsThereAnyDeal/IsThereAnyDeal-Issues#3090]
I noticed my waitlist included an entry for a game called Ancient:
https://isthereanydeal.com/game/ancient/info/

Whereas my steam wishlist has Ancient: Legacy of Azul
https://isthereanydeal.com/game/ancientlegacyofazul/info/#/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
