### ISSUE TITLE
Duplicate (redundant): Crown Trick

### ISSUE THREAD

**Issue by CubeTheThird** [IsThereAnyDeal/IsThereAnyDeal-Issues#3091]
The entry for Crown trick can be found in two places:
https://isthereanydeal.com/game/crowntrickbusiyidehuangguan/info/
https://isthereanydeal.com/game/crowntrick/info/

The first of these does not point to any valid store pages, and should be merged into the second one.

**Comment by MarkitkaM** [comment]
Entries to merge #2324
