### ISSUE TITLE
Duplicate (redundant): ENDER LILIES: Quietus of the Knights

### ISSUE THREAD

**Issue by CubeTheThird** [IsThereAnyDeal/IsThereAnyDeal-Issues#3092]
This game can be found in both of these pages:
https://isthereanydeal.com/game/enderliliesquietusofknights/info/
https://isthereanydeal.com/game/enderlilies/info/

The first of these does not point to a store page, and should be merged with the second.

**Comment by MarkitkaM** [comment]
Entries to merge #2324
