### ISSUE TITLE
Duplicate (redundant): Minecraft Dungeons

### ISSUE THREAD

**Issue by CubeTheThird** [IsThereAnyDeal/IsThereAnyDeal-Issues#3095]
This game can be found in two places:
https://isthereanydeal.com/game/minecraftdungeonsminecraftdungeons/info/
https://isthereanydeal.com/game/minecraftdungeons/info/

The first entry does not point to a valid store page, and should be merged into the second.

**Comment by MarkitkaM** [comment]
Entries to merge #2324
