### ISSUE TITLE
Duplicate: Pronty

### ISSUE THREAD

**Issue by CubeTheThird** [IsThereAnyDeal/IsThereAnyDeal-Issues#3096]
This game can be found in 3 places:
https://isthereanydeal.com/game/prontyfishyadventure/info/
https://isthereanydeal.com/game/pronty/info/
https://isthereanydeal.com/game/qihaibodidamaoxianprontysfishyadventure/info/

The first of these does not point to a valid store page.

**Comment by MarkitkaM** [comment]
Entries to merge #2324
