### ISSUE TITLE
Duplicates: Survivors of the Void

### ISSUE THREAD

**Issue by CubeTheThird** [IsThereAnyDeal/IsThereAnyDeal-Issues#3098]
Multiple duplicates for Risk of Rain 2 DLC Survivors of the Void:
https://isthereanydeal.com/game/survivorsofvoidsurvivorsofvoid/info/
https://isthereanydeal.com/game/riskofrainiisurvivorsofvoid/info/
https://isthereanydeal.com/game/riskofrainiiexpansioni/info/
https://isthereanydeal.com/game/survivorsofvoid/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
