### ISSUE TITLE
Duplicate (redundant): 暖雪 Warm Snow

### ISSUE THREAD

**Issue by CubeTheThird** [IsThereAnyDeal/IsThereAnyDeal-Issues#3100]
https://isthereanydeal.com/game/nuanxuewarmsnownuanxuewarmsnow/info/
https://isthereanydeal.com/game/nuanxuewarmsnow/info/

The first entry does not point to a valid store page.

**Comment by MarkitkaM** [comment]
Entries to merge #2324
