### ISSUE TITLE
Incorrect sorting: AIDEN

### ISSUE THREAD

**Issue by forenta** [IsThereAnyDeal/IsThereAnyDeal-Issues#3101]
https://store.steampowered.com/app/783060/AIDEN/

ITAD-entry with 0 offers: https://isthereanydeal.com/game/aiden/info/
'Dungeon Defenders II'-entry with price for AIDEN listed: https://isthereanydeal.com/game/dungeondefendersii/info/

**Comment by MarkitkaM** [comment]
Entries to split #2323
