### ISSUE TITLE
Wrong Game Listing: The Gunk vs Gunk

### ISSUE THREAD

**Issue by Rhyono** [IsThereAnyDeal/IsThereAnyDeal-Issues#3107]
The Gunk: https://store.steampowered.com/app/1087760/The_Gunk/
Gunk: https://store.steampowered.com/app/1131830/Gunk/

They are being treated as the same game from Augmented Steam and there's only a listing for Gunk: https://isthereanydeal.com/search/?q=the+gunk#/

**Comment by MarkitkaM** [comment]
Entries to split #2323
