### ISSUE TITLE
Wrong Game: Be Hero vs Be The Hero

### ISSUE THREAD

**Issue by Yiab0** [IsThereAnyDeal/IsThereAnyDeal-Issues#3113]
The page for "Be The Hero" on ITAD (https://isthereanydeal.com/game/behero/info/)
is linked to both the Steam page for "Be The Hero" (https://store.steampowered.com/app/744460/BE_THE_HERO/) - a VR action game
and the Steam page for "Be Hero" (https://store.steampowered.com/app/1299790/Be_Hero/) - a farming sim

"Be Hero" should have its own separate ITAD page.

**Comment by MarkitkaM** [comment]
Entries to split #2323
