### ISSUE TITLE
Wrong Game: Pathmaker vs Path Maker

### ISSUE THREAD

**Issue by Yiab0** [IsThereAnyDeal/IsThereAnyDeal-Issues#3114]
The ITAD page for "Path Maker" (https://isthereanydeal.com/game/pathmaker/info/)
is linked to both the Steam page for "Path Maker" (https://store.steampowered.com/app/1412250/Path_Maker/) - a 2D puzzle platformer
and the Steam page for "Pathmaker" (https://store.steampowered.com/app/1404790/Pathmaker/) - a logic puzzle game

"Pathmaker" should have its own separate ITAD page.

**Comment by MarkitkaM** [comment]
Entries to split #2323
