### ISSUE TITLE
Wrong Game: MagNets vs The Magnets

### ISSUE THREAD

**Issue by Yiab0** [IsThereAnyDeal/IsThereAnyDeal-Issues#3115]
The ITAD page for "MagNets" (https://isthereanydeal.com/game/magnets/info/)
is linked to both the Steam page for "MagNets" (https://store.steampowered.com/app/343020/MagNets/) - an action multiplayer game
and the Steam Page for "The Magnets" (https://store.steampowered.com/app/1532780/The_Magnets/) - a logic puzzle game

"The Magnets" should have its own separate ITAD page.

**Comment by MarkitkaM** [comment]
Entries to split #2323
