### ISSUE TITLE
Duplicate: Elden Ring

### ISSUE THREAD

**Issue by andrew-hill** [IsThereAnyDeal/IsThereAnyDeal-Issues#3117]
ITAD pages
https://isthereanydeal.com/game/eldenringeldenring/info/
https://isthereanydeal.com/game/eldenring/info/

Steam page in my wishlist syncs to the first one:
https://store.steampowered.com/app/1245620/ELDEN_RING/

**Comment by MarkitkaM** [comment]
Duplication #3005
