### ISSUE TITLE
Duplicate: Vampire Survivors

### ISSUE THREAD

**Issue by andrew-hill** [IsThereAnyDeal/IsThereAnyDeal-Issues#3118]
ITAD pages:
https://isthereanydeal.com/game/vampiresurvivorsvampiresurvivors/info/
https://isthereanydeal.com/game/vampiresurvivors/info/

Steam page from my wishlist syncs to the first one:
https://store.steampowered.com/app/1794680/Vampire_Survivors/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
