### ISSUE TITLE
Duplicate: Cult of the Lamb

### ISSUE THREAD

**Issue by andrew-hill** [IsThereAnyDeal/IsThereAnyDeal-Issues#3119]
ITAD pages:
- https://isthereanydeal.com/game/cultoflambcultoflamb/info/
- https://isthereanydeal.com/game/cultoflamb/info/

Steam page on my wishlist syncs to the first one:
- https://store.steampowered.com/app/1313140/Cult_of_the_Lamb/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
