### ISSUE TITLE
Game Called Ruin In Your Database Now Called Macabre

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#312]
Game called Ruin in your database is now called Macabre. If you pull up the info on the game it shows a graphic with Macabre included. It is activated within Steam as Macabre

[Issue created by ShandyAndy: 2015-09-23]

**Comment by MarkitkaM** [comment]
The game Macabre™ is not on steam anymore https://store.steampowered.com/search/?term=Macabre%E2%84%A2
-> tracked only for Humble Widgets with propper name https://isthereanydeal.com/game/macabre/info/
