### ISSUE TITLE
Duplicate: Ender Lilies: Quietus of the Knights

### ISSUE THREAD

**Issue by andrew-hill** [IsThereAnyDeal/IsThereAnyDeal-Issues#3120]
ITAD pages:
- https://isthereanydeal.com/game/enderliliesquietusofknights/info/
- https://isthereanydeal.com/game/enderlilies/info/

Steam page on my wishlist syncs to the first one:
https://store.steampowered.com/app/1369630/ENDER_LILIES_Quietus_of_the_Knights/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
