### ISSUE TITLE
Duplicate: Factorio

### ISSUE THREAD

**Issue by andrew-hill** [IsThereAnyDeal/IsThereAnyDeal-Issues#3121]
ITAD pages:
- https://isthereanydeal.com/game/factoriofactorio/info/
- https://isthereanydeal.com/game/factorio/info/

Steam page on my wishlist syncs to the second (the correct one), but the first exists too so is perhaps syncing from some other page:
- https://store.steampowered.com/app/427520/Factorio/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
