### ISSUE TITLE
Duplicate: Final Fantasy VII Remake Intergrade

### ISSUE THREAD

**Issue by andrew-hill** [IsThereAnyDeal/IsThereAnyDeal-Issues#3122]
ITAD pages:
- https://isthereanydeal.com/game/finalfantasyviiremake/info/
- https://isthereanydeal.com/game/finalfantasyviiremakeintergrade/info/

Steam Page from my wishlist syncs to the second one, but the first exists too and should probably be merged:
- https://store.steampowered.com/app/1462040/FINAL_FANTASY_VII_REMAKE_INTERGRADE/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
