### ISSUE TITLE
Wrong game: [The] Colonists

### ISSUE THREAD

**Issue by forenta** [IsThereAnyDeal/IsThereAnyDeal-Issues#3125]
In [1] there are 6 offers, but only the offer on itch.io is the correct game. All the other offers should apply to [2] where there isn't any deal right.

[1] https://isthereanydeal.com/game/colonists/info/
[2] https://isthereanydeal.com/game/thecolonists/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
