### ISSUE TITLE
Waitlist deals sometimes links to the wrong game

### ISSUE THREAD

**Issue by RonnieViklund** [IsThereAnyDeal/IsThereAnyDeal-Issues#3135]
This has happened several times, I get a notification about a deal which brings me to a game on steam that I have not wish-listed.

For example I have wishlisted "GUILT: The Deathless" on steam (see https://store.steampowered.com/app/1047950/GUILT_The_Deathless/), but on isthereanydeal the same game simply has the short name "GUILT" but with the correct banner graphics for "GUILT: The Deathless" (see https://isthereanydeal.com/game/guilt/info/) if you check the discount it links to another game on steam that is named "GUILT" (see https://store.steampowered.com/app/2108990/GUILT/).

So it seems like colons (and possibly other special characters?) in the name might be breaking things, the title for games on isthereanydeal seems to omit colons and all trailing characters and then the deals for that game seem to link to the wrongly named title instead of the proper game.

**Comment by RonnieViklund** [comment]
Possibly same or similar to this issue https://github.com/IsThereAnyDeal/IsThereAnyDeal-Issues/issues/3131

**Comment by MarkitkaM** [comment]
Entries to split #2323
