### ISSUE TITLE
Rise & Shine missing Steam link

### ISSUE THREAD

**Issue by mewmaster300** [IsThereAnyDeal/IsThereAnyDeal-Issues#3146]
https://isthereanydeal.com/log/#/page:game/info?plain=riseandshine
https://store.steampowered.com/app/347290/Rise__Shine/

**Comment by MarkitkaM** [comment]
You can find the game with the Steam price here https://isthereanydeal.com/game/riseshine/info/, but it must be merged via -> Entries to merge #2324
