### ISSUE TITLE
King's Quest and King's Quest: Season Pass listed on Season Pass page

### ISSUE THREAD

**Issue by mewmaster300** [IsThereAnyDeal/IsThereAnyDeal-Issues#3147]
The original game's page also empty -
https://isthereanydeal.com/log/#/page:game/info?plain=kingsquestseasonpass
https://isthereanydeal.com/game/kingsquest/info/
https://store.steampowered.com/app/345390/Kings_Quest/

**Comment by MarkitkaM** [comment]
Entries to split #2323
