### ISSUE TITLE
Wrong Game: "Wolf PACK" and "Wolfpack"

### ISSUE THREAD

**Issue by tinoue** [IsThereAnyDeal/IsThereAnyDeal-Issues#3151]
The ITAD page for "Wolf Pack" (https://isthereanydeal.com/game/wolfpack/info/)
is linked to both the Steam page for "Wolf PACK" (https://store.steampowered.com/sub/770867/) - a FPS game bundle
and the Steam Page for "Wolfpack" (https://store.steampowered.com/app/490920/Wolfpack/) - a sumbarine simulation

"Wolfpack" should have its own separate ITAD page.

Thanks.

**Comment by MarkitkaM** [comment]
Duplication #2386
Entries to split #2323
