### ISSUE TITLE
No official page for The Quarry, PC(Steam)

### ISSUE THREAD

**Issue by firingthoughts** [IsThereAnyDeal/IsThereAnyDeal-Issues#3156]
There's no official page for the Quarry, it only has two separate listings for xbox. The top game shown in the list is Drill down, not the quarry. 
https://store.steampowered.com/app/1577120/The_Quarry/

**Comment by MarkitkaM** [comment]
It is here https://isthereanydeal.com/game/quarry/info/

**Comment by firingthoughts** [comment]
That is the wrong game or thumbnail as I mentioned, drill down is another game.
________________________________
