### ISSUE TITLE
`Re-volt` recognized as `Revolt` on waitlist

### ISSUE THREAD

**Issue by Slowacki** [IsThereAnyDeal/IsThereAnyDeal-Issues#3158]
If you add the game [Re-volt](https://store.steampowered.com/app/287310/ReVolt/) to your Steam wishlist and it's imported to your IsThereAnyDeal Waitlist it's actually incorrectly imported as a different product: [Revolt](https://store.steampowered.com/app/416330/Revolt/)

**Comment by MarkitkaM** [comment]
Entries to split #2323
