### ISSUE TITLE
Merge: RESIDENT EVIL 2 / BIOHAZARD RE:2 Deluxe Edition

### ISSUE THREAD

**Issue by puddydoo** [IsThereAnyDeal/IsThereAnyDeal-Issues#3165]
https://isthereanydeal.com/game/residenteviliibiohazardreiideluxeedition/info/
https://isthereanydeal.com/game/residenteviliideluxeedition/info/
https://isthereanydeal.com/game/residenteviliideluxe/info/
https://isthereanydeal.com/game/residenteviliibiohazardreiideluxe/info/
https://isthereanydeal.com/game/residenteviliibiohazardreiideluxeeditionpreorder/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
