### ISSUE TITLE
Merge: Resident Evil: Revelations 2 Deluxe Edition

### ISSUE THREAD

**Issue by puddydoo** [IsThereAnyDeal/IsThereAnyDeal-Issues#3166]
https://isthereanydeal.com/game/residentevilrevelationsiideluxeedition/info/
https://isthereanydeal.com/game/residentevilrevelationsiideluxe/info/
https://isthereanydeal.com/game/residentevilrevelationsiibiohazardrevelationsiideluxeedition/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
