### ISSUE TITLE
Merge: Resident Evil 7 Biohazard

### ISSUE THREAD

**Issue by puddydoo** [IsThereAnyDeal/IsThereAnyDeal-Issues#3167]
https://isthereanydeal.com/game/residentevilviibiohazard/info/
https://isthereanydeal.com/game/residentevilvii/info/
https://isthereanydeal.com/game/residentevilviibiohazardbiohazardviiresidentevil/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
