### ISSUE TITLE
Merge: RESIDENT EVIL 7 biohazard Gold Edition

### ISSUE THREAD

**Issue by puddydoo** [IsThereAnyDeal/IsThereAnyDeal-Issues#3168]
https://isthereanydeal.com/game/residentevilviibiohazardgoldedition/info/
https://isthereanydeal.com/game/residentevilviigoldedition/info/
https://isthereanydeal.com/game/residentevilviigold/info/
https://isthereanydeal.com/game/residentevilviibiohazardgold/info/
https://isthereanydeal.com/game/residentevilviibiohazardgoldeditionxboxonewini0pcdownloadcode/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
