### ISSUE TITLE
Merge: Resident Evil 7 biohazard Season Pass

### ISSUE THREAD

**Issue by puddydoo** [IsThereAnyDeal/IsThereAnyDeal-Issues#3169]
https://isthereanydeal.com/game/residentevilviibiohazardseasonpass/info/
https://isthereanydeal.com/game/residentevilviiseasonpass/info/
https://isthereanydeal.com/game/residentevilviibiohazardviiseasonpass/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
