### ISSUE TITLE
Merge: RESIDENT EVIL 2 / BIOHAZARD RE:2 Standard Edition

### ISSUE THREAD

**Issue by puddydoo** [IsThereAnyDeal/IsThereAnyDeal-Issues#3170]
https://isthereanydeal.com/game/residenteviliibiohazardreiistandardedition/info/
https://isthereanydeal.com/game/residentevilii/info/
https://isthereanydeal.com/game/residenteviliibiohazardreii/info/

**Comment by puddydoo** [comment]
Related to #3063

**Comment by MarkitkaM** [comment]
Entries to merge #2324
