### ISSUE TITLE
Merge/Split: Resident Evil 0 / biohazard 0 HD Remaster

### ISSUE THREAD

**Issue by puddydoo** [IsThereAnyDeal/IsThereAnyDeal-Issues#3171]
https://isthereanydeal.com/game/residentevil0biohazard0hdremaster/info/
https://isthereanydeal.com/game/residentevil0hd/info/
https://isthereanydeal.com/game/residentevil0/info/
https://isthereanydeal.com/game/residentevil0hdremaster/info/
https://isthereanydeal.com/game/residentevil0remasterhd/info/

These should be merged, however, the itch.io link contained in https://isthereanydeal.com/game/residentevil0/info/ is a different game and should be split.

**Comment by MarkitkaM** [comment]
Entries to merge #2324
Entries to split #2323
