### ISSUE TITLE
Merge: FTL: Faster Than Light; FTL: Advanced Edition

### ISSUE THREAD

**Issue by Cimanyd0** [IsThereAnyDeal/IsThereAnyDeal-Issues#3177]
https://isthereanydeal.com/game/ftlfasterthanlight/info/
https://isthereanydeal.com/game/ftladvancededition/info/

Advanced Edition is a free expansion for FTL: Faster Than Light, built into the base game for everyone who owns the base game. There are no versions of FTL without AE. All these stores are selling the same game, just under a different name in GOG's case.

Also the Origin link is broken, because [Origin stopped selling it in June.](https://www.ea.com/ea-pc-third-party-titles-2022)

**Comment by MarkitkaM** [comment]
Entries to merge #2324
