### ISSUE TITLE
The 'Ghostrunner' base game is actually monitoring/displaying a DLC pack

### ISSUE THREAD

**Issue by PMTabs** [IsThereAnyDeal/IsThereAnyDeal-Issues#3178]
https://isthereanydeal.com/#/page:game/info?plain=ghostrunner

The base game is here:

https://store.steampowered.com/app/1139900/Ghostrunner/

When you click through to Steam via ITAD, however, it takes you to the following DLC instead:

https://store.steampowered.com/app/1760130/Ghostrunner__Halloween_Pack/

The price history is also reflecting changes to the DLC and not the base game.

**Comment by MarkitkaM** [comment]
Entries to split #2323
