### ISSUE TITLE
please show Steam link if game is on Steam

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#318]
If you look at the game info page for Pixel Puzzles 2: Anime ( https://isthereanydeal.com/specials/#/page:game/info?plain=pixelpuzzlesiianime ), there's a Steam rating shown under the Reviews heading, so ITAD knows it's on Steam, but there's no link to the Steam page. It would sure be convenient to have one! (and considering there are links to Wikipedia, Youtube and Metacritic, omitting Steam seems odd)

(I assume there is no Steam line under "Current Deals" (which I usually rely on) because it's not discounted there? Is a "deal" necessarily a discount, or just a game offered for sale?)

[Issue created by bb34887: 2015-09-29]
[Last updated on bitbucket: 2017-03-30]

[Comment created by tfedor: 2017-03-30]
Seems like my fixed helped, here are current counts. If you still find any game that's missing let me know

```
au 26646
br 26554
ca 26572
cn 24898
eu1 26687
eu2 26691
ru 26385
tr 26415
uk 26678
us 26748
```

[Comment created by tfedor: 2017-03-30]
I've tried something, let's give it a day or two to see whether missing titles appear. For future check I'm pasting current catalog counts from Steam:

```
au 21207
br 21168
ca 20835
cn 19603
eu1 21333
eu2 21451
ru 21299
tr 21332
uk 21358
us 21210
```

[Comment created by tfedor: 2017-03-30]
It's a bug. Unfortunately, but I'm doing what I can.

Heroes of Arca is currently shown in 6 regions, not sure why it's missing from the rest. Looking into database it was discovered, but its page have not been loaded yet.

[Comment created by bb34887: 2017-03-30]
A year and a half later, and this is [still happening](http://imgur.com/a/f1Zay). There is no visible problem on the [status page](https://isthereanydeal.com/status/), and even if there was, you should be caching such rarely-changing information as the existence of a game on steam and the link to the store page!

When I open the "page:game/info" popup (whatever it is called?) for a game, and ITAD knows the game is on Steam (as evidenced by having a Steam user review score), I expect there to be a link to the Steam store page, so I don't have go searching for it.

Perhaps I am misunderstanding something. What is your definition of a Deal? Does a game have to be discounted to be a Deal, or does it just have to be available for sale?

[Comment created by tfedor: 2015-09-30]
By the way, unless the parser's terribly broken (and thus won't be showing deals), links may be missing only for games not on sale. Deals for Steam are refreshed each 30 minutes so if some page can't be loaded now it will probably loaded next 30 minutes. Catalog, on the other hand is checked each 23 hours. Since there's not one page that would list all prices and ITAD has to go through Steam store it may happen that sometimes loading will fail somewhere in the middle.

[Comment created by tfedor: 2015-09-30]
It looks like there's some problem with US region https://isthereanydeal.com/status/

I'll take a look at it when I finish Collections update.

[Comment created by TheAtomicPenguin: 2015-09-30]
I've been having this issue for 2 days. EVERY game I click on from my isthereanydeal.com email notices is missing Steam links. All of them. Even when I click links from previous older emails that I KNOW had Steam listed a few days ago (and they all should), Steam does not show up now.

Shopping for deals when you can't easily click the links to see the games on Steam is like trying to make a Peanut Butter & Jelly sandwich without bread. Sloppy, messy & ultimately not very filling ;p

[Comment created by bb34887: 2015-09-29]
It's not the first time I've noticed a game info page missing the Steam deal line though, far from it.

[Comment created by bb34887: 2015-09-29]
Either you fixed that a second after I posted it, or it's an "intermittent fault", which probably makes it hard to debug :(

![pixelpuzzles2-2.PNG](https://bitbucket.org/repo/b6qGGA/images/2501743074-pixelpuzzles2-2.PNG)

**Comment by MarkitkaM** [comment]
Solved within the conversation.
