### ISSUE TITLE
Two very different items listed under https://isthereanydeal.com/game/subverse/info/

### ISSUE THREAD

**Issue by Shadowpheonix** [IsThereAnyDeal/IsThereAnyDeal-Issues#3184]
There are two very different items listed under https://isthereanydeal.com/game/subverse/info/

1 = https://store.steampowered.com/app/1001630/ which is a video series, and is always available for $0.00 (IE: free).
2 = https://store.steampowered.com/app/1034140/ which is a game that has no relation to the video series, and is usually $29.99.

**Comment by MarkitkaM** [comment]
Duplication #2145

Entries to split #2323
