### ISSUE TITLE
Journey incorrectly linked with games on steam and itch.io

### ISSUE THREAD

**Issue by skullriot** [IsThereAnyDeal/IsThereAnyDeal-Issues#3186]
https://isthereanydeal.com/game/journey/info/

Game page for Journey is associated with a listing of the same name on itch.io and a bundle on steam which is a different game than the other listings. Causes mistakes when you have automated filters set up for notifications

the fanatical page for the correct game:
https://www.fanatical.com/en/game/journey?

the page linked on the itad page that is under the steam listing:
https://store.steampowered.com/bundle/25486/Journey/

the page linked for itch.io:
https://journeygame.itch.io/journey

note that the steam and itch pages are not the correct game. There is a second steam listing on the page which does link to the correct game.

**Comment by dhowland** [comment]
+1

**Comment by remoteman213** [comment]
+1

**Comment by MarkitkaM** [comment]
Entries to split #2323
