### ISSUE TITLE
Issue with Master of Magic page

### ISSUE THREAD

**Issue by FortyMinutes** [IsThereAnyDeal/IsThereAnyDeal-Issues#3188]
This page (https://isthereanydeal.com/game/masterofmagic/info/) appears to be mixing together the old version (regular price $5.99) and the new remaster (regular price $39.99).

Since the old and new versions are being mixed together, it thinks the old version on sale at GOG matches my waitlist looking for a sale on the new version (and it thinks the lowest price points for the new version are the same as the lowest price points for the original).

I think these should be two different pages: one for the original, one for the new remaster.

**Comment by MarkitkaM** [comment]
Entries to split #2323
