### ISSUE TITLE
Nebulous: Fleet Command's steam page is attached to the wrong game

### ISSUE THREAD

**Issue by romano21A** [IsThereAnyDeal/IsThereAnyDeal-Issues#3189]
[Nebulous: Fleet Command](https://isthereanydeal.com/game/nebulousfleetcommand/info/) is available on Steam but not listed as such on ITAD.
Instead the Steam store entry is listed on the ITAD page for [Nebulous](https://isthereanydeal.com/game/nebulous/info/) (a different game) which now has to Steam entries

**Comment by MarkitkaM** [comment]
Entries to split #2323
