### ISSUE TITLE
Merge: Resident Evil 4 (2014)

### ISSUE THREAD

**Issue by puddydoo** [IsThereAnyDeal/IsThereAnyDeal-Issues#3196]
https://isthereanydeal.com/game/residenteviliv2014/info/
https://isthereanydeal.com/game/residentevilivultimatehdedition/info/
https://isthereanydeal.com/game/residentevilivhd/info/
https://isthereanydeal.com/game/residentevilivbiohazardiv/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
