### ISSUE TITLE
Merge: Resident Evil 5 GOLD Edition

### ISSUE THREAD

**Issue by puddydoo** [IsThereAnyDeal/IsThereAnyDeal-Issues#3200]
https://isthereanydeal.com/game/residentevilvgoldedition/info/
https://isthereanydeal.com/game/residentevilvbiohazardvgoldedition/info/
https://isthereanydeal.com/game/residentevilvgold/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
