### ISSUE TITLE
Merge: Resident Evil 5 - UNTOLD STORIES BUNDLE

### ISSUE THREAD

**Issue by puddydoo** [IsThereAnyDeal/IsThereAnyDeal-Issues#3201]
https://isthereanydeal.com/game/residentevilvuntoldstoriesbundle/info/
https://isthereanydeal.com/game/residentevilvuntoldstories/info/
https://isthereanydeal.com/game/residentevilvuntoldstoriesdlc/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
