### ISSUE TITLE
Split: Cuphead & The Delicious Last Course

### ISSUE THREAD

**Issue by puddydoo** [IsThereAnyDeal/IsThereAnyDeal-Issues#3205]
https://isthereanydeal.com/game/cupheaddeliciouslastcourse/info/

The DLC "Cuphead - The Delicious Last Course" is mixed with the bundle called "Cuphead & The Delicious Last Course" which is a bundle of the base game and DLC.

**Comment by MarkitkaM** [comment]
Entries to split #2323
