### ISSUE TITLE
Merge: Mega Man Zero/ZX Legacy Collection

### ISSUE THREAD

**Issue by puddydoo** [IsThereAnyDeal/IsThereAnyDeal-Issues#3207]
https://isthereanydeal.com/game/megamanzerozxlegacycollection/info/
https://isthereanydeal.com/game/megamanzerozxlegacycollectionrow/info/
https://isthereanydeal.com/game/megamanzerozxlegacycollectionrokkumanzeroandzekusudaburuhirokorekushon/info/
https://isthereanydeal.com/game/megamanzerozxlegacycollectionrokkumanzerozekusudaburuhirokorekushon/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
