### ISSUE TITLE
Merge: Mega Man X Legacy Collection 2

### ISSUE THREAD

**Issue by puddydoo** [IsThereAnyDeal/IsThereAnyDeal-Issues#3209]
https://isthereanydeal.com/game/megamanxlegacycollectionii/info/
https://isthereanydeal.com/game/megamanxlegacycollectioniirockmanxanniversarycollectionii/info/
https://isthereanydeal.com/game/megamanxlegacycollectioniirokkumanxanibasarikorekushonii/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
