### ISSUE TITLE
Merge: Mega Man X Legacy Collection

### ISSUE THREAD

**Issue by puddydoo** [IsThereAnyDeal/IsThereAnyDeal-Issues#3210]
https://isthereanydeal.com/game/megamanxlegacycollection/info/
https://isthereanydeal.com/game/megamanxlegacycollectionrow/info/
https://isthereanydeal.com/game/megamanxlegacycollectionrockmanxanniversarycollection/info/
https://isthereanydeal.com/game/megamanxlegacycollectionrokkumanxanibasarikorekushon/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
