### ISSUE TITLE
Merge: Mega Man X Legacy Collection 1+2 Bundle

### ISSUE THREAD

**Issue by puddydoo** [IsThereAnyDeal/IsThereAnyDeal-Issues#3211]
https://isthereanydeal.com/game/megamanxlegacycollectioniplusiibundle/info/
https://isthereanydeal.com/game/megamanxlegacycollectioniiibundle/info/
https://isthereanydeal.com/game/megamanxlegacycollectioniplusiibundlerokkumanxanibasarikorekushoniplusiibandoru/info/
https://isthereanydeal.com/game/megamanxlegacycollectioniplusiibundlerokkumanxanibasarikorekushoniplusiibandorurow/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
