### ISSUE TITLE
Merge: Mega Man Legacy Collection 2

### ISSUE THREAD

**Issue by puddydoo** [IsThereAnyDeal/IsThereAnyDeal-Issues#3212]
https://isthereanydeal.com/game/megamanlegacycollectionii/info/
https://isthereanydeal.com/game/megamanlegacycollectioniirokkumankurashikkusukorekushonii/info/
https://isthereanydeal.com/game/megamanlegacycollectioniiaaaaaaaaaaaaaaaaaii/info/
https://isthereanydeal.com/game/megamanlegacycollectioniirow/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
