### ISSUE TITLE
Merge: HITMAN 3

### ISSUE THREAD

**Issue by puddydoo** [IsThereAnyDeal/IsThereAnyDeal-Issues#3215]
https://isthereanydeal.com/game/hitmaniii/info/
https://isthereanydeal.com/game/hitmaniiisteamedition/info/
https://isthereanydeal.com/game/hitmaniiistandardedition/info/
https://isthereanydeal.com/game/hitmaniiistandardeditionsteam/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
