### ISSUE TITLE
Merge: HITMAN 3 - Deluxe Edition

### ISSUE THREAD

**Issue by puddydoo** [IsThereAnyDeal/IsThereAnyDeal-Issues#3216]
https://isthereanydeal.com/game/hitmaniiideluxeedition/info/
https://isthereanydeal.com/game/hitmaniiisteamdeluxeedition/info/
https://isthereanydeal.com/game/hitmaniiideluxeeditionsteam/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
