### ISSUE TITLE
Wrong Link/Similarly-Named Game: Graveyard Keeper

### ISSUE THREAD

**Issue by 3F2A8C4AE9** [IsThereAnyDeal/IsThereAnyDeal-Issues#3218]
Hello, I'm not sure how to write this out, but here goes.

There's a game, Graveyard Keeper, https://store.steampowered.com/app/599140/Graveyard_Keeper/ that I've been tracking. However, another game, _also_ called graveyard keeper, https://store.steampowered.com/app/2099990/graveyard_keeper/ has replaced the correct game on ITAD as far as waitlist and all goes. 

Also, because lowercase graveyard keeper is free, it also incorrectly reports that uppercase Graveyard Keeper has a historic low of $0.00.

**Comment by MarkitkaM** [comment]
There are two Steam links and one of them is poiting to the wrog game with the same name https://isthereanydeal.com/game/graveyardkeeper/info/

It was already reported #3159
