### ISSUE TITLE
Split: Catmaze

### ISSUE THREAD

**Issue by somethingSTRANGE** [IsThereAnyDeal/IsThereAnyDeal-Issues#3223]
https://isthereanydeal.com/game/catmaze/info/

There are two Steam entries on this info page that point to different games.

1. [The Cat Maze](https://store.steampowered.com/app/2143190/The_Cat_Maze/)
2. [Catmaze](https://store.steampowered.com/app/620220/Catmaze/)

The second one seems correct. The first should be split into a separate game page.

**Comment by MarkitkaM** [comment]
Entries to split #2323
