### ISSUE TITLE
Citadel: Forged with Fire tracking in extension links to wrong game

### ISSUE THREAD

**Issue by Madmick2963** [IsThereAnyDeal/IsThereAnyDeal-Issues#3224]
_Citadel: Forged with Fire_ is hosted on Steam here: 
https://store.steampowered.com/app/487120/Citadel_Forged_with_Fire/

The best price shown is wrong. Weirdly, if you click the "On Origin" hyperlink, it sends you to _Mass Effect 3_ on EA (probably because there is a DLC titled "Citadel" for that game). 

If you click the "Current Best" hyperlink to go to the isthereanydeal website, it sends you to a game called _Citadel_, but this is a different game: 
https://isthereanydeal.com/game/citadel/info/

This is the game it should be tracking: 
https://isthereanydeal.com/game/citadelforgedwithfire/info/

**Comment by MarkitkaM** [comment]
Duplication #3224
Entries to split #2323
