### ISSUE TITLE
Merge: Monster Hunter Stories 2: Wings of Ruin

### ISSUE THREAD

**Issue by puddydoo** [IsThereAnyDeal/IsThereAnyDeal-Issues#3227]
https://isthereanydeal.com/game/monsterhunterstoriesiiwingsofruin/info/
https://isthereanydeal.com/game/monsterhunterstoriesiiwingsofruinforpc/info/
https://isthereanydeal.com/game/monsterhunterstoriesiiwingsofruinstandardedition/info/

**Comment by MarkitkaM** [comment]
ntries to merge #2324
