### ISSUE TITLE
Import Steam Inventory into collection

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#323]
I use my inventory as "games I own, but am not ready to play yet, and if a bundle rolls around with this game then I now have a tradeable inventory copy to trade off"

Since you now have a trade tag, can we import things into the collection this way?  Also, since the contents of the inventory change frequently, it may need to track if it's no longer there any more?

[Issue created by rahul_vaidya: 2015-10-02]

**Comment by MarkitkaM** [comment]
We are not gonna do that.
