### ISSUE TITLE
Total War: WARHAMMER III - Incorrect Steam link and price

### ISSUE THREAD

**Issue by NVQs2** [IsThereAnyDeal/IsThereAnyDeal-Issues#3236]
ITAD page:
[https://isthereanydeal.com/game/totalwarwarhammeriii/info/](url)

The game's Steam page link (and Steam price) are currently linked to the bundle of the previous games ([Total War: WARHAMMER I & II](https://store.steampowered.com/bundle/9505/Total_War_WARHAMMER_I__II/))
The page they should be linked to is:
[https://store.steampowered.com/app/1142710/Total_War_WARHAMMER_III/](url)

This has interfered with the historical lowest price, and I only noticed it as it is currently messing with the best price

**Comment by MarkitkaM** [comment]
Entries to split #2323
