### ISSUE TITLE
Graveyard Keeper - tracking wrong steam game price

### ISSUE THREAD

**Issue by ratva** [IsThereAnyDeal/IsThereAnyDeal-Issues#3240]
The graveyard keeper had two steam price links being tracked - the first one is free and for the wrong game (the wrong game is also called graveyard keeper, but is made by Magic Cat). This causes the 'best price' to show as free.
The right game (by lazy bear games) is still also tracked.
 https://isthereanydeal.com/game/graveyardkeeper/info/#/

**Comment by MarkitkaM** [comment]
Duplication #3159

Entries to split #2323
