### ISSUE TITLE
SimRail: Steam-ID forwards to wrong ITAD-ID

### ISSUE THREAD

**Issue by forenta** [IsThereAnyDeal/IsThereAnyDeal-Issues#3242]
https://isthereanydeal.com/steam/app/1422130/

should lead to
✅ https://isthereanydeal.com/game/simrailrailwaysimulator/info/

leads to
❌ https://isthereanydeal.com/game/simrailii0iiirailwaysimulator/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
