### ISSUE TITLE
App id ignored, multiple games wish similar title (Wanderer)

### ISSUE THREAD

**Issue by asgraf** [IsThereAnyDeal/IsThereAnyDeal-Issues#3247]
I have added following game to my steam wishlist:
https://store.steampowered.com/app/1599560/Wanderer/

Now i keep getting notifications about completetly different games with same name:
https://isthereanydeal.com/game/wanderer/info/

Augmented Steam browser add-on also shows wrong info (from other games) in this game store page:
https://store.steampowered.com/app/1599560/Wanderer/

**Comment by MarkitkaM** [comment]
Duplication #2675

Entries to split #2323
