### ISSUE TITLE
Clanfolk wrong detected

### ISSUE THREAD

**Issue by schnaggi** [IsThereAnyDeal/IsThereAnyDeal-Issues#3251]
I added Clanfolk (https://store.steampowered.com/app/1700870/) in my steam wishlist. If I sync my ITAD account the game is detected as Clanfolk Clanfolk (https://isthereanydeal.com/waitlist/#/page:game/info?plain=clanfolkclanfolk) and there is not price found.

**Comment by MarkitkaM** [comment]
Entries to merge #2324
