### ISSUE TITLE
ELDEN RING wrong detected

### ISSUE THREAD

**Issue by schnaggi** [IsThereAnyDeal/IsThereAnyDeal-Issues#3252]
I added ELDEN RING (https://store.steampowered.com/app/1245620/) in my steam wishlist. If I sync my ITAD account the game is detected as ELDEN RING ELDEN RING (https://isthereanydeal.com/waitlist/#/page:game/info?plain=eldenringeldenring)  and there is not price found.

**Comment by MarkitkaM** [comment]
Duplication #3005
Entries to merge https://github.com/IsThereAnyDeal/IsThereAnyDeal-Issues/issues/2324
