### ISSUE TITLE
God of War wrong detected

### ISSUE THREAD

**Issue by schnaggi** [IsThereAnyDeal/IsThereAnyDeal-Issues#3253]
I added God of War (https://store.steampowered.com/app/1593500/) in my steam wishlist. If I sync my ITAD account the game is detected as God of War God of War (https://isthereanydeal.com/waitlist/#/page:game/info?plain=godofwargodofwar)  and there is not price found.

**Comment by MarkitkaM** [comment]
Duplication #3044
Entries to merge #2324
