### ISSUE TITLE
Dead Space 2008 and Dead Space (remake) have the same ITAD page

### ISSUE THREAD

**Issue by adinklotz** [IsThereAnyDeal/IsThereAnyDeal-Issues#3255]
activating the Isthereanydeal Everywhere extension on the [new one](https://store.steampowered.com/app/1693980/Dead_Space/) and the [original](https://store.steampowered.com/app/17470/Dead_Space_2008/) take you to the same ITAD page https://isthereanydeal.com/game/deadspace/info/

These are tracked on stores as separate games, so they should have different ITAD entries so we can wishlist them separately

**Comment by MarkitkaM** [comment]
Entries to split #2323
