### ISSUE TITLE
The Entropy Centre has duplicate links, imported link from Steam wishlist will never track prices as such

### ISSUE THREAD

**Issue by LinkSlayer64** [IsThereAnyDeal/IsThereAnyDeal-Issues#3258]
This is the link that gets imported: 
https://isthereanydeal.com/game/entropycentreentropycentre/info/

This is the link on the site that tracks prices, also missing an icon.
https://isthereanydeal.com/game/entropycentre/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
