### ISSUE TITLE
incorrect title, extra entry from Amazon listing: Deep Eclipse: New Space Odyssey (Steam)

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#326]
https://isthereanydeal.com/#/search:Deep+Eclipse%3A+New+Space+Odyssey;/scroll:%23gamelist

So Super Duper Bundle #4 uses this version, which seems to have been named by the Amazon store.

https://isthereanydeal.com/specials/#/page:game/info?plain=deepeclipsenewspaceodysseysteam

Thanks.

[Issue created by bugmenot: 2015-10-03]

**Comment by MarkitkaM** [comment]
Amazon is not tracked anymore.

**MERGE ENTRIES:**
https://isthereanydeal.com/game/deepeclipsenewspaceodyssey/info/
https://isthereanydeal.com/game/deepeclipse/info/?

**Comment by MarkitkaM** [comment]
Entries to merge  #2324
