### ISSUE TITLE
"Orwell" and "Orwell: Keeping an Eye on You" are the same game, "Orwell" missing thumbnail because of this.

### ISSUE THREAD

**Issue by LinkSlayer64** [IsThereAnyDeal/IsThereAnyDeal-Issues#3261]
https://isthereanydeal.com/game/orwell/info/

https://isthereanydeal.com/game/orwellkeepinganeyeonyou/info/

"Keeping an Eye on You" only lists Epic Game Store currently, whereas just "Orwell" lists info for Humble, Steam, and Gog.

**Comment by MarkitkaM** [comment]
Duplication #1730 
Entries to merge #2324
