### ISSUE TITLE
"Sword with Sauce" and "Sword with Sauce Alpha" are same game

### ISSUE THREAD

**Issue by LinkSlayer64** [IsThereAnyDeal/IsThereAnyDeal-Issues#3262]
Syncing via wishlist does not produce proper results because of this

https://isthereanydeal.com/game/swordwithsauce/info/

https://isthereanydeal.com/game/swordwithsaucealpha/info/

Non-alpha says game is untracked, however, the alpha is the only version there is.

Alpha which points to Steam properly does not have a thumbnail because of this.

**Comment by MarkitkaM** [comment]
Entries to merge #2324
