### ISSUE TITLE
Witch Hunt

### ISSUE THREAD

**Issue by zelgaris** [IsThereAnyDeal/IsThereAnyDeal-Issues#3265]
Every link on the Witch Hunt ITAD page https://isthereanydeal.com/game/witchhunt/info/#/
is for different game

Origin is for Dragon Age Origins DLC, which is listed on Dragon Age Origins Origin page, and it's free, so it messes up historical low for the whole ITAD entry

Itch and Humble are for two different JRPG games.

And Steam is for the Witch Hunt game on Steam, which header image is used for the ITAD entry.

**Comment by MarkitkaM** [comment]
Duplication #3185

Entries to split #2323
