### ISSUE TITLE
Info about copies from a bundle stay even if game is deleted from collection.

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#327]
Unless I'm misunderstanding something, there is no way to add and re-add games to collections without getting multiple copies.

I'm trying to delete and re-add a bundle to my collection because i want to make sure it it was added with the right price and so on. When I delete the games one by one from the bundle page and re-add them my collection says i have two copies. I can't remove all copies from the game page and save it seems either.

Also the page says "You already own this special." How can I remove it then?

Is there a way to delete a special in one go? Would be awesome if you could edit all the games in one bundle at once also, add the price you paid long after you added it and so on.

http://steamcommunity.com/groups/isthereanydeal/discussions/0/490121928357961672/

[Issue created by tfedor: 2015-10-05]

**Comment by MarkitkaM** [comment]
![image](https://user-images.githubusercontent.com/88401908/140611199-d30be856-d20f-45bd-b204-b107f6c5ff7f.png)

**Comment by MarkitkaM** [comment]
We don't track specials anymore.
