### ISSUE TITLE
Game "Citadel" has a messed up page

### ISSUE THREAD

**Issue by Seibah75** [IsThereAnyDeal/IsThereAnyDeal-Issues#3277]
The first Steam listing and the Fanatical one are for this game: https://store.steampowered.com/app/1378290/The_Citadel/

The Origin listing is for a Mass Effect 3's DLC named Citadel.
The second Steam listing is for a game called "Citadel: Forged with Fire": https://store.steampowered.com/app/487120/Citadel_Forged_with_Fire/

The thumbnail is of a game which is also named "Citadel" on steam, but cannot be purchased: https://store.steampowered.com/app/485590/Citadel/

**Comment by MarkitkaM** [comment]
Entries to split #2323
