### ISSUE TITLE
Bundle Page Missing

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#328]
Hello, I wanted to add a new bundle available, just for my own records and to remember when it would end, I am in no way affiliated with the seller. However the page is missing and it says on your site to contact you should the page be missing. It is: https://www.hrkgame.com. I will try to default to Blink Bundle and pls change it whenever you get time to. thx.

[Issue created by [deleted]: 2015-10-08]
[Last updated on bitbucket: 2019-02-11]

[Comment created by Knightw0lf: 2019-02-11]
this can be closed

[Comment created by bb34887: 2017-03-19]
@Black3ird said:

> Legit sites always use PayPal instead of enforcing other systems.

They accept Paypal now

[Comment created by tfedor: 2016-08-31]
Store has to prove that they have rights to sell keys at given market, online. So for example if you get rights to sell physical copies in Russia, you can't then open the boxes and sell those keys to the rest of the world online.

[Comment created by bb34887: 2016-08-31]
Anonymous, do you mean [https://www.hrkgame.com/randomkeyshop/make-bundle/](https://www.hrkgame.com/randomkeyshop/make-bundle/) ? (I recently bought it, but was annoyed by the proprietary payment system)

Tomas, I am curious what "rights" you need in order to sell games. If they were physical goods, owning them would be sufficient. Is there some legal restriction on selling Steam keys?

[Comment created by Black3ird: 2015-10-28]
HRK is most likely a rebundler using G2A pay system to sell leftover bundle keys. Legit sites always use PayPal instead of enforcing other systems.

[Comment created by tfedor: 2015-10-08]
The guy behind HRK contacted me few days ago and so far wasn't able to prove he has rights to sell those games there.

**Comment by MarkitkaM** [comment]
Solved within the conversation.
