### ISSUE TITLE
Wrong links: The Saboteur

### ISSUE THREAD

**Issue by SoWhy** [IsThereAnyDeal/IsThereAnyDeal-Issues#3281]
Game site:
https://isthereanydeal.com/game/saboteur/info/ 

Correct links:
https://www.gog.com/en/game/saboteur
https://www.ea.com/games/saboteur/the-saboteur

Wrong links (different games):
https://store.steampowered.com/app/1785600/
https://www.gog.com/en/game/the_saboteur

**Comment by MarkitkaM** [comment]
Entries to split #2323
