### ISSUE TITLE
To merge: all Hitman entries for World of Assassination

### ISSUE THREAD

**Issue by MattHorn25** [IsThereAnyDeal/IsThereAnyDeal-Issues#3285]
Hitman 3 and Hitman Trilogy are now merged into a single SKU called Hitman: World of Assassination - it would make sense to merge all of their old entries into one World of Assassination entry (with a separate Deluxe upgrade DLC) and point them to the correct store destinations:

https://isthereanydeal.com/game/hitmaniiihitmantrilogy/info/
https://isthereanydeal.com/game/hitmaniii/info/
https://isthereanydeal.com/game/hitmaniiisteamedition/info/
https://isthereanydeal.com/game/hitmaniiistandardedition/info/
https://isthereanydeal.com/game/hitmanworldofassassination/info/ (this looks like the best candidate to leave active)
https://isthereanydeal.com/game/hitmantrilogy/info/
https://isthereanydeal.com/game/hitmantrilogyepic/info/
https://isthereanydeal.com/game/hitmantrilogysteam/info/

NOT to be confused with Hitman Collection (https://isthereanydeal.com/game/hitmancollection/info/), which is the old Hitman games!

These are the store pages that I'm aware of for the new SKU:

https://store.steampowered.com/sub/672746/
https://www.humblebundle.com/store/hitman-world-of-assassination
https://www.greenmangaming.com/games/hitman-world-of-assassination-pc/
https://store.epicgames.com/en-US/p/hitman-3 (they kept the old URL but it's for World of Assassination now)
https://www.xbox.com/en-us/games/store/hitman-world-of-assassination/9pdrm8bfw1x1

**Comment by MarkitkaM** [comment]
Entries to merge #2324
