### ISSUE TITLE
The Legend of Heroes: Kuro no Kiseki Lists Two Separate Releases

### ISSUE THREAD

**Issue by burnpsy** [IsThereAnyDeal/IsThereAnyDeal-Issues#3287]
So this is a bit of an unusual situation, but...

The Legend of Heroes: Kuro no Kiseki has two separate versions on Steam. One in Chinese and Korean, a rather straight port with some bugs (that's [this one](https://store.steampowered.com/app/1811950/The_Legend_of_Heroes_Kuro_no_Kiseki/) published by Clouded Leopard). One in Japanese with some quality of life additions that will be later patched to include English (that's [this one](https://store.steampowered.com/app/2138610/The_Legend_of_Heroes_Kuro_no_Kiseki/) published by NIS America).

Both versions are [currently listed as the same on the website](https://isthereanydeal.com/game/legendofheroeskuronokiseki/info/), which is awkward since the two different publishers and two different release dates mean they will have separate discounts and separate historical lows. It may be wise to split the listings.

**Comment by MarkitkaM** [comment]
Entries to split #2323
