### ISSUE TITLE
Last Stop (Annapurna) page has links for Last Stop (Tainted Games)

### ISSUE THREAD

**Issue by Brycey92** [IsThereAnyDeal/IsThereAnyDeal-Issues#3294]
[The game named Last Stop released by Annapurna](https://isthereanydeal.com/game/laststop/info/) has links that lead to Steam and itch.io pages for the game named Last Stop released by Tainted Games, which is a totally different game.

**Comment by MarkitkaM** [comment]
Duplication #2302

Entries to split #2323
