### ISSUE TITLE
Incorrect link and title for The Wreck

### ISSUE THREAD

**Issue by safes007** [IsThereAnyDeal/IsThereAnyDeal-Issues#3295]
The page for the game The Wreck (https://isthereanydeal.com/game/wreck/info/) is incorrectly titled as Wreck when it should be The Wreck.

Also, one of the links is to a different itch game called Wreck
![image](https://user-images.githubusercontent.com/72974403/225173458-4eede8c0-09a1-497d-ad9b-4cdd138e93bd.png)

**Comment by MarkitkaM** [comment]
Entries to split #2323
