### ISSUE TITLE
Three different games under one link

### ISSUE THREAD

**Issue by Kondiq** [IsThereAnyDeal/IsThereAnyDeal-Issues#3296]
https://isthereanydeal.com/game/meat/info/

There are three different titles linked as one product:
- M.E.A.T. RPG on Steam
- MEat on itch.io
- M.E.A.T. - Monster Elimination And Tactics on Indiegala

I got notification about the one on itch, while I'm only interested in the Steam game.

**Comment by MarkitkaM** [comment]
Entries to split #2323 

Duplication #2083
