### ISSUE TITLE
To split: Loop/LO-OP/The Loop

### ISSUE THREAD

**Issue by ProfessionalismIsMyMiddleName** [IsThereAnyDeal/IsThereAnyDeal-Issues#3302]
https://isthereanydeal.com/game/loop/info/

Has links to 3 different steam games: loop, loop, LO-OP, and the image and name of a fourth unreleased game, The Loop (https://store.steampowered.com/app/636270/The_Loop/)

**Comment by MarkitkaM** [comment]
Entries to split #2323
