### ISSUE TITLE
Link to wrong free game for Chasm

### ISSUE THREAD

**Issue by ProfessionalismIsMyMiddleName** [IsThereAnyDeal/IsThereAnyDeal-Issues#3303]
https://isthereanydeal.com/game/chasm/info/

Has a steam link to "The Chasm - Mines of madness", a free game.
This creates a lack of notifications for "chasm".
The link should be removed, and the lowest steam price reset.

**Comment by MarkitkaM** [comment]
Entries to split https://github.com/IsThereAnyDeal/IsThereAnyDeal-Issues/issues/2323

Duplication https://github.com/IsThereAnyDeal/IsThereAnyDeal-Issues/issues/1538
