### ISSUE TITLE
Sally Face issues

### ISSUE THREAD

**Issue by ProfessionalismIsMyMiddleName** [IsThereAnyDeal/IsThereAnyDeal-Issues#3306]
The game sally face has multiple issues steeming from its episodic nature:
https://isthereanydeal.com/game/sallyface/info/ Has two links to storepage that sell "sally face episode one" (https://isthereanydeal.com/game/sallyfaceepisodeonestrangeneighbors/info/) (although the gamejolt page also sells the season pass)

https://isthereanydeal.com/game/sallyfaceseasonpass/info/ is missing the gamejolt season pass mentioned above.

https://isthereanydeal.com/game/sallyfaceepisodesiiiiiplusseasonpass/info/
and
https://isthereanydeal.com/game/sallyfaceepisodesiiiiiivpluspreorderv/info/
have no links, and should probably deleted, I think they were previous bundles when all episodes were not released yet.

**Comment by MarkitkaM** [comment]
> The game sally face has multiple issues steeming from its episodic nature:
> https://isthereanydeal.com/game/sallyface/info/ Has two links to storepage that sell "sally face episode one" (https://isthereanydeal.com/game/sallyfaceepisodeonestrangeneighbors/info/) (although the gamejolt page also sells the season pass)
Entries to merge #2324

> https://isthereanydeal.com/game/sallyfaceseasonpass/info/ is missing the gamejolt season pass mentioned 
> above.
#3336

> https://isthereanydeal.com/game/sallyfaceepisodesiiiiiplusseasonpass/info/
> and https://isthereanydeal.com/game/sallyfaceepisodesiiiiiivpluspreorderv/info/
> have no links, and should probably deleted, I think they were previous bundles when all episodes were not released yet.
#3337
