### ISSUE TITLE
To merge: Moncage

### ISSUE THREAD

**Issue by ProfessionalismIsMyMiddleName** [IsThereAnyDeal/IsThereAnyDeal-Issues#3309]
https://isthereanydeal.com/game/moncage/info/
and
https://isthereanydeal.com/game/moncagelongzhongkuimeng/info/
are the same game.
The second link has no stores (I think it was the prerelease link), but should be merged regardless for the sake of the people who wishlisted it before release.

**Comment by MarkitkaM** [comment]
Entries to merge #2324
