### ISSUE TITLE
A Tale of Paper issues

### ISSUE THREAD

**Issue by ProfessionalismIsMyMiddleName** [IsThereAnyDeal/IsThereAnyDeal-Issues#3311]
https://isthereanydeal.com/game/ataleofpaperrefoldededition/info/
https://isthereanydeal.com/game/ataleofpaperrefolded/info/
https://isthereanydeal.com/game/ataleofpaper/info/
Are the same and should be merged.

https://isthereanydeal.com/game/ataleofpaperrefoldededitionsoundtrack/info/
https://isthereanydeal.com/game/ataleofpaperrefoldedsoundtrack/info/
https://isthereanydeal.com/game/ataleofpapersoundtrack/info/
https://isthereanydeal.com/game/ataleofpaperrefoldededitionost/info/
Are the same too.

https://isthereanydeal.com/game/ataleofpaperdigitaldeluxe/info/
https://isthereanydeal.com/game/ataleofpaperrefoldeddigitaldeluxeedition/info/
https://isthereanydeal.com/game/ataleofpaperrefoldededitiondigitaldeluxeedition/info/
Same.

https://isthereanydeal.com/game/ataleofpaperdemo/info/
Is a demo, and should probably be deleted? Not sure what your policy is for demos.

**Comment by MarkitkaM** [comment]
Entries to merge #2324
