### ISSUE TITLE
Alchemist adventure Merges

### ISSUE THREAD

**Issue by ProfessionalismIsMyMiddleName** [IsThereAnyDeal/IsThereAnyDeal-Issues#3312]
https://isthereanydeal.com/game/alchemistadventure/info/
https://isthereanydeal.com/game/alkimyamemoriesoflastalchemist/info/
Should be merged, the game was renamed before release I think.

https://isthereanydeal.com/game/alchemistadventuresoundtrack/info/
https://isthereanydeal.com/game/alchemistadventureost/info/
Should be merged too.

https://isthereanydeal.com/game/alchemistadventureprologue/info/
This was the demo, it doesn't appear to be available anymore.

**Comment by MarkitkaM** [comment]
Entries to merge #2324
