### ISSUE TITLE
To Merge: IMMORTALITY/Project A

### ISSUE THREAD

**Issue by ProfessionalismIsMyMiddleName** [IsThereAnyDeal/IsThereAnyDeal-Issues#3313]
https://isthereanydeal.com/game/projecta/info/
https://isthereanydeal.com/game/immortality/info/
Should be merged, under the IMMORTALITY name. Game was renamed after page creation but before release.

**Comment by MarkitkaM** [comment]
Entries to merge #2324

**Comment by MarkitkaM** [comment]
Entries to merge #2324
