### ISSUE TITLE
To merge: House flipper luxury DLC

### ISSUE THREAD

**Issue by ProfessionalismIsMyMiddleName** [IsThereAnyDeal/IsThereAnyDeal-Issues#3315]
https://isthereanydeal.com/game/luxuryhouserenovation/info/
https://isthereanydeal.com/game/houseflipperluxury/stats/

**Comment by MarkitkaM** [comment]
Entries to merge #2324

**Comment by MarkitkaM** [comment]
Entries to merge #2324
