### ISSUE TITLE
log is incomplete?

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#332]
When I filter my (huge) log by "by user", the only things shown are waitlist items removed. No waitlist items added (there are definitely many) or collection items added or removed. (I definitely added some collection items manually, not sure about removing any)

[Issue created by bb34887: 2015-10-15]
[Last updated on bitbucket: 2015-10-16]

[Comment created by tfedor: 2015-10-16]
Unfortunately no. The reason why it's not being logged is  that I thought that it's not really needed since you can see time of addition from the Waitlist/Collection + you know you added the game if you're doing it manually.

What are you trying to read from the log?

[Comment created by bb34887: 2015-10-16]
Is it possible for you to retroactively make them be logged?

[Comment created by tfedor: 2015-10-16]
I think that right now manual additions are not logged, will have to check though.

**Comment by MarkitkaM** [comment]
Not responded by the user and the issue is too old.
