### ISSUE TITLE
To Merge: Just Shapes & Beats

### ISSUE THREAD

**Issue by ProfessionalismIsMyMiddleName** [IsThereAnyDeal/IsThereAnyDeal-Issues#3323]
https://isthereanydeal.com/game/justshapesandbeats/info/
https://isthereanydeal.com/game/justshapesbeats/info/
Same game.

https://isthereanydeal.com/game/justshapesbeatsmonstercattrackselection/info/
https://isthereanydeal.com/game/justshapesandbeatsmonstercattrackselection/info/
DLC is duplicated too.

**Comment by MarkitkaM** [comment]
Entries to merge #2324
