### ISSUE TITLE
To Merge: Hypnolab/Hypnolab VR

### ISSUE THREAD

**Issue by ProfessionalismIsMyMiddleName** [IsThereAnyDeal/IsThereAnyDeal-Issues#3325]
https://isthereanydeal.com/game/hypnolab/info/
https://isthereanydeal.com/game/hypnolabvr/info/
Same game.

I think I'm done going through my waitlist and trying to find entries having errors. Sorry for the mass of new issues.

**Comment by MarkitkaM** [comment]
Entries to merge #2324
