### ISSUE TITLE
To merge/split: Jekyll and Hyde

### ISSUE THREAD

**Issue by candela97** [IsThereAnyDeal/IsThereAnyDeal-Issues#3326]
https://isthereanydeal.com/game/jekyllhyde/info/
1. Steam link should be split and merged with https://isthereanydeal.com/game/mazmjekyllandhyde/info/
2. Gamefly link is unavailable for some reson, but I checked and could only find https://www.gamefly.com/game/mysterious-case-of-dr-jekyll-and-mr-hyde/144650, which judging by the title should belong in https://isthereanydeal.com/game/mysteriouscaseofdrjekyllandmrhyde/info/. Looks like they only sell console versions though.

**Comment by MarkitkaM** [comment]
Entries to split #2323
