### ISSUE TITLE
To Split: CardShark/Card Shark

### ISSUE THREAD

**Issue by SomeNameDee** [IsThereAnyDeal/IsThereAnyDeal-Issues#3327]
https://isthereanydeal.com/game/cardshark/info/
contains two separate games:

CardShark (one word)
https://store.steampowered.com/app/2316840/CardShark/

Card Shark (two words)
https://store.steampowered.com/app/1371720/Card_Shark/

**Comment by MarkitkaM** [comment]
Duplication #3286

Entries to split #2323
