### ISSUE TITLE
To Split: Chasm/The Chasm

### ISSUE THREAD

**Issue by Zeal0tte** [IsThereAnyDeal/IsThereAnyDeal-Issues#3329]
https://isthereanydeal.com/game/chasm/info/
contains two separate games:

Chasm
https://store.steampowered.com/app/312200/Chasm/

The Chasm - Mines of Madness
https://store.steampowered.com/app/1140900/The_Chasm__Mines_Of_Madness/

**Comment by MarkitkaM** [comment]
Entries to split #2323 

Duplication #1538
