### ISSUE TITLE
To Merge: Various Europa Universalis IV duplicates

### ISSUE THREAD

**Issue by TomTheHand** [IsThereAnyDeal/IsThereAnyDeal-Issues#3332]
The following are duplicates for the main game, "Europa Universalis IV":
https://isthereanydeal.com/game/europauniversalisiv/info/
https://isthereanydeal.com/game/europauniversalisivnew/info/
https://isthereanydeal.com/game/europauniversalisivdigital/info/
https://isthereanydeal.com/game/europauniversalisivmac/info/
https://isthereanydeal.com/game/europauniversalisivtrlatam/info/

The following are all the same expansion pack, which should probably be located at "Europa Universalis IV: Dharma Expansion" ("Expansion" is necessary to differentiate it from the Dharma Content Pack; yes, confusing!):
https://isthereanydeal.com/game/europauniversalisivdharma/info/
https://isthereanydeal.com/game/expansioneuropauniversalisivdharma/info/
https://isthereanydeal.com/game/europauniversalisivdharmatr/info/

And another expansion pack, "Europa Universalis IV: The Cossacks Expansion":
https://isthereanydeal.com/game/europauniversalisivcossacks/info/
https://isthereanydeal.com/game/expansioneuropauniversalisivcossacks/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
