### ISSUE TITLE
Some game titles not displayed correctly after editing a bundle

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#334]
https://isthereanydeal.com/specials/interface/bundle/711/

I was editing an old bundle to split it into it's tiers, having added the games to the new tier, some of the game names were not displayed correctly after the update was saved.

The edit history shows what I assume are the database id's for those titles, but the human readable title is missing.

I assume this is only a cosmetic problem, and will not be noticeable if the edit is accepted.

[Issue created by [deleted]: 2015-10-16]

[Comment created by tfedor: 2015-10-16]
Yeah, that's weird. I think it's because the interface doesn't really like new tiers. Changes seem alright though so once I go to approve it it should be fine.

**Comment by MarkitkaM** [comment]
Erorr 404 https://isthereanydeal.com/specials/interface/bundle/711/
