### ISSUE TITLE
Two games with similar names: Card Shark and CardShark

### ISSUE THREAD

**Issue by Robson** [IsThereAnyDeal/IsThereAnyDeal-Issues#3345]
There are two games with very similar names:
- CardShark: https://store.steampowered.com/app/2316840/CardShark/
- Card Shark: https://store.steampowered.com/app/1371720/Card_Shark/

The ITSD page at https://isthereanydeal.com/game/cardshark/info/ shows Steam links for both games:
![image](https://user-images.githubusercontent.com/3868660/230952158-f87b6b32-935d-4831-8ed2-4833312a7b32.png)

The ITSD section of the Steam page for Card Shark shows the price for CardShark:
![image](https://user-images.githubusercontent.com/3868660/230951619-781bc8b2-46f0-413e-9dc1-241b55a01f9d.png)

**Comment by SomeNameDee** [comment]
Duplication #3286 

Entries to split #2323 

Should be closed and receive labels "bug", "duplicate", and "entry"
(I don't have the privs to do so myself)

**Comment by MarkitkaM** [comment]
Duplication #3327
Entries to split #2323
