### ISSUE TITLE
To merge: Pile Up! Box by Box

### ISSUE THREAD

**Issue by forenta** [IsThereAnyDeal/IsThereAnyDeal-Issues#3353]
Duplicate, same game with short / long title.

https://isthereanydeal.com/game/pileup/info/
https://isthereanydeal.com/game/pileupboxbybox/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324

**Comment by candela97** [comment]
Actually, those 2 entries are separate games
`https://store.steampowered.com/app/2094910/Pile_Up/`
`https://store.steampowered.com/app/1109820/Pile_Up_Box_by_Box/`

https://isthereanydeal.com/game/pileup/info/ needs to be associated with the game in the Steam link instead, and the other 3rd-party stores needs to be merged with https://isthereanydeal.com/game/pileupboxbybox/info/.
