### ISSUE TITLE
Remove stealth game Steam link from space FPS entry

### ISSUE THREAD

**Issue by spare-addy** [IsThereAnyDeal/IsThereAnyDeal-Issues#3355]
Hello ITAD,

On this ITAD page: https://isthereanydeal.com/game/boundary/info/

Please remove this entry for a stealth zombie game called "Boundary VR": https://store.steampowered.com/app/1004180/Boundary_VR/

The other links are for a space FPS called "Boundary". https://store.steampowered.com/app/1364020/Boundary/

Thank you. I enjoy using the ITAD site for pricing history and finding deals.

**Comment by MarkitkaM** [comment]
Entries to split #2323
