### ISSUE TITLE
The Hex not finding prices

### ISSUE THREAD

**Issue by Kumagoro42** [IsThereAnyDeal/IsThereAnyDeal-Issues#3358]
The Hex (the one by Daniel Mullins) is recognized by the system, but it says "no tracked stores are currently selling the game", which is false, because at the very least Steam is selling it. After a quick check, Fanatical is also selling it.
https://isthereanydeal.com/game/thehex/info/#/

**Comment by MarkitkaM** [comment]
It is tracked here https://isthereanydeal.com/game/hex/info/ It must be split.
Entries to split #2323 
Duplication Entries to split #2323
