### ISSUE TITLE
Dredge [Digital] Deluxe Edition - Entries to merge

### ISSUE THREAD

**Issue by MagikGimp** [IsThereAnyDeal/IsThereAnyDeal-Issues#3359]
a. [DREDGE Digital Deluxe Edition](https://isthereanydeal.com/game/dredgedigitaldeluxeedition/info/)
b. [Dredge Deluxe Edition](https://isthereanydeal.com/game/dredgedeluxeedition/info/)

1. These are the same bundle under slightly different names.
2. There are two Steam entries for a. but one is a mistake.

**Comment by MarkitkaM** [comment]
Entries to merge #2324
