### ISSUE TITLE
There are two games titled Ravager on steam but only one ITAD page

### ISSUE THREAD

**Issue by Krynh** [IsThereAnyDeal/IsThereAnyDeal-Issues#3360]
Ravager: https://store.steampowered.com/app/689100/Ravager/  has an ITAD page at https://isthereanydeal.com/game/ravager/info/#/, however the prices for another game called Ravager https://store.steampowered.com/app/1683560/Ravager/ also show up on the page. 

The NSFW Ravager needs its own ITAD page

**Comment by MarkitkaM** [comment]
Entries to merge #2324
