### ISSUE TITLE
"To The Moon" Itch.io link is for a different game with the same name for $1.  Impossible to track now.

### ISSUE THREAD

**Issue by jmwilsoND** [IsThereAnyDeal/IsThereAnyDeal-Issues#3362]
[ITAD-To The Moon](https://isthereanydeal.com/game/tomoon/info)
[Itch.io "To The Moon"](https://adalutegames.itch.io/to-the-moon)
[Steam link for correct "To The Moon" game as described on ITAD](https://store.steampowered.com/app/206440/)

The game tracked for itch.io is a $1 unknown game as opposed to the $10 "overwhelmingly positive" Steam game.  Due to its price, it's impossible to track the actual game since it rarely has gone below $1.

**Comment by MarkitkaM** [comment]
Duplication #3174
Entries to split #2323
