### ISSUE TITLE
Journey - Wrong Games Linked

### ISSUE THREAD

**Issue by marcusvroberto** [IsThereAnyDeal/IsThereAnyDeal-Issues#3363]
In the "Journey" game page, the entries for the stores "Game Jolt" and "Itch.io" are for completely different games. They need to be removed.

![image](https://user-images.githubusercontent.com/132313772/235553543-359cb01c-d904-4a45-8eeb-e063d8eceb5a.png)
![image](https://user-images.githubusercontent.com/132313772/235553575-d22518ad-44ca-4b2f-8b93-e17d95ca5848.png)
![image](https://user-images.githubusercontent.com/132313772/235553604-8af70c3c-510f-497e-afe8-d13abbf25591.png)

**Comment by MarkitkaM** [comment]
Duplication #1644
Entries to split #2323
