### ISSUE TITLE
Entries to Merge: Production Line

### ISSUE THREAD

**Issue by dgw** [IsThereAnyDeal/IsThereAnyDeal-Issues#3365]
Production Line has two entries, one for Humble Store and one for Steam/Epic/GOG:

* https://isthereanydeal.com/game/productionline/info/
* https://isthereanydeal.com/game/productionlinecarfactorysimulation/info/

These are the same; the presence of a subtitle on Humble seems to have confused ITAD's system.

I'm unsure if/how I can contribute to #2324 directly, so here's a standalone report instead.

**Comment by MarkitkaM** [comment]
Entries to merge #2324
