### ISSUE TITLE
"CardShark" and "Card Shark", different games under same listing

### ISSUE THREAD

**Issue by Roxolan0** [IsThereAnyDeal/IsThereAnyDeal-Issues#3368]
![image](https://github.com/IsThereAnyDeal/IsThereAnyDeal-Issues/assets/5077722/c778cc1e-cc89-4d5c-a2ed-02111e082a16)

The Steam games [Card Shark](https://store.steampowered.com/app/1371720/Card_Shark/) and [CardShark](https://store.steampowered.com/app/2316840/CardShark/) are different, but both appear on the price list for Card Shark (you can see there are two Steam entries). 

I'm waitlisting Card Shark, but CardShark is cheaper so it's that incorrect price that gets displayed on my waitlist.

**Comment by MarkitkaM** [comment]
Duplication #3286 

Entries to split https://github.com/IsThereAnyDeal/IsThereAnyDeal-Issues/issues/2323
