### ISSUE TITLE
Mount & Blade II: Bannerlord listing has two problems

### ISSUE THREAD

**Issue by RandDenner** [IsThereAnyDeal/IsThereAnyDeal-Issues#3371]
This is the base game version only.

**FIRST ISSUE**
It has two different sites for the same version of the game.

1) https://isthereanydeal.com/game/mountbladeiibannerlord/info/
(no "and" in address - includes only Steam and 2game)
![image](https://github.com/IsThereAnyDeal/IsThereAnyDeal-Issues/assets/73523034/98fd9b29-8c1d-4ed7-a471-3509b80bc86a)

2) https://isthereanydeal.com/game/mountandbladeiibannerlord/info/
(has "and" in address - includes all other sellers **EXCEPT** Steam and 2game)
![image](https://github.com/IsThereAnyDeal/IsThereAnyDeal-Issues/assets/73523034/628a93a5-fafe-4b69-b83b-9f86e77da13f)

**SECOND ISSUE**
Some sort of bug with the Fanatical entry showing lowest price as $0.00

**Comment by MarkitkaM** [comment]
Entries to merge #2324
