### ISSUE TITLE
Entries to Split: Humanity Lost (2021) & Humanity (2023)

### ISSUE THREAD

**Issue by dgw** [IsThereAnyDeal/IsThereAnyDeal-Issues#3376]
https://isthereanydeal.com/game/humanity/info/

Links to two different Steam pages, https://store.steampowered.com/app/1165910/Humanity_Lost/ and https://store.steampowered.com/app/1581480/Humanity/

**Comment by MarkitkaM** [comment]
Entries to split #2323

**Comment by themegaxandy** [comment]
This issue has not been resolved yet. ITAD still treats it as the same game.
