### ISSUE TITLE
To split/merge: The Chameleon

### ISSUE THREAD

**Issue by candela97** [IsThereAnyDeal/IsThereAnyDeal-Issues#3377]
`https://store.steampowered.com/app/1493970/` links to https://isthereanydeal.com/game/chameleon/info/, which contains correct store links, but the title/header image/release date/reviews seem to belong to another game: `https://store.steampowered.com/app/1212740/`, which links to https://isthereanydeal.com/game/chameleonkurukurukamereon/info/

**Comment by MarkitkaM** [comment]
Entries to split #2323
