### ISSUE TITLE
To split: Wanderlust

### ISSUE THREAD

**Issue by burnpsy** [IsThereAnyDeal/IsThereAnyDeal-Issues#3378]
https://isthereanydeal.com/game/wanderlust/info/#/

This page points to [a walking sim on itch under the name Wanderlust](https://eternitystudios.itch.io/wanderlust), which also has a Steam version under the name [LSD: Wanderlust (Lo-fi Edition)](https://store.steampowered.com/app/729670/LSD_Wanderlust_Lofi_Edition/). That much is good.

But it also points to [this adults-only game, named Wanderlust on Steam](https://store.steampowered.com/app/1507420/WanderLust/).

**Comment by MarkitkaM** [comment]
Entries to split #2323
