### ISSUE TITLE
Lost in Play issues

### ISSUE THREAD

**Issue by Kumagoro42** [IsThereAnyDeal/IsThereAnyDeal-Issues#3385]
The basic Lost in Play entry only looks at GreenManGaming prices. I noticed because there's currently a Steam deal, but it doesn't show up in my waiting list. Turns out there's another entry called "Lost in Play Game". The sync of course only finds the other.

Honestly, I'm kind of losing faith in ITAD. I have 84 titles in my waiting list, and for too many of them, ITAD isn't helping alerting me of deals because they're not monitored correctly for one reason or another.

**Comment by MarkitkaM** [comment]
Entries to merge #2324
