### ISSUE TITLE
Two games with same name have their prices and deals mixed up

### ISSUE THREAD

**Issue by Jabulba** [IsThereAnyDeal/IsThereAnyDeal-Issues#3386]
Hello, steam has two games called "Graveyard Keeper" and their prices and deals are being reported wrongly by ITAD, 2099990 seems to be a free game but 599140 is reported as free but being sold at full price on steam.

https://store.steampowered.com/app/2099990/graveyard_keeper/
https://store.steampowered.com/app/599140/Graveyard_Keeper/

![image](https://github.com/IsThereAnyDeal/IsThereAnyDeal-Issues/assets/2008205/5b15db51-9f56-4cf2-8b44-4db560750b58)
![image](https://github.com/IsThereAnyDeal/IsThereAnyDeal-Issues/assets/2008205/71a46892-f846-428b-a4ae-04d2e06c6dd9)
![image](https://github.com/IsThereAnyDeal/IsThereAnyDeal-Issues/assets/2008205/21cdb8e2-a838-42b0-be60-5eef0dc8417c)

**Comment by MarkitkaM** [comment]
Duplication #3159

Entries to split #2323
