### ISSUE TITLE
To Split: Undercover Agent

### ISSUE THREAD

**Issue by burnpsy** [IsThereAnyDeal/IsThereAnyDeal-Issues#3395]
https://isthereanydeal.com/game/undercoveragent/info/

- Undercover Agent (2018 text adventure game)
- Undercover Agent (2021 NSFW deck building game)
- Undercover Agent DLC (free DLC to the 2021 game)

Due to these games being improperly listed together, the price is erroneously listed as $0.00 because it's using the DLC's price.

**Comment by MarkitkaM** [comment]
Entries to split #2323
