### ISSUE TITLE
To Split: Ghostrunner

### ISSUE THREAD

**Issue by burnpsy** [IsThereAnyDeal/IsThereAnyDeal-Issues#3396]
https://isthereanydeal.com/game/ghostrunner/info/

The page contains:

- Ghostrunner (the main game here, published by 505 games)
- Ghostrunner - Halloween Pack (DLC for that game)
- Ghostrunner (Switch port of the game above, for which an eShop key is sold on the Humble Store)
- ghost runner (indie game on itch)

**Comment by MarkitkaM** [comment]
Entries to split #2323
