### ISSUE TITLE
Game Entry to be merged

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#350]
[Endless Space: Emperor Edition](https://isthereanydeal.com/specials/#/page:game/info?plain=endlessspaceemperoredition) and [Endless Space](https://isthereanydeal.com/#/page:game/info?plain=endlessspace) are the same game and need to be merged.

[Issue created by [deleted]: 2015-11-05]

**Comment by MarkitkaM** [comment]
**MERGE ENTRIES:**
https://isthereanydeal.com/game/endlessspaceemperoredition/info/
https://isthereanydeal.com/game/endlessspace/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
