### ISSUE TITLE
Adding Humble Widgets and Humble Store to GB site section

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#351]
Both are available in EU/US/BR region sections, but not UK, despite being able to purchace in UK.

[Issue created by [deleted]: 2015-11-05]

[Comment created by tfedor: 2015-11-05]
This is not possible until Humble creates product feeds

**Comment by MarkitkaM** [comment]
Already tracked for UK - Humble Widgets and Humble store
https://isthereanydeal.com/?country=GB#/filter:humblewidgets,humblestore
