### ISSUE TITLE
combines games with similar names - needs to take developer / publisher into account

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#354]
Sometimes different games with similar names get "combined" into a single ITAD entry.

It's not the first time I've noticed this, and if I had the time I would use some automated method to make a list, but here's a particularly bad example, because there are 3 different games involved:

https://isthereanydeal.com/specials/#/page:game/info?plain=orbit

[Issue created by bb34887: 2015-11-07]

**Comment by MarkitkaM** [comment]
Still valid bug
https://isthereanydeal.com/game/orbit/info/
![image](https://user-images.githubusercontent.com/88401908/139596421-13ab809f-1de4-490c-8710-0e1bea977c8b.png)

**Comment by MarkitkaM** [comment]
Entries to split #2323
