### ISSUE TITLE
Waitlist Disappeared, Then Wishlist Can't Be Imported.

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#363]
Hello,

My Waitlist went blank, maybe in the past couple of days, on my account AllRoCol. After that I tried to refresh it every way the site offers, but it wouldn't connect. I tried 3 browsers, as well. Maybe it's the size of it, but I haven't had any problems in the past. It's only my Steam wishlist, that I want to import. Kind of rough in the middle of all the sales. :)

If I try to import the wishlist, I get a never ending spinner. If I try to refresh, I get "The requested content cannot be loaded. Please try again later.". No method seems to work and on top of that, I have no idea why it disappeared in the first place, before it even gets to why it won't import.

Thanks for any help.

https://steamcommunity.com/id/AllRoCol/wishlist/

[Issue created by AllRoCol: 2015-11-26]

[Comment created by AllRoCol: 2015-11-26]
Thanks. I appreciate it. This will keep me busy for a while. I already found three things to buy. :D

[Comment created by tfedor: 2015-11-26]
I'll figure something out but I don't have quickfix. For now I have turned off automatic sync for you and "undeleted" the games from your Waitlist based on log. I hope I didn't miss any.

[Comment created by AllRoCol: 2015-11-26]
I appreciate your responses. Thank you.

Well I know I don't have the largest wishlist at this point, mainly because I keep buying stuff and dropping you affiliate clicks in the process. I have seen over 8k at this point. I would hate to see it try to load.

Is this the end of being able to fully utilize ITAD? Say it isn't so. :( So much buying through there. So much usefulness. Not having it makes me realize how much I need it because of the quick filtering to wishlist, to find things I need to buy. I can still use SteamDB to buy on Steam, but the other sites take a lot more work without it in place.

Well either way you have me for life. So no worries. :D I can adjust.

Thanks for the info. I figured it was something like that. I had never seen the full erase bug, but I did figure it was timing out. Stress testing. :)

[Comment created by tfedor: 2015-11-26]
Alright, I think I know why it happens - becase of the size of your wishlist.
When I try to access your wishlist it is loading incredible long. Not even that, it times out for me:

> Gateway Timeout
> The proxy server did not receive a timely response from the upstream server.

That's the reason why you can't import your wishlist.

The reason why your games were removed... Probably the system doesn't check for timeout, sees it got page where are no games and thus thinks your wishlist is empty. That's a bug.

[Comment created by AllRoCol: 2015-11-26]
My waitlist went from like 6k items to 0, with no ability to import it. The log is just one giant removed page. http://puu.sh/lzhoL/44ec396dce.png 

[Comment created by tfedor: 2015-11-26]
hm, wtf. So your Waitlist is like completely empty now? Are yu in correct region? Does log says anything?

**Comment by MarkitkaM** [comment]
Solved within the conversation.
