### ISSUE TITLE
Merge Sid Meier's Civilization Beyond Earth and Starships bundles

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#365]
It is full of duplicates one another:

1. https://isthereanydeal.com/#/page:game/info?plain=sidmeierscivilizationbeyondearthandstarshipsbundle
2. https://isthereanydeal.com/#/page:game/info?plain=sidmeiersstarshipsandcivilizationbeyondearth
3. https://isthereanydeal.com/#/page:game/info?plain=sidmeiersstarshipsandcivilizationbeyondearthbundle
4. https://isthereanydeal.com/#/page:game/info?plain=sidmeiersstarshipsandsidmeierscivilizationbeyondearthbundle
5. https://isthereanydeal.com/#/page:game/info?plain=sidmeiersstarshipsbeyondearthbundle
6. https://isthereanydeal.com/#/page:game/info?plain=sidmeiersstarshipscivilizationbeyondearthbundle

[Issue created by Bujno: 2015-11-27]
[Last updated on bitbucket: 2018-11-10]

[Comment created by Bujno: 2018-11-10]
So, is it the same bundles, or are they somehow different?

**Comment by MarkitkaM** [comment]
Entries to merge #2324
