### ISSUE TITLE
Add game "Tension" and "The Void" by Ice-Pick Lodge

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#377]
aka "Тургор" (http://www.ag.ru/games/tension) and "Тургор. Голос цвета" (http://www.gog.com/game/void_the, http://www.ag.ru/games/turgor-golos-cveta).

[Issue created by Bujno: 2015-12-09]
[Last updated on bitbucket: 2018-11-10]

[Comment created by Bujno: 2018-11-10]
"The Void" is [added](https://isthereanydeal.com/game/thevoid). "Tension" is not.

**Comment by MarkitkaM** [comment]
I found these games with similar names but probably different games:
https://isthereanydeal.com/search/?q=Tension

**Comment by Korb** [comment]
These are different versions of the same game:
https://ru.wikipedia.org/wiki/Тургор_(игра)#Отличия_Тургора_и_Голоса_Цвета
https://en.wikipedia.org/wiki/The_Void_(video_game)#Editions_and_titles

There are official links in ITAD. Unofficial are not legal / are the resale of single copies. I think the ticket can be closed.

**Comment by MarkitkaM** [comment]
Thank you for the explanation,
