### ISSUE TITLE
Name Issues

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#378]
GOCCO OF WAR
Steam link : store.steampowered.com/app/346730/
Name on ITAD : peakvox GOCCO OF WAR (rev 111230)

Mafia 3
Steam link : store.steampowered.com/app/360430/
Name on ITAD : Whiskey

[Issue created by [deleted]: 2015-12-11]

**Comment by MarkitkaM** [comment]
**Names are correct:**
https://isthereanydeal.com/game/goccoofwar/info/
https://isthereanydeal.com/game/mafiaiiidefinitiveedition/info/
