### ISSUE TITLE
Duplicate entries for Final Fantasy VII and VIII

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#381]
Final Fantasy VII:
https://isthereanydeal.com/#/page:game/info?plain=finalfantasyvii
https://isthereanydeal.com/#/page:game/info?plain=finalfantasyvll

Final Fantasy VIII:
https://isthereanydeal.com/waitlist/#/page:game/info?plain=finalfantasyviii
https://isthereanydeal.com/waitlist/#/page:game/info?plain=finalfantasyvlli

[Issue created by [deleted]: 2015-12-20]

[Comment created by GTBit: 2015-12-20]
Hi, 

it is not a bug. The fact is that the automatic algorithm that takes the game list from the stores is not always able to understand that two entries found in two different stores are actually referring to the same game.

If you want to help to fix this kind of situation you can report them at this address:

https://isthereanydeal.com/dots/

**Comment by MarkitkaM** [comment]
**Merge ENTRIES:**
https://isthereanydeal.com/game/finalfantasyvii/info/
https://isthereanydeal.com/game/finalfantasyvll/info/

https://isthereanydeal.com/game/finalfantasyviii/info/
https://isthereanydeal.com/game/finalfantasyvlli/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
