### ISSUE TITLE
Add support for filtering waitlist by store, price, etc.

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#390]
Sometimes, I'll have a coupon that ITAD is unaware of and I'd like to put it toward a purchase on my waitlist without undue hassle.

It'd really be useful if I could filter for things like "All waitlisted games on store X with price Y or less".

[Issue created by ssokolow: 2015-12-25]

**Comment by MarkitkaM** [comment]
On the home page is possible to filter games in the waitlist, by the store, price and so on..

About the coupon - it is a very old issue, better to give more details about the coupon if not possible to add.
