### ISSUE TITLE
Syncing collections from non-public profiles

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#392]
I would like to keep my stores' collections synced with IsThereAnyDeal's collection, but i do not want to set my profiles to public.

For the steam collection the syncing could happen through steam's account linking feature, but almost all sites offer a "share with friends" setting between the extremes of public and private profile settings.

So a simple (practically) catch all solution would be to have IsThereAnyDeal have special accounts on all supported services, and use them for parsing user profiles. That way users can add it to their friend lists to give it access, without switching their profiles to all public.

[Issue created by snv: 2015-12-30]

[Comment created by tfedor: 2015-12-30]
I don't plan to create special accounts and parse wishlists/collections like that. It's too much work and I don't think it's worth it. You can always temporarily switch it to public, import and switch back.

For Steam library you can use this https://github.com/tfedor/itad_steam_library_import

**Comment by MarkitkaM** [comment]
Solved within the conversation.
