### ISSUE TITLE
A lot of games are now missing Steam price information

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#397]
Eg. check the following games:

https://isthereanydeal.com/#/page:game/info?plain=starbound
https://isthereanydeal.com/#/page:game/info?plain=terraria
https://isthereanydeal.com/#/page:game/info?plain=loversinadangerousspacetime

Steam price information are totally gone.

[Issue created by [deleted]: 2016-01-07]
[Last updated on bitbucket: 2021-04-10]

[Comment created by HYBRID_BEING: 2021-04-10]
Issue seems to be resolved. Please close.

**Comment by MarkitkaM** [comment]
Steam is listed.
https://isthereanydeal.com/#/page:game/info?plain=starbound
https://isthereanydeal.com/#/page:game/info?plain=terraria
https://isthereanydeal.com/#/page:game/info?plain=loversinadangerousspacetime
