### ISSUE TITLE
Slime Rancher doesn't show humble store&widget price.

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#408]
https://isthereanydeal.com/#/page:game/info?plain=slimerancher

is missing prices and links to DRM-free + steam key humble prices

https://www.humblebundle.com/store/p/slimerancher_storefront

https://www.humblebundle.com/widget/v2/standalone/slimerancher/fLzikDZexU

[Issue created by [deleted]: 2016-01-26]

[Comment created by tfedor: 2016-01-26]
Are you in UK? If so, there's nothing I can do. I've written about it multiple times, e.g. [here](https://www.reddit.com/r/GameDealsMeta/comments/26qfru/psa_why_itad_isnt_doing_a_good_job_of_covering/) or [at the bottom here](https://isthereanydeal.com/status/) or zelgaris written about it today on our [facebook](https://www.facebook.com/IsThereAnyDeal/posts/957483207666681).

**Comment by MarkitkaM** [comment]
Already listed also for UK
https://isthereanydeal.com/game/slimerancher/info/?country=GB
![image](https://user-images.githubusercontent.com/88401908/139583911-a4881f32-bd09-4606-8f2e-9e32f82ef214.png)
