### ISSUE TITLE
Oxenfre + Soundtrack - wrong Steam link

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#413]
https://isthereanydeal.com/?by=time:desc#/page:game/info?plain=oxenfreeplussoundtrack

It links to Street Fighter sale

[Issue created by [deleted]: 2016-02-06]

**Comment by MarkitkaM** [comment]
Allready correct https://store.steampowered.com/app/388880/Oxenfree/
