### ISSUE TITLE
Feature request: Filtering out movies

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#414]
Hi Tomáš, If you find the time to implement a filter to get rid of those Steam movies, it would be nice.

[Issue created by catapultier: 2016-02-06]

**Comment by MarkitkaM** [comment]
Already possible:
![image](https://user-images.githubusercontent.com/88401908/139582809-386c7b6b-e237-4db1-8793-0ba5e90f0e90.png)
