### ISSUE TITLE
Age of Empires II HD

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#419]
[Age of Empires II HD](http://store.steampowered.com/app/221380/) is listed on ITAD as [Age of Empires II HD Edition](https://isthereanydeal.com/#/page:game/info?plain=ageofempiresiihdedition). Since this is not the title it is listed as on Steam it creates issues with websites which are automatically creating links to ITAD. The result is [this](https://isthereanydeal.com/#/page:game/info?plain=ageofempiresiihd). If there is no specific reason for the different name I would like to ask if it could be changed according to it's Steam name.

Thank you.

[Issue created by [deleted]: 2016-02-09]
[Last updated on bitbucket: 2019-02-02]

[Comment created by Knightw0lf: 2019-02-02]
just needs to be merged into Age of Empires II: HD Edition
Steam https://isthereanydeal.com/game/ageofempiresii/history/
Humble / GMG https://isthereanydeal.com/game/ageofempiresiihdedition/info/

[Comment created by Terrkaan: 2016-02-09]
Sorry, I screwed up the links and can't edit the post as anonymous user.

https://isthereanydeal.com/#/page:game/info?plain=ageofempiresiihdedition

https://isthereanydeal.com/#/page:game/info?plain=ageofempiresiihd

**Comment by a60wattfish** [comment]
There is a third entry for this game on ITAD - https://isthereanydeal.com/game/ageofempiresiiii0iiii/info/ . My wishlist sync from Steam links to this entry rather than the two listed in OP.

**Comment by MarkitkaM** [comment]
Steam is not listed anymore https://isthereanydeal.com/game/ageofempiresiihdedition/info/
It should be added https://store.steampowered.com/app/221380/Age_of_Empires_II_2013/.

---
**MERGE ENTRIES:**
https://isthereanydeal.com/game/ageofempiresiihdedition/info/
https://isthereanydeal.com/game/ageofempiresiiii0iiii/info/
https://isthereanydeal.com/game/ageofempiresiihd/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
