### ISSUE TITLE
Gear Up: missing update/DLC to "Basic" and "Premium" version

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#424]
http://steamcommunity.com/groups/isthereanydeal/discussions/0/458606877311202369/
See http://store.steampowered.com/app/214420/?snr=1_7_7_230_150_134
Missing 

Buy Gear Up: Basic - 9,99€
Buy Gear Up: Premium - 19,99€

[Issue created by zelgaris: 2016-02-21]

**Comment by MarkitkaM** [comment]
Already added https://isthereanydeal.com/search/?q=Gear+Up
