### ISSUE TITLE
Live in One Region while you buy stuff from a different.

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#426]
Dunno if this is an issue. But most of my purchasing is done with my home country funds/account. Even my steam account is still there. Which is North America.

I live in Taiwan, but still buy stuff back home and look for those prices (Taiwan gets shafted a lot).

Am I missing anything? At the top it always says I am in a region that is not followed by ITAD.

[Issue created by [deleted]: 2016-02-28]

**Comment by MarkitkaM** [comment]
There is no name of the user on the bitbucket and it is an old issue.
