### ISSUE TITLE
Merge 2 entries for the same game

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#427]
STAR WARS™ Knights of the Old Republic™ II - The Sith Lords™ => http://store.steampowered.com/app/208580/?snr=1_7_7_151_150_1

Has these 2 entries:

> starwarsknightsofoldrepubliciisithlords

> starwarsknightsofoldrepublicii

[Issue created by dEnissay: 2016-03-01]

**Comment by MarkitkaM** [comment]
**MERGE ENTRIES:**
https://isthereanydeal.com/game/starwarsknightsofoldrepubliciisithlords/info/
https://isthereanydeal.com/game/starwarsknightsofoldrepublicii/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
