### ISSUE TITLE
Lowest recorded price doesn't work in Specials

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#428]
It's showing current price in both columns.

[Issue created by Kirara: 2016-03-02]
[Last updated on bitbucket: 2016-03-03]

[Comment created by tfedor: 2016-03-03]
I just pushed a fix, it should show correct values within hour.

**Comment by MarkitkaM** [comment]
Solved within the conversation.
