### ISSUE TITLE
Alternate display rendering option

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#433]
I would prefer it if there was another layout option where the game is at the top of the record and the prices are slightly indented and each beginning a row that lists percent off and store.
This would be especially helpful for mobile where I have to move the page left to right in order to see the whole record. Posting as major as it is the default and minor just doesn't seem to cut it.

[Issue created by hackwrench: 2016-03-08]

**Comment by MarkitkaM** [comment]
New websites have a mobile version.
