### ISSUE TITLE
Feature Request: Threshold for Voucher Notifications

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#435]
Hi,

Is it possible to add a feature by which voucher notifications are sent only if the voucher
a) relates to a game on the user's wishlist; and
b) reduces the price of the said game to below the notification threshold

If this is not possible, could notifications be sent if either:
a) The voucher is above a pre-defined percentage; and/or
b) The voucher is for a game that is on the user's wishlist?

I think the options above would be very useful for users in helping them get the information they want.

[Issue created by jrht80: 2016-03-12]
[Last updated on bitbucket: 2016-04-17]

[Comment created by tfedor: 2016-04-17]
Hm, by the sound of it you don't want to be notifed about vouchers, but about games instead.

If you turn off voucher notifications and turn on "Resend Waitlist notification with a new voucher" option, you may get the behavior you want, since it will relate to your Waitlist settings.
https://isthereanydeal.com/#/page:user/account/settings?section=notifWait&option=resend_with_voucher

**Comment by MarkitkaM** [comment]
Solved by the conversation.
