### ISSUE TITLE
Correct mapping the site in your mobile Google Chrome with traffic compression

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#447]
At the moment the scripts used on the site do not work properly on mobile devices. Need a mobile version of the site.
![Screenshot_2016-03-31-00-18-26.png](https://bitbucket.org/repo/b6qGGA/images/736796607-Screenshot_2016-03-31-00-18-26.png)

[Issue created by Bujno: 2016-03-30]
[Last updated on bitbucket: 2018-11-10]

[Comment created by Bujno: 2018-11-10]
Now the site is displayed normally. Thank!

**Comment by MarkitkaM** [comment]
Solved.
