### ISSUE TITLE
Automatically remove game from waitlist when it appears in collection

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#449]
It's great how when I buy a game on Steam it automatically shows up in my ITAD collection since the profile is linked. It would be great if ITAD could notice if a game on my waitlist appears in my collection, and remove it from the waitlist. When I buy a game I often forget to go back and remove it from my waitlist so this would make it automatic.

[Issue created by Folksong: 2016-04-08]
[Last updated on bitbucket: 2016-04-12]

[Comment created by tfedor: 2016-04-12]
Yup, ITAD's UI sux

[Comment created by Draco18s: 2016-04-12]
I think there's something to be said that every time I've tried to locate this setting I've been unable to find it, because I was always looking in the "sync with steam" settings.

[Comment created by tfedor: 2016-04-08]
This option has been on ITAD for quite some time now.

https://isthereanydeal.com/#/page:user/account/settings?section=collection&option=auto_waitlist_remove

**Comment by MarkitkaM** [comment]
Solved within the conversation.
