### ISSUE TITLE
price is diferent on actual site: de.gamesplanet.com

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#450]
Dragon Ball Xenoverse, is listed as 16.99€ but when i follow the link it is  24,99€.
Is this difference common, and is it a mistake on your part or some kind of trickery from gamesplanet (like realizing im not from germany)?
Not sure if this "issue" belongs here, so sorry if it's supposed to be on some forum.

[Issue created by [deleted]: 2016-04-08]

[Comment created by tfedor: 2016-04-08]
I see 24.99€ now, probably the deal just ended and ITAD didn't have time to update?

**Comment by MarkitkaM** [comment]
Solved within the conversation.
