### ISSUE TITLE
Yellow Text not readable

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#453]
First time I've come to this site, I noticed on the front page for Fallout 4s deal.  The sellers name is barely readable as a yellow text.

![Example](http://puu.sh/okC0n/80a1d02e16.jpg)

[Issue created by [deleted]: 2016-04-16]

**Comment by MarkitkaM** [comment]
Must be different before and with a new websites will be different again.
