### ISSUE TITLE
Add Breached game

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#455]
http://store.steampowered.com//app/460640
http://www.ag.ru/games/breached
https://new.vk.com/breached

[Issue created by Bujno: 2016-04-19]
[Last updated on bitbucket: 2018-11-10]

[Comment created by Bujno: 2018-11-10]
https://isthereanydeal.com/game/breached - thank!

https://isthereanydeal.com/game/breachedsoundtrack = https://isthereanydeal.com/game/breachedoriginalsoundtrack. Combine them?

**Comment by MarkitkaM** [comment]
Soundtrack - two same listing for Steam
https://isthereanydeal.com/game/breachedoriginalsoundtrack/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324 and #2703
