### ISSUE TITLE
cancel game info dialog when you click outside of it

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#464]
If I click on a game, a game info dialog pops up. If I want to go back, I have to move the mouse cursor to the top right corner of the dialog and hit the X icon. That is unpleasant, when you need to do it over and over again (you need to move your mouse a lot and be quite precise when targeting the close icon).

Example:
![itad.png](https://bitbucket.org/repo/b6qGGA/images/2053808730-itad.png)

Please make the dialog disappear even when you click anywhere outside of it. That is how dialogs usually work on the web. When you click outside of them, it means "close".

Thank you.

[Issue created by kparal: 2016-05-06]

[Comment created by tfedor: 2016-05-06]
This is working as intended. These popups require more interaction than usual popups on web like when looking at images, so I want to prevent unwanted closing. **You can either click on X or use Escape key on the keyboard, so I think it's sufficient that way.**

**Comment by jarikmarwede** [comment]
@tfedor Sorry for posting to this issue post-mortem, but have you considered displaying the Escape-keyboard-shortcut somewhere in the dialog UI? 
I just found out about it through this issue and it is really helpful.
If you think this is a good idea, I can create a separate issue for it.
