### ISSUE TITLE
sort free items as last

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#465]
This is how the output looks when I search for Witcher 3:

![witcher3.png](https://bitbucket.org/repo/b6qGGA/images/1710556933-witcher3.png)

I don't think it makes much sense to see lots of free items on top, and having to scroll down a lot just to see the important non-free items. Would it make sense to show non-free items first, and only then show the free ones? The free items are not why we use itad.com, after all...

Thanks.

[Issue created by kparal: 2016-05-06]

**Comment by MarkitkaM** [comment]
It is not sorted from zero price by default (at least now, not sure how it was before)
https://isthereanydeal.com/?by=cut:desc#/filter:&search/Witcher%203

![image](https://user-images.githubusercontent.com/88401908/139293777-d07cb6ec-389e-43e5-8161-2ccbae779971.png)
