### ISSUE TITLE
Humble Bundle Store Listings

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#472]
I cannot see the Humble Bundle Store listings on the website, I can find the bundles but not the store.

It may also be worth adding in a couple of other features with this.
1. The Humble Monthly Bundle, the ability to auto add these for subscribers
2. Subscribers get 10% off all store purchases, lowering the price of many things if they get them here, some way for people to see either both of these separately, or to be able to enable a 10% off these to see what they would pay.

[Issue created by [deleted]: 2016-05-25]

[Comment created by tfedor: 2016-05-25]
Humble Store is listed only in some regions, to be specific in EU1, EU2 and US. I've talked about this multiple times, Humble doesn't have a way to change your currency/country/region like e.g. Steam does, nor they have a product feed, so to be able to see prices for, say, UK, you need to have physical server there. Which I don't.

I have contacted them multiple times with a product feed request, each time all I've got was that they are small team and it's not high on priority list. They don't offer affiliate program, so their coverage on ITAD is for free, so I can't justify renting server in other countries just to cover them. As soon as I get product feed or a way to get prices for other regions, I'll add them. Maybe if users told them they want to see them on ITAD...

> The Humble Monthly Bundle, the ability to auto add these for subscribers

It's very specific bundle, only of it's kind. Not sure if it's the best feature on which I can spend my time.

>  Subscribers get 10% off all store purchases, lowering the price of many things if they get them here, some way for people to see either both of these separately, or to be able to enable a 10% off these to see what they would pay.

You can do that for deals list, if you set price modifier to 0.9 for Humble Store here: https://isthereanydeal.com/#/page:user/account/stores
But yeah, that won't have any effect on Waitlist limits or elsewhere, just in the deals list.

**Comment by MarkitkaM** [comment]
Solved within the conversation.
