### ISSUE TITLE
Separate default notification settings for each import

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#473]
It would be nice to have different default notification setting for games synced from different wishlists (or GOG's mix).
For example, when i wishlist games on Steam, i'm not interested in buying them on GOG, but i still need GOG wishlist to be synced so i could track some games not availiable on Steam.

[Issue created by HYBRID_BEING: 2016-05-30]

[Comment created by tfedor: 2016-05-30]
And here I thought ITAD's complicated enough already :)

**Comment by MarkitkaM** [comment]
Solved within the conversation.
