### ISSUE TITLE
Notify me when price is below/at most "best non-deal price"

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#474]
Currently one can set to be notified when price is below/at most "current *store* non-deal price", however it's stated, that for some reason (what reason, actually?) synced/imported games are checked against the store they are synced/imported from not the store with the best price. What if i want to receive notifications on games imported from Steam wishlist only if there is a 75% cut on cheapest price among selected stores, and not 75% cut on Steam price?

[Issue created by HYBRID_BEING: 2016-05-30]
[Last updated on bitbucket: 2016-06-01]

[Comment created by HYBRID_BEING: 2016-06-01]
Do you mean that *store* is only selected during import/sync/adding to wishlist?

It doesn't adapt if there appears a cheaper source then?

[Comment created by tfedor: 2016-06-01]
That's technical limit. Checking other prices during import would be too computationaly demanding.

**Comment by MarkitkaM** [comment]
Solved within the conversation.
