### ISSUE TITLE
Import/sync Steam's followed games list or Barter.vg to ITAD waitlist

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#479]
Hello,
will there be a possibility to import or sync the followed games list from Steam in the future?

Here is the list I'm talking about:
http://steamcommunity.com/my/followedgames

Due to the restriction of my country I cannot see all games in the Steam store. Because of that it's impossible to add those games to my Steam wishlist. Nevertheless I'm able to activate the restricted games with keys or gifts. So the only way for me to keep track of the games is to follow their Hub.

The Barter.vg wishlist would be a good option as well: https://barter.vg/u/205/w/

Thank you in advance. Keep up the good work!
Regards, .4nDr3

[Issue created by 4nDr3_: 2016-06-02]
[Last updated on bitbucket: 2019-12-30]

[Comment created by Rudey: 2019-12-30]
I made a userscript that can export/upload followed games, you can find the script and instructions here: [https://steamhunters.com/tools#steam-wishlist-exporter](https://steamhunters.com/tools#steam-wishlist-exporter)

[Comment created by tfedor: 2016-11-15]
Because I'm working on my thesis. Once that's done I'm back working on ITAD full time and this will be implemented.

[Comment created by Akkaz: 2016-11-15]
I don't see why this isn't already implemented. It would be very practical, and it shouldn't be too much work since the followed list and the wishlist are nearly identical.

**Comment by MarkitkaM** [comment]
Solved within the conversation.
