### ISSUE TITLE
Please do automatically remove ignored stores when i add games to my waitlist.

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#480]
Takes to long to untick them manually. :/

Sorry for bad english.

[Issue created by [deleted]: 2016-06-03]

[Comment created by tfedor: 2016-06-03]
Set up your defaults for Waitlist: https://isthereanydeal.com/#/page:user/wait/defaults

**Comment by MarkitkaM** [comment]
Solved within the conversation.
