### ISSUE TITLE
Infobox for Paragon show a different game

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#485]
Viewing the details for Epic's upcoming Paragon game incorrectly shows some details for a game called Jumpdrive. The description looks correct but reviews, screenshots and links are for Jumpdrive.

https://isthereanydeal.com/#/page:game/info?plain=paragon

[Issue created by [deleted]: 2016-06-10]

**Comment by MarkitkaM** [comment]
Entries to split #2323
