### ISSUE TITLE
"Labyrinth" points to a different game on Amazon with the same title

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#489]
Labyrinth, an early access strategy game, points to a .99 cent platforming game in the Amazon link on ITAD

https://isthereanydeal.com/#/page:game/info?plain=labyrinth

http://store.steampowered.com/app/412310/

https://www.amazon.com/Rogers-Games-Labyrinth-Download/dp/B018CZZBNK

[Issue created by [deleted]: 2016-06-15]

**Comment by MarkitkaM** [comment]
There is any tracking for Amazon but anyway all entries are wrong.
![image](https://user-images.githubusercontent.com/88401908/139216504-a32bf253-f69c-4517-8b3f-1c0805b71640.png)

**Comment by MarkitkaM** [comment]
Entries to split #2323
