### ISSUE TITLE
Image for merged games

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#49]
ArcaniA is merged with ArcaniA: Gothic 4, but since steam entry is called ArcaniA, the latter doesn't have image.

Solve automatically or just copy image during merge? What if picture changes?

[Issue created by tfedor: 2014-02-24]

**Comment by MarkitkaM** [comment]
**ArcaniaA** - seems to be allright
https://isthereanydeal.com/game/arcania/info/

**ArcaniA: Gothic 4**
-> **MERGE ENTRIES and add thumbnail**
https://isthereanydeal.com/game/arcaniagothiciv/info/
https://isthereanydeal.com/game/gothicivarcania/info/
https://isthereanydeal.com/game/arcaniagothicivsteam/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
