### ISSUE TITLE
Snapshot deal links to wrong product

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#500]
**Steps to reproduce:**

1. Go to https://isthereanydeal.com/#/page:game/info?plain=snapshot
2. Note that the gammer banner, "About" text, and "Found on Youtube" all refer to the game "Snapshot" and not to the app "Snapshot - DSLR Camera Control"
3. Click on the entry "Steam	-88%	$0.49	$0.49	$3.99"

**Expected Behaviour:**

Taken to http://store.steampowered.com/app/204220/ for the game "Snapshot"

**Observed Behaviour:**

Taken to http://store.steampowered.com/app/388280/?snr=1_7_7_204_150_393 for the app "Snapshot - DSLR Camera Control"

[Issue created by Nebu: 2016-06-26]

**Comment by MarkitkaM** [comment]
![image](https://user-images.githubusercontent.com/88401908/139206128-4247a9be-00fe-41c7-b053-5508b1a8c30c.png)

**Comment by MarkitkaM** [comment]
Entries to split #2323
