### ISSUE TITLE
Victoria II DLC collection on Steam is not listed

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#530]
The Victoria II DLC collection is available on both Green Man Gaming and on Steam (http://store.steampowered.com/sub/29111/). However, only the Green Man Gaming version is listed on your website.

[Issue created by [deleted]: 2016-08-13]

**Comment by MarkitkaM** [comment]
http://store.steampowered.com/sub/29111/ - this link is leading to the Steam HP

Can't find the game on Steam https://store.steampowered.com/search/?term=Victoria+II+DLC
