### ISSUE TITLE
Arcanum: Of Steamworks and Magick Obscura Added to Steam

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#534]
Steam has added Arcanum: Of Steamworks and Magick Obscura Here:

http://store.steampowered.com/app/500810/

The ITAD listing has GOGs entry.  Steam should be added/tracked:

https://isthereanydeal.com/#/page:game/info?plain=arcanumofsteamworksandmagickobs

OOPS!! EDIT:

Looks like there's just two separate entries... should be merged.

https://isthereanydeal.com/#/page:game/info?plain=arcanum

[Issue created by OrbitalBliss: 2016-08-30]

**Comment by MarkitkaM** [comment]
GOG is moved here https://isthereanydeal.com/game/arcanumofsteamworksandmagickobscura/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324

**Comment by detelosk** [comment]
The two entries are currently (still, once again?) not merged:
* https://isthereanydeal.com/game/arcanum/info/
* https://isthereanydeal.com/game/arcanumofsteamworksandmagickobscura/info/
