### ISSUE TITLE
Peter Jackson's King Kong

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#542]
ITAD allows me to add this game to my wait list, but does not identify a price or vendor.  A Google search shows that this game is available for digital download from Amazon.  Please add it so it is also trackable.

Thank you!

[Issue created by [deleted]: 2016-09-18]
[Last updated on bitbucket: 2016-09-19]

[Comment created by tfedor: 2016-09-19]
I can't find this game through Amazon's search = ITAD can't either. That's why it's not listed.

**Comment by MarkitkaM** [comment]
Solved within the conversation.
