### ISSUE TITLE
Adventure in the tower

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#543]
**Adventure in the tower** in The Labor Day GameBundle by GameBundle
(https://isthereanydeal.com/specials/#/page:game/info?plain=adventureintower) 
is  **Adventure in the Tower of Flight** 
(https://isthereanydeal.com/specials/#/page:game/info?plain=adventureintowerofflight)

[Issue created by [deleted]: 2016-09-19]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
