### ISSUE TITLE
The Sandbox have two entry

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#544]
The Sandbox 
(https://isthereanydeal.com/#/page:game/info?plain=sandbox)
The Sandbox - Pixel World Builder 
(https://isthereanydeal.com/#/page:game/info?plain=sandboxpixelworldbuilder)
are same

[Issue created by [deleted]: 2016-09-20]

**Comment by MarkitkaM** [comment]
Entries to split #2323 and Entries to merge #2324
