### ISSUE TITLE
F.E.A.R. have two entry

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#545]
F.E.A.R
(https://isthereanydeal.com/?by=cut:desc#/page:game/info?plain=fear)
F.E.A.R. First Encounter Assault Recon
(https://isthereanydeal.com/?by=cut:desc#/page:game/info?plain=fearfirstencounterassaultrecon)
are same

[Issue created by [deleted]: 2016-09-20]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
