### ISSUE TITLE
Red Orchestra 2: Heroes of Stalingrad with Rising Storm has two entry

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#546]
"Red Orchestra 2: Heroes of Stalingrad with Rising Storm"
(Rising Storm/Red Orchestra 2 Multiplayer 
+ Red Orchestra 2: Heroes of Stalingrad - single player(DLC)+Rising Storm(DLC))
has two entry
Rising Storm/Red Orchestra 2 Multiplayer
(https://isthereanydeal.com/#/page:game/info?plain=risingstormredorchestraiimultiplayer)
Red Orchestra 2: Heroes of Stalingrad with Rising Storm
(https://isthereanydeal.com/?by=cut:desc#/page:game/info?plain=redorchestraiiheroesofstalingradwithrisingstorm)

Red Orchestra 2: Heroes of Stalingrad
(Rising Storm/Red Orchestra 2 Multiplayer 
+ Red Orchestra 2: Heroes of Stalingrad - single player(DLC))
has two entry
Red Orchestra 2: Heroes of Stalingrad
(https://isthereanydeal.com/?by=cut:desc#/page:game/info?plain=redorchestraiiheroesofstalingrad)
Red Orchestra 2
(https://isthereanydeal.com/?by=cut:desc#/page:game/info?plain=redorchestraii)

[Issue created by [deleted]: 2016-09-20]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
