### ISSUE TITLE
MUD Motocross World Championship has 6 entry

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#547]
**MUD Motocross World Championship** has 6 entry

MUD - FIM Motocross World Championship
https://isthereanydeal.com/?by=cut:desc#/page:game/info?plain=mudfimmotocrossworldchampionship
MUD - FIM Motorcross World Championship
https://isthereanydeal.com/?by=cut:desc#/page:game/info?plain=mudfimmotorcrossworldchampionship
MUD Motocross World Championship
https://isthereanydeal.com/?by=cut:desc#/page:game/info?plain=mudmotocrossworldchampionship
MUD Motocross Championship
https://isthereanydeal.com/?by=cut:desc#/page:game/info?plain=mudmotocrosschampionship
MUD FIM Motocross
https://isthereanydeal.com/?by=cut:desc#/page:game/info?plain=mudfimmotocross
MUD
https://isthereanydeal.com/?by=cut:desc#/page:game/info?plain=mud
are same 

[Issue created by [deleted]: 2016-09-20]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
