### ISSUE TITLE
Reverse Crawl shows a new entry every 20 minutes in my RSS reader since yesterday

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#548]
My feed URL: http://isthereanydeal.com/rss/waitlist/79nll:49a9158d83979777c3653bce0d5a6ab2/

Screenshot attached.

[Issue created by [deleted]: 2016-09-23]

**Comment by MarkitkaM** [comment]
RSS will be new
