### ISSUE TITLE
v02/game/plain/ doesn't appear to return DLC

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#551]
I was trying to use the game/plain/ endpoint to look up prices for a given game's DLC, by the DLC title, but couldn't get results for it.

For example, the endpoint I tried to hit was:

https://api.isthereanydeal.com/v02/game/plain/?key=<key>&title=brave%20new%world

in order to look up a plain for Civilization V's DLC Brave New World, so that I could then feed the resulting plain into: https://api.isthereanydeal.com/v01/game/prices, but since the /game/plain doesn't appear to return for DLC titles, I can't do this.

What's the suggested approach for finding DLC gameplains so that I can look up their current prices on the api?

[Issue created by [deleted]: 2016-09-27]
[Last updated on bitbucket: 2016-09-28]

[Comment created by Acidictadpole: 2016-09-28]
Ok, thanks.

[Comment created by tfedor: 2016-09-28]
Not currently

[Comment created by Acidictadpole: 2016-09-28]
Alright thanks.

(This is my issue). 

Is there some way to do a text search -> game plain?

[Comment created by tfedor: 2016-09-28]
If I remember correctly, you have to use whole title. That endpoint doesn't work like search. So try 
```
#!
Sid Meier's Civilization V: Brave New World
```

**Comment by MarkitkaM** [comment]
Solved within the conversation.
