### ISSUE TITLE
Lords of Xulima Deluxe - Separate DLC addon combined with Deluxe Version game

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#566]
This problem affects the Steam version.  See here: https://isthereanydeal.com/#/page:game/info?plain=lordsofxulimadeluxeedition

[Issue created by [deleted]: 2016-10-31]

**Comment by MarkitkaM** [comment]
![image](https://user-images.githubusercontent.com/88401908/138601772-19c60e7f-e0a8-4dae-bedd-614579046a10.png)

**Comment by MarkitkaM** [comment]
Entries to split #2323
