### ISSUE TITLE
Game entries to be merged

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#568]
* https://isthereanydeal.com/waitlist/#/page:game/info?plain=callofdutyinfinitewarfare

+

* https://isthereanydeal.com/waitlist/#/page:game/info?plain=callofdutyinfinitewarfaremiddleeastprepurchase

------------------------------------

* https://isthereanydeal.com/waitlist/#/page:game/info?plain=farcryprimal

+

* https://isthereanydeal.com/waitlist/#/page:game/info?plain=farcryprimalstandardedition

-------------------------------------------

Regular editions from this one:

* https://isthereanydeal.com/waitlist/#/page:game/info?plain=forhonordeluxeedition

 to be merged with:

* https://isthereanydeal.com/waitlist/#/page:game/info?plain=forhonor

-------------------------------------------------

* https://isthereanydeal.com/waitlist/#/page:game/info?plain=osiris

+

* https://isthereanydeal.com/waitlist/#/page:game/info?plain=osirisnewdawn

------------------------------------------------------

* https://isthereanydeal.com/waitlist/#/page:game/info?plain=assembly

+

* https://isthereanydeal.com/waitlist/#/page:game/info?plain=assemblynonvr

------------------------------------------------------

* https://isthereanydeal.com/waitlist/#/page:game/info?plain=urbanempire

+

* https://isthereanydeal.com/waitlist/#/page:game/info?plain=urbanempireprepurchase

[Issue created by [deleted]: 2016-11-01]
[Last updated on bitbucket: 2016-11-21]

[Comment created by AndySav92: 2016-11-21]
Also, the Steam entry of the actual game and the season pass for Homefront is mixed up, both are under the season pass on ITAD.

https://isthereanydeal.com/waitlist/#/page:game/info?plain=homefrontrevolution

+

https://isthereanydeal.com/waitlist/#/page:game/info?plain=homefrontrevolutionexpansionpass

[Comment created by AndySav92: 2016-11-21]
Still an issue with these

**Comment by MarkitkaM** [comment]
**Osiris & Osiris: New Dawn** are separated games, I would not merge them together/
Split from https://isthereanydeal.com/game/osiris/info/

**The Assembly** -> Wrong listing for Steam and itch.io
https://isthereanydeal.com/game/assembly/info/
https://rockus-games.itch.io/assembly
https://store.steampowered.com/app/1777560/Assembly/

**Homefront** - Steam entries seems to be alright
https://isthereanydeal.com/game/homefrontrevolution/info/
DLC - https://isthereanydeal.com/game/homefrontrevolutionexpansionpass/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
Entries to split #2323
