### ISSUE TITLE
Import from an excel file (or similar like csv)

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#572]
crosspost from: https://steamcommunity.com/groups/isthereanydeal/discussions/0/350540974010490906/

Enhancement: import excel (or csv or whatever format which I can just copy paste from excel) games wishlist to isthereanydeal.com.

If it's not doable, is it doable to import to steam and then to ITAD?

[Issue created by TerviLing: 2016-11-04]

**Comment by MarkitkaM** [comment]
Already exist.
