### ISSUE TITLE
Selecting "Mac" breaks other filters

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#578]
If I select "Mac" as a filter, then adding almost any other filter produces a blank list, i.e. no games.   

For example, click "Mac" and you'll see games at a variety of prices, including some for $4.99 or $9.99, etc.  But if you then add the filter "Under $5" or "Under $10", even the games that were listed which meet that criterion will no longer appear on the list.  

Similarly, adding filters like  "At least 50% Off", "Lowest Price", etc. will produce empty lists even if there are Mac games that meet those criteria.

[Issue created by [deleted]: 2016-11-19]

**Comment by MarkitkaM** [comment]
The platform section is gonna be new.

**Comment by thw0rted** [comment]
Did this feature get removed at some point?  I'm looking at [one bundle](https://isthereanydeal.com/specials/#/options:pending;/filter:id/11175) and trying to figure out a way to filter by operating system.  Each row in the results says the supported OSes next to the platform, but I don't see how to filter by e.g. only games that work on Mac.
