### ISSUE TITLE
Specials Notifications and Collection Settings don't save

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#580]
For about 1 week now the Special Notifications and Collection settings don't stay saved like I set them.
The Special Notifications settings from "How often do you want to receive notifications about new Specials?" to the bottom are always "reset" to default and in the Collection settings the "Expand all games in Collection to show collected copies by default." is always checked, despite the fact that I always unckeck it and save.
Is there a problem with my account, since this didn't happen until recently?

[Issue created by DjKaijin: 2016-11-20]
[Last updated on bitbucket: 2016-11-22]

[Comment created by DjKaijin: 2016-11-22]
I tried with IE and the settings were saved. Something might have changed with the latest Firefox update.
Thanks for your help.

[Comment created by tfedor: 2016-11-20]
Hm, I just tried that and it works fine for me. Can you try different browser maybe?

**Comment by MarkitkaM** [comment]
Solved within the conversation.
