### ISSUE TITLE
From the Depths has been bundled and being sold in multiple stores

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#585]
https://www.bundlestars.com/en/bundle/indie-legends-5-bundle

https://www.bundlestars.com/en/game/from-the-depths

[Issue created by [deleted]: 2016-11-28]
[Last updated on bitbucket: 2016-12-10]

[Comment created by tfedor: 2016-12-10]
You can edit Specials and add missing games to them directly.

**Comment by MarkitkaM** [comment]
Solved within conversation.
