### ISSUE TITLE
Log change notification error

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#590]
Recently I have received quite a few email notification from ITAD saying that "During last check we have found suspicious activity on your Collection", and then a list of tens of games (sometimes close to a hundred) that were supposedly "removed by system". These games are actually still in my Steam Library. This is not some site-breaking problem but it scares me from time to time. Hope you can resolve it.

SteamID: 76561198103068934

[Issue created by faragona: 2016-12-04]
[Last updated on bitbucket: 2016-12-10]

[Comment created by tfedor: 2016-12-10]
I just pushed another update which I think will solve issues we have discussed here: http://steamcommunity.com/groups/isthereanydeal#announcements/detail/599373548490274397

[Comment created by xnitad: 2016-12-06]
Okay, may be a non-issue. I now have Enchanted Edition in my collection - it wasn't when I commented. The log shows Enchanted being added.

In this particular case, though, isn't the original Trine still available through Steam? I know it is through Humble and other storefronts.

My Steam copy was "automatically upgraded," but that was months and months ago.

[Comment created by tfedor: 2016-12-05]
Can you check and printscreen log for me?
https://isthereanydeal.com/log/

For example, in my Collection, Trine was removed by Trine: Enchanted Edition was added.

[Comment created by xnitad: 2016-12-05]
It's removing **valid** games imported from my Steam account, and  there doesn't appear to be a way to add the games back, other than manually—which isn't feasible, now that it's removed about 15 games.

For example, both Trine and Trine: Enchanted Edition are gone from my collection. The Humble copies still exist, but the Steam copies are gone. If this is due to a rename, shouldn't all four entries be gone? And where are the equivalents? There's nothing else in my collection that would stand in for either Trine or T:ED.

[Comment created by tfedor: 2016-12-04]
It's being send when games get renamed. I will add to the email also additions, so you could see if the game really got removed or renamed, but I'll get to it after my thesis is done.

[Comment created by faragona: 2016-12-04]
Latest email received today.

**Comment by MarkitkaM** [comment]
Solved within conversation.
