### ISSUE TITLE
Syndicate's pricing from Gamestop isn't being displayed

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#600]
Syndicate's price on Origin and Amazon is being displayed but the gamestop pc download isn't.

https://isthereanydeal.com/#/page:game/info?plain=syndicate

http://www.gamestop.com/pc/games/syndicate/95535

[Issue created by [deleted]: 2016-12-23]

**Comment by MarkitkaM** [comment]
The GameStop is not tracked anymore.

Actually there is 2x listed Amazon:
Syndicate [Game Connect] https://www.amazon.co.uk/dp/B00IDIDQI4?linkCode=ogi&th=1&tag=isthcom-21
Syndicate [Online Game Code] https://www.amazon.co.uk/dp/B00IDIDQI4?linkCode=ogi&th=1&tag=isthcom-21

**Comment by MarkitkaM** [comment]
Entries to split #2323
