### ISSUE TITLE
Entry to be merged

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#611]
https://isthereanydeal.com/#/page:game/wait?plain=uncertain

+

https://isthereanydeal.com/#/page:game/info?plain=uncertainepisodeilastquietday

[Issue created by AndySav92: 2017-01-12]

**Comment by MarkitkaM** [comment]
**MERGE ENTRIES:**
https://isthereanydeal.com/game/uncertain/info/
https://isthereanydeal.com/game/uncertainepisodeilastquietday/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
