### ISSUE TITLE
Humble store 10% off for subscribers

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#613]
Check box **I'm Humble store monthly subscriber** in profile settings would be nice as getting prices -10 from humble store prices in ITAD also.

[Issue created by [deleted]: 2017-01-13]

[Comment created by tfedor: 2017-01-13]
You can set up that manually for yourself here: https://isthereanydeal.com/#/page:user/account/stores

Although, it currently only works at the deals list

**Comment by MarkitkaM** [comment]
Solved within conversation.
