### ISSUE TITLE
Getting historical low for a game on a particular store

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#614]
My current app deals with prices on Steam, and it would be a great help to see what the lowest price has been on Steam, rather than just for any arbitrary site.

[Issue created by BobTheLawyer: 2017-01-15]

**Comment by MarkitkaM** [comment]
Filtered like that
https://isthereanydeal.com/#/filter:&historylow,steam,&search/cyberpunk;/options:strict
