### ISSUE TITLE
There are 2 games called streamline that are causing each other issues

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#622]
**SPLIT ENTRIES:**
https://isthereanydeal.com/#/page:game/info?plain=streamline
The steam app IDs are the following
252850
393660

[Issue created by [deleted]: 2017-01-31]

[Comment created by bb34887: 2017-01-31]
There are many examples of games sharing a name. ITAD needs a primary key that isn't just derived from the name.

**Comment by MarkitkaM** [comment]
Entries to split #2323
