### ISSUE TITLE
Advanced Filter "Hide DLC" hides everything in Collection

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#624]
When I click "Hide DLCs," taking me to https://isthereanydeal.com/collection/#/filter:hidedlc , my entire Collection disappears. I only have a handful of DLCs tracked in ITAD, so this is a minor nuisance, but it's definitely not the right behavior!

[Issue created by [deleted]: 2017-02-02]

**Comment by MarkitkaM** [comment]
Works for me now
![image](https://user-images.githubusercontent.com/88401908/138586856-3ab5f5b6-1b59-4616-bf8e-a962a93e042f.png)
