### ISSUE TITLE
Status filters should be OR not AND

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#625]
When selecting multiple options under "Status" in the Collection view, you end up with a query string like filter:status-notplayed,&status-played . This makes no sense, because a given game can have only one Status. Given it's a sensible use case to say e.g. "show me all the games I haven't beaten yet" by selecting Played and Not Played, this should be an OR filter, not an AND.

[Issue created by [deleted]: 2017-02-02]

[Comment created by tfedor: 2017-02-02]
Filters UI needs rework. For now you can achieve that be removing "&" from URL, so use

```
#!php

filter:status-notplayed,status-played
```

**Comment by MarkitkaM** [comment]
Possible in advance mode 
![image](https://user-images.githubusercontent.com/88401908/138586386-8fa5738a-246c-48d8-b06c-9613e05d5f87.png)
