### ISSUE TITLE
Infinite scroll + Footer = Bad design idea

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#626]
Main page has infinite scrolling, so it is almost impossible to read footer. I guess there are pages without infinite scrolling and it's not that big of a deal but still.

[Issue created by HYBRID_BEING: 2017-02-03]

**Comment by MarkitkaM** [comment]
It is still there but we will not fix it while there are upcoming new websites.

**Comment by MarkitkaM** [comment]
Duplication of the #689.
