### ISSUE TITLE
Star Wars - Knights of the Old Republic, MacGameStore should be under the Mac entry for the game, not PC

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#628]
Currently MacGameStore is under the PC entry for KOTOR https://isthereanydeal.com/#/page:game/info?plain=starwarsknightsofoldrepublic instead of the Mac entry https://isthereanydeal.com/#/page:game/info?plain=starwarsknightsofoldrepublicmac

[Issue created by [deleted]: 2017-02-04]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
