### ISSUE TITLE
GamersGate collection cannot handle bundles

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#635]
I have a 1C Complete Pack which includes a lot of games, and some other bundles too. The collection importer for GamersGate only imports the bundle name itself, e.g. "1C Complete Pack", not the games which are included in it. Is it possible to fix this?

[Issue created by [deleted]: 2017-02-19]

[Comment created by Gustra: 2017-02-19]
Just FYI, I was the one who submitted this.

**Comment by MarkitkaM** [comment]
Duplication #1171
