### ISSUE TITLE
Entries to be merged

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#643]
https://isthereanydeal.com/waitlist/#/page:game/info?plain=typoman

+

https://isthereanydeal.com/waitlist/#/page:game/info?plain=typomanrevised

[Issue created by AndySav92: 2017-03-02]
[Last updated on bitbucket: 2017-03-06]

[Comment created by bb34887: 2017-03-06]
This is for merging entries: https://isthereanydeal.com/dots

**Comment by MarkitkaM** [comment]
**MERGE ENTRIES:**
https://isthereanydeal.com/game/typoman/info/
https://isthereanydeal.com/game/typomanrevised/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
