### ISSUE TITLE
The Forest Itch.io link is for wrong game

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#644]
The Itch.io link goes to an entirely different game called Forest, no wonder it's three times as cheap.

[Issue created by [deleted]: 2017-03-03]
[Last updated on bitbucket: 2020-09-18]

[Comment created by Nothing4You: 2020-09-18]
it’s at least not listed as current anymore, however, it still skews historical low.

[Comment created by vanillajuice: 2017-03-05]
![Capture.PNG](https://bitbucket.org/repo/b6qGGA/images/3827883135-Capture.PNG)

Picture for reference.  Almost purchased lol.

**Comment by MarkitkaM** [comment]
Duplication of the #657
