### ISSUE TITLE
Error 500 while importing from official ITAD app

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#645]
Importing Steam Collection with the official ITAD Web App is broken.

The script of the app : https://github.com/tfedor/itad_steam_library_import seems to be broken at this time.

Even while changing the URL in the script from "https://isthereanydeal.com/outside/user/collection/3rdparty/steam" to "https://isthereanydeal.com/outside/user/collection/3rdparty" (I read somewhere that it should work better with this new URL but it doesn't).

With the old URL the error code is 500, with the new URL the error is that the source of data should be define.

[Issue created by H0stilax: 2017-03-03]

**Comment by MarkitkaM** [comment]
Synced.
https://steamcommunity.com/id/3rdparty
![image](https://user-images.githubusercontent.com/88401908/138567940-342ae7c8-af23-4f29-9a37-6d5a27345571.png)
