### ISSUE TITLE
ArmA 3 Apex

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#646]
Currently, the ArmA 3 Apex edition (base game + Apex DLC) shows as the same game as just the Apex DLC, you might want to split them up :)

[Issue created by [deleted]: 2017-03-03]
[Last updated on bitbucket: 2017-07-03]

[Comment created by modrink: 2017-07-03]
Confirmed, still bugged.

[Comment created by tfedor: 2017-03-14]
Still bugged, Edition check in titles doesn't consider sticky plains

**Comment by MarkitkaM** [comment]
https://isthereanydeal.com/search/?q=ArmA+3+Apex

**Comment by MarkitkaM** [comment]
Entries to split #2323
