### ISSUE TITLE
Add games to Collection which are not in ITAD's database

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#65]
(2:02:14 AM) Marek Hrušovský: nepridas moznost pridat do kolekcie hry mimo ITAD databazy?

[Issue created by tfedor: 2014-07-26]
[Last updated on bitbucket: 2015-03-01]

[Comment created by ssokolow: 2015-03-01]
Given that the userscript import API can do this, I've actually considered extending my userscript for this purpose so I could add games like Minecraft and OpenTTD to my collection.

**Comment by MarkitkaM** [comment]
Solved.
