### ISSUE TITLE
[BUG]Ghost 1.0 on ITAD

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#650]
1) With "ghost" plain
https://isthereanydeal.com/#/page:game/info?plain=ghost
the picture in the popup is from Ghost 1.0 game, but the itch.io link is for completely different game
https://wazuap.itch.io/ghost

2) Plain for Ghost 1.0 is "ghosti0" - shouldn't it be "ghost10"?

3) More related to how ITAD handles search, but if I search for "ghost" only, it shows me a lot of games ending with "We have found more than 75 games. Please be more specific in your search." not actually showing the game Ghost 1.0.
One has to search for Ghost 1 at least

[Issue created by [deleted]: 2017-03-08]

**Comment by MarkitkaM** [comment]
**SPLIT ENTRIES:**
https://isthereanydeal.com/#/page:game/info?plain=ghost
![image](https://user-images.githubusercontent.com/88401908/138567284-59543679-d443-41d9-8de5-4e8b2ad5ea88.png)

**Comment by MarkitkaM** [comment]
Entries to split #2323
