### ISSUE TITLE
Lost refers to different games

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#655]
Lost is a game available on Steam. Apparently there's a completely different game on itch.io with the same name, and it breaks notifications for deals.

[Issue created by lminiero: 2017-03-12]

**Comment by MarkitkaM** [comment]
**SPLIT ENTRIES.**

itch.io + 3x wrong Steam listing
https://isthereanydeal.com/game/lost/info/
![image](https://user-images.githubusercontent.com/88401908/138566877-c6b1e330-0d91-4a94-afe6-76c2b8062d75.png)

**Comment by MarkitkaM** [comment]
Entries to split #2323
