### ISSUE TITLE
bundle stars

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#658]
was looking at Civ 6 prices and the (current) lowest shown here is 30% off while on bundle stars its 38% off (digital deluxe). Consider adding that website?

[Issue created by [deleted]: 2017-03-16]

[Comment created by tfedor: 2017-03-16]
It's listed as Star deal here: https://isthereanydeal.com/#/page:game/info?plain=stardealcivilizationvidigitaldeluxe

Don't ask me why they do it, that's how I get it in the feed.

**Comment by MarkitkaM** [comment]
Solved within conversation.
