### ISSUE TITLE
Can't find 1993 - Space machine

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#663]
Searching here:

https://isthereanydeal.com/#/search:1993%20-%20Space%20machine;/scroll:%23gamelist

finds nothing, though the game exists. Link to the "popup":

https://isthereanydeal.com/#/page:game/info?plain=iixixiiispacemachine

which looks like this:

![1993 space machine.PNG](https://bitbucket.org/repo/b6qGGA/images/573259862-1993%20space%20machine.PNG)

There are probably more examples, but having no idea what the problem is, I don't know how to look for them

[Issue created by bb34887: 2017-03-20]

[Comment created by tfedor: 2017-03-20]
Weeell, I might argue otherwise. Let's say you own half of Europa Universalis DLCs and are looking for the rest. Here omitting it from search results could be useful. But I agree I need to explain it in a better way. Search is currently considered to be a filter like any other.

[Comment created by bb34887: 2017-03-20]
Oh, fair enough. I was looking in the filters, and the Deals settings.

Just as a usability issue, it would probably be a good idea to ignore that setting when using the search box. If you're looking for a particular game (that you may own) it doesn't seem helpful.

[Comment created by tfedor: 2017-03-20]
https://isthereanydeal.com/#/page:user/account/settings?section=collection&option=ignore_from_collection

[Comment created by bb34887: 2017-03-20]
Where is the option to remove games from deals list if you own them (if it's a separate thing from "Add ignored & omitted")?

[Comment created by bb34887: 2017-03-20]
(I was replying to previous comment, I can find "Add ignored & omitted")

[Comment created by bb34887: 2017-03-20]
I think you are right, but I can't seem to find that setting?

[Comment created by tfedor: 2017-03-20]
Your "Add to Collection" link is grey, so you have the game in Collection. Try searching with the option "Add ignored & omitted" turned on:

https://isthereanydeal.com/#/search:1993%20-%20Space%20machine;/option:ignoreuser

[Comment created by bb34887: 2017-03-20]
Oops, I had "selected" the title (to copy & paste) just before taking the screenshot. So it's not normally grey on white.

[Comment created by tfedor: 2017-03-20]
I got it in search without issue, but I see you have this game in collection and I bet you have option to remove games from deals list if you own them turned on, that's why you can't find it.

**Comment by MarkitkaM** [comment]
Explained within the conversation above.
