### ISSUE TITLE
new bundle seller

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#671]
Good news Tomáš, your favourite store now offers [bundles](https://www.g2a.com/game-deals)!

Joking aside, they are now on their second bundle, which seems to be a monthly affair similar to Humble. Unlike Humble however, you can actually see what games are in the bundle before buying it, and also you can buy just the current bundle (for €0.50 extra) without being forced to subscribe. So in those two respects, they are actually less shady than Humble!

Their FAQ also claims that "The keys come directly from developers and publishers. There are no third-party sellers involved in G2A Deal." (G2A Deal is the name of their monthly bundle)

I think you should at least investigate this and consider the possibility that their bundles (though not their store) should be included on ITAD.

[Issue created by bb34887: 2017-04-02]
[Last updated on bitbucket: 2019-02-11]

[Comment created by Knightw0lf: 2019-02-11]
this can be closed since G2A is a gray site as well had many issiues over the years

[Comment created by bb34887: 2017-04-08]
I'm inclined to concede the point, but I'll continue the discussion a little longer and say that their failure to meet Gearbox's demands proves nothing.
Imagine if you were a large client of Microsoft and you gave them 24 hours to stop all the [spying in Windows 10](https://www.theregister.co.uk/2017/04/06/microsoft_windows_10_creators_update/) - for everyone, not just for you. Do you think they'd even issue a public response, let alone give in to your demands?

[Comment created by tfedor: 2017-04-08]
> I'm not saying G2A is wonderful, but I'd rather know about their bundles and have the option of taking the risk, than not know (or have to browse other bundle-listing sites to make sure I'm not missing anything).

Well, you're not a typical user, I'd say. Although you may be aware of what G2A is and what risks it takes, a regular gamer probably won't be, partly due to huge ad campaign G2A has. Moreover, I am not sure I feel morally ok with supporting G2A by providing them coverage, even if we are talking about bundles only.

And now, as TB said, it's clear they don't have a customer in mind and don't really want to better themselves.

[Comment created by tfedor: 2017-04-08]
Update on Gearbox: https://waypoint.vice.com/en_us/article/gearbox-backs-out-of-criticized-bulletstorm-deal-with-shady-key-reseller-g2a

[Comment created by bb34887: 2017-04-07]
OK... I watched the rest of the video and it does make G2A sound pretty bad, but I still don't think it's black and white, for example one of the dodgy practices he cites is including hidden or obfuscated charges, which I've [commented on before](https://bitbucket.org/tfedor/isthereanydeal.com/issues/635/new-bundle-seller#comment-34487522), but **here is itch.io doing the same thing!**. If your minimum payment is 50c, then you shouldn't be advertising products for less than 50c, and if you accept Bitcoin (which is the button I clicked), then your minimum payment should be a lot lower than 50c!

![itch payment.png](https://bitbucket.org/repo/b6qGGA/images/3835091490-itch%20payment.png)

[Comment created by bb34887: 2017-04-07]
A video like that sounds very persuasive, but it's harder to fact-check than a written article. However, at 1:39 he made a statement that struck me as obviously false: "Small startup digital retailers such as IndieGameStand had to shut down under the burden of credit card chargebacks". It might be a wild exaggeration or a mistake, but it doesn't give me confidence in the accuracy of what he has to say.

Credit card fraud is very unfortunate. CCs are a wildly insecure payment instrument that should never have been let loose on the internet, but the existence of fraud is sort of the banks' fault for failing to provide (and popularize) more secure alternatives.

What are vendors of digital goods supposed to do about it? If they ask customers for ID, they [suffer a lot of hatred as a result](https://www.google.com.au/search?q=CD+Keys+asking+for+ID) and undoubtedly lose a lot of business.

Also, at least two developers / publishers have publicly confirmed their deal with G2A to sell keys in the bundle: [1](https://twitter.com/Syberia/status/831798750582566912), [2](https://www.facebook.com/microids/posts/1217590214983453).

I'm not saying G2A is wonderful, but I'd rather know about their bundles and have the option of taking the risk, than not know (or have to browse other bundle-listing sites to make sure I'm not missing anything).

Also, ITAD isn't just used for linking to a bundle website to purchase it. It's used for research. A couple of weeks ago I traded a key for Superhot not realizing it was in a bundle (and therefore "worth less" than I thought) - after doing an ITAD search, of course. In hindsight, I probably still would have made the trade (and got to avoid buying the bundle!), but this sort of ignorance is a downside of only listing "approved" sellers :(

[Comment created by tfedor: 2017-04-07]
More reasons why I don't want to cover G2A: https://www.youtube.com/watch?v=cac0ACHux-Q

**Comment by MarkitkaM** [comment]
Solved within the conversation above.
