### ISSUE TITLE
"TRI: Of Friendship and Madness" incorrectly merged with "TRI"

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#674]
It seems that to handle some stores calling it simply "TRI", "TRI: Of Friendship and Madness" was merged with "TRI": 

https://isthereanydeal.com/#/page:game/info?plain=trioffriendshipandmadness
https://isthereanydeal.com/#/page:game/info?plain=tri

However, a game has been released on itch.io with the name "TRI": https://tri-developer.itch.io/tri. As a result, of course, it has been added to the "TRI" page.

And since the itch.io one seems keen on playing with the price button (https://isthereanydeal.com/#/page:game/price?plain=tri), it fires notifications all around for me, since I have "TRI: Of Friendship and Madness" in my waitlist, but that's a simple consequence.

Now I don't know what would be a proper fix to that. Ideally, the longer name game page should be reverted to https://isthereanydeal.com/#/page:game/info?plain=trioffriendshipandmadness, and the itch.io one should be on https://isthereanydeal.com/#/page:game/info?plain=tri. But that doesn't handle the case of stores using a short name instead of the full name, like https://indiegamestand.com/store/223/tri/

So I don't know really what can be fixed on the code level even. Ultimately it's a combined consequence of stores not respecting the full name, a game having a complicated name with a ":", and a simple itch.io game having a simple name which can be associated to an already existing one. Aside from adding special manual cases, not much to do about it, I guess.

[Issue created by gnoupi: 2017-04-03]
[Last updated on bitbucket: 2017-04-04]

[Comment created by bb34887: 2017-04-04]
It's a recurring issue since forever. Sometimes a game popup on ITAD links to multiple different games *on the same service*. Games really need to be matched on developer/publisher, not just title (and anti-matched it they're for sale at the same time on the same service)

[Comment created by gnoupi: 2017-04-03]
Ok, actually, it seems like a recurring issue since plugging itch.io, I see: 
https://bitbucket.org/tfedor/isthereanydeal.com/issues/656/lost-refers-to-different-games
https://bitbucket.org/tfedor/isthereanydeal.com/issues/658/the-forest-contains-a-different-game-under

**Comment by MarkitkaM** [comment]
Entries to split #2323
