### ISSUE TITLE
some items are missing "Deal" links on their page:game/info

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#679]
Well here's one example anyway. It's a bug I've seen before, so I assume there are more examples.

![BOB.PNG](https://bitbucket.org/repo/b6qGGA/images/3681947398-BOB.PNG)

![BOB2.PNG](https://bitbucket.org/repo/b6qGGA/images/222019211-BOB2.PNG)

Needless to say, there [is a deal](http://store.steampowered.com/bundle/1594/), and ITAD seems to know about it because it shows the discount percentage in the deals list.

[Issue created by bb34887: 2017-04-14]
[Last updated on bitbucket: 2017-05-15]

[Comment created by tfedor: 2017-05-15]
So I think the problem was that the parser temporarily didn't see the deal. Since game info pages are not cached and the deals list, that's the result we got.

[Comment created by bb34887: 2017-04-30]
The "Bundle of Bundles" Bundle is gone from Steam now.

Archived Steam page: 1. https://web.archive.org/web/20170408162448/http://store.steampowered.com/bundle/1594/   2. https://archive.fo/XEJtq

Archived steamdb page: https://archive.fo/Rekw5

[Comment created by bb34887: 2017-04-14]
I assume so. I took them within about a minute, from the same browser. Up the top it looks like this:

![region.PNG](https://bitbucket.org/repo/b6qGGA/images/2127706536-region.PNG)

I never changed these settings.

[Comment created by tfedor: 2017-04-14]
Are both screenshots from same region?

[Comment created by tfedor: 2017-04-14]
Well, that's a new one for me... what the...

**Comment by MarkitkaM** [comment]
Solved within the conversation.
