### ISSUE TITLE
filter suggestion: price is OVER x amount

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#682]
front page filter suggestion: allow user to look for games that are over X amount. This will filter out all the under $1 rubbish games. 

I was looking for historical low priced games, but the results are flooded with all the small shovelware games. 

Also, please allow the user to turn off the 'neverending page' feature. thanks.

[Issue created by [deleted]: 2017-04-15]

[Comment created by tfedor: 2017-04-15]
If you apply price filter you can see in URL that you can edit the range. In upcoming update there will be an UI support for that too.

Regards "neverending page", turn if off here: https://isthereanydeal.com/#/page:user/account/settings?section=deals&option=auto_lazyload

**Comment by MarkitkaM** [comment]
Explained within the conversation.
