### ISSUE TITLE
Can't read the bottom of the page

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#689]
When I try to scroll to the bottom of the page it starts auto-loading more results so quickly that it's almost impossible to read the bottom of the page (eventually managed to screenshot it but it took a few tries to do it quickly enough before it disappeared)

Congrats on having such a quick site but maybe include a button to cancel the auto-load (just don't put it right at the bottom of the page or I'd have no chance to click it quickly enough)

[Issue created by [deleted]: 2017-04-22]
[Last updated on bitbucket: 2017-04-23]

[Comment created by bb34887: 2017-04-23]
See also Issue #626

**Comment by MarkitkaM** [comment]
It is still there but we will not fix it while there are upcoming new websites.
