### ISSUE TITLE
some IG Store deals not shown

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#690]
IG Store sale:

Link: https://www.indiegala.com/store/search?type=games&filter=discounted&page=1  
Archived snapshot: https://archive.is/fnkQK  

Search for same items on ITAD:

Link: https://isthereanydeal.com/?by=cut:desc#/filter:indiegalastore    
Archived snapshot: https://archive.is/Dmx6H  

Most deals are listed but some are missing:

* HOUND
* Soulless: Ray Of Hope
* Freedom Cry
* Threads of Destiny
* Last Heroes 2

(I've only searched through the first page of deals on IG Store; there are presumably more)

If you find these games on ITAD, they all show 0% discount for IG Store, and they all have a recent IG Store price chart that looks like this:

![HOUND-IGstore.PNG](https://bitbucket.org/repo/b6qGGA/images/3814737145-HOUND-IGstore.PNG)

(this one's for HOUND)

The above 5 in a handy list: https://isthereanydeal.com/#/search:#^HOUND$|Soulless:%20Ray%20Of%20Hope|^Freedom%20Cry$|^Threads%20of%20Destiny$|Last%20Heroes%202;/scroll:#gamelist

And archived: https://archive.is/zGikf

[Issue created by bb34887: 2017-04-23]
[Last updated on bitbucket: 2017-05-09]

[Comment created by bb34887: 2017-05-09]
Revised URL: https://isthereanydeal.com/#/filter:search/!^HOUND$|Soulless%3A%20Ray%20Of%20Hope|^Freedom%20Cry$|^Threads%20of%20Destiny$|Last%20Heroes%202;/options:all,showhidden

**Comment by MarkitkaM** [comment]
**Not tracked by Indiegala store, not found at Indiegala store:**
Hound 
https://isthereanydeal.com/game/hound/info/

Soulless: Ray Of Hope
https://isthereanydeal.com/game/soullessrayofhope/info/

**Tracked by Indiegala store:**
Freedom Cry
https://isthereanydeal.com/game/freedomcry/info/

Threads of Destiny
https://isthereanydeal.com/game/threadsofdestiny/info/

Last Heroes 2
https://isthereanydeal.com/game/lastheroesii/info/
