### ISSUE TITLE
Most DreamGame regions missing

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#691]
[DreamGame](https://www.dreamgame.com/) supports the following currencies (see the dropdown at the top left):

    USD - US Dollar
    AUD - Australian Dollar
    GBP - British Pound Sterling
    CAD - Canadian Dollar
    DKK - Danish Krone
    EUR - Euro
    PLN - Polish Zloty
    CZK - Czech Republic Koruna
    SEK - Swedish Krona
    CHF - Swiss Franc

I assume if it supports my currency then it supports my region.  
ITAD currently only shows its games if you set your region to EU or UK. (unless they're sold on other stores - you still see the prices / links for the other stores)

[Issue created by bb34887: 2017-04-23]

**Comment by MarkitkaM** [comment]
The Dreamgame store is no longer existing.
