### ISSUE TITLE
Mismatch between waitlist's displayed price and that inside detailed window.

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#695]
In my (pbv5g) waitlist there is a "Bioshock Infinite: Season Pass" position which right now displays price of 4.65 EUR, while the lowest price for this item inside its detailed window is 17.59 EUR.

[Issue created by [deleted]: 2017-04-27]

[Comment created by tfedor: 2017-04-27]
In the Waitlist window you see current best price. In the Waitlist list you see current best price that matches your notification settings.

**Comment by MarkitkaM** [comment]
Solved within the conversation.
