### ISSUE TITLE
are missing from log

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#705]
(see what I did there with the title?)

When I filter my log by author=user

https://isthereanydeal.com/log/#/filter:user

I only see items **removed** from **waitlist** (it shows 27 of them). Nothing added and nothing from Collection.

My waitlist has 51 items added by me, and I don't know how many my Collection has due to Issue #704.

Also Waitlist and Collection should have a filter for Added by User / System.

[Issue created by bb34887: 2017-04-30]
[Last updated on bitbucket: 2018-05-27]

[Comment created by bb34887: 2018-05-27]
Looks like you added those logging items around January or earlier?

[Comment created by tfedor: 2017-05-03]
Hm, seems like I'm not logging all "entry points". Log was added later and mainly for purposes of automatic sync, will need to go through it and update it.

**Comment by MarkitkaM** [comment]
Solved within the conversation.
