### ISSUE TITLE
Default filtering mode is unintuitive, restricted mode is possibly broken

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#707]
Catalyst: https://www.reddit.com/r/GameDealsMeta/comments/68i7n6/is_there_any_deal_made_a_major_update_to_the_site/

By default selective mode is chosen. For anyone who is used to the previous site this is going to be waay too confusing and unintuitive for them. Also, restricted mode (no icon selected) seems to be broken. 

To put it another way, the previous default was to AND the filters. Now it's OR. Restricted mode is, to my understanding, supposed to AND them. However, restricted mode appears to be broken and function the same as selective mode.

Restricted mode should really be the default with the "+" icon continuing to be highlighted, then selective mode should be without any icons. It's still slightly unintuitive for people without software development training but I think it's a much better trade-off.

You can also read the reddit thread and decide for yourself (it's on gamedeals/meta so it's generally short-ish and low traffic).

[Issue created by MetalPlateMage: 2017-04-30]
[Last updated on bitbucket: 2017-05-03]

[Comment created by tfedor: 2017-05-03]
https://www.reddit.com/r/GameDealsMeta/comments/68i7n6/is_there_any_deal_made_a_major_update_to_the_site/dh1y4b2/

**Comment by MarkitkaM** [comment]
Solved via reddit.com
