### ISSUE TITLE
still receiving sales from macgamestore after deselecting store.

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#711]
I'm a pc gamer, so I deactivated macgamestore notifications...and obv enabled wingamestore's.

dunno if it's kind of twin site, but still receiving notifications from both.

I think it's a bug

[Issue created by [deleted]: 2017-05-01]
[Last updated on bitbucket: 2017-05-02]

[Comment created by tfedor: 2017-05-02]
Please update your default notification settings and apply them https://isthereanydeal.com/#/page:user/wait/defaults

**Comment by MarkitkaM** [comment]
Solved within the conversation above.
