### ISSUE TITLE
Negative filters not working now?

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#715]
It looks like "!" filters don't do anything at the moment.

[Issue created by bb34887: 2017-05-03]
[Last updated on bitbucket: 2017-05-15]

[Comment created by bb34887: 2017-05-15]
You should make ! filters produce an error message, otherwise it's potentially confusing to visit an URL (eg. bookmark or link in bitbucket) that uses old-style filters and get the wrong results.

[Comment created by tfedor: 2017-05-03]
Ok, ! should work again but just a warning that behaviour of filters will change to be simpler.

[Comment created by bb34887: 2017-05-03]
But "-" is still subtracting sub-items.

[Comment created by tfedor: 2017-05-03]
I updated filters to work more like in older version of ITAD. + is OR, & is AND and - is negative. Temporary solution so for regular users filter work, and we can figure out kinks and improve them. Old system with those modes were too complicated by the looks of it.

See https://www.reddit.com/r/GameDealsMeta/comments/68i7n6/is_there_any_deal_made_a_major_update_to_the_site/dh1y4b2/ for discussion

**Comment by MarkitkaM** [comment]
Solved within the conversation above.
