### ISSUE TITLE
title isnt displaying deal

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#716]
So when i view this particular item "golfing with friends" on my wait list, this title will not show up on filtering ("current cut" and such.)

I know this is the same title and it isn't a duplicate, because when i click on this title by hand it does display that there is a deal.

Upon searching on the front page (searching "deals") this particular discount WILL show up.

(thanks for everything. Great service, i use daily)

[Issue created by [deleted]: 2017-05-03]

[Comment created by tfedor: 2017-05-03]
Can you send me a screenshot of what you mean please?

**Comment by MarkitkaM** [comment]
Missing additional info from the user.
