### ISSUE TITLE
Waitlist notifications doesn't seem to care about local currency conversions.

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#720]
I just got notified for this 50% off deal:
![](https://cdn.pbrd.co/images/e1QUvOac.png)
When the deal is more expensive than the game's default price on steam. I have my settings for BRL currency and historical low notification.

Either there's a setting I'm not aware of, and should be made clearer to find if that's the case, or I think this should be looked into. It's not very helpful.

[Issue created by [deleted]: 2017-05-04]

[Comment created by Soulwynd: 2017-05-04]
Glad you found the issue. I will let you know if anything like this happens again.

[Comment created by tfedor: 2017-05-04]
Ok, I see the problem, it's not because of Waitlist, it's because historical lows were wrongly recorded for these games. If you look at history you see listed historical low 0.00 for both of these, which when added as notification limit translates to "any".

This was probably caused by some bug or glitch in either my parser or store itself. I will remove 0 prices from historical lows, add additional check for these and re-record historical lows, which should fix the problem for future instances.

[Comment created by Soulwynd: 2017-05-04]
[Speaking of the devil, it just happened.](https://cdn.pbrd.co/images/2hXoreYu3.png)

I've just updated as you asked, but Mirage and Starship corporation ignored the No-sale BRL prices from other stores.

[Comment created by Soulwynd: 2017-05-04]
Done. It did update this time around. There's a bit of a discrepancy on the prices with 30% off, but since it's showing it in dollars, I don't know if it was due to currency fluctuation or a price change. [Here.](https://cdn.pbrd.co/images/2hHGFCY9x.png)

I will have to wait and see if I get notified with more games ignoring the currency conversion.

[Comment created by tfedor: 2017-05-04]
Hm, could you instead try to apply defaults again?

If you look here: https://isthereanydeal.com/waitlist/#/page:game/wait?plain=edenstar you will see that you have 15 as price limit there right now.

Try to go to defaults and hit "save and update", it should change that price limit to current historical low (7 something, iirc): https://isthereanydeal.com/waitlist/#/page:user/wait/defaults

If that won't work we found a bug and I'll take a look where the problem is.

[Comment created by Soulwynd: 2017-05-04]
Yes, but I did hit the update waitlist button on the bottom as well. Unless that doesn't work that way. Should I remove all items and reimport?

[Comment created by tfedor: 2017-05-04]
Is it possible that you had this game in your Waitlist and then you changed default notifications for historical low?

[Comment created by Soulwynd: 2017-05-04]
Username: Soulwynd

Thanks.

[Comment created by tfedor: 2017-05-04]
Please let me know your email, username or user ID on ITAD so I can check your notification settings. Thank you.

**Comment by MarkitkaM** [comment]
Solved within the conversation above.
