### ISSUE TITLE
Duplicate Alone in the Dark (5)

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#723]
* https://isthereanydeal.com/#/page:game/info?plain=aloneindark
* https://isthereanydeal.com/#/page:game/info?plain=aloneindarkv

[Issue created by Bujno: 2017-05-05]
[Last updated on bitbucket: 2018-11-10]

[Comment created by Bujno: 2018-11-10]
Perhaps they should be combined?

**Comment by MarkitkaM** [comment]
Entries to merge #2324
