### ISSUE TITLE
Search field broken in Safari 10.1 (Mac OS X 10.11.6)

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#733]
The search field is incorrectly displayed.

![http://i.imgur.com/IPS9RJ9.png](http://i.imgur.com/IPS9RJ9.png)

When selecting the field and typing a new search the text input is not shown, however the search is being done after Enter is pressed.

[Issue created by [deleted]: 2017-05-09]

**Comment by MarkitkaM** [comment]
Old bug.
