### ISSUE TITLE
Dreamgame should be listed

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#737]
It actually has the best deal on Cities: Skylines right now. It should be one the stores that gets checked.

[Issue created by [deleted]: 2017-05-18]
[Last updated on bitbucket: 2017-05-23]

[Comment created by tfedor: 2017-05-23]
I'm waiting for the feeds from Dreamgame

**Comment by MarkitkaM** [comment]
The Store is no longer existing.
