### ISSUE TITLE
Some Newegg titles not being tracked since August 2016

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#738]
In particular various Acitivision titles like Gun or Prototype aren't. I.E.:

See:

https://isthereanydeal.com/#/page:game/info?plain=prototypefranchisepack

Vs:

https://www.newegg.com/Product/Product.aspx?Item=N82E16832133212

They were tracked correctly for quite a while then around August 2016 dropped for some reason.

[Issue created by MetalPlateMage: 2017-05-20]

**Comment by MarkitkaM** [comment]
No Newegg tracked anymore.
