### ISSUE TITLE
Feature: crowd-sourced merging

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#743]
It would be nice to have the ability to suggest merging items and/or have community admins who can merge games. For example, Crusader Kings II has a lot of duplicated pages right now:

https://isthereanydeal.com/collection/#/page:game/info?plain=crusaderkingsiiswordofislamdlc
https://isthereanydeal.com/collection/#/page:game/info?plain=crusaderkingsiiswordofislam
https://isthereanydeal.com/collection/#/page:game/info?plain=expansioncrusaderkingsiiswordofislam

[Issue created by [deleted]: 2017-05-27]
[Last updated on bitbucket: 2017-06-06]

[Comment created by bb34887: 2017-06-06]
You mean like this? https://isthereanydeal.com/dots/

**Comment by MarkitkaM** [comment]
Not gonna be merged, these are DLC:
https://isthereanydeal.com/collection/#/page:game/info?plain=crusaderkingsiiswordofislamdlc
https://isthereanydeal.com/collection/#/page:game/info?plain=expansioncrusaderkingsiiswordofislam
