### ISSUE TITLE
Prices aren't showing up on my wishlist

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#744]
My wishlist worked great for months, and then it just didn't.  The items show up, but there are no prices listed.  See the screenshot attached for more clarity on that.
![image](https://user-images.githubusercontent.com/88401908/137974043-cd1870e2-dfad-4c52-ad34-4d6464716674.png)

Thanks, I love your site, and I appreciate you looking into it!

[Issue created by cyan02: 2017-05-28]

[Comment created by cyan02: 2017-05-28]
Witchcraft!!

Wow, that was the fastest resolution time ever.  :)

Thank you very much Tomáš!

[Comment created by tfedor: 2017-05-28]
Items in your Waitlist are in CA region, but you have diffenre tregion selected (probably US). Check the top left and switch your region, or move your items to correct one, as you seem to have some in CA and some in US.

**Comment by MarkitkaM** [comment]
Solved within the conversation above.
