### ISSUE TITLE
Letter links on Dots page endlessly load

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#745]
The default A page is loaded fine, but clicking on any other letter just loads the page endlessly.

[Issue created by Nokiaman: 2017-05-29]
[Last updated on bitbucket: 2018-08-22]

[Comment created by tfedor: 2018-08-22]
Issue #985 was marked as a duplicate of this issue.

[Comment created by tfedor: 2018-08-22]
Dots page is dead, how do you guys even keep getting there.

[Comment created by bb34887: 2018-08-22]
It shows a spinning throbber, but it doesn't even make an XMLHttpRequest!

**Comment by MarkitkaM** [comment]
Duplication of the #787
