### ISSUE TITLE
Trouble upload very large steam wishlist (7000+ games)

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#748]
When I try to upload my steam wishlist, The process appears to stall and freeze, even though the progress circle is still rotating. Is there any way you guys or I can fix this?

[Issue created by akayoshi1: 2017-06-05]

**Comment by MarkitkaM** [comment]
WOrks for me 
![image](https://user-images.githubusercontent.com/88401908/137971253-a33770fa-9b52-4284-b27b-a56e8c8a2d42.png)
