### ISSUE TITLE
Itch.io special prices dont exist

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#749]
Hello,

I have seen this before, and since it happend again I gues ill report it.

I got an email telling me northgard is currently for EUR 3,31 on Itch.io
since that game has  been on my watch list, I went like WOOP and clicked it,

this however brings me to a 404 page not found error on Itch.io
if I than browse itch.io, the game is listed at its normal price of EUR 19.99 and no evidence that it ever was on discount.

last time I tought I was just to late, but this time I went to the site within 2 hours of receiving the email.

can you guys please check what is going on between isthereadeal and the itch.io website.

thank you,

Hans

[Issue created by Hansie9999: 2017-06-05]

[Comment created by tfedor: 2017-06-05]
Yeah, that's how it works over there https://itch.io/docs/general/about

[Comment created by Hansie9999: 2017-06-05]
Ah ok,

thanks for the input,

kinda anoying tho :(

weird that anyone (not only official indie game developers or sellers) can make just any kind of entry there :( :(

Hans

[Comment created by tfedor: 2017-06-05]
The thing is that itch.io doesn't control who submits what before it goes live, as far as I know. That means that someone may create fake entry, and before they catch it it gets tracked by ITAD. Although ITAD checks deals each 20 minutes in general, the catalog is checked only once per 24 hours. Games may be removed from ITAD only during catalog check, so if the game is tracked, even if it's removed from the store shortly after that it may take up to a day for it to be removed from ITAD.

I've removed Northgard manually so it should be fine now.

**Comment by MarkitkaM** [comment]
Solved within conversation above.
