### ISSUE TITLE
Cannot access Waitlist

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#760]
When I have logged into my ISTAD account and try to access my Waitlist, I get an error page saying:

"This page isn’t working

isthereanydeal.com didn’t send any data.
ERR_EMPTY_RESPONSE"

I can access the deals page, can do any searches, access my Collection list and all other settings. I can also add items to my Waitlist, but cannot access the Waitlist directly. 

My user ID is J4SXF.

[Issue created by [deleted]: 2017-06-10]
[Last updated on bitbucket: 2017-06-12]

[Comment created by tfedor: 2017-06-12]
Can you please mark your Waitlist public? https://isthereanydeal.com/#/page:user/account/settings?section=profile&option=public_waitlist

I want to check whether it can be loaded as a public page.

**Comment by MarkitkaM** [comment]
Duplication of the #773
