### ISSUE TITLE
Fix region colors

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#762]
![isthereanydeal.com - region colors.PNG](https://bitbucket.org/repo/b6qGGA/images/655617101-isthereanydeal.com%20-%20region%20colors.PNG)

Foreground:#28152B (dark grey)
Background:#404040 (grey)
The contrast ratio is: 1,6:1
Text failed at Level AA
Text failed at Level AAA
Large text failed at Level AA
Large text failed at Level AAA

All OK:
Foreground:#28152B and background:#A8A8A8
or
Foreground:#000000 background:#969696

[Issue created by Bujno: 2017-06-14]
[Last updated on bitbucket: 2018-11-10]

[Comment created by Bujno: 2018-11-10]
Tomáš, now the search results are much better. The whole text is well distinguishable and read without difficulty.

The following is not clear: what does white, blue and green mean in prices on game page?

[Comment created by Bujno: 2017-06-23]
I have been using your site for a long time. For this you are very grateful. But I still do not understand where what colors mean. There is no detailed reference, manual. In this colorful farce, "the devil's leg is broken." And, accordingly, if I see some text, I'm trying to read it. If the text is not needed - it's logical to remove it altogether. And show only when it is needed.

[Comment created by tfedor: 2017-06-23]
I'm not sure this needs fixing. These tags are only needed to be seen when the regions don't match - and in that case they turn red.

**Comment by MarkitkaM** [comment]
Nowadays it is different.
