### ISSUE TITLE
Waitlist with region in URL behaves oddly

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#765]
Don't know if it's supposed to be supported but a public waitlist behaves oddly under these circumstances:

1. Login. (Don't know if it's needed)
2. Set region to euro1. (Something other than US.
3. Navigate to waitlist address with region in URL: https://isthereanydeal.com/u/jc5ja/waitlist/us
Notice that the region has switched to US.
4. Scroll down so the page dynamically loads.
Expected result: all items are displayed with US region.
Actual result: Dynamically loaded items will be displayed as if euro1 was selected.

5. Apply a Deal filter.
Expected result: Deals displayed.
Actual result: No deals displayed since euro1 is being used behind the scenes even though US seams to be selected.

(Bug or feature request?)

[Issue created by supersmo: 2017-06-14]

**Comment by MarkitkaM** [comment]
Deals are showing https://isthereanydeal.com/u/jc5ja/waitlist/?country=FR
