### ISSUE TITLE
Game is listed as discounted, but isn't

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#767]
I have Total War Shogun 2 Collection in waitlist, I got mail about price discount on amazon, yet it isn't 11,20 euro but regular price.

[Issue created by [deleted]: 2017-06-22]
[Last updated on bitbucket: 2017-06-23]

[Comment created by tfedor: 2017-06-23]
I'm gonna need more info - ideally send me the notification you got.

**Comment by MarkitkaM** [comment]
Not received the additional info.
