### ISSUE TITLE
Steam missing on EU1 for The Elder Scrolls V Skyrim: Legendary

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#771]
Steam does not show up in the stores selling The Elder Scrolls V Skyrim: Legendary when EU1 is the selected zone in my waitlist.
It does correctly show up when US is selected.
The other dozen shops show up in both zones.

[Issue created by [deleted]: 2017-06-24]

[Comment created by StefBzh: 2017-06-24]
You are right, I can't find it either, only this "Special Edition".

And it appears it is yet another version of the same game, different from the Legendary one which disappeared completely from Steam.

Bethesda is really pushing this version of the game: even the original Skyrim game page http://store.steampowered.com/app/72850/The_Elder_Scrolls_V_Skyrim/ still exists but does not appear at all in the search results when you simply search for "skyrim" !

Anyway, sorry, IsThereAnyDeal is not at fault at all here.

[Comment created by tfedor: 2017-06-24]
Is it sold on Steam? I'm trying to find Skyrim Legendary on Steam but it doesn't show up for me. Only this one http://store.steampowered.com/app/489830/The_Elder_Scrolls_V_Skyrim_Special_Edition/

**Comment by MarkitkaM** [comment]
Solved within the conversation.
