### ISSUE TITLE
Cannot Access Waitlist

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#773]
After logging in, I cannot access my Waitlist. The page displays the error message:

This page isn’t working

isthereanydeal.com didn’t send any data.
ERR_EMPTY_RESPONSE

I can access the store hompage and My Collection, but not the Waitlist. Additionally, when signing in under a different account, I can access that Waitlist, so it is not a Browser issue on my part. 

My account is J4SXF

[Issue created by [deleted]: 2017-06-24]

[Comment created by tfedor: 2017-06-24]
Can you try to set your Waitlist as public? https://isthereanydeal.com/#/page:user/account/settings?section=profile&option=public_waitlist

**Comment by MarkitkaM** [comment]
Solved within the conversation above.
