### ISSUE TITLE
Wait - Extended

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#774]
I looked for Wait - Extended and it seems you placed the Soundtrack Edition on a bundle. I checked the linked Lovecraftian Bundle and it seems the bundle only contained the vanilla version. Is there something I overlooked?

[Issue created by [deleted]: 2017-06-25]
[Last updated on bitbucket: 2017-06-26]

[Comment created by tfedor: 2017-06-26]
Bundle pages are free to edit for everyone so please, if you saw a mistake, don't hesitate to fix it.

**Comment by MarkitkaM** [comment]
Solved within the conversation above.
