### ISSUE TITLE
Uplay missing from Canada region

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#775]
The UPLAY store is missing from the Canada region but if I switch to US region it works. Thanks

[Issue created by [deleted]: 2017-06-26]

[Comment created by tfedor: 2017-06-26]
There is no way for me to get accurate Canadian prices for the Uplay, that's why it is missing.

**Comment by MarkitkaM** [comment]
Solved within the coversation above.
