### ISSUE TITLE
"LA Noire" Listed as DLC

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#776]
The standalone game should be listed as such, whereas right now it is under the DLC category within the 'L.A. Noire' package.

https://isthereanydeal.com/#/page:game/info?plain=lanoire

[Issue created by bejonsson: 2017-06-30]

**Comment by MarkitkaM** [comment]
Now it is correct https://isthereanydeal.com/#/filter:&search/L.A.%20Noire,&package
