### ISSUE TITLE
"Frost" and "The Frost" is falsely treated as one game

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#777]
Hi there,

The game "Frost" on Steam
http://store.steampowered.com/app/490950/Frost/
is merged with the game "The Frost"
http://store.steampowered.com/app/622540/The_Frost/

https://isthereanydeal.com/#/page:game/info?plain=frost

They are two separate games.

Cheers!

[Issue created by [deleted]: 2017-07-02]

**Comment by MarkitkaM** [comment]
Entries to split #2323
