### ISSUE TITLE
Firefight is different game on Steam vs itch.io

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#780]
https://isthereanydeal.com/waitlist/#/page:game/info?plain=firefight

Two very different game have the same title. I am not sure ITAD can tease out the difference.

[Issue created by [deleted]: 2017-07-04]

**Comment by MarkitkaM** [comment]
2 different games on itch.io an on different on Steam:
![image](https://user-images.githubusercontent.com/88401908/137772581-cee31576-e601-49df-9adc-60f5a36ed120.png)

**Comment by MarkitkaM** [comment]
Entries to split #2323
