### ISSUE TITLE
Kindergarten store links are for wrong games

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#782]
The info page for the game 'Kindergarten' found here: [https://isthereanydeal.com/#/page:game/info?plain=kindergarten](Link URL) seems to have links for three different games in the "current deals" section. The Steam store link is the correct game for the thumbnail, but the other store links are for a different game called 'Kindergarten' but also, the "digital download" store link seems to be linked to a third different game called 'Big Thinkers Kindergarten.'

[Issue created by [deleted]: 2017-07-06]

**Comment by MarkitkaM** [comment]
Duplication of the #2088
