### ISSUE TITLE
Sync status based on custom category

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#788]
Not sure if Steam's API allows for this, but in my Steam Library, whenever I beat a game, I put it into a custom category named "Games I've Beaten".

It'd be nice if I could configure my collection so that when it syncs with my Steam account and sees games in this category it'll automatically to set the status of the game to "beaten".

Of course, when you set this up, I suppose you could allow this to be applied to any type of status, the "beaten" status is just what I'd be using it for.

[Issue created by [deleted]: 2017-07-15]

[Comment created by tfedor: 2017-07-15]
As far as I know this is not possible. Steam API does not show user's categories.

**Comment by MarkitkaM** [comment]
Solved within the conversation above.
