### ISSUE TITLE
Invisible selection

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#791]
1. Enter waitlist and select several titles.
2. Notice that all selected filters are "in collection", so use filter "in collection".

Result: selected games remains selected and added to "selected games" counter, but I see it as not selected. Clicking selection box actually de-select it (as it must), and selecting again now properly shows tick.

[Issue created by [deleted]: 2017-07-21]
[Last updated on bitbucket: 2017-09-04]

[Comment created by tfedor: 2017-09-04]
Fixed on dev branch, will be up with next update

**Comment by MarkitkaM** [comment]
Solved within the conversation above.
