### ISSUE TITLE
Categories for Waitlist

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#793]
I was trying to do some organization on my Waitlist and was surprised to discover that you can't categorize items on there the way you can for the Collection. The use case I'm after is to see at a glance which waitlist items are for my own wishlist vs. friends' wishlists I've imported to look out for gift opportunities. Would it be possible to add tags or categories to Waitlist entries, and sort by price etc. within those categories?

[Issue created by SabreCat: 2017-07-22]

**Comment by MarkitkaM** [comment]
Already possible to use categories in Waitlist, to sort by price etc..
