### ISSUE TITLE
Merge: Deponia Doomsday

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#797]
"Deponia 4: Deponia Doomsday" on GOG is actually same as "Deponia Doomsday" elsewhere - would be good to merge these together.

[Issue created by [deleted]: 2017-07-26]

**Comment by MarkitkaM** [comment]
https://isthereanydeal.com/search/?q=Deponia+Doomsday%22

**Comment by MarkitkaM** [comment]
Entries to merge #2324
