### ISSUE TITLE
DLC for Age of Empires II HD not detected.

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#798]
I do own the DLC Age of Empires II HD - The Forgotten in steam. See attached screen shot. 
However ITAD doesn't show that I own this DLC

[Issue created by [deleted]: 2017-07-27]

**Comment by MarkitkaM** [comment]
https://isthereanydeal.com/game/ageofempiresiihdforgotten/info/ - no tracking
https://isthereanydeal.com/game/ageofempiresiihdplusforgottenexpansion/info/ - just historical low from Steam

is it this one on Steam? https://store.steampowered.com/app/239550/Age_of_Empires_II_2013_The_Forgotten/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
