### ISSUE TITLE
Gemly store - add prices

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#799]
https://gemly.com

they are offering dying light the following EE for 25$, about half the price currently listed everywhere else. might be a good source to add to the list.

[Issue created by [deleted]: 2017-07-28]
[Last updated on bitbucket: 2019-03-06]

[Comment created by Knightw0lf: 2019-03-06]
this has been added and now can be closed

**Comment by MarkitkaM** [comment]
The store is not existing anymore.
