### ISSUE TITLE
Filter Copies > Not Set on Collection page doesn't work

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#809]
The number shows next to the filter works, but nothing is shown in the list when the filter is applied.

[Issue created by [deleted]: 2017-08-16]

**Comment by MarkitkaM** [comment]
Works.
![image](https://user-images.githubusercontent.com/88401908/137639278-c541eb0d-c1f4-4ace-8704-bab5a9e61d22.png)
