### ISSUE TITLE
Multiple entries for Crusader Kings II: Charlemagne

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#813]
There are currently 3 different entries for Crusader Kings II: Charlemagne each with a different set of stores. Shouldn't those be merged into one? I'm pretty sure there's no differences (except the stores) between the entries.

https://isthereanydeal.com/search/?#/page:game/info?plain=crusaderkingsiicharlemagne
https://isthereanydeal.com/search/?#/page:game/info?plain=expansioncrusaderkingsiicharlemagne
https://isthereanydeal.com/search/?#/page:game/info?plain=crusaderkingsiicharlemagnedlc

[Issue created by [deleted]: 2017-08-22]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
