### ISSUE TITLE
Bad filters bug

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#817]
Is there any deal page is bug or is it my thing? Even after formatting I still have the same error as I had (I thought it was a browser thing in its day), and that is that even if I sort my wish list by price, offer or another type of filter I will not be ordered. : / I remember that before I could see what kind of offer there was and order it for games that had more offer, but no longer leaves me, any idea why?

[img]https://i.gyazo.com/8687ae8cafda61f321efb5047897ac8d.png[/img]
[img]https://i.gyazo.com/ca79a960bf87a4f2cd0ef9ecbe198359.png[/img]

[Issue created by [deleted]: 2017-08-25]

[Comment created by tfedor: 2017-08-25]
I don't really understand what you are trying to say, but maybe you are looking for this?

https://isthereanydeal.com/#/filter:&wait

**Comment by MarkitkaM** [comment]
Any additional info.
