### ISSUE TITLE
Day of Infamy Savemi listing for free when it's not discounted

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#822]
I just got an email saying that Day of Infamy was on sale. It said it was 100% off, but the subject line said it was a wish list notification instead of the normal specials notification for free games. So I decided to check it out, and on the [Day of Infamy](https://isthereanydeal.com/#/page:game/info?plain=dayofinfamy) entry on the site, under the Savemi site, it lists it as 100% off, but when you go to the [page](https://us.savemidownload.com/product/day-of-infamy/), it's its normal price. I thought I may as well report this weird bug. I attached a pic of the email I received.

[Issue created by dgosling: 2017-08-30]

**Comment by MarkitkaM** [comment]
The sore Savemi is no longer existing.
