### ISSUE TITLE
Cannot stay logged in for more than a few days

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#830]
Allow us to stay logged in for more than a few days. This is insane how often I need to renter my credentials using traditional login instead of steam login. At least give us an option to stay log in for at minimum of a month preferably forever.

[Issue created by [deleted]: 2017-09-09]

[Comment created by tfedor: 2017-09-09]
Your log in should be remembered for something like a month, and refreshed for another month on each visit. Are you sure you're not clearing your cookies when closing browser or something like that?

**Comment by MarkitkaM** [comment]
Any additional info from the user.
