### ISSUE TITLE
merge lego batman store page

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#832]
**MERGE ENTRIES:**
this https://isthereanydeal.com/?by=cut:desc#/page:game/info?plain=legobatman
and this https://isthereanydeal.com/?by=cut:desc#/page:game/info?plain=legobatmanvideogame
are the same game

[Issue created by [deleted]: 2017-09-09]

**Comment by MarkitkaM** [comment]
Entries to merge #2324
