### ISSUE TITLE
Solstice sold on Itch.io is not the same game as what other stores are selling

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#835]
Solstice is listed for three different store. The one sold on Itch.io is a completely different game and should be listed separately. There's a huge retail price difference ($20 vs $2), so it's throwing off my notifications for the copy sold in other stores.

[Issue created by [deleted]: 2017-09-12]

**Comment by MarkitkaM** [comment]
Duplication of the #1740
