### ISSUE TITLE
Waitlist Shows Deals From Ignored Store

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#847]
Today when I sorted my Waitlist to see what is on sale, a game was at the top of the list as 75% off, but when I clicked on the name to see which store had the sale, all of the shown stores were at full price. Turns out it is a store I am ignoring that has the sale. I would have expected ignoring it to prevent its price from affecting the listing as well as the information on click.

If it is relevant for testing, the game is Minecraft: Story Mode, and it is on sale at WinGameStore.com, which shows as ignored on both my defaults and on the info for that specific game. I am leaving this as a major bug because it compromises the entire function of the Waitlist if it occurs, but I understand if it gets reduced due to being  a fairly specific event. I would expect it to vary in significance depending on how many stores a user is ignoring.

[Issue created by Nightsmaiden: 2017-10-02]
[Last updated on bitbucket: 2017-10-06]

[Comment created by Nightsmaiden: 2017-10-06]
Fair enough. Glad it's on the list.

[Comment created by tfedor: 2017-10-06]
This will be fixed in upcoming update. No ETA, I am already pass the date I thought it's gonna be ready.

**Comment by MarkitkaM** [comment]
Should be solved within the conversation above.
