### ISSUE TITLE
Two games with same name Killing Time

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#848]
There are two different games with same name Killing Time:

http://store.steampowered.com/app/493320/
http://store.steampowered.com/app/686190/

Currently, they are grouped together in one entry on ITAD:

https://isthereanydeal.com/waitlist/#/page:game/info?plain=killingtime

Is there anyway to split them into different entries?

[Issue created by [deleted]: 2017-10-03]
[Last updated on bitbucket: 2017-10-06]

[Comment created by nhahtdh: 2017-10-06]
I see it in the first link, but not the second link.

I used this query to reduce irrelevant results, but it doesn't show up in the result list:

https://isthereanydeal.com/search/?q=%22killing+time%22

[Comment created by tfedor: 2017-10-06]
You can't see it here? https://isthereanydeal.com/#/filter:&search/!%5Ekilling%20time%24

nor here? https://isthereanydeal.com/search/?q=killing+time

[Comment created by nhahtdh: 2017-10-05]
It's no longer grouped together, but I can't find http://store.steampowered.com/app/686190/ to track it.

**Comment by MarkitkaM** [comment]
**SPLIT ENTRIES:**
https://isthereanydeal.com/waitlist/#/page:game/info?plain=killingtime
https://store.steampowered.com/app/686190/Killing_Time/
https://store.steampowered.com/app/493320/Killing_Time/

**Comment by MarkitkaM** [comment]
Entries to split #2323
