### ISSUE TITLE
Pizza Connection 3 imports from Steam WL as Pizza Connection 1&2

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#858]
PC3  http://store.steampowered.com/app/588160/
PC1&2 http://store.steampowered.com/bundle/2853/

[Issue created by [deleted]: 2017-10-27]

**Comment by MarkitkaM** [comment]
**SPLIT ENTRIES:**

**Pizza connection 1 & 2**
https://isthereanydeal.com/game/pizzaconnectioniii/info/
-> Steam -> Pizza connection 3 https://store.steampowered.com/app/588160/Pizza_Connection_3/

**Comment by MarkitkaM** [comment]
Entries to split #2323

**Comment by forenta** [comment]
Issue still kinda exists, but in another way: 1 + 2 != 3.
https://isthereanydeal.com/steam/app/588160/ still says it's Pizza Connection 1 + 2, but the link redirects to Pizza Connection 3 as it should, picture is also fine.
