### ISSUE TITLE
Two games named Luna

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#860]
There are two games on Steam called Luna, but they appear as one on IsThereAnyDeal.

[Issue created by mayhew3: 2017-10-27]

**Comment by MarkitkaM** [comment]
https://isthereanydeal.com/game/luna/info/
https://store.steampowered.com/app/666810/Luna/
https://store.steampowered.com/app/605770/Luna/
https://funomena.itch.io/luna - not sure about this game
![chrome_wvuZyRzXjt](https://user-images.githubusercontent.com/88401908/137624590-8a85c15e-3fb0-45ad-a3f9-9c6e381f1cfc.png)


https://isthereanydeal.com/game/luna1/info/ - Empty entry called Luna
-> https://store.steampowered.com/app/666810/Luna/ Belongs here

**Comment by MarkitkaM** [comment]
Entries to split #2323
