### ISSUE TITLE
Void Game

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#863]
There are 2 games called Void on Steam, and in your web you **shows the old game with the cover of the new game**, as if both games are the same.

[Issue created by [deleted]: 2017-11-01]
[Last updated on bitbucket: 2020-01-01]

[Comment created by karlcastle: 2020-01-01]
This is up to 4 now.

[https://store.steampowered.com/app/503710/Void/](https://store.steampowered.com/app/503710/Void/)

[https://store.steampowered.com/app/716330/VOID/](https://store.steampowered.com/app/716330/VOID/)

[https://store.steampowered.com/app/855510/VOiD/](https://store.steampowered.com/app/855510/VOiD/)

[https://store.steampowered.com/app/898290/VOID/](https://store.steampowered.com/app/898290/VOID/) ← this one has the DLC [https://store.steampowered.com/app/945250/VOID\_Alpha\_Beats\_Soundtrack/](https://store.steampowered.com/app/945250/VOID_Alpha_Beats_Soundtrack/)

All are linked to [https://isthereanydeal.com/game/void/info/](https://isthereanydeal.com/game/void/info/)

**Comment by MarkitkaM** [comment]
Related #961

**Comment by MarkitkaM** [comment]
Entries to split #2323
