### ISSUE TITLE
A way to combine separate games (or a easy way to suggest the combination)

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#868]
Consider for example the game “Nioh: Complete Edition”. It for some reason is split over two distinct entries.

There should be a way to easily mark these cases for a review or something so they can be combined into a single entry.

[Issue created by simukis: 2017-11-10]

**Comment by MarkitkaM** [comment]
The issue for the merging of entries reported #1163

**Comment by MarkitkaM** [comment]
Entries to merge #2324
