### ISSUE TITLE
Hand of Fate Wildcards DLC, incorrect price

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#876]
Hand of Fate Wildcards DLC is currently 2,49€ @ Steam, but in my wishlist it still shows up as 4,99€. Not sure if other DLCs are affected as well, since there aren't any other in my wishlist.

[Issue created by [deleted]: 2017-11-23]

**Comment by MarkitkaM** [comment]
The actual price is 4,99€, on the waitlist is the same price.
