### ISSUE TITLE
Friends List or other way of keeping track of others' waitlists

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#881]
It would be helpful when keeping track of friends' waitlists, if I didn't have to keep their links bookmarked- this would be more logically a function of the website itself. Could be anything from actual social features with call-and-response friending to just being able to have a list off in the sidebar where we can have easier access to collections/waitlists we have used the link to while logged in. Pretty much the same functionality either way, but the latter would probably be easier to implement.

The way I see this most simply working is that Alice sends Bob the link to her Waitlist and/or Collection. When Bob loads the page and is logged in, ITAD pops up an option (either an actual popover or just a toggle near the top of the page) to remember this list for later. If he accepts, an entry appears in the right sidebar for "Remembered Waitlists" or "Remembered Collections", with Alice's username listed in the appropriate spot. Either a toggle button or another popover for "forgetting" a list that one isn't worried about anymore.

Not insanely complex, and requiring the use of the link provides some privacy through passive means for people who don't show their lists around.

[Issue created by Nightsmaiden: 2017-11-27]

**Comment by MarkitkaM** [comment]
Already on ITAD.
