### ISSUE TITLE
Discount percentage limit on email notifications not working

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#882]
Set my account to only notify me of deals if the discount was over 20% off the original price several weeks ago. It seems to work most of the time (I've gotten fewer emails lately) but I still occasionally get notifications for deals that are outside my filter.

Example below, got this email less than an hour ago.

![ItadIssue.PNG](https://bitbucket.org/repo/b6qGGA/images/2811822409-ItadIssue.PNG)

[Issue created by Speshool_K: 2017-11-28]

[Comment created by tfedor: 2017-11-28]
Tell me that once it's actually live, I'll add it to current update but I have no ETA yet.

[Comment created by Speshool_K: 2017-11-28]
Awesome! You rule dude

[Comment created by tfedor: 2017-11-28]
Not right now, but I'll add an option for it

[Comment created by Speshool_K: 2017-11-28]
Is there a way to get it to only send based on the sale price, without
considering vouchers?

[Comment created by tfedor: 2017-11-28]
Hi, this seems correct, if you count voucher the price should be 20% off

**Comment by MarkitkaM** [comment]
Solved within the conversation above.
