### ISSUE TITLE
ITAD is not showing GMG prices.

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#884]
Hello. As title says, ITAD is not showing prices for Green Man Gaming for me. I'm in EU2 zone.

[Issue created by [deleted]: 2017-12-01]

**Comment by MarkitkaM** [comment]
Too old issue. GMG is showing price generally.
https://isthereanydeal.com/?country=IT#/filter:greenmangaming
