### ISSUE TITLE
Name Clash entries that are NOT supervised in Bundles

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#896]
Since ITAD do not use any kind of numbering like Steam does, name clashes occurs more than developers believed not to. For example:
* http://store.steampowered.com/app/412540/ and http://store.steampowered.com/app/496660/ also another Minotaur game, share the **same entry** within ITAD.  -> **Duplication of the #1794**
* same goes for http://store.steampowered.com/app/682640/ and http://store.steampowered.com/app/39670/ which happened to share Chaser as name.  

For Steam they are separate games. For ITAD they're *same game* misleading anyone who're visiting your site. I found out first example by trying to activate /app/496660/ trusting you but get /app/412540/ instead since your site mods are not doing their job properly.

I know that many users contribute to bundle entry creation but also know they are supervised by mods (at least should be) to be correct. But getting mod privilege does not mean sit there and grant entries WITHOUT inspection first.

Please either warn your site mods, which are not you by their names, or improvise better system so that their laziness won't cost to all users who are relying to your site.

[Issue created by [deleted]: 2017-12-18]

**Comment by MarkitkaM** [comment]
**Chaser:**
The link is not existing http://store.steampowered.com/app/682640/

Entries to split #2323
