### ISSUE TITLE
merge kingdom into kingdomclassic

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#898]
**MERGE ENTRIES:**
The original "Kingdom" (https://isthereanydeal.com/#/page:game/info?plain=kingdom ) was renamed sometime between August and November of last year to "Kingdom: Classic" (https://isthereanydeal.com/#/page:game/info?plain=kingdomclassic )

-> https://web.archive.org/web/20160101000000*/http://store.steampowered.com/app/368230/

So the entries still have to be merged ;-)

[Issue created by [deleted]: 2017-12-20]

[Comment created by M-Vankog: 2017-12-20]
(damn, forgot to login ^^)

**Comment by MarkitkaM** [comment]
Not a bug. Games above are different.
