### ISSUE TITLE
Amazon.co.uk

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#905]
Hello, when I switch to UK region and GBP Amazon shows nothing,. I think because it searchs only Amazon.com, any chance to add Amazon.co.uk? Thanks.

[Issue created by [deleted]: 2017-12-25]

**Comment by MarkitkaM** [comment]
For instance https://www.amazon.co.uk/dp/B01NCOEDA9?&linkCode=ogi&th=1&psc=1&tag=isthcom-21
![image](https://user-images.githubusercontent.com/88401908/137518732-73898994-7937-40fe-8d00-70b02eb71d89.png)
