### ISSUE TITLE
Missing GoGoBundle from shop list

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#907]
There's a 15% voucher that I can't submit because GoGoBundle is missing from the list.

[Issue created by Managarmr: 2017-12-26]
[Last updated on bitbucket: 2018-11-14]

[Comment created by tfedor: 2018-11-14]
It should be possible to edit these bundles now.

[Comment created by tfedor: 2018-11-14]
Yes, I have removed it few days ago because of the reports they are not paying devs for their keys. I have also emailed them for comment but didn't hear back yet. I did not realize that removal from the list will cause issues with past edits, which should not be the case - gonna look at it now.

See https://www.reddit.com/r/GameDealsMeta/comments/9v2ixt/psa_insanely_twisted_shadow_planet_steam_key/

[Comment created by bb34887: 2018-11-14]
There are [4 expired GoGo bundles](https://isthereanydeal.com/specials/#/filter:page/gogobundle,&search/undated,&active) that I can't set an end date for because ITAD complains 

> We couldn't continue due to following errors:
>
> * You have to choose bundle page

It erases the "bundle page" value in the Special editor because the dropdown no longer contains *GoGoBundle*, and this means you can't edit past bundles! (or you can edit but can't save)

Have you decided that GoGo is not legitimate or something @tfedor ?

**Comment by MarkitkaM** [comment]
Solved within conversation above.
