### ISSUE TITLE
Optimize page for mobile devices

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#912]
So I use my phone very often. Other people use their phone very often. So I think it would be nice if you could make an mobile-oriented style of a website.This way, we can access the website without having to stay in the PC. So please, add this feature so that we can use the website without problems in or mobiles.

[Issue created by Ultracoolguy4: 2017-12-31]

**Comment by MarkitkaM** [comment]
New websites have a mobile version.
