### ISSUE TITLE
Add Steam URL 2 "Mad Max: Fury Road (Theatrical)"

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#914]
"[Mad Max: Fury Road](https://isthereanydeal.com/search/?q=%22mad+max%22+%22fury+road%22#/page:game/info?plain=madmaxfuryroad)" = "[Mad Max: Fury Road (Theatrical)](https://isthereanydeal.com/search/?q=%22mad+max%22+%22fury+road%22#/page:game/info?plain=madmaxfuryroadtheatrical)"

[Issue created by Bujno: 2018-01-05]
[Last updated on bitbucket: 2018-11-10]

[Comment created by Bujno: 2018-11-10]
This is a movie, not a game.

![Image 003.png](https://bitbucket.org/repo/b6qGGA/images/1053417307-Image%20003.png)

[Comment created by Bujno: 2018-01-16]
yes

[Comment created by tfedor: 2018-01-12]
Is that a movie?

**Comment by MarkitkaM** [comment]
Steam is not tracked any more:
![image](https://user-images.githubusercontent.com/88401908/137512105-2d62f0f8-1d50-4648-8c31-6fd227d5cb76.png)

**Comment by Korb** [comment]
"Mad Max: Fury Road" is deleted from Steam. The issue can be closed.
