### ISSUE TITLE
Filter for x% of historically lowest

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#92]
When the historically lowest item costs around 5€ i wouldnt mind buying it for 6 € right now instead of waiting.

So it would be nice to filter for something like "110% of historically lowest" or "1-2€ above historically lowest"

[Issue created by [deleted]: 2015-01-19]
[Last updated on bitbucket: 2018-11-10]

[Comment created by Bujno: 2018-11-10]
Tomáš, in the profile settings, set "by default when adding a game to the wish list to offer a price (...) % more than the minimum historical price"?

**Comment by MarkitkaM** [comment]
Solved.
