### ISSUE TITLE
Add store: Microsoft Store

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#936]
https://www.microsoft.com/fi-fi/store/games/windows?icid=CNavGamesWindowsGames

[Issue created by deiga: 2018-01-27]
[Last updated on bitbucket: 2019-03-25]

[Comment created by MSmarek: 2019-03-25]
please add the microsoft store!

[Comment created by Knightw0lf: 2019-02-12]
still on hold are all good now?

[Comment created by deiga: 2018-01-28]
Damn :(

[Comment created by tfedor: 2018-01-27]
I've tried multiple times, but Microsoft doesn't seem too happy about using bots to parse the store:

![ms.png](https://bitbucket.org/repo/b6qGGA/images/3211864687-ms.png)

I've tried again, it seemed promising but no luck after all

**Comment by MarkitkaM** [comment]
Microsoft store is there.
