### ISSUE TITLE
Bad merge: Dwarfs

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#942]
**SPLIT ENTRIES:**
https://isthereanydeal.com/?by=price:asc#/page:game/info?plain=dwarfs

This ITAD entry is linked to two GamersGate pages about two different games: one is "Dwarfs!?" (Steam ID 35480), the other is "D.W.A.R.F.S." (steam ID 281560).

[Issue created by metilli: 2018-02-04]

**Comment by MarkitkaM** [comment]
![image](https://user-images.githubusercontent.com/88401908/137373925-5c087b0d-3991-4cc0-bc85-07804150a523.png)

**Comment by MarkitkaM** [comment]
Entries to split #2323
