### ISSUE TITLE
Gog and humble bundle link

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#943]
hey guys. So currently I can't get the gog and humble bundle account ink to work
what address exactly do I need for it to work ?
or is it currently not working ?

[Issue created by [deleted]: 2018-02-05]

[Comment created by tfedor: 2018-02-05]
Hi, what URLs are you using now?

**Comment by MarkitkaM** [comment]
No additional info was sent.
