### ISSUE TITLE
GreenManGaming (GMG) not in the store list anymore?

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#944]
Is it a bug or did you kick it?

[Issue created by [deleted]: 2018-02-06]
[Last updated on bitbucket: 2018-02-07]

[Comment created by zelgaris: 2018-02-07]
Hi, we explained removal of GMG in https://bitbucket.org/tfedor/isthereanydeal.com/issues/618/greenmangaming-prices-not-being-counted

**Comment by MarkitkaM** [comment]
GMG is there.
