### ISSUE TITLE
Bad Merge: Way Out (791380) and WayOut (551110)

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#945]
**SPLIT ENTRIES:**
These 2 games should not be tracked [under the same title](https://isthereanydeal.com/#/page:game/info?plain=wayout)

![image](https://user-images.githubusercontent.com/88401908/137371958-4ac7eae7-fb1a-4903-a381-f951f22c20e7.png)

[Issue created by [deleted]: 2018-02-10]

**Comment by MarkitkaM** [comment]
Entries to split #2323
