### ISSUE TITLE
Bad Merge: BOXVR and THE BOX VR

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#946]
**SPLIT ENTRIES:**
https://isthereanydeal.com/#/page:game/info?plain=boxvr
![image](https://user-images.githubusercontent.com/88401908/137370784-26881265-16a3-4568-b222-734e77f5512a.png)

[Issue created by [deleted]: 2018-02-10]

**Comment by MarkitkaM** [comment]
Duplication of the #2060
