### ISSUE TITLE
I can't link my GOG profile.

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#953]
My GOG user ID is "1jocator" but I can't link my profile using the url https://www.gog.com/u/1jocator/ It says "URL wasn't recognized as valid profile URL".

[Issue created by [deleted]: 2018-02-16]
[Last updated on bitbucket: 2018-02-17]

[Comment created by tfedor: 2018-02-17]
Either your ID is incorrect, or your wishlist is not public. This URL should show your wishlist: https://www.gog.com/u/1jocator/wishlist but it returns 404 instead.

In your GOG wishlist, check your URL and privacy setting, take a look at screenshot I've attached:

![gog.png](https://bitbucket.org/repo/b6qGGA/images/2259777948-gog.png)

**Comment by MarkitkaM** [comment]
The account is private now:
![chrome_Gb03LJNvIU](https://user-images.githubusercontent.com/88401908/137363737-88491c98-b6b0-4da6-a6e9-3ba4236d4b24.png)
