### ISSUE TITLE
Rise of the Tomb Raider stats

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#957]
Rise of the Tomb Raider info shows only two stores (SquareEnix and Gamestop PC), and does not include Steam (and any other store).

[Issue created by [deleted]: 2018-02-20]

[Comment created by tfedor: 2018-02-20]
https://isthereanydeal.com/#/page:game/info?plain=riseoftombraiderii0yearcelebration

**Comment by MarkitkaM** [comment]
Related #982

**Comment by MarkitkaM** [comment]
SOlved within the conversation above.
