### ISSUE TITLE
Stellaris: Synthetic Dawn DLC duplicate entries

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#960]
There are two duplicate entries for this DLC:

Stellaris: Synthetic Dawn
https://isthereanydeal.com/search/?q=Stellaris%3A+Synthetic+Dawn#/page:game/info?plain=stellarissyntheticdawn

Stellaris: Synthetic Dawn Story Pack
https://isthereanydeal.com/search/?q=Stellaris%3A+Synthetic+Dawn#/page:game/info?plain=stellarissyntheticdawnstorypack

[Issue created by [deleted]: 2018-02-28]

**Comment by MarkitkaM** [comment]
Entries to merge #2324

Stellaris: Synthetic Dawn
- Add a thumbnail
- NEWEGG -> "OOPS! Your offer could not be found..." ->http://www.tkqlhce.com/click-6305441-10446076?URL=https%3A%2F%2Fwww.newegg.com%2Fparadox-interactive-stellaris-synthetic-dawn%2Fp%2FN82E16832021276
https://isthereanydeal.com/game/stellarissyntheticdawn/info/

**Comment by MarkitkaM** [comment]
Entries to merge #2324
