### ISSUE TITLE
Bad Merge: Void and The Void

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#961]
The Wait List setting for [Void](https://isthereanydeal.com/waitlist/#/page:game/info?plain=void) has been merged with [The Void](https://isthereanydeal.com/waitlist/#/page:game/info?plain=thevoid), which is incorrect.

Not to mention there are tons of entries in the 2 games that are actually of different games altogether.

[Issue created by nhahtdh: 2018-02-28]

**Comment by MarkitkaM** [comment]
**SPLIT ENTRIES:**

**VOID**
Itch.io - listed both different games
STEAM - according to the pictures all three games are different games
- this one should be listed for Steam https://store.steampowered.com/app/503710/Void/
https://isthereanydeal.com/game/void/info/


**THE VOID**
All listing are correct
https://isthereanydeal.com/game/thevoid/info/

**Comment by MarkitkaM** [comment]
duplication #863
Entries to split #2323
