### ISSUE TITLE
Wrong "Reality" game added to wish list

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#964]
I recently added </reality> [http://store.steampowered.com/app/562280] to my steam wishlist and when it synced to isthereanydeal Reality [http://store.steampowered.com/app/561970] was added.

[Issue created by [deleted]: 2018-03-02]

**Comment by MarkitkaM** [comment]
**SPLIT ENTRIES:**
https://isthereanydeal.com/game/reality/info/
![image](https://user-images.githubusercontent.com/88401908/137256518-a0fe7eeb-8207-4a2a-a0ca-b4a93cc065aa.png)

**Comment by MarkitkaM** [comment]
Entries to split #2323
