### ISSUE TITLE
Waitlist Historical Low only

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#965]
Hey there, I can't seem to find this feature so I figured maybe it wasn't implemented yet (as you can see here https://i.imgur.com/qsuKONG.png).

Basically, I want a rule that only passes when one of the stores hit a new or latest historical low, but all I'm seeing right now is a rule that only passes when it hits certain price or percentage cut.

[Issue created by [deleted]: 2018-03-03]
[Last updated on bitbucket: 2018-03-05]

[Comment created by tfedor: 2018-03-05]
This is possible through defaults: https://isthereanydeal.com/settings/waitlist/defaults/?a=price

If setting price manually, you can set current historical low and then you can turn on this option: https://isthereanydeal.com/settings/waitlist/?a=priceUpdate

**Comment by MarkitkaM** [comment]
Solved within a conversation above.
