### ISSUE TITLE
Manage Groups link returns 404

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#968]
Clicking the Manage Groups link when editing a game returns 404:

https://isthereanydeal.com/settings/collection-groups/

E.g via this link:

https://isthereanydeal.com/collection/#/page:game/collect?plain=ageofsteelrecharge

[Issue created by Gustra: 2018-03-05]

**Comment by MarkitkaM** [comment]
New link https://isthereanydeal.com/settings/collection/groups/
