### ISSUE TITLE
The submenus do not work for me in firefox or microsoft edge

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#971]
![picture of the issue](https://imgur.com/a/IaD9H)

see title. not sure what is causing it, i deactivated adblockers, so thats not it

[Issue created by [deleted]: 2018-03-10]

[Comment created by tfedor: 2018-03-10]
Attached screenshot doesn't work for me, but I'm using ITAD from Firefox without issue. Please resend image or provide more info

**Comment by MarkitkaM** [comment]
No additional screenshot sent.
