### ISSUE TITLE
GOG.com import doesn't work

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#972]
see attachment
![image](https://user-images.githubusercontent.com/88401908/137016075-cda6e064-7e77-42b4-a3a3-ee25a22e4e03.png)

[Issue created by [deleted]: 2018-03-10]

[Comment created by tfedor: 2018-03-10]
Is you wishlist public?

**Comment by MarkitkaM** [comment]
Solved within the conversation above.
