### ISSUE TITLE
Blackguards 2 info error

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#973]
https://isthereanydeal.com/search/?q=%22Blackguards%22#/page:game/info?plain=blackguardsiisteamversion
https://isthereanydeal.com/search/?q=%22Blackguards%22#/page:game/info?plain=blackguardsiinodrmversion
Firefox 59.0 x64, Windows 10.

[Issue created by Bujno: 2018-03-12]
[Last updated on bitbucket: 2018-11-10]

[Comment created by Bujno: 2018-11-10]
Fixed, now both links display "No tracked stores are currently selling this game".

**Comment by MarkitkaM** [comment]
https://isthereanydeal.com/search/?q=%22Blackguards%22#/page:game/info?plain=blackguardsiisteamversion
https://isthereanydeal.com/search/?q=%22Blackguards%22#/page:game/info?plain=blackguardsiinodrmversion
"No tracked stores are currently selling this game"

**Comment by MarkitkaM** [comment]
Solved within the conversation above.
