### ISSUE TITLE
steam sync not working

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#978]
i noticed that my wishlist has not been synced for 4 months even though it was set to synchronize periodically. when I click the 'sync now' button it reads 'last import now' but the wishlist did not update and after a browser refresh it doesn't read 'last import now' anymore. even after clearing the collection and wishlist and removing and adding the profile the synchronization still doesn't work.

[Issue created by [deleted]: 2018-03-17]
[Last updated on bitbucket: 2018-03-20]

[Comment created by jodokhuber: 2018-03-20]
Thanks, that was it :) Must have somehow changed it.
Maybe a small note in the profile page would be helpful.

[Comment created by tfedor: 2018-03-18]
Is your wishlist public?

**Comment by MarkitkaM** [comment]
Solved within the conversation above.
