### ISSUE TITLE
Steam Account not actually syncing.

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#991]
Steam Account not actually syncing.  That's pretty much all the issue. I have linked my steam to my profile on here twice now. When I click the sync plug-in it says it's synced but it's not. Because when i check to see any sales on my wishlist or even to see my collection, nothing. Then going back to check the sync thing in profile settings it says it was never synced. I even unlinked steam and linked it back and tried all thisd over and over and same thing.

[Issue created by [deleted]: 2018-04-12]

[Comment created by tfedor: 2018-04-12]
Hi, that's because new Steam settings, https://steamcommunity.com/groups/isthereanydeal#announcements/detail/1669022841793945687

**Comment by MarkitkaM** [comment]
Solved within the conversation above.
